### ISSUE TITLE
Help - Unable to install eclipse

### ISSUE THREAD

**Issue by wyssdbd** [CypherpunkArmory/UserLAnd#1007]
Package eclipse is not available, but is referred to by another package. This may mean that the package is missing, has been obsoleted, or is only available from another source E

**Comment by corbinlc** [comment]
We requested you provide more information and we provided a template to help with that.  As is, we cannot duplicate your issue and help resolve it.  I am closing this for now, but please reopen it if you update it to follow our template and definitely provide all the commands from a fresh install to the error, so we can repeat the issue.

**Comment by Jhevison** [comment]
See my video, in it I teach how to install Eclipse on Android (with the use of Termux)

Link: https://youtu.be/fszeKOrCPyk

**Comment by yununusmulla** [comment]
> See my video, in it I teach how to install Eclipse on Android (with the use of Termux)
> 
> Link: https://youtu.be/fszeKOrCPyk

Video is private bro

**Comment by Jhevison** [comment]
> > See my video, in it I teach how to install Eclipse on Android (with the use of Termux)
> > Link: https://youtu.be/fszeKOrCPyk
> 
> Video is private bro

Now is public!
