### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ulist** [CypherpunkArmory/UserLAnd#1015]
Good evening im new there excuse me if I didn't read the topic of this community
Awhile ago I tried to run Windows program on android both of wine and exagear doesn't work now I'm thinking of idea its running a small terminal on limbo x86 and then installing wine on it is that possible? And how

**Comment by ulist** [comment]
Wrong place to ask that question stupid am I ;)

**Comment by corbinlc** [comment]
I am not sure if that will work or not.  We don't normally cover how-to's here.  In general, how you do something in UserLAnd should be the same as how you would do it on a standard Linux install.  If that is not true, than people file an issue.  So, we encourage you to try out what you want (though your example seems high complexity) and then open an issue if it doesn't work in the "normal" fashion.
