### ISSUE TITLE
Help - [Best phone for userland] 

### ISSUE THREAD

**Issue by Kymonlucky** [CypherpunkArmory/UserLAnd#1017]
# Describe the issue you are having.
I dont have any issue actually, I just wanna ask if you can suggest me whats the best  phone brand/specs to use for userland because I'm planning to buy a new phone. Phone that has minimal issue when using userland and has greater compatibility. 

# Describe how your task behaves in a regular Linux environment

N/A

**Comment by MatthewTighe** [comment]
Phones that are running closest to stock Android are going to be the most reliable, in my experience. I developed mostly on a Pixel 2, and saw issues with it very infrequently.
