### ISSUE TITLE
stuck if failed to download rootfs

### ISSUE THREAD

**Issue by phone-burner** [CypherpunkArmory/UserLAnd#1018]
I want to use Alpine in UserLAnd,but I failed to download Alpine's rootfs.I tried to fix this problem,but I cannot make UserLAnd work again.I cannot start Ubuntu or Debian,either.I know that reinstall UserLAnd will work,but I have about 20GB data in it and making a backup seems impossible.How to protect my data?

**Comment by corbinlc** [comment]
@MatthewTighe any idea on this one?  Why would a failed download cause it to be stuck there after.  @phone-burner can you update your issue with the template, as mentioned?

**Comment by MatthewTighe** [comment]
@phone-burner Where do Ubuntu and Debian get stuck? How do you know the download failed?

**Comment by corbinlc** [comment]
@phone-burner followed the template, but did it in a new issue.  @MatthewTighe please see #1039 .  I am closing this issue.
