### ISSUE TITLE
Bug report - System up filesystem

### ISSUE THREAD

**Issue by Yugo33** [CypherpunkArmory/UserLAnd#1025]
![Screenshot_20190828_102013_tech ula](https://user-images.githubusercontent.com/34394755/63838576-ddc0b600-c97d-11e9-9d1c-715e7b60aeea.jpg)
On Ubuntu the app sttay at this point (look the screenshot)

**Comment by x2slasher** [comment]
As I see you have a similar problem, follow this thread. https://github.com/CypherpunkArmory/UserLAnd/issues/1014

**Comment by Yugo33** [comment]
@corbinlc like what??

**Comment by corbinlc** [comment]
Please read the above comment made by @enforce-issue-templates which requested more info from you.  There is a link to the template.

**Comment by corbinlc** [comment]
@Yugo33 can you update your issue to use the issue template found here [here](https://github.com/CypherpunkArmory/UserLAnd/issues/new/choose)?
