### ISSUE TITLE
Help - [YOUR ISSUE HERE]

### ISSUE THREAD

**Issue by jancm** [CypherpunkArmory/UserLAnd#1031]
(sorry, forgot to change the subject)
# Describe the issue you are having.
Upgraded to Q beta 6. Debian install.
Being asked for a root password when I try to use su (or sudo). What's the default password?

Also tried to join slack. Getting "token revoked" error when asking for invite 
This should include things like:

# Describe how your task behaves in a regular Linux environment
Never needed an su password before (on the phone)

**Comment by JHSargent** [comment]
Not opening kali

**Comment by jancm** [comment]
Resolved. Uninstalled and reinstalled. I suspect there was a problem restoring via Titanium after a clean install moving from Pie to Qb6
