### ISSUE TITLE
Help - Permission denied

### ISSUE THREAD

**Issue by gseonkid91** [CypherpunkArmory/UserLAnd#1035]
# Describe the issue you are having.

I was trying to mount ftp storage locally using curlftpfs command on Debian lxde environment. I get "fuse: failed to open /dev/fuse: Permission denied". And when trying to run the command as root user issue persists. Also when using chmod to change permission of /Dev/fuse same outcome.

# Describe how your task behaves in a regular Linux environment

Issue persists even adding my username to fuse user group using 
"sudo usermod -a -G fuse my-user"

**Comment by corbinlc** [comment]
This would require your rooting your device and UserLAnd requesting to run as real root.  Please see #910 .  We still plan on adding this feature someday.  I am closing this as it is covered by the mentioned open issue.  Please follow that issue for updates.
