### ISSUE TITLE
Distribution Installation Unable

### ISSUE THREAD

**Issue by AidPea** [CypherpunkArmory/UserLAnd#1036]
Hi i need help. I install userland from google play but unable to install any distribution. The installation block and take several time (**up to 1 hou**r). For exemple i retrying now to install Kali and it block to   **Extracting: media/**

**Comment by corbinlc** [comment]
We need more information to help you.  Please update your issue to follow the template as mentioned, or there is not much we can do to understand if this is a known issue or not.

**Comment by corbinlc** [comment]
v2.6.3 was just released (may be a few hours until you see the option to update to it).  It fixes a couple of issues that could cause extraction or launching to get stuck.  You have not provided enough info for me to determine if your specific issue is fixed or not.  I am closing this for now, but please open it if v2.6.3 does not fix it and you update your original issue to follow the template.
