### ISSUE TITLE
Bug report - Stuck at Starting Services

### ISSUE THREAD

**Issue by Java-S-Rabbit** [CypherpunkArmory/UserLAnd#1050]
# Describe the bug
Before entering a terminal session, Userland completes all steps up to "Starting service..." Userland is stuck at this point.

# Steps to reproduce the behavior:
1) Deleted the UserLand Filesystem.
2) Updated all apps, including UserLand and VNC Viewer.
3) Powered device off and on.
4) Started UserLand
5) Selected Debian (tried other selections same issue)
6) Stuck at "Starting service..."

# Screenshots
Just shows "Starting service..."

# Device Information
Device: BLU Vivo One Plus  
Android Version: Nougat, 7.1.1  
UserLAnd Version: 2.6.3  
Whether the device is rooted: No, device is not rooted  
Whether the device is running LineageOS: No, device is not running LineagesOS

# Please add any other context you think might help us resolve your issue.
I have rebuilt UserLand on 2 tablets this week with no issues. UserLand was already running on the BLU Vivo One Plus. Was trying to updating to the new Debian Buster, which did not go well. Noticed: "Android security patch level": July 5,2019.  Did not use UserLand on that device between then and now.

From the UserLand Logs:
proot info: vpid 1: translate("/" + "/bin/bash")
proot info: vpid 1:          -> "/data/data/tech.ula/files/1/bin/bash"
proot info: vpid 1: terminated with signal 11

[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3623998/Proot_Debug_Log.txt)
![Screenshot_20190914-134344](https://user-images.githubusercontent.com/55330100/65096226-d2afe300-d989-11e9-92ac-e83e2289640b.png)

**Comment by NightfallAlicorn** [comment]
I'm having the same issue. I don't know how but I managed to get XFCE from apps tab to run last night with no problem. I was giving UserLAnd a test run.

I tried again today and UserLAnd hangs on starting service with anything Debian after I have cleared the app cache for a clean reinstall. Debian FS itself, XFCE desktop from apps tab and LXDE desktop from apps tab are hanging with starting service. I think the issue is with Debian. Maybe the assets been updated?

I've alternatively tried Ubuntu and ran `sudo apt install xfce4`. Starts up alright after restarting session but there's a majority of error icons and I can't change the font size with Appearance GUI application like I could last night.

**Comment by stephenprater** [comment]
@Java-S-Rabbit are you able to connect to the VNC server from a different device?  You should be able to do this by using port 5951 against your devices IP.

https://github.com/CypherpunkArmory/UserLAnd/wiki/FAQ#1-how-do-i-connect-from-a-device-on-the-same-network

**Comment by Java-S-Rabbit** [comment]
After updating UserLand and reloading Debain today, EVERYTHING IS WORKING !!! Thank you for fixing UserLand. It's very fast and very stable, running the LXDE desktop (GUI).

![Screenshot_20191022-102250](https://user-images.githubusercontent.com/55330100/67348740-85381000-f50b-11e9-8e12-4283a712b543.png)

**Comment by Java-S-Rabbit** [comment]
After updating UserLand and reloading Debain today, EVERYTHING IS WORKING !!! Thank you for fixing UserLand. It's very fast and very stable, running the LXDE desktop (GUI).

![Screenshot_20191022-102250](https://user-images.githubusercontent.com/55330100/67348989-39d23180-f50c-11e9-8007-d7a2f4a48ae5.png)

**Comment by corbinlc** [comment]
Yes.  I fixed it yesterday.  I went back through recent issues, but obviously didn't update this one.  Thanks for following up with us.
