### ISSUE TITLE
Bug report - Host directory /sdcard is suddenly gone.

### ISSUE THREAD

**Issue by arjay195** [CypherpunkArmory/UserLAnd#1053]
# Describe the bug
The Android host companion location to "/storage/sdcard" in Debian suddenly disappeared while I was reinstalling Userland from googleplay.  I have a directory I initially created there- "Linux_Share" used for getting files in and out of the Linux environment.  I have removed and installed Userland twice more expecting the directory path to be restored without success.  Strangely, "/storage/sdcard/Linux_Share" is still available on the Debia directory list,
Is there a script that is failing to create the missing directories?

# Steps to reproduce the behavior:
Using my Android file manager app, viewing the root directory shows that the needed and previously existing file structure is missing.  Also, using the Android file manager app's search tool for "Linux_Share" gets 0 hits.

# Screenshots
N/A

# Device Information
Device: Galaxy Tab S3.  
Android Version: Pie, 9  
UserLAnd Version   2.6.3
Whether the device is rooted.  Not rooted
Whether the device is running LineageOS 

Please add any other context you think might help us resolve your issue.

**Comment by MatthewTighe** [comment]
Unfortunately, the changes to storage we made to be compatible with Android 10 means that we switched to what is called _scoped storage_. The lifetime of scoped storage is tied to the application itself. That is, when UserLAnd is uninstalled, its scoped storage directory is deleted. The [wiki](https://github.com/CypherpunkArmory/UserLAnd/wiki/Importing-and-exporting-files-in-UserLAnd) page describing how to import and export files in UserLAnd has a warning for this at the beginning of the page.
