### ISSUE TITLE
DPKG Error

### ISSUE THREAD

**Issue by noxycyber** [CypherpunkArmory/UserLAnd#1055]
Bugdpkg: error processing package gvfs:arm64 (--configure): dependency problems - leaving unconfigured Errors were encountered while processing: udisks2 gvfs-daemons gvfs:arm64 E: Sub-process /usr/bin/dpkg returned an error code (1) root@localhost: report

**Comment by nakele** [comment]
Same problem here,  Samsung s8 Android 9 with Debian Xfce using latest userland app.

Using Userland 2.4 > problem isn't there

**Comment by stephenprater** [comment]
Please at least try to fill in the template - it's clever that you've figured out how to avoid having the bot yell at you but we really do look at every issue and this kind of thing is not helpful when we're trying to reproduce your bug.

**Comment by corbinlc** [comment]
Started debugging this.  Please see #1072 .   Closing this one as #1072 will track my progress on this.
