### ISSUE TITLE
Bug report - Output is slow

### ISSUE THREAD

**Issue by 3v1n0** [CypherpunkArmory/UserLAnd#1056]
# Describe the bug

I've just rebuilt a new ubuntu instance, after that reading #419 and others, where was stated that new FS was better.

However... I've something like 15035 pics right now in my Camera folder, but just `ls`'ing with termux is way faster compared to UserLAnd (which I really prefer, being just something more complate).

# Steps to reproduce the behavior:

I'm connected via ssh to my phone, to both termux and userland ubuntu instance:

```bash
[04:12 AM] Termux:~ $ time ls -1 storage/dcim/Camera/
...
...
real	0m0.756s
user	0m0.050s
sys	0m0.600s
```

```bash

marco@ubuntu:~$ time ls -1 /host-rootfs/sdcard/DCIM/Camera/
...
...
real	0m31.620s
user	0m0.760s
sys	0m9.860s
```

This doesn't look too much an I/O issue, but mostly on listing files, as the file reading is exactly the same:
```bash
[04:04 AM] Termux:~ $ ls -1 storage/dcim/Camera/IMG_201909* | wc -l
1010
[04:04 AM] Termux:~ $ time cat storage/dcim/Camera/IMG_201909* > /dev/null

real	0m12.838s
user	0m0.100s
sys	0m7.580s
```

```bash
marco@ubuntu:~$ time cat /host-rootfs/sdcard/DCIM/Camera/IMG_201909* > /dev/null

real	0m13.572s
user	0m0.080s
sys	0m6.930s
```

# Screenshots

![immagine](https://user-images.githubusercontent.com/345675/65810123-6a8da800-e1a6-11e9-98c4-b0a4f9e45c23.png)

# Device Information

Device: LG V30+ (stock, not rooted).  
Android Version: Oreo
UserLAnd Version 2.3.6

**Comment by corbinlc** [comment]
This is just the result of running in a PRooted environment.  `ls` is an extreme example of the performance penalty of `proot` because it is very system call intensive and specifically uses the `stat` family of system calls which get handled in multiple places in `proot`.
