### ISSUE TITLE
Bug report - Unable to install completely Git on termux based on Oppo Neo7

### ISSUE THREAD

**Issue by Upanori7** [CypherpunkArmory/UserLAnd#1059]
l had a problem with termux and installing git 
when l updated and upgraded the termux it's all normal but when its come to installing git ( #apt install git ) a bit of error occur and terminates its proses as shown belows:$ ./start-kali.sh
root@localhost:~# apt install git
Reading package lists... Done
Building dependency tree
Reading state information... Done
git is already the newest version (1:2.23.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Setting up udisks2 (2.8.4-1) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs:armhf:
 gvfs:armhf depends on gvfs-daemons (<< 1.38.1-5.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:armhf depends on gvfs-daemons (>= 1.38.1-5); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:armhf (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)

Device/Type: OPPO NEO 7/A33
ROOT : Yes ( Via Termux)
OPERATING SYSTEM ( COLOR OS)
COLOR OS VERSION (2.10i)
Android Version :5.1

**Comment by corbinlc** [comment]
I am sorry if termux is not working for you, but we are not the developers of termux.  This is UserLAnd.  Can you file your issue against termux instead?
