### ISSUE TITLE
apt-get update not working

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [CypherpunkArmory/UserLAnd#106]
I am using ssh using connectbot , the installation of rootfs is successful but when i type apt-get update it give me error like cannot open var/lib/dpkg/lock permission denied i am using Android 7.1

**Comment by corbinlc** [comment]
This happens on a standard Debian system.  You enter as a non-root user and need `su` or `sudo` before doing things that require root.  In this case do `sudo apt-get update`
