### ISSUE TITLE
Help - [Installing apps with apt-get is very slow]

### ISSUE THREAD

**Issue by UDPSendToFailed** [CypherpunkArmory/UserLAnd#1065]
# Describe the issue you are having.

I'm trying to install lxde on Ubuntu with apt-get, it's running for a hour and still not finished. Is this normal? I have Galaxy Tab A 2018 with Snapdragon 450 (8x 1.8 GHz A53 + Adreno 506) and 3GB RAM. 

# Describe how your task behaves in a regular Linux environment

N/A

**Comment by corbinlc** [comment]
There is a performance impact to running things in PRoot, which is how UserLAnd runs.  Installing packages, especially untarring files, is noticeably slower in a prooted environment.
