### ISSUE TITLE
Bug report - [I can't start any distribution or apps on vnc]

### ISSUE THREAD

**Issue by mateus131** [CypherpunkArmory/UserLAnd#1071]
# Describe the bug

I enter any distribution I hope to finish the installation and configuration and when I try to connect via vnc it hangs on starting service

# Steps to reproduce the behavior:

1. Open userland

2. Click on any distribution or app

3. Select vnc after setup

# Screenshots

![Screenshot_20191016-181954_UserLAnd](https://user-images.githubusercontent.com/56730519/67102825-86c7a800-f19a-11e9-92d3-4ba326aa8f0e.jpg)

# Device Information

Device: [Samsung Galaxy J7 Metal 2016].  
Android Version: [Oreo, 8.0].  
UserLAnd Version [2.6.4].  
Whether the device is rooted.  No
Whether the device is running LineageOS No

What I think can solve my problem is to add some function to manually connect via vnc

**Comment by mateus131** [comment]
Proot_debug_log.txt: https://pastebin.com/2auMrBXb

**Comment by corbinlc** [comment]
`ssh` connection works fine?  I am guessing so, but just making sure.  It is weird...it shows you are missing some fonts that are needed by the vnc server.  Did you install some packages (like a desktop environment?) before getting this error?

**Comment by mateus131** [comment]
I didn't install anything before starting via vnc I just clicked on the distribution put password and name and selected vnc

**Comment by mateus131** [comment]
And yes ssh works normally

**Comment by corbinlc** [comment]
Can you change the PRoot verbosity to 9 and repeat the failure?  The log you provided has the minimal verbosity.

**Comment by corbinlc** [comment]
After you change the verbosity and recreate the failure, can you provide the proot log again?  Thanks!

**Comment by mateus131** [comment]
and very big I will send prints

**Comment by mateus131** [comment]
and very large I can not copy or take print has more than 1300 lines

**Comment by mateus131** [comment]
It has more than 13000 lines 😮

**Comment by mateus131** [comment]
I will edit and add the new proot_debug_log

**Comment by corbinlc** [comment]
You can use dropbox or mediafire etc to share the file.

**Comment by mateus131** [comment]
here is the proot: http://www.mediafire.com/file/4luobs3a8l3t74b/Proot_Debug_Log.txt/file

**Comment by mateus131** [comment]
on line 13429 i found this 13429 :  xterm: Xt error: Can't open display: localhost:51

**Comment by corbinlc** [comment]
This is the error that is killing the server `could not open default font 'fixed'`

**Comment by corbinlc** [comment]
This is weird, you are on an `aarch64` (that is a 64bit arm) device from what I read online, but it is using the `armhf` (that is a 32bit arm) image.  Something is wacky with how your device is choosing what libraries to use.

**Comment by corbinlc** [comment]
I will force my device to use the 32bit images and see if I can repeat the error.

**Comment by mateus131** [comment]
on cpu-z it's like 64bits (32bits) mode

**Comment by mateus131** [comment]
I read about it and my phone activates 64 bit mode when it's needed i guess but most apps don't support this function if not and then i was robbed by samsung

**Comment by corbinlc** [comment]
Android apps sometimes include native libraries, ours does.  It is up the the Android on your device to use the libraries that are most appropriate for it.  It is choosing `armhf` even though `aarch64` would be a better option that it should support.  This should not cause the issue you are facing by itself.

It looks like `Kali` and `Debian` launching into VNC are not working.  `Ubuntu` or `Alpine` are working fine.  This probably has been happening ever since the last time I rebuilt the images.  Looks like there is additional package that I need to include in the image to fix this.  I should be able to solve this pretty fast now that I know what is going on.

**Comment by mateus131** [comment]
first look at this http://prnt.sc/pmeu25

**Comment by mateus131** [comment]
Ubuntu and Alpine will run perfectly in vnc

**Comment by corbinlc** [comment]
Interesting that it says (32bit mode).

Anyway, this fixes the issue on `Kali` or `Debian`
Connect via SSH
```
sudo apt update
sudo apt remove --purge xfonts-base
sudo apt install xfonts-base
```
Then you can `exit` and reconnect via VNC.

Looks like I just need to rebuild the images as it looks like that package was broken at the time I rebuilt all images last.

**Comment by mateus131** [comment]
if I run these 3 commands in ssh and switch to vnc will work?

**Comment by corbinlc** [comment]
worked for me.

**Comment by mateus131** [comment]
thanks it worked out, I'll write it down if you need it again

**Comment by corbinlc** [comment]
This was the only command needed `dpkg-reconfigure xfonts-base`

This has been fixed in the latest Debian and Kali images.  Thanks for your help.
