### ISSUE TITLE
Several apps not working

### ISSUE THREAD

**Issue by valadina223** [CypherpunkArmory/UserLAnd#1074]
# Describe the bug

Guys, something is wrong, lots of apps are not working.
These are as of today: 

Chromium
Wget
Curl
Links

Firefox is black, Firefox-esr cannot be installed with sudo add-apt-repository ppa:mozillateam/ppa. It shows an error about SSL missing which means I cant add the ppa.

Setup:
Freshly installed UserLAnd + Ubuntu + sudo apt install xfce4. Desktop is running fine otherwise.

**Comment by valadina223** [comment]
Ok, it actually is possible to install Firefox-esr but with a lot of hassle.
One would need to go to /etc/apt and put the link to the ppa manuall into the file sources.list.
Also it is important to put [trusted=yes] right after deb. It would like deb [trusted=yes] http://...

Otherwise apt update wouldnt work on that repo.

Well, to edit sources.list I installed nano. All in all a lot of work and way to much work for just getting firefox started.

By the way - I love your project and a extensive Wiki would really be a benefit. I don't say this has to be written by you alone but it's definitely missing.

**Comment by corbinlc** [comment]
It is possible that you never installed `wget` or `curl` previously.  We start with a very limited set of packages installed to save on space.  Installing something big like `Firefox-esr` probably did install those for you.  If you see something like `command not found` this means you need to install the package.

**Comment by corbinlc** [comment]
Yes, we definitely need more documentation.  I was planning on starting on that more seriously when I team and funding changed dramatically.  I am going to try to make everything more community driven, so hopefully others can help write this.  Right now, can you put how the commands for how you installed Firefox-esr here in this issue's comments.  This might help someone.

That being said, installing Firefox is one of the few things I have documented: https://github.com/CypherpunkArmory/UserLAnd/wiki/FAQ#2-how-do-i-get-firefox-working

**Comment by valadina223** [comment]
Sure, I installed wget and curl separately as they are not installed by default. It could not be run then because libdl.so was missing if I remember correctly.

Right, I see. But it's not working like you documented. It's not possible to add the firefox ppa because something with SSL is wrong. Sorry, I don't have the exact error message anymore. But it didn't work.

**Comment by phone-burner** [comment]
I just download firefox-esr from the mirror site and then run 'sudo dpkg -i /sdcard/Download/firefox*'.Surely it works.

**Comment by rcragun** [comment]
> I just download firefox-esr from the mirror site and then run 'sudo dpkg -i /sdcard/Download/firefox*'.Surely it works.

Can you clarify what "the mirror site" is?

**Comment by Dirk-LG** [comment]
Hi,

Unfortunately I can confirm the issues on a LG G7 running Android 9:
I freshly installed versions 2.6.5 and then 2.5.13 in the last days, then downloaded Debian file system + lxde desktop (the latter installs the Firefox ESR, too). Plus LibreOffice.
- Firefox just shows a black window. When I open it in a terminal session, it repeatedly shows errors:
```
    [Parent 11255, Main Thread] WARNING: failed to open shm: Permission denied: file /build/firefox-esr-nC2zIw/firefox-esr-68.2.0esr/ipc/chromium/src/base/shared_memory_posix.cc, line 142
and
    Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to lock new back buffer. (t=1.98033)
    
```
- LibreOffice shows the splash screen, and nothing more.
```
kan@localhost:~$ libreoffice 
Xlib:  extension "XINERAMA" missing on display ":51.0".
Maximum number of clients reachedMaximum number of clients reached

```
- Too often when opening any X11 app in a terminal session, I get "Maximum number of clients reached" although I have less than 6 apps on screen. Sometimes even fewer.

- Also this happens on v2.5.13 even it worked in October:
```
kan@localhost:~$ sudo modprobe usblp
/sbin/modprobe: error while loading shared libraries: libdl.so: cannot open shared object file: No such file or directory

```
Cheers
Dirk

**Comment by Dirk-LG** [comment]
I imagine that the errors are in the current file systems. Can I somehow obtain archives (.tar.gz ?) from July / October?

**Comment by corbinlc** [comment]
Version 2.7.1 just released fixes Firefox.  It should show up for upgrade in the next few hours.

**Comment by corbinlc** [comment]
wget and curl can be installed via `sudo apt install` or similar.

**Comment by corbinlc** [comment]
Going to close this one.  Please file new issue(s) 1 per program not working.
