### ISSUE TITLE
Feature Request - Docker installation and run support

### ISSUE THREAD

**Issue by rajibhasan11** [CypherpunkArmory/UserLAnd#1080]
Docker installation and run support.
I am trying to run the docker instance in Android device with or without rooting the device gives me similar kind of results. In different Android device armf, armv7l, aarch64 etc. I have tried.

Android version: Android 5+
Tried in Linux distro: Ubuntu 18.04 LTS arch aarch64

Guideline: https://github.com/moby/moby/blob/master/docs/rootless.md

Connected software:

Initial try (without root privileges)

Termux Android app
AndroNix Android app
Linux deploy Android app
UserLand Android app

In the second try I have installed the debian/ubuntu following the docker installation guidelines of docker rootlesskit but getting the below error when try to run the rootlesskit

/home/android/bin/dockerd-rootless.sh --experimental --iptables=false

[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: invalid argument

Before that I have exported the env variables explicitly and in .bashrc:

export XDG_RUNTIME_DIR=/tmp/docker-60000
export PATH=/home/android/bin:$PATH
export PATH=$PATH:/sbin
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

as well as install all required dependencies in Ubuntu 18.04

Installed tar files from nightly builds:

STATIC_RELEASE_URL="https://download.docker.com/linux/static/nightly/aarch64/docker-0.0.0-20190727010531-15bdbd7.tgz"
STATIC_RELEASE_ROOTLESS_URL="https://download.docker.com/linux/static/nightly/aarch64/docker-rootless-extras-0.0.0-20190727010531-15bdbd7.tg"
Docker requires namespaces for more detail see https://github.com/moby/moby/issues/40121

**Comment by RichardoC** [comment]
@rajibhasan11 did you manage to get this working? If so, please update this thread with how as I think others will be very interested. If not, mind updating your ticket to the format so that the bot cheers up?

**Comment by Nostres25** [comment]
Yes... i need to know how install docker on a debian session of the userland app please.

**Comment by vspirit777** [comment]
> Yes... i need to know how install docker on a debian session of the userland app please.
Do we have solution so far?
