### ISSUE TITLE
Cannot remove directories

### ISSUE THREAD

**Issue by ghost** [CypherpunkArmory/UserLAnd#110]
I have found that I cannot remove directories no matter what I try. I always get an error because of a non-empty dir, even for empty dirs. Sudo, rm -rf, rmdir with the flag to ignore non-empty dirs...
~~I cannot even uninstall packages because of this, the system just gets progressively more and more broken.~~ I don't even know how to try to start to figure out the root cause.

**Comment by corbinlc** [comment]
We need a more specific example as in general this works for us.  Starting from a new filesystem, can you provide the steps to see the issue you are describing?

**Comment by MatthewTighe** [comment]
Also please provide device information including phone type and Android version.

**Comment by mdowman** [comment]
I have experienced this issue on a Samsung Galaxy S9 running Oreo 8.0.0. The non-empty folders that rm etc. refuse to delete appear to be empty upon "ls -la". Steps to recreate can be found on issue #111

**Comment by proz0r** [comment]
I apologise for not including more info upfront. It seems to be similar to what mdowman describes. Installing git, cloning any repository and trying to rm the directory reproduces the issue. Upon further examination, packages can be purged, there was one that had a problem which was due to an unrelated error caused by my mistake.
The device is a Galaxy S8 running Oreo (8.0.0)

**Comment by Malrok** [comment]
I am also facing this kind of issue.
Just as it was stated above, the problem occurs for me on directories cloned from git, and in a subdir created by node after an `npm install.`
Interestingly, it seems to happen on directories that are hidden or subdirs of hidden directories in my case.

**Comment by corbinlc** [comment]
You know, we fixed this issue once before.  We will have to investigate why
it is cropping up again.  Shouldn't be too hard.

**Comment by pmi123** [comment]
I have the same issue on BusyBox v1.27.2 (Ubuntu 1:1.27.2-2ubuntu3) multi-call binary running on a Samsung Galaxy Tab S3, SM-T820, Android 8.0.0. 

The following works:
mkdir -p test/fred/sam
touch test/fred/sam/foo.bar
rm -rf test

However, I cannot delete a directory with a .git folder created by git (ie git clone xxxx). I get the error that the .git folder is not empty, when it is (ls -a the .git folder). However, the following does work

mkdir -p test/.git
touch test/.git/foo.bar
rm -rf test

Mark

**Comment by corbinlc** [comment]
so directories that currently cannot be deleted are stuck for now, but new directories made by `git` or otherwise should not have this issue after UserLAnd assets automatically update.  Please confirm that if you repeat the stated steps that things are now fine.

**Comment by predragmandic** [comment]
I am experiencing this issue with latest version of UserLand. I can't delete directories cloned using git.

**Comment by wrvsrx** [comment]
Directories cloned using git can't be deleted once being renamed, I reproduce it on v2.8.3. Check #1485
