### ISSUE TITLE
Bug report - Firefox app crash on launch

### ISSUE THREAD

**Issue by Beetix** [CypherpunkArmory/UserLAnd#1105]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug

Firefox crashes on launch.

Output of the terminal inside the VNC session:
```
ExceptionHandler::GenerateDump cloned child 22912
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
beetix@localhost:~$ 2019-11-20 11:16:05: minidump.cc:5098: ERROR: Minidump could not open minidump /home/beetix/.mozilla/firefox/jzbiu8nc.default-esr/minidumps/580d62a4-c668-da8e-3da2-0217c86b1c22.dmp, error 2: No such file or directory
2019-11-20 11:16:05: minidump.cc:5195: ERROR: Minidump cannot open minidump
```

# Steps to reproduce the behavior:

Launch the single click Firefox app

# Device Information

Device: Samsung Tab A (2016), SM-P580
Android Version: 8.1 
UserLAnd Version: 2.6.5 
Device is not rooted running stock ROM.

**Comment by corbinlc** [comment]
Version 2.7.1 just released fixes Firefox.  It should show up for upgrade in the next few hours.
