### ISSUE TITLE
Unable to change shell (with chsh)

### ISSUE THREAD

**Issue by mdowman** [CypherpunkArmory/UserLAnd#111]
Using a clean debian filesystem on a Samsung Galaxy S9 (Oreo 8.0.0) running the following commands

$ sudo apt update
$ sudo apt list --upgradable
$ sudo apt upgrade

$ sudo apt-get install git zsh curl

In this instance installing oh my zsh...

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

... which puts me in a nice zsh prompt but the shell in /etc/passwd has only changed for the root user.

manually running...

$ chsh -s /usr/bin/zsh

... also has the same or no effect.

Additionally when trying to delete " ~/.oh-my-zsh" to attempt a reinstall I encountered the same error as #110 

I did have success manually changing the entry in /etc/passwd but assume the chsh command should work as expected.

**Comment by AdamMatthewLTM** [comment]
@mdowman ,

I ran into a similar issue attempting to replicate yours. I installed ksh and attempted to switch to it with the chsh command, however I received a PAM authentication error after it asked for a password, even as sudo. Manually attempting to change the /etc/passwd file resulted in the same error. Further could you please let me know if you are able to rm any directory or file? This should be a non-issue with the latest build and we're not sure why some people are experiencing it.

Thank you,
-Adam

**Comment by AdamMatthewLTM** [comment]
I am closing this issue because this no longer appears to be a problem. If it crops up again please file a new issue with the details template. Thanks for your consideration,
-Adam

**Comment by corbinlc** [comment]
I think a few things are behaving differently on the S9.  I am looking into this next week.  This may still be an issue

**Comment by af-creations7** [comment]
I edited the file in the home directory

localhost:~$ nano $HOME/.bashrc

Added zsh in the end of the file. And restarted the userland nd it worked

**Comment by OurCodeBase** [comment]
> I edited the file in the home directory
> 
> localhost:~$ nano $HOME/.bashrc
> 
> Added zsh in the end of the file. And restarted the userland nd it worked

Hello @fayaz-modz 
Can you teach me how can I use ohmyzsh in userland application ???

**Comment by fayaz-modz** [comment]
> > I edited the file in the home directory
> > 
> > localhost:~$ nano $HOME/.bashrc
> > 
> > Added zsh in the end of the file. And restarted the userland nd it worked
> 
> Hello @fayaz-modz 
> Can you teach me how can I use ohmyzsh in userland application ???


install the zsh first

`sudo apt install zsh`

then execute this command to download ohmyzsh.

`sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"`

now in the home directory `nano .zshrc`

add a line in the last and type

`zsh`

now ctrl+s to save the file and then press ctrl+x to close.

then refresh the terminal

**Comment by nikmax42** [comment]
Editing `/etc/passwd` worked for me. Thanks for opening this thread
