### ISSUE TITLE
Help - Customize :/

### ISSUE THREAD

**Issue by Morpheus2077** [CypherpunkArmory/UserLAnd#1111]
1. Is possible change color of App.
2. How to change font or remove vibration feedback.
3. Sign in without password.

**Comment by l3laze** [comment]
No idea about changing the color of the app. It doesn't seem to follow the system theme at all, so unless it's updated to do so it won't be easily possible.


Font and vibration feedback should be possible to change through an SSH client, such as [ConnectBot](https://play.google.com/store/apps/details?id=org.connectbot).


Conveniently, passwordless login is also possible with ConnectBot:

* With UserLAnd closed, open ConnectBot.
* Press `Manage PubKeys` -> `+`, enter a nickname for the key, check `Load key on start`, and press `Generate`.
* Long press the generated Pubkey and then hit `Copy public key`, and again for `Load into memory`.

* Start a session in UserLAnd with ConnectBot, and go to the home folder (`/home/username` by default).
* Run `mkdir .ssh`
* Run `echo 'Ctrl + Shift + V' > .ssh/authorized_keys` (but replace <Ctrl + Shift + V> with actually pressing the keys, to paste the copied public key, and be sure to use the single quotes so it's not parsed by the commandline)
* Run `exit` or stop the current UserLAnd session however you'd like.


Now, when you start a session with ConnectBot, it will not need to login but you will be left at a prompt about 1/3 from the top the page.
