### ISSUE TITLE
Firefox crashes from Ubuntu/

### ISSUE THREAD

**Issue by khenty** [CypherpunkArmory/UserLAnd#1112]
# Describe the bug

After I start up the vnc client session, and run firefox from the command line, I get a segmentation fault with an error message, as follows: 

WARNING: failed to open shm: Permission denied: file /build/firefox-JJy9z9/firefox-70.0.1+build1/ipc/chromium/src/base/shared_memory_posix.cc, line 250. 
Segmentation fault.

# Steps to reproduce the behavior:

1. Start up UserLAnd.
2. Start up Ubuntu distribution.
3. Connect to VNC interface, which brings up xfce4 desktop. (I get the same error with the lxde desktop.)
4. Open terminal window.
5. Run "firefox" from the command line in terminal window. 

# Screenshots
N/A

# Device Information
Samsung Galaxy Tab S4 256GB
Android Version: 9
UserLAnd Version: 2.6.5
Device is not rooted.

**Comment by mna99** [comment]
Have the same problem! Or had, rather.  I created an Ubuntu filesystem and connected to it via vnc just as you did.

The problem appears to be one of permissions.  You have to launch Firefox as root.  sudo won't work . . . you need something like gksu/gksudo.  But the gksu package was deprecated as of Ubuntu 18.04.  So what can you do?

Note that I have not fully solved the problem, but I did take some steps to alleviate the issue of permissions.

First, you can add the 17.10 repos which will give you access to the gksu package.  To do this, create the file /etc/apt/sources.list.d/artful.list .  You need the following lines in that file:

deb http://old-releases.ubuntu.com/ubuntu/ artful main universe
deb-src http://old-releases.ubuntu.com/ubuntu/ artful main universe

Then type: sudo apt-get update followed by sudo apt-get install gksu .  With luck, you will have gksu and gksudo commands available at the command line.  Be careful! The first time I installed gksu in my Ubuntu session, the session bombed out with numerous errors, and I could not relaunch it.  The second time I tried it, I installed gksu first, then lxde, and it worked.

Next try running Firefox from command line.  Type: gksudo firefox .

If you have the same problem I have, it will fail to launch, complaining of an RANDR/XRANDR problem.  That is a red herring! XRandr is not causing the problem.  Apparently there is something else preventing Firefox from launching under these circumstances.  Will post again later with more info as I get it.

**Comment by mna99** [comment]
Okay, here is the additional information I wished to post above:

https://ubuntuforums.org/showthread.php?t=982114

Specifically, read the bottom post about trying to run Firefox over tightvncViewer.  It looks like the poster who had the same problem using xrdp found a solution, but that solution does not appear to be applicable to those of us messing with UserLAnd.

**Comment by corbinlc** [comment]
Version 2.7.1 just released fixes Firefox.  It should show up for upgrade in the next few hours.
