### ISSUE TITLE
Feature Request - [Script Repo]

### ISSUE THREAD

**Issue by brettjrea** [CypherpunkArmory/UserLAnd#1117]
# Describe the problem your feature request solves.
Your platform offers Linux on Android and that can open up doors to many creative and useful scripts, I have wrote such a script [Techintheclouds/Android-UserLand-LAMP-Wordpress](https://github.com/Techintheclouds/Android-UserLand-LAMP-Wordpress) but I had to email support regarding a place for it to affiliate with you guys.

# Describe the solution you'd like 
I would suggest a repo or wiki of some sort both in and outside of the app that is a list of community driven scripts. This could really allow your app to drive some really novel solutions advance linux education and open new areas of interest for the team, maybe a script that sets up a jupyter notebook? 

# Describe alternatives you've considered
I don't really know of much alternatives accept hosting my own repos or wiki.

Please add any other context or screenshots you think might help us resolve your issue.

**Comment by richiecast** [comment]
Hasta lavista. Arnold palmer

**Comment by brettjrea** [comment]
Closed unanswered.
