### ISSUE TITLE
Cannot open a session without internet access after a reboot

### ISSUE THREAD

**Issue by wyatt8740** [CypherpunkArmory/UserLAnd#113]
I'm out of the country where I have a cellular data plan, and I was unable to start a new SSH or VNC session (with an existing environment that I had used before) after rebooting my phone until I connected to a wifi network.

This might be something else wrong on my end, but I can only confirm what I have experienced. Tapping to start a new session resulted in absolutely nothing happening when offline.

**Comment by MatthewTighe** [comment]
This is fixed in the upcoming release.
