### ISSUE TITLE
Bug report - Installing Hollywood Terminal

### ISSUE THREAD

**Issue by roshanravan** [CypherpunkArmory/UserLAnd#1148]
# Describe the problem your feature request solves.

I can successfully install the package but it doesn't run

i used:
$ sudo apt-get install byobu hollywood

# Describe the solution you'd like 
which shows it is downloading some packages but doesn't run hollywood

# Describe alternatives you've considered

$ sudo apt-get install byobu
$ sudo apt install hollywood

**Comment by corbinlc** [comment]
Can you connect via vnc and try to run hollywood?  The terminal manager won't work in an ssh session.

**Comment by roshanravan** [comment]
Actually I am now using Termux and installed Hollywood pkg there,

**Comment by corbinlc** [comment]
Sounds like you no longer need this and this is pretty low priority to investigate given the application.  Also, I tried this on an Ubuntu install inside UserLAnd and it mostly worked (sometimes quit after a while) in an SSH session and in a VNC session.
