### ISSUE TITLE
Application Stops at StartUP

### ISSUE THREAD

**Issue by keyiflerolsun** [CypherpunkArmory/UserLAnd#1167]
# Screenshots 

![Screenshot_2020-01-20-14-54-19-227_com miui bugreport](https://user-images.githubusercontent.com/57468649/72724713-28450800-3b95-11ea-8795-0762363ddd41.png)
# Device Information

Device: [Xiaomi Redmi Note 6 Pro].  
Android Version: [Pie, 9.0].  
UserLAnd Version [2.6.5].  
Whether the device is rooted.

**Comment by doggukan** [comment]
Change your phone language to english refresh apps and switch back to turkish.Telefon ingilizce olunca crash olmuyor.yenile tekrar turkce yap
