### ISSUE TITLE
Help - Remind people to prominently connect to ssh using port 2022

### ISSUE THREAD

**Issue by jiayaoO3O** [CypherpunkArmory/UserLAnd#1170]
# Remind people to prominently connect to ssh using port 2022
I spent a lot of time trying to connect to the system from the outside using ssh. I didn't know that I needed to use port 2022 until I was on github. I think this is a very important information and should be prompted inside the app, otherwise there will be more people Thought the port used was 22, thanks : )

**Comment by 0atman** [comment]
I second this
