### ISSUE TITLE
Help - disabling the special keys bar (esc, ctrl) at the bottom of the screen - WITHOUT physical volume buttons

### ISSUE THREAD

**Issue by 0atman** [CypherpunkArmory/UserLAnd#1175]
Similar to #892
Any idea how to hide this bar it if your device doesn't have physical volume keys? Thanks!

# Describe the issue you are having.
I can't hide the special soft keys

# Describe how your task behaves in a regular Linux environment
na

**Comment by 5p0ng3b0b** [comment]
You could try from android terminal perhaps.
Volume up: `input keyevent 24`. Volume down `input keyevent 25`.
Sorry I can't test because of bug #1013

**Comment by bones4cats** [comment]
IIRC and this hasnt been patched, you can open the side bar (swipe left from terminal) and hold the `keyboard` button, that should do

**Comment by 0atman** [comment]
This works! Thank you so much!!
