### ISSUE TITLE
Bug report - [apt install midori eroor Start via TCSAFLUSH for]

### ISSUE THREAD

**Issue by charlybone** [CypherpunkArmory/UserLAnd#1215]
help

![Screenshot_20200502-093934_UserLAnd](https://user-images.githubusercontent.com/64667841/80852179-188b9400-8c59-11ea-9327-4c8163b3bea8.jpg)

**Comment by corbinlc** [comment]
Use `sudo apt update` and `sudo apt install`. Without `sudo`, you cannot use `apt`.

**Comment by corbinlc** [comment]
Please close the issue if that helps
