### ISSUE TITLE
Bug report - [Help userland browser mozilla firefox blank not respond]

### ISSUE THREAD

**Issue by charlybone** [CypherpunkArmory/UserLAnd#1216]
help
![Screenshot_20200502-152952_VNC Viewer](https://user-images.githubusercontent.com/64667841/80858150-04ac5600-8c8a-11ea-84bb-bd646beb3bb7.jpg)

**Comment by corbinlc** [comment]
What version of UserLAnd do you have installed?  How are you installing and launching Firefox?

**Comment by corbinlc** [comment]
Version 2.7.1 fixed a similar issue.  I am closing this.  Tell me if it is still a problem
