### ISSUE TITLE
Today's upgrade broke Wolfram Mathematica --- Segmentation fault

### ISSUE THREAD

**Issue by tigran123** [CypherpunkArmory/UserLAnd#1217]
After today's upgrade I cannot start Wolfram Mathematica --- the only application that I need UserLAnd for. Trying to start it results in "Segmentation fault". I suspect it is caused by the recent fixes to support some programs (node and something else).

The device I am using is Samsung Galaxy Tab S4, Android 9.

Just in case more info is needed, it is in #867

**Comment by tigran123** [comment]
I found on apkpure versions 2.7.0 and 2.6.5 of UserLAnd, but it is such a big job to re-install everything from scratch (though I can backup my filesystem I suppose)... So, I'll wait and see, maybe you guys will fix this problem.

**Comment by tigran123** [comment]
Here is some more information:

```
$ file cp
cp: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=7527ff4479e970d9bda0929ccd8d2c0a0511b78c, stripped
$ ./cp
Segmentation fault
$ strace ./cp
execve("./cp", ["./cp"], [/* 14 vars */]) = -1 EFAULT (Bad address)
exit(182)                               = ?
+++ exited with 182 +++
```

So, if I execute the simplest armhf binary like `cp` it fails with EFAULT.

**Comment by tigran123** [comment]
Good news: I installed version 2.7.0 apk of UserLAnd and Mathematica works again! Now I have a static application that is not going to be overwritten by update. For those who wish to follow the steps to install Wolfram Mathematica on Android in UserLAnd here are the three libraries you need to copy from the Raspberry Pi: `libgmp.so.10.3.2`, `libstdc++.so.6.0.22`, `libz.so.1.2.8` to `/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM` and make the symlinks with the major version (like `libz.so.1 -> libz.so.1.2.8` etc).

**Comment by tigran123** [comment]
Btw, attempting to start the GUI frontend gives this error:

```
Qt issued a fatal error: This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.
```

Any ideas how one might fix this? I tried setting `QT_DEBUG_PLUGINS=1` but there are no error messages that would clarify the problem (i.e. all the loading steps succeed).

**Comment by corbinlc** [comment]
Version 2.7.2 should restore the functionality that I broke.  Can you confirm that?  Also, can you send me a quick script that does exactly what you do to install mathematica?  I can add a test case, or even and app and confirm I don't break this in the future.  Sorry.

**Comment by tigran123** [comment]
Thank you. I only saw this today. I will test it and get back to you.

**Comment by tigran123** [comment]
Yes, I confirm that the text-based Wolfram Engine ("math" or "wolfram" command) works fine with UserLAnd version 2.7.2. Here is the script to make the symlinks in `/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/`:

```
ln -s libasound.so.2.0.0 libasound.so.2
ln -s libbsd.so.0.8.3 libbsd.so.0
ln -s libdbus-1.so.3.14.16 libdbus-1.so.3
ln -s libdrm.so.2.4.0 libdrm.so.2
ln -s libexpat.so.1.6.2 libexpat.so.1
ln -s libffi.so.6.0.4 libffi.so.6
ln -s libfontconfig.so.1.8.0 libfontconfig.so.1
ln -s libfreetype.so.6.12.3 libfreetype.so.6
ln -s libgcrypt.so.20.1.6 libgcrypt.so.20
ln -s libglapi.so.0.0.0 libglapi.so.0
ln -s libglib-2.0.so.0.5000.3 libglib-2.0.so.0
ln -s libGL.so.1.2.0 libGL.so.1
ln -s libgmp.so.10.3.2 libgmp.so.10
ln -s libgobject-2.0.so.0.5000.3 libgobject-2.0.so.0
ln -s libgpg-error.so.0.21.0 libgpg-error.so.0
ln -s libgraphite2.so.3.0.1 libgraphite2.so.3
ln -s libgthread-2.0.so.0.5000.3 libgthread-2.0.so.0
ln -s libharfbuzz.so.0.10400.2 libharfbuzz.so.0
ln -s libhunspell-1.4.so.0.0.0 libhunspell-1.4.so.0
ln -s libicudata.so.57.1 libicudata.so.57
ln -s libicui18n.so.57.1 libicui18n.so.57
ln -s libicuuc.so.57.1 libicuuc.so.57
ln -s libjack.so.0.1.0 libjack.so.0
ln -s liblz4.so.1.7.1 liblz4.so.1
ln -s liblzma.so.5.2.2 liblzma.so.5
ln -s libopus.so.0.5.3 libopus.so.0
ln -s libpcre16.so.3.13.3 libpcre16.so.3
ln -s libpcre.so.3.13.3 libpcre.so.3
ln -s libpixman-1.so.0.34.0 libpixman-1.so.0
ln -s libpng16.so.16.28.0 libpng16.so.16
ln -s libportaudio.so.2.0.0 libportaudio.so.2
ln -s libstdc++.so.6.0.22 libstdc++.so.6
ln -s libsystemd.so.0.17.0 libsystemd.so.0
ln -s libX11.so.6.3.0 libX11.so.6
ln -s libX11-xcb.so.1.0.0 libX11-xcb.so.1
ln -s libXau.so.6.0.0 libXau.so.6
ln -s libxcb-dri2.so.0.0.0 libxcb-dri2.so.0
ln -s libxcb-dri3.so.0.0.0 libxcb-dri3.so.0
ln -s libxcb-glx.so.0.0.0 libxcb-glx.so.0
ln -s libxcb-present.so.0.0.0 libxcb-present.so.0
ln -s libxcb.so.1.1.0 libxcb.so.1
ln -s libxcb-sync.so.1.0.0 libxcb-sync.so.1
ln -s libXdamage.so.1.1.0 libXdamage.so.1
ln -s libXdmcp.so.6.0.0 libXdmcp.so.6
ln -s libXext.so.6.4.0 libXext.so.6
ln -s libXfixes.so.3.1.0 libXfixes.so.3
ln -s libxshmfence.so.1.0.0 libxshmfence.so.1
ln -s libXxf86vm.so.1.0.0 libXxf86vm.so.1
ln -s libz.so.1.2.8 libz.so.1
```

Strictly speaking you need only three libraries `libz`, `libstdc++`, `libgmp` but I copied also those required by the GUI frontend (command "mathematica").

Also, you need to edit the scripts (math, mathematica, wolfram etc) like this to get rid of "Cannot determine operating system" error:

```
$ diff -u math.0 math
--- math.0	2020-05-07 12:05:11.298999496 +0100
+++ math	2020-05-07 12:05:19.848999493 +0100
@@ -26,7 +26,7 @@
 					else
 						SystemIDList="Linux-x86-64 Linux"
 					fi;;
-				armv?l)
+				aarch64|armv?l)
 					SystemIDList="Linux-ARM";;
 				*)
 					SystemIDList="Unknown";;
```

All this is related to version 11.2 only. If I try to run version 12.0 kernel then it fails with:

```
/home/tigran/Wolfram/WolframEngine/12.0/SystemFiles/Kernel/Binaries/Linux-ARM/WolframKernel: error while loading shared libraries: libopenblas.so.0: cannot enable executable stack as shared object requires: Permission denied
```

As far as I know this is related to the selinux being, unfortunately, enabled on Android. But maybe I am mistaken and there is some way to overcome this also? That would be nice, but not super-important as version 11.2 is not inferior to 12.0 in any major way. What would be really nice is to get the frontend to work, which currently fails in this way:

```
$ export QT_DEBUG_PLUGINS=1
$ mathematica
ERROR: ld.so: object '/support/libdisableselinux.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
QFactoryLoader::QFactoryLoader() checking directory path "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer" ...
QFactoryLoader::QFactoryLoader() looking at "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqconnmanbearer.so"
Found metadata in lib /opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqconnmanbearer.so, metadata=
{
    "IID": "org.qt-project.Qt.QBearerEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "connman"
        ]
    },
    "className": "QConnmanEnginePlugin",
    "debug": false,
    "version": 329218
}


Got keys from plugin meta data ("connman")
QFactoryLoader::QFactoryLoader() looking at "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqgenericbearer.so"
Found metadata in lib /opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqgenericbearer.so, metadata=
{
    "IID": "org.qt-project.Qt.QBearerEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "generic"
        ]
    },
    "className": "QGenericEnginePlugin",
    "debug": false,
    "version": 329218
}


Got keys from plugin meta data ("generic")
QFactoryLoader::QFactoryLoader() looking at "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqnmbearer.so"
Found metadata in lib /opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqnmbearer.so, metadata=
{
    "IID": "org.qt-project.Qt.QBearerEngineFactoryInterface",
    "MetaData": {
        "Keys": [
            "networkmanager"
        ]
    },
    "className": "QNetworkManagerEnginePlugin",
    "debug": false,
    "version": 329218
}


Got keys from plugin meta data ("networkmanager")
loaded library "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqconnmanbearer.so"
loaded library "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqgenericbearer.so"
loaded library "/opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM/Qt-Plugins/bearer/libqnmbearer.so"
Qt issued a fatal error: This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: linuxfb, minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted
```

Also, I think we were not getting this warning/error with UserLAnd 2.7.0:

```
ERROR: ld.so: object '/support/libdisableselinux.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

Is this benign or could it cause some problem?

**Comment by tigran123** [comment]
Closing the issue as you have fixed it already. Thank you again! :)

**Comment by tigran123** [comment]
Re-opening the issue as the problem is back with UserLAnd 2.7.3 version. Again, even the simplest executable like cp causes Segmentation fault, just like before:

```
$ uname -a
Linux localhost 3.18.41+ #11 SMP PREEMPT Fri Aug 24 14:57:08 CST 2018 aarch64 GNU/Linux
$ ./cp
ERROR: ld.so: object '/support/libdisableselinux.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Segmentation fault
```

I am glad I didn't upgrade my main tablet to 2.7.3 -- it is running 2.7.2 and everything is perfect there.

**Comment by tigran123** [comment]
UPDATE: Installing version 2.7.2 on this tablet (Android 7.1.1) did NOT solve the problem, i.e. `cp` binary from Raspberry Pi still coredumps.

**Comment by corbinlc** [comment]
I see the issue.  I should be able to fix it fairly quickly.  I haven't had any test case for this in the past, but am building an app that will need this feature working, so it probably won't get broken yet again.

**Comment by tigran123** [comment]
Any ideas if the fix is coming soon? Without the fix we are stuck with Wolfram Engine 11.2 on Android 7.1.1, but with the fix we should be able to run Wolfram Engine 12.1 (as it works fine on Android 9 with UserLand 2.7.3).

**Comment by tigran123** [comment]
I have just upgraded UserLAnd to 2.8.3 and this problem is still not fixed.

**Comment by corbinlc** [comment]
I added back the arm loader when on an arm64 device a while ago.
