### ISSUE TITLE
How can I connect android userLand ubuntu via my mac ssh?

### ISSUE THREAD

**Issue by dev4mobile** [CypherpunkArmory/UserLAnd#1222]
# How do userLand ubuntu ssh connect from my mac ssh client
- I have installed ssh on ubuntu(apt install -y ssh) and config port 2223, when I exec command `ssh root@192.168.1.7 -p 2223`, the result is `ssh: connect to host 192.168.1.7 port 2223: Connection refused`
- I want connect ubuntu ssh via mac ssh client, but I can't find a good way to handle it

**Comment by Yrosenz** [comment]
Are you sure you have the sshd running?

**Comment by Yrosenz** [comment]
If not mistaking Userland have the ssh server on port 2022. At least my one works on that port.

**Comment by soiqualang** [comment]
> If not mistaking Userland have the ssh server on port 2022. At least my one works on that port.

Thanks many! , I can ssh to my Android UserLAnd via `2022` port

**Comment by mobagenie** [comment]
> If not mistaking Userland have the ssh server on port 2022. At least my one works on that port.

damn simple think but really hard to solve. thx for solving my problem.

**Comment by EasternPA** [comment]
Can anyone tell me the default password? I can't guess any passwords successfully. I set a new password at the command prompt on the phone, and that won't work. I added my public key to .ssh/authorized_keys, which isn't working either. I'm stumped. Any clues? Thanks!

**Comment by bat52** [comment]
what is the default password ?

**Comment by mitic0320** [comment]
> 

You can change the password of `root`:
```
sudo passwd root
```

**Comment by startersaas** [comment]
> If not mistaking Userland have the ssh server on port 2022. At least my one works on that port.

Bump great Answer working Ty!!!

**Comment by aplotor** [comment]
> what is the default password ?

default password of `userland` user can be found at: "Filesystems" ➔ hold on "apps" ➔ "Edit" ➔ tap the eye icon in the "Password" field to reveal the password

**Comment by bharathrajviswa** [comment]
Old package versions (8.9p1-3ubuntu0.1, 3.0.2-0ubuntu1.8, etc.) that no longer exist on the mirror, so the server correctly returns **404 Not Found.**

`sudo rm -rf /var/lib/apt/lists/*
sudo apt clean
sudo apt update
sudo apt install -y openssh-server`
