### ISSUE TITLE
Feature Request - [HOW TO ACCESS FILES STORED ON SDCARD]

### ISSUE THREAD

**Issue by Ravi-verma-97** [CypherpunkArmory/UserLAnd#1237]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the problem your feature request solves.
How can i use files stored on sdcard in download folder into octave ?

# Describe the solution you'd like 
a simple way to access files on sdcard

# Describe alternatives you've considered
N/A

**Comment by catitisbone** [comment]
this needs a bit technical know-how in android filesystems but here it is, first type su to be root (not really but it avoids unnessesary permission problems) and change to root directory, `su` and then `cd /`
after that look for 'host-rootfs', cd into this and ls, permission denied right?
that is the root of your device so to go to your sd card you should use something like `cd /host-rootfs/sdcard` or even `cd /host-rootfs/storage/emulated/0`

**Comment by Ravi-verma-97** [comment]
ooh great..! Thanks for solving my problem.
