### ISSUE TITLE
Bug report - Unable to Install UFW. Iptables don't work

### ISSUE THREAD

**Issue by drshaktiyadav** [CypherpunkArmory/UserLAnd#1241]
# Describe the bug

Tried to install ufw with kali and ubuntu and got permission error citing Issue with iptables. Exact code and error below

# Steps to reproduce the behavior:
lazypanda@localhost:~$ sudo ufw status
ERROR: problem running iptables: iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

lazypanda@localhost:~$ iptables -L
iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

lazypanda@localhost:~$ sudo iptables -L
iptables v1.6.1: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

# Screenshot
N/A

# Device Information

Device: [e.g. Redmi Note 8 Pro].  
Android Version: [e.g. 9.0].  
UserLAnd Version [e.g. 0.1.2].  
Whether the device is rooted - No
Whether the device is running MIUI 11

Apparently arm version of kali and ubuntu have some issues with iptables legacy and nft versions of ip table
Trying to move legacy and symlink as default might fix it.

**Comment by drshaktiyadav** [comment]
Updated

**Comment by desyncr** [comment]
@drshaktiyadav I had the same issue. Unfortunately UserLAnd doesn't run as root so it can't change iptables.

As a workaround I used Termux (with root privileges) and run iptables there.
