### ISSUE TITLE
Help - unable to set execute permission of compiled binary

### ISSUE THREAD

**Issue by vasid99** [CypherpunkArmory/UserLAnd#1285]
# Describe the issue you are having.

I am trying to execute a simple Hello World on UserLAnd Ubuntu SSH using C (`gcc`).

The compilation occurs successfully, but the compiled binary cannot be executed because it does not have execute permission, which even `sudo chmod` cannot alter.

![Screenshot_20200826-005654_UserLAnd.jpg](https://user-images.githubusercontent.com/11539360/91218706-16cd6b00-e737-11ea-8532-5b29b89f6d1b.jpg)

Note that I can execute Python scripts just fine, as shown in the last two commands of the image.

I have come to know from online resources that the `exec()` function cannot be used without root from Android Q onwards, and it is necessary in order to execute binaries. Does this mean that no compiled binaries can be executed in UserLAnd?

Also, I did not find any previous issues related to this, so is there something that I'm doing differently?

# Describe how your task behaves in a regular Linux environment

In regular Ubuntu Linux, the compiled binary has execute permission because it is not restricted by the OS, and so executes as expected and prints the output.

**Comment by Herzogs** [comment]
If you don't give it execution permissions it will never run, to give it the permissions you must do ```
sudo chmod +x ./a.out
```

**Comment by Herzogs** [comment]
The only way that I see that I run you is that the cell phone is root
