### ISSUE TITLE
Netdiscover and some features of nmap not working

### ISSUE THREAD

**Issue by raheemmuizz** [CypherpunkArmory/UserLAnd#1295]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug
     When I try os fingerprinting on nmap with an ip address regardless if I use SU or sudo command for root it throws up an error.
     Also if I use netdiscover for range or network discovery for any ip address it doesn't work also

# Steps to reproduce the behavior:

A list of **exact** steps to reproduce the behavior. If we cannot follow the steps to recreate the issue, we won't be able
to help you.

For example:
1. 'Su' command for login as root

2. For nmap: root@localhost:~# nmap -O 127.0.0.1 (changed the original ip for security reasons)
 Starting Nmap 7.80 ( https://nmap.org ) at 2020-09-24 12:04 UTC
route_dst_netlink: can't find interface "tun0"
   For netdiscover: root@localhost:~# netdiscover -r 127.0.0.1
Couldn't find default device: ccmni0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Permission denied  (I changed the original ip address for security purposes)

# Screenshots
   Nmap error: route_dst_netlink: can't find interface "tun0"
   Netdiscover error: Couldn't find default device: ccmni0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Permission denied

# Device Information

Device: [e.g. umidigi A7 pro].  
Android Version: [ Android 10].  
UserLAnd Version [2.7.3].  
Not rooted.  
No lineage os

I know most network tools will need root to function but if there are any workaround this as it works on metasploit I will be very happy, I need those tools badly :)

**Comment by dave636** [comment]
Please always close issues with a simple comment. [E.g. Command not supported due to unrooted device...etc.]
