### ISSUE TITLE
How to setup mic in userland

### ISSUE THREAD

**Issue by valizadeidin** [CypherpunkArmory/UserLAnd#1322]
I need for my schol it so good but i need mic 
How to have mic in linux?

**Comment by fbarda** [comment]
If you want to use your phone as a mic to your PC, try [Droidcam](https://github.com/dev47apps/droidcam).
It will be annoying but you can use it in inside a UserLAnd session with Droidcam on "WiFi" mode.

**Comment by valizadeidin** [comment]
thanks
