### ISSUE TITLE
Qt does not work

### ISSUE THREAD

**Issue by a20god** [CypherpunkArmory/UserLAnd#133]
Running an application (such as qgit) that uses Qt fails with this error message:
>error while loading shared libraries: libQt5Gui.so.5: cannot enable executable stack as shared object requires: Permission denied

Android version: 7.1.1

**Comment by bet** [comment]
When I figured out how to build perl6 within Gnuroot Debian, I tripped over this, there's a compiler option LDFLAGS=-Wl,-z,noexecstack that worked for that.

**Comment by a20god** [comment]
qgit works in GNURootDebian indeed.

**Comment by corbinlc** [comment]
This looks the same as #49

**Comment by AdamMatthewLTM** [comment]
I am closing this issue, please see thread #49 for all other updates.
