### ISSUE TITLE
vncserver: accept: Function not implemented

### ISSUE THREAD

**Issue by a20god** [CypherpunkArmory/UserLAnd#134]
I used vncserver for about 150 minutes and got more than 300,000,000 error messages in .vnc/localhost:1.log (about 20 Gigabytes!), all reading like this:
> rfbCheckFds: accept: Function not implemented

**Comment by corbinlc** [comment]
Interesting.  I have marked this as high priority because log files of that size are going to be a problem fast

**Comment by corbinlc** [comment]
I believe this has to do with seccomp filtering of certain system calls added in android 8.0+

**Comment by corbinlc** [comment]
There is already a work around for accept not being allowed by seccomp filtering.  It also didn't occur on the first device I tried.  Can you do a couple of things...
1) provide more info.  What device are you using?  What version of android are you using?  What version of our app are you using?  
2) Enable proot logging from the settings menu and set the verbosity to 9 and then run for few minutes until there are some of these errors in the vnc log and then send the /sdcard/PRoot_Debug_Log to us.

**Comment by a20god** [comment]
Device: Planet Gemini
Android version: 7.1.1
UserLAnd version: unknown. has been updated in the meantime. It was the latest version available from the play store at the time of the report.

I've enabled logging. but the problem has not yet cropped up.

**Comment by a20god** [comment]
The problem still hasn't occurred again. In the meantime, here's the beginning of the vncserver log file:
[localhost:1.log](https://github.com/CypherpunkArmory/UserLAnd/files/2266525/localhost.1.log)

**Comment by a20god** [comment]
src/syscall/seccomp.c sets a filter for accept and accept4:
>	{ PR_accept,		FILTER_SYSEXIT },
>	{ PR_accept4,		FILTER_SYSEXIT },

but src/tracee/seccomp.c handles accept only (not accept4):
>	switch (sysnum) {
>	case PR_accept:
>		prepare_restart_syscall_after_seccomp(tracee);

That is, PR_accept4 is handled here:

>	default:
>		/* Set errno to -ENOSYS */
>		set_result_after_seccomp(tracee, -ENOSYS);

Could this be the culprit?

**Comment by corbinlc** [comment]
I don't think that is it as we actually turn accept->accept4 when seccomp filtering denies accept, but i will look into this
need to figure out how to replicate

**Comment by corbinlc** [comment]
is this still an issue?

**Comment by a20god** [comment]
It hasn't happened again.

**Comment by corbinlc** [comment]
i am closing this now because i have no idea if it is fixed (probably not) but also no idea how to repeat this and collect more data.  if anyone is seeing this again and definitely if someone knows how i can recreate this for debugging, please reopen this issue.
