### ISSUE TITLE
Help - node error - libc.so invalid ELF header

### ISSUE THREAD

**Issue by moshpirit** [CypherpunkArmory/UserLAnd#1344]
# Describe the issue you are having.

I'm using UserLand to run debian on my Samsung Galaxy S7 Edge with XFCE. One of the things I want with this is to use it as a host for a discord bot. In order to do that, I need `node` and `npm`. I installed both. Here is my problem: I need to install `discord.js` but when I type `sudo npm install discord.js` I get this message: `node: error while loading shared libraries: /usr/lib/aarch64-linux-gnu/libc.so: invalid ELF header` (IDK why `aarch64` though). 

# Describe how your task behaves in a regular Linux environment

N/A. I did this on my Manjaro Plasma laptop and I encountered no issues that I can recall.

**Comment by sanderjo** [comment]
Wrong binary: binary for a different CPU architecture than you  have?

**Comment by sanderjo** [comment]
So ... what was it? Not so useful to close an issue like that.

**Comment by moshpirit** [comment]
Sorry, I couldn't check it out and probably won't until few weeks because something came up and thought that you didn't want many open issues, some devs don't like that 😅  I'll try to give you an answer ASAP
