### ISSUE TITLE
Text Editor is Missing in Kali OS

### ISSUE THREAD

**Issue by tajamulsheeraz** [CypherpunkArmory/UserLAnd#1354]
Hi Cypher,

Greetings!

I have identified that the text editors(nano, vi, vim) are missing in Kali linux OS running on UserLand.

**Comment by onceagainifindmyselfhere** [comment]
I'm starting to wonder if these issues remain open because if you cant fix them you're not proficient enough to run kali securely

**Comment by tajamulsheeraz** [comment]
> I'm starting to wonder if these issues remain open because if you cant fix them you're not proficient enough to run kali securely

LOL

Thank you for your motivational comments.

Remember you were a beginner once.

**Comment by stephenprater** [comment]
@onceagainifindmyselfhere Let's all play nice, okay?

@tajamulsheeraz Unfortunately, nobody is working full time on UserLAnd anymore, so the likelihood that someone will address this issue for you in the prebuilt Kali images is pretty low.  You should consult your search engine of choice to learn about how to install a text editor into your session.  

A good example of an an appropriate issue for this repo would be a crash or error when trying to install a text editor.
