### ISSUE TITLE
Bug report - CANT UPDATE

### ISSUE THREAD

**Issue by jazuly** [CypherpunkArmory/UserLAnd#1357]
# Describe the bug

i using kali, when trying to `apt update` it says "signature were invalid". and i try to update the signature with `wget -q -O - https://archive.kali.org/archive-key.asc  | apt-key add -` it says wget not found..

# Steps to reproduce the behavior:
typing `apt update`  after fresh install..

**Comment by onceagainifindmyselfhere** [comment]
Pretty sure its because the repos url doesn't have a secure connection. Trying to edit but no dedicated text editor.

**Comment by Tisa9** [comment]
Same issue here.
We can fix it refering this link : 
https://unix.stackexchange.com/questions/421821/invalid-signature-for-kali-linux-repositories-the-following-signatures-were-i

But all command are missing even VIM... 
Can you please add vim / wget / gpg : In fact all basics ?

Thank you !

**Comment by corbinlc** [comment]
I have update the Kali image being used by UserLAnd.  There were 3 issues:
1) The old image did not have the latest package keys (https://http.kali.org/kali/pool/main/k/kali-archive-keyring)
2) The old image did not have wget or similar installed so it was not easy to pull the latest keys and fix this issue yourself.
These are both now fixed.
There is another issue that is not fixed...
3) After `sudo apt upgrade` basic applications, like `ls` stop working.
I have not solved the last issue yet, so don't do an `sudo apt upgrade`, just do `sudo apt update; sudo apt install package_of_interest`
