### ISSUE TITLE
Unable to install net tools

### ISSUE THREAD

**Issue by shady003** [CypherpunkArmory/UserLAnd#1367]
404  Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1_arm64.deb  404  Not Found [IP: 192.99.200.113 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? This is what I'm getting while installing net-tools

**Comment by rogerio77** [comment]
I have the same issue after the execute the following command
sudo apt install net-tools
![imagen](https://user-images.githubusercontent.com/35785359/113454986-ea21b600-93df-11eb-904a-ee7507bec7b0.png)

**Comment by rogerio77** [comment]
this command did't work neither 
sudo apt update
![imagen](https://user-images.githubusercontent.com/35785359/113455114-35d45f80-93e0-11eb-8362-bf13d79283f3.png)

**Comment by rogerio77** [comment]
I forgot to add that issue is in Kali Linux

**Comment by corbinlc** [comment]
I have update the Kali image being used by UserLAnd.  There were 3 issues:
1) The old image did not have the latest package keys (https://http.kali.org/kali/pool/main/k/kali-archive-keyring)
2) The old image did not have wget or similar installed so it was not easy to pull the latest keys and fix this issue yourself.
These are both now fixed.
There is another issue that is not fixed...
3) After `sudo apt upgrade` basic applications, like `ls` stop working.
I have not solved the last issue yet, so don't do an `sudo apt upgrade`, just do `sudo apt update; sudo apt install package_of_interest`

**Comment by onceagainifindmyselfhere** [comment]
Userland Kali is so minimal that if you dont know how to fix that its not
worth it. Try nethunter for termux
