### ISSUE TITLE
Help - [Can't install net-tools and do an update in Kali Linux]

### ISSUE THREAD

**Issue by rogerio77** [CypherpunkArmory/UserLAnd#1371]
# Describe the issue you are having.

after execute this two commands I got theses errors
sudo apt update
sudo apt install net-tools
![imagen](https://user-images.githubusercontent.com/35785359/113455998-6ddca200-93e2-11eb-8558-b5c885ab7c6c.png)
![imagen](https://user-images.githubusercontent.com/35785359/113456012-78973700-93e2-11eb-8d3e-58c54b8c686a.png)

Moto Z Play - Android 8   (unrooted)
Moto Z2 Play - Android  9 (rooted)

# Describe how your task behaves in a regular Linux environment

As you can see in the screens every time I got these errros

**Comment by corbinlc** [comment]
I have update the Kali image being used by UserLAnd.  There were 3 issues:
1) The old image did not have the latest package keys (https://http.kali.org/kali/pool/main/k/kali-archive-keyring)
2) The old image did not have wget or similar installed so it was not easy to pull the latest keys and fix this issue yourself.
These are both now fixed.
There is another issue that is not fixed...
3) After `sudo apt upgrade` basic applications, like `ls` stop working.
I have not solved the last issue yet, so don't do an `sudo apt upgrade`, just do `sudo apt update; sudo apt install package_of_interest`

**Comment by SHAHID919** [comment]
thanks for information
