### ISSUE TITLE
What happened to UserLAnd

### ISSUE THREAD

**Issue by ghost** [CypherpunkArmory/UserLAnd#1429]
The release was 1 year ago, Does it project abandoned?

**Comment by omxpro** [comment]
> The release was 1 year ago, Does it project abandoned?

Who knows, I am trying to find a better alternative

**Comment by tigran123** [comment]
In Andronix one gets the same issue with Raspberry Pi binaries coredumping, just like in UserLAnd on Android 7. Well, at least we have it working on Android 9 on Samsung Galaxy Tab S4, so that is the only decent tablet at present. I've just bought another one of those, for my daughter :)

**Comment by corbinlc** [comment]
UserLAnd is still being developed.  There is only one developer though, other than minor other contributions, so things will be slow.  That said, a lot has improved since this issue was filed.
