### ISSUE TITLE
Which SSH port Userland uses now?

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#1450]
Dear developers,
Please, who of us will tell Me, which port number Userland uses now? I can not determine its number by reading initialisation screen by using screen reader. No port number. As A result, I can not connect remotely without using internal client. Who of us will tell Me The secret or where port number is stored, so I could find it?
Thank you.

**Comment by corbinlc** [comment]
No.  It just requests a username and password.  We should switch to using keys later.
