### ISSUE TITLE
Help - DEBIAN / Caution skipping local host check for localhost

### ISSUE THREAD

**Issue by agiltriono** [CypherpunkArmory/UserLAnd#1471]
# Describe the issue you are having.
I have working at nodejs project with debian distribution still looks fine for me when doing some coding, but everytime i open the terminal the output say `skipping host key for localhost`

# What you are trying to accomplish
 I was trying to eliminate this caution message when launch the command line

# What you have tried so far
I've been trying to figured it out i think this is cause the environment missing ?
Note that this is not affect on any working project.

But this seems a bit crazy when opening the terminal everytime..

# Describe how your task behaves in a regular Linux environment
Running this distribution on my old phone MIUI3 PRO

This is when i open the terminal
![Screenshot_2021-12-16-20-51-25-024_tech ula](https://user-images.githubusercontent.com/7345591/146384859-37e00b2d-0b29-4a73-8a81-c17f6d578d36.png)

**Comment by oskar-skog** [comment]
I think it's just a warning from the ssh client.  Normally it would ask you to verify that the ssh fingerprint of the server is correct, but it skips the check because it knows there can't be a MITM attack.  (SSH to localhost on the *correct* port number is guaranteed to be the real server and not an attacker)

**Comment by agiltriono** [comment]
> I think it's just a warning from the ssh client. Normally it would ask you to verify that the ssh fingerprint of the server is correct, but it skips the check because it knows there can't be a MITM attack. (SSH to localhost on the _correct_ port number is guaranteed to be the real server and not an attacker)

Is that possible to disable this ssh warning notification ? Maybe i should ignore it. Thank you.
