### ISSUE TITLE
sudo broken on new Ubuntu filesystem

### ISSUE THREAD

**Issue by tjwieg** [CypherpunkArmory/UserLAnd#150]
Just got an update to the app via play store and saw that Ubuntu is now supported. Fired up a new Ubuntu filesystem, logged in, and tried to `sudo apt-get update` but it threw an error.

![screenshot of the error message](https://i.imgur.com/Ea1ovB4.jpg)

Same error persisted even after a `su; apt-get update; apt-get upgrade` and all packages brought up to date.

I'm running on a Samsung Galaxy S9, Snapdragon 845, Android 8.0.0.

**Comment by corbinlc** [comment]
I wonder if the version of PRoot you are using didn't update along with the release.  Not sure why that would be, but if you stop all sessions and then long press on the session of interest, you should be able to force an update.  Please see if that changes anything.

**Comment by tjwieg** [comment]
Updated assets, turned on debug logs, and set verbosity to 9. Opened Ubuntu
service, logged in, and tried both `sudo sl /` (because I have fat fingers,
haha) and `sudo ls /`

**Comment by corbinlc** [comment]
Did sudo now work?  If not, can you provide the log file.

**Comment by tjwieg** [comment]
Apologies, log didn't post like I thought. It still didn't work. Apparently the log was too long for GitHub, ha.

Here's the log: https://paste.ee/p/mXmQW

**Comment by Root-voidX** [comment]
I noticed that too, in order to do anything requiring sudo i had to first su and then do the command.

**Comment by corbinlc** [comment]
I can confirm that I see this issue now

**Comment by tjwieg** [comment]
Any updates on this? Any way I can help with a fix?

**Comment by corbinlc** [comment]
No update.  I undertook a bigger refactor of PRoot to merge the work of others and our work for mutual benefit.  This has delayed other PRoot fixes.  I am almost done with that merge, so I expect to be back to this soon.

**Comment by corbinlc** [comment]
Ok.  Next time you run, it should download new assets and then sudo should work on ubuntu.  Please confirm.

**Comment by tjwieg** [comment]
It works! One error popped up when I did a "sudo apt-get upgrade" but I
don't know if it's related.

"""
user@localhost:~$ sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [83.2
kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7
kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6
kB]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64
Packages [126 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-security/main
Translation-en [62.9 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe arm64
Packages [66.1 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe
Translation-en [39.2 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
Packages [276 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main
Translation-en [122 kB]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe arm64
Packages [188 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports bionic-updates/universe
Translation-en [90.0 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports bionic-updates/multiverse
Translation-en [2740 B]
Fetched 1219 kB in 13s (92.3 kB/s)
Reading package lists... Done
user@localhost:~$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  apt base-files initramfs-tools initramfs-tools-bin initramfs-tools-core
libapt-pkg5.0 libtomcrypt1 libx11-6 libx11-data libx11-xcb1 x11-common
11 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 3035 kB of archives.
After this operation, 29.7 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
base-files arm64 10.1ubuntu2.3 [60.2 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64
libapt-pkg5.0 arm64 1.6.3ubuntu0.1 [760 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64 apt
arm64 1.6.3ubuntu0.1 [1131 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
initramfs-tools all 0.130ubuntu3.3 [9360 B]
Get:5 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
initramfs-tools-core all 0.130ubuntu3.3 [47.9 kB]
Get:6 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
initramfs-tools-bin arm64 0.130ubuntu3.3 [13.1 kB]
Get:7 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64
libx11-data all 2:1.6.4-3ubuntu0.1 [113 kB]
Get:8 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64
libx11-6 arm64 2:1.6.4-3ubuntu0.1 [521 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports bionic-security/universe arm64
libtomcrypt1 arm64 1.18.1-1ubuntu0.1 [348 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports bionic-security/main arm64
libx11-xcb1 arm64 2:1.6.4-3ubuntu0.1 [9512 B]
Get:11 http://ports.ubuntu.com/ubuntu-ports bionic-updates/main arm64
x11-common all 1:7.7+19ubuntu7.1 [22.5 kB]
Fetched 3035 kB in 8s (365 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
E: Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13:
Permission denied)
(Reading database ... 10079 files and directories currently installed.)
Preparing to unpack .../base-files_10.1ubuntu2.3_arm64.deb ...
Unpacking base-files (10.1ubuntu2.3) over (10.1ubuntu2.1) ...
Setting up base-files (10.1ubuntu2.3) ...
Installing new version of config file /etc/update-motd.d/50-motd-news ...
(Reading database ... 10081 files and directories currently installed.)
Preparing to unpack .../libapt-pkg5.0_1.6.3ubuntu0.1_arm64.deb ...
Unpacking libapt-pkg5.0:arm64 (1.6.3ubuntu0.1) over (1.6.3) ...
Setting up libapt-pkg5.0:arm64 (1.6.3ubuntu0.1) ...
(Reading database ... 10081 files and directories currently installed.)
Preparing to unpack .../apt_1.6.3ubuntu0.1_arm64.deb ...
Unpacking apt (1.6.3ubuntu0.1) over (1.6.3) ...
Setting up apt (1.6.3ubuntu0.1) ...
(Reading database ... 10081 files and directories currently installed.)
Preparing to unpack .../0-initramfs-tools_0.130ubuntu3.3_all.deb ...
Unpacking initramfs-tools (0.130ubuntu3.3) over (0.130ubuntu3.1) ...
Preparing to unpack .../1-initramfs-tools-core_0.130ubuntu3.3_all.deb ...
Unpacking initramfs-tools-core (0.130ubuntu3.3) over (0.130ubuntu3.1) ...
Preparing to unpack .../2-initramfs-tools-bin_0.130ubuntu3.3_arm64.deb ...
Unpacking initramfs-tools-bin (0.130ubuntu3.3) over (0.130ubuntu3.1) ...
user@localhost:~$
"""

**Comment by corbinlc** [comment]
No, that is unrelated and does not cause any problems.  Cool.  Thanks for confirming.
