### ISSUE TITLE
Automatically start up GUI?

### ISSUE THREAD

**Issue by GuyFromMars365** [CypherpunkArmory/UserLAnd#151]
Is there a way to simply open Userland & launch right into a GUI? Having to start an SSH, launch XSDL, type in some commands, then return to XSDL is cumbersome. Maybe I am at fault because I am new to Linux, but I love a full desktop on my Galaxy Note 8! Great job for all the hard work, BTW. :)

**Comment by AdamMatthewLTM** [comment]
@GuyFromMars365 ,
Thank you for your post. As an answer to your question first: at the moment there is no functionality for launching straight into a desktop environment, however it may be included in a future release. There are other high priority bugs that need to be addressed in the underlying first before this enhancement can be implemented.

Given that this falls under the categories of a feature request and multiple people have asked for this and similar features, may I ask if you feel it is appropriate to close this thread issue? If you feel it should remain open please respond here with your reasoning and I will recommend it remain open and referenced to other threads.

Finally, if you file any new future GitHub issues could you please ensure that they use the correct template so we may have all the information necessary to assist you in an expedited manner? I know that this is a feature request and therefore the bug template does not apply, just a heads up for future issues (I'll be giving this message to everyone else).

I apologize for the length reply and thank you for your time and understanding @GuyFromMars365 ,
-Adam

**Comment by AdamMatthewLTM** [comment]
@GuyFromMars365 ,

I am sorry for the inconvenience, I made a slight mistake. The original reply text has been edited, please take a look at this thread on GitHub and refresh the page to see the correct text. Thank you

**Comment by GuyFromMars365** [comment]
I'm not sure how to change templates. Accessing via Chrome on Android.

**Comment by yunus70** [comment]
No you can start into a gui you need to install it first.

**Comment by corbinlc** [comment]
I use lxde and xfce during testing.  I have not tried gnome or kde.

**Comment by AdamMatthewLTM** [comment]
I am going to close this thread for the following reason:

This feature is being implemented at the time of the closing of this thread. Initially, only applications will specifically be addressed, however graphical environments will not be far behind. 

If an issue arises for a particular GUI launcher, I will recommend all issues for it be filed under their own separate thread. 

Therefore, if anyone feels this particular thread should remain open, please cite your reasons for doing so (not application/launcher specific) and I will re-open this ASAP.

Thank you all for your time and consideration,
-Adam
