### ISSUE TITLE
Related to frequent connection lost with connectbot

### ISSUE THREAD

**Issue by ashutoshmaurya1122** [CypherpunkArmory/UserLAnd#153]
I was trying ubuntu,i noted that whenever your network shutdown or you disconnect with wifi there is a connection lost with connectbot.This also happens when you try to fix broken packages.This does not happens with debian file system

**Comment by bet** [comment]
It might help to work within screen(1) in the session, that's what I do
whenever I've got an unreliable connection to a unix system.

**Comment by ashutoshmaurya1122** [comment]
I am using only one screen

**Comment by bet** [comment]
The screen(1) utility allows you to have a long-lasting session, until the server reboots --- if you get disconnected, after you log back in, run "screen -r" to reconnect. If the screen server hasn't realized you got disconnected you might have to run screen -dr

**Comment by ashutoshmaurya1122** [comment]
How to install screen(1) utility?

**Comment by bet** [comment]
sudo apt-get install screen

**Comment by AdamMatthewLTM** [comment]
@ashutoshmaurya1122 ,

Thank you for your post. For future bug reports, could you please ensure that the correct bug template be included so as to expedite resolving the issue and that we have all the information needed?

In regards to the connectbot disconnects, this is technically not a userland bug and is an issue with connectbot's software. I have closed my previous issue filed but will reopen it and have it reference this one for general connectbot problems. 

I have personally filed a bug report with connectbot on _their github page, but have yet to receive a response. So for now I recommend keeping this post here open as a low priority non-userland bug issue.

Please let me know if you were successfully able to use screen as a workaround to the network disconnect, and thank you for your time and patience,

-Adam

**Comment by AdamMatthewLTM** [comment]
I have marked this and issue #63 as duplicates. **Any bugs regarding connectbot disconnects should be replied to in issue #63 , thank you.**

**Comment by bet** [comment]
Just confirmed that command. You then need to sudo chmod 0777 /run/screen
Then it works
