### ISSUE TITLE
Help - [Connect externally to linux via ssh ]

### ISSUE THREAD

**Issue by lnxfsf** [CypherpunkArmory/UserLAnd#1554]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the issue you are having.

After setting up Arch linux on my android (fresh install), i wanted to use it via my Linux PC as it's easier to type commands and do what i want to do from PC.
I used ssh to connect to my android device. 
I know IP address of my android phone, and when trying to connect to it (from my linux PC) with `ssh <username>@<android IP address> -p 2022` (real parameters i used are `ssh igor-tablet@192.168.1.128 -p 2022` just for clarity) after it prompts me for password i get error `Permission denied (publickey,password)`

and it refuses to connect.
i tried looking into ssh port forwarding (as it looks like only solution for this), but, i don't understand how to set it up, as android is not supporting ssh natively, so that localhost 127.0.0.1 is really unaccessible to other in same network.

How i can set this up?
Or, how i can set up ssh port forwarding so i can connect from other host in same network?
 

# Describe how your task behaves in a regular Linux environment

**Comment by ardianp** [comment]
I have the exact problem and question: what is the username and password to ssh in UserLAnd session from a linux pc?
Username of the session is userland.
What is the password for ssh?

**Comment by ardianp** [comment]
I found it how:
1. On the Filesystems tab, press and hold the desired filesystem name and tap edit.
2. Click the eye icon next t password, to show it.
3. Install and configure ssh on the session, leaving the default port 22 and allowing password authentification uncommenting the row PasswordAuthentication yes on the file /etc/ssh/sshd_config (ubuntu in my case)
4. Start the ssh service on the session. 
5. Take note of the session ip and connet remotely with:
     ssh userland@<the mobile IP address> -p 2022
It is evident that the userland app exposes port 2022 to external PCs and then routes it to the port 22 of the active session.


![ksnip_20220710-191438](https://user-images.githubusercontent.com/605940/178155378-fab4e8f5-9874-41f9-9a00-328c0807ba6b.png)

**Comment by lnxfsf** [comment]
> I have the exact problem and question: what is the username and password to ssh in UserLAnd session from a linux pc? Username of the session is userland. What is the password for ssh?

I fixed it with making apache2 listen on other ports in same  network other than localhost (as i accesed ssh from pc to phone on same network). 
I just went in ``` /etc/apache2/apache2.conf ```
And edited:
```
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride None
   # this is line where it matters
   Require all granted
# and, these is from what hosts, to allow connection. you can change, this, if you have different subnet mask
   Allow from 192.168.1.*
   Allow from localhost


</Directory>
 

```


And so, i was able to access it via my PC (ssh, via linux terminal)
