### ISSUE TITLE
Help wanted for #i386 cross compile 

### ISSUE THREAD

**Issue by Saikatsaha1996** [CypherpunkArmory/UserLAnd#1569]
I want help
I want to build mesa driver for x86-linux device
Can it possible to guide how can I cross compile in userland ?
### Which PKG i should install?

**Comment by AdminIT-arch** [comment]
> I want help I want to build mesa driver for x86-linux device Can it possible to guide how can I cross compile in userland ?
> 
> ### Which PKG i should install?
