### ISSUE TITLE
Bug report - Some Files Not Showing!

### ISSUE THREAD

**Issue by Jumbo810** [CypherpunkArmory/UserLAnd#1621]
# Describe the bug
1. All Files Are Not Shows in Mounted FS. e.g. /sdcard, /Downloads/, /Documents.
2. Only Some Type OF Files Are Shows e.g. *.jpg, *.png, *.gif, *.mp4.
These Type Of Files Not Shows:
Compressed Files.
pdf files. & etc.....
3. Those Files Show Which is Created By Userland Terminal. e.g. *.txt & etc....

# Steps to reproduce the behavior:
Add Those Files TO Download Folder & Then List Directory Items.
`ls /Download/`

# Screenshots
![Screenshot_20220926-101542_ZArchiver](https://user-images.githubusercontent.com/106257478/192199592-501cc0ee-df04-4b24-8f61-69f610947ae1.jpg)
![Screenshot_20220926-101746_UserLAnd](https://user-images.githubusercontent.com/106257478/192199625-fa02a856-8704-4955-9dfb-8ac8e0a7d0ac.jpg)

# Device Information

Device: Samsung Galaxy A12. 
Android Version: 11.  
UserLAnd Version 3.0.0.  
Device is non-rooted.

**Comment by coppergold** [comment]
Agree I'm with you.

**Comment by Saikatsaha1996** [comment]
> # Describe the bug
> 1. All Files Are Not Shows in Mounted FS. e.g. /sdcard, /Downloads/, /Documents.
> 2. Only Some Type OF Files Are Shows e.g. *.jpg, *.png, *.gif, *.mp4.
>    These Type Of Files Not Shows:
>    Compressed Files.
>    pdf files. & etc.....
> 3. Those Files Show Which is Created By Userland Terminal. e.g. *.txt & etc....
> 
> # Steps to reproduce the behavior:
> Add Those Files TO Download Folder & Then List Directory Items. `ls /Download/`
> 
> # Screenshots
> ![Screenshot_20220926-101542_ZArchiver](https://user-images.githubusercontent.com/106257478/192199592-501cc0ee-df04-4b24-8f61-69f610947ae1.jpg) ![Screenshot_20220926-101746_UserLAnd](https://user-images.githubusercontent.com/106257478/192199625-fa02a856-8704-4955-9dfb-8ac8e0a7d0ac.jpg)
> 
> # Device Information
> Device: Samsung Galaxy A12. Android Version: 11. UserLAnd Version 3.0.0. Device is non-rooted.

Hus ! Same problem with everyone..
No solution found..

**Comment by Jumbo810** [comment]
**I Founded The Solution.**

**Comment by Saikatsaha1996** [comment]
> **I Founded The Solution.**

So can you share?

**Comment by Jumbo810** [comment]
> **I Founded The Solution.**

Some Files Not Showing! **Because**

Android 11+ Uses **MANAGE_EXTERNAL_STORAGE** TO Read/Write Files Properly.

You Can Better Understand From Android Documentation:
[https://developer.android.com/about/versions/11/privacy/storage](url)

So You Can Implement **MANAGE_EXTERNAL_STORAGE** In Your App Using This Article...
[https://stackoverflow.com/questions/62782648/android-11-scoped-storage-permissions](url)

I Already Implemented in My App.
If You Need More Help, Then Tell ME
