### ISSUE TITLE
Can't add certificate to apt

### ISSUE THREAD

**Issue by maxbl4** [CypherpunkArmory/UserLAnd#163]
After recent update (when Ubuntu fs was introduced), I created a new fs and session and found a sad regression.
user@localhost:~$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
gpg: can't connect to the agent: IPC connect call failed

That command work fine previously and I could add new certificates for repos

**Comment by corbinlc** [comment]
To clarify, before we only supported Debian.  So the specific case of grabbing a new Ubuntu certificate was probably not what you did, instead you probably grabbed a Debian certificate from inside a Debian session...right?  If that is the case, can you confirm that you have the same issue when doing something similar from inside a Debian filesystem?  Please help us understand this and also provide what version of Android you are running and what device you are using.  After all of that, we will probably request you gather a PRoot log for us.

**Comment by maxbl4** [comment]
Hi, I did try both fs, Debian and Ubuntu with the same result.
I have Galaxy S7 edge with latest official Android 8.0

**Comment by corbinlc** [comment]
Ok interesting.  Can you grab a PRoot log?  You do this by stopping your session if it is running currently.  Then go to settings inside the UserLAnd app and turn on PRoot debugging and setting the verbosity to 9.  Then you launch your sessions again and run the command that is giving you trouble (in your case the one you listed).  Then you should find a file on your sdcard (real or emulated) called PRoot_Debug_Log.  Please share that with us one way or another as it will help debug this.  I or @AdamMatthewLTM will also see if we can replicate this issue.

**Comment by maxbl4** [comment]
Here is the log from Debian fs
https://drive.google.com/file/d/1peCo0i8HXU80oDvqjTzTYj3cdBtPSExb/view?usp=drivesdk
If you need, I can create Ubuntu fs again and provide the log

**Comment by maxbl4** [comment]
Allowed access

**Comment by maxbl4** [comment]
Also interesting, that previously I could add a certificate in a fresh fs. Now I have to manually install gnupg before attempting

**Comment by maxbl4** [comment]
This seems to be fixed with update that I've downloaded today. I was able to add certificates and install nodejs and docker.

**Comment by corbinlc** [comment]
Great.  Thanks for following up.

**Comment by maxbl4** [comment]
After more checking, I can say it was fixed for debian fs and still not working for ubuntu

**Comment by WisdomWolf** [comment]
I don't think this is completely fixed.  I'm running into the same issue and am unable to add an apt-key from either a Debian or Ubuntu fs.

**Comment by yourpleasure** [comment]
Same error in Ubuntu fs now
