### ISSUE TITLE
Help - [Can't access terminal via phone / Userland default password?]

### ISSUE THREAD

**Issue by ElGlicho** [CypherpunkArmory/UserLAnd#1638]
# I can't access ubuntu terminal from my phone because i changed the password of the userland user.

Hi, I'm new to UserLAnd. I installed the app on my phone and then installed ubuntu, and I wanted to log into the userland user via ssh with my computer using
`ssh userland@ip -p 2022`
But I didn't know what password to enter when asked for a passwod, so I used `sudo passwd userland` in my phone to change it to one i would know.
Now I can access via ssh, but when I try to use the terminal in the phone, it throws an error that says:

```
/data/user/0/tech.ula/files/support/dbclient: Connection to userland@localhost:2022 exited: Remote closed the connection

[Process completed (code 1) - press Enter]
```

So I believe resetting the original password would solve this, but I can't find it anywhere. Any ideas? Have I done something wrong?

# N/A
N/A

**Comment by kenny-skaggs** [comment]
Hi @ElGlicho, I stumbled across this trying to figure out ssh from my laptop to my phone. I haven't had much luck connecting yet, but I think I know how to find the password you're looking for.

In the UserLAnd app (outside any active sessions) do you see the tab items at the bottom (Apps, Sessions, Filesystems)? Go to Filesystems and long press on the filesystem you're trying to access. You should see an option to edit the filesystem. On the edit screen you should be able to view the password that UserLAnd has for the user of that system.

(Sorry if I completely misunderstood something about what you were trying to figure out!)

**Comment by ElGlicho** [comment]
Hi @kenny-skaggs. Yes, that is exactly what i was looking for. Thank you very much!

**Comment by Jofernmorais** [comment]
preciso dos comandos para utilizar o aplicativo
