### ISSUE TITLE
[SOLVED] - Feature Request - [Allow hiding special keys when physiscal keybaord detected]

### ISSUE THREAD

**Issue by zhengliw** [CypherpunkArmory/UserLAnd#1646]
# Describe the problem your feature request solves.
WHen working with UserLAnd on a phone and a physical keyboard via built-in ssh, it is a bit annoying that the lower special-keys bar take up a bit space, which especially affects users who use UserLAnd on a phone and rotate the screen horizontal.

# Describe the solution you'd like 
Add a checkbox in the settings panel allowing to hide the special keys bar in the ssh interface if a physical keyboard is detected
That shouldn't affect normal usage with a virtual touch keyboard, though :)

# Describe alternatives you've considered
I think the solution above is probably the best fit.

**Comment by dairiki-ren** [comment]
Oh nevermind i found out you could swipe away the special keys bar

**Comment by dairiki-ren** [comment]
No, I misunderstood this, swiping away that bar doesn't hide it. It still takes up space :(

**Comment by dairiki-ren** [comment]
Okay, I am sorry for reopening and closing. I have found the solution:

### Hold VOLUME_UP, then press Q on your keyboard. That toggles the extra keys bar hiding.

[Reddit link to the original comment](https://www.reddit.com/r/termux/comments/ayalwl/comment/ehzm0hp/?utm_source=share&utm_medium=web2x&context=3)

**Comment by HappyAmos** [comment]
Ok, this tidbit really needs to be plugged in the wiki somewhere, or a toast message in app or something.

**Comment by dairiki-ren** [comment]
@HappyAmos Didn't expect that people find this older thread :) Forgot myself this exists...
either way, I believe UserLAnd is not actively maintained anymore... you should give Termux a go
