### ISSUE TITLE
Help - [Abandoned project?]

### ISSUE THREAD

**Issue by testman42** [CypherpunkArmory/UserLAnd#1654]
Is this project abandoned?

Any active forks?

Any Matrix room or IRC channel or other place where community can discuss the project?

# Describe the issue you are having.

this is just one of the many issues that I encountered when using this application:
Arch session fails to start after `sudo pacman -Syu`.

# Describe how your task behaves in a regular Linux environment
VM or bare metal successfully boots up again.

**Comment by corbinlc** [comment]
Still going, but just me.  The active branch right now is https://github.com/CypherpunkArmory/UserLAnd/tree/library . 
 Also, there was a Play Store release on 12/23/22.  There is no Matrix or IRC channel.  I need to refresh all the distros images in the near future.  Some are out of date enough to cause basic issues like the one you are seeing with pacman.

**Comment by testman42** [comment]
Maybe put a notice at the top of README.md that you are looking for people to help you?
Taking a look at the recent issues and seeing a lot of irrelevant posts does not really inspire confidence.
