### ISSUE TITLE
Unexpected crash before download is finished

### ISSUE THREAD

**Issue by rootkaliusr** [CypherpunkArmory/UserLAnd#166]
The app crashes before the download can finish. Once before the app would crash at the start of extract. No more. LG premier running 5.1.1 i can give more info if needed.

**Comment by AdamMatthewLTM** [comment]
@rootkaliusr ,

Apologies for the delayed response. Can you please detail the exact steps you are performing and at what point the application crashes? On top of that, if it still crashes can you please provide the proot log and paste it here? Thank you,

-Adam

**Comment by AdamMatthewLTM** [comment]
I am closing this issue for the time being. If this problem persists please comment here and re-open this thread. Thank you for your consideration,
-Adam

**Comment by adrianinsaval** [comment]
The app crashes immediately after the download finishes in my case, If you could give instructions I could get you the log this weekend.

**Comment by adrianinsaval** [comment]
The app crashes immediately after the download finishes in my case, If you could give instructions I could get you the log this weekend.

**Comment by adrianinsaval** [comment]
The app crashes immediately after the download finishes in my case, If you could give instructions I could get you the log this weekend.
