### ISSUE TITLE
Userland Debian on bVNC error/warning?

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#168]
This is on the Samsung Galaxy S9+ with a SD845 running on latest linux kernal. 

When I launch Debian (and even Ubuntu) filesystem and connect to the bVNC app (I believe bVNC was used in Gnuroot Debian as well) gives a error that states:

`ERROR: id.so: object libTcpOptimizer.so from LD_PRELOAD cannot be Preloaded (cannot open shared files`

Sometimes it says to ignore the message other times it doesn't let me do anything and keeps displaying the same message.

**Comment by AdamMatthewLTM** [comment]
@Root-voidX ,

Thanks for your post. I've run into issues with shared objects before, just never with the VNC client (and I am running an older version as well). Can you please confirm this still happens with the latest UserLAnd version and include a proot log here just in case? The log may not disclose any relevant information but we'll go over it anyway. Thanks for your time,

-Adam

**Comment by Root-voidX** [comment]
@AdamMatthewLTM yes on the latest version of userland running on a samsung Galaxy s9 plus on android 8.0 the issue is there

**Comment by AdamMatthewLTM** [comment]
@Root-voidX ,

I've done some light testing on a device running 8.0 and on my 7.0 device and haven't experienced any crashes with the latest updates at all. I'm going to go ahead and close this thread temporarily, if the issue persists for you however please let me know and I'll re-open this immediately and file it under high priority and take a significantly more extensive look at what's going on.

Thanks for your time and patience in these matters,
-Adam

**Comment by Root-voidX** [comment]
Yea no more crashing for me to. Whats the update on the Ld_preload warning?

**Comment by zeeshan9128** [comment]
I've got this pre-loaded issue

**Comment by zeeshan9128** [comment]
I've downloaded lxde and then when i closed all the apps and then opened it lxde got deleted and I've install it again doesn't it save download files
