### ISSUE TITLE
Errors on Installing Ubuntu-Desktop

### ISSUE THREAD

**Issue by GuyFromMars365** [CypherpunkArmory/UserLAnd#169]
Just trying to install GNOME, so I can have a desktop environment & running into issues. Not sure what this means, but thought I should report.
Snipet of command line via Termux:

user@localhost:~$ sudo tasksel install ubuntu-desktop
debconf: delaying package configuration, since apt-utils is not installed
**E: Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13: Permission
denied)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based fronte
nd cannot be used**. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Created symlink /etc/systemd/system/getty.target.wants/getty@tty1.service → /lib
/systemd/system/getty@.service.
Created symlink /etc/systemd/system/multi-user.target.wants/remote-fs.target → /
lib/systemd/system/remote-fs.target.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-timesyncd.servi
ce → /lib/systemd/system/systemd-timesyncd.service.
Created symlink /etc/systemd/system/dbus-org.freedesktop.resolve1.service → /lib
/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-resolved.ser
vice → /lib/systemd/system/systemd-resolved.service.
Created symlink /etc/systemd/system/multi-user.target.wants/ondemand.service → /
lib/systemd/system/ondemand.service.
Initializing machine ID from random generator.
[/usr/lib/tmpfiles.d/tmp.conf:15] Failed to replace specifiers: /tmp/systemd-pri
vate-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:16] Failed to replace specifiers: /tmp/systemd-pri
vate-%b-*/tmp
[/usr/lib/tmpfiles.d/tmp.conf:17] Failed to replace specifiers: /var/tmp/systemd
-private-%b-*
[/usr/lib/tmpfiles.d/tmp.conf:18] Failed to replace specifiers: /var/tmp/systemd
-private-%b-*/tmp
symlink(../proc/self/mounts, /etc/mtab) failed: Invalid cross-device link
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based fronte
nd cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
[More]

**Comment by bet** [comment]
Might not solve your problem, but I do like to clean up noise. At the top the output included

debconf: delaying package configuration, since apt-utils is not installed

I like to

sudo apt-get install apt-utils

to neaten things up

**Comment by corbinlc** [comment]
The errors in bold are not fatal, are they?  They show up when installing other packages successfully. 
 What are the later errors?

**Comment by GuyFromMars365** [comment]
I'm not sure. I'm new to Linux & honestly was hoping to just install GNURoot Debian (& now UserLand) & have a full Linux desktop on my Samsung Note 8, but as mentioned elsewhere Synaptic doesn't launch in gui & frankly getting into a desktop environment is a pain in the rear. I thought posting any errors might help to work out bugs. That being said, I super appreciate all the hard work! :) I've wanted a full desktop environment ever since Android first came out.

**Comment by AdamMatthewLTM** [comment]
@GuyFromMars365 ,

Thank you for your post. The errors you are encountering are normal due to the nature of the application, with the exception of the errors near the end regarding 'replacing specifiers'. I'm still in the process of testing various graphical environments, and my general conclusion at the moment is that GUIs which rely on less resources are significantly more successful in getting them to run. If I can find a workaround for ubuntu-desktop specifically I'll go ahead and post one here as soon as I can.

Thanks for your time and patience in these matters,
-Adam

**Comment by AdamMatthewLTM** [comment]
The errors for most graphical environments and packages seem to have been resolved with the recent update. I am going to go ahead and close this thread. If people are still running into errors -specifically- for ubuntu-desktop please let me know and I'll go ahead and re-open this thread immediately. All other graphical issues should be filed under their own thread.

Thank you all for your understanding,
-Adam
