### ISSUE TITLE
Can't connect to proxy

### ISSUE THREAD

**Issue by Lokawn** [CypherpunkArmory/UserLAnd#171]
Terminus output :

groups: cannot find name for group ID 3003
groups: cannot find name for group ID 9997
groups: cannot find name for group ID 50503
DEBUG: I am .bash_profile
user@localhost:~$ wget https://dl.google.com/
dl/android/studio/ide-zips/3.1.4.0/android-st
udio-ide-173.4907809-linux.zip
--2018-08-13 12:32:23--  https://dl.google.co
m/dl/android/studio/ide-zips/3.1.4.0/android-
studio-ide-173.4907809-linux.zip
Connecting to 172.25.1.32:3128...

It just shows this for a few minutes then retries.
Can connect using termux
Proxy details in .bash_profile file.

**Comment by AdamMatthewLTM** [comment]
@Lokawn ,

Thanks for your post. I'm having a little difficulty replicating your issue with consistent results (another issue filed regarding extraction seems to be getting in the way). When I find a workaround for this I'll update this thread. Please keep this open for now. 

Thank you,
-Adam

**Comment by AdamMatthewLTM** [comment]
@Lokawn ,

Are you still having issues? Please let me know if you can replicate the same problems on the latest userland version and what your device specifics are.

Thanks,
-Adam
