### ISSUE TITLE
Instructions passing data

### ISSUE THREAD

**Issue by michael-m-rosenthal** [CypherpunkArmory/UserLAnd#172]
Is it possible to create a directory shared with both the phone and the userland so that I can securely pass in files back and forth? I can't seem to locate a directory that stores files from the userland.

**Comment by AdamMatthewLTM** [comment]
@michael-m-rosenthal ,

Thank you for your post. I'm not quite sure myself how android splits up its directories, however the "official" directory (which is inaccessible even as root through userland) is /host-rootfs , which is where all the system files and data are stored. If there is a way to save data between the local phone and the application's storage locations, I will post an update to this thread. I'll go ahead and make this a feature request as well. 

Thanks for your patience,
-Adam

**Comment by corbinlc** [comment]
UserLAnd should be able to see files on the real or emulated sdcard.

**Comment by sarigama** [comment]
how can i do that? gnurootdebian was easy cuz its home was there in android's /gnuroot dir. did a df in userland and i could see /mnt there..shoud i do the mount command?

**Comment by bet** [comment]
I just found /sdcard/Download/ readable and writeable in Android, and from both Termux and userLAnd

**Comment by sarigama** [comment]
oh yes great! it worked that way. thanks so much ;)
