### ISSUE TITLE
Apt broken 

### ISSUE THREAD

**Issue by Asrithtechsys** [CypherpunkArmory/UserLAnd#174]
user@localhost:~$ apt update
Reading package lists... Error!
E: Could not open lock file /var/lib/apt/lists/lock - open
13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not create temporary file for /var/cache/apt/srcpk
cache.bin - mkstemp (13: Permission denied)
E: The package lists or status file could not be parsed or
pened.

**Comment by bet** [comment]
Does sudo apt work better for you?

**Comment by AdamMatthewLTM** [comment]
@Asrithtechsys ,

Thank you for your post. Can you please either update the original comment or reply on this thread with the file issue template so we can better assist you? Thank you,
-Adam

**Comment by corbinlc** [comment]
@bet is right.  They just forget to use `sudo`

**Comment by Asrithtechsys** [comment]
Thanks sudo apt works fine but installing package is too slow you may work on that plz
