### ISSUE TITLE
Alpine freezes on new session

### ISSUE THREAD

**Issue by ghost** [CypherpunkArmory/UserLAnd#1749]
When starting a new Alpine session it freezes at the welcome screen.
Debian however will launch.

**Comment by ghost** [comment]
# Describe the bug
When launching a Alpine session the session freezes at the terminal welcome screen after the welcome message.
All input is echoed back including ^C.

# Steps to reproduce the behavior:
1. Launch Userland
2. Select Alpine from the Distributions section of the Sessions tab
3. wait for the session to launch

# Screenshots

# Device Information

Device: LG Fortune
Android Version: 8.0.1
UserLAnd Version: 3.1.8
rooted: no
LineageOS: no

The issue happened after I noticed ps calls would return hundreds of processes. Seems like something was spawning processes. 
Also Userland was crashing from time to time
when running Alpine (before Alpine froze up).
And if it helps, when it initially froze up I was running 4 Alpine sessions (terminals). It froze initially when I started a fifth session. 
After restarting Userland it freezes as described
(immediately).

I was able to get in using a vnc connection.

The Debian distro boots no problem.

**Comment by ghost** [comment]
update
  
  i got in with multiple random ctrl C and Z
  ex:
    /^C^X^Zc^X^Xc^X^X^C^X^C^Cexez^Csu: must be suid to work properly
    Welcome to Alpine Linux in UserLAnd!
  
Note the su error is output once it unfreezes.
It is not part of the random ctrl keys entered.

The problem is the call
from /etc/profile.d/zzzzzzzzzzzzzzzz.sh
to remove itself after an initial welcome
mesaage eg:
  sudo rm -f $SCRIPT_PATH
    
The sudo rm call hangs. It also spawns hundreds and even thousands of processes.
  
I changed zzzzzzzzzzzzzzzz.sh to call
mv -f SCRIPT_PATH SCRIPT_PATH.disabled
without sudo.
Of course other options that don't call the
sudo script to rm or mv the calling script will work as well. Of course also  there's really no point to get the one time message a second time only to mv it except of course for the pleasure of fixing the bug.
 
The su error that shows up when you get past
the freeze,   su: must be suid to work properly,
was resolved with
  chmod u+s /bin/busybox
   
So overall everthing is working
but
  How did busybox lose the setuid flag
  in the first place ??
    
  and of course, what exactly is going 
  on with the sudo script to cause it to hang
  when the calling script deletes itself 
noting also that sudo calls spwan tens and even hundreds of processes ?

Note: all this happened after an update,  upgrade

??

**Comment by ghost** [comment]
update

The issue is with the Alpine upgrade.
su is upgraded to a link without setuid
and the odd rm behaviour ensues from this
also.

The freeze it seems is from the indirection, or rather too much indirection with the link
// bbsu is busybox su
script -> bbsu root -c rm -f self                 // works
script -> sudo -> bbsu root -c rm -f self   // works
script -> sudo -> sulink -> bbsu root -c..   // freeze

In any case it's an Alpine issue so I'll close it here
though heads up Userlanders.

**Comment by AdminIT-arch** [comment]
> When starting a new Alpine session it freezes at the welcome screen. Debian however will launch.
