### ISSUE TITLE
Access Java and Python frameworks from Android

### ISSUE THREAD

**Issue by mhous33** [CypherpunkArmory/UserLAnd#184]
Hello, I am trying to access Java and Python apps for use on files in local storage.
I've tried copying files to a working directory in the chroot home; however, attempting to modify them within userland returns "permission denied", even when trying to chmod them.
Is there a way to allow modification of files copied to the chroot, or even better, call the Java and Python apps from Android directly?

**Comment by AdamMatthewLTM** [comment]
@mhous33 ,

Thanks for your post. Can you please provide a little bit more detail according to the issue file template? I also need to know which directory you're copying the files to specifically in chroot and what commands you are issuing as what user. 

Thank you for your consideration,
-Adam

**Comment by mhous33** [comment]
Hey Adam,
I'll use apktool.jar and lawnchair.apk for my example.
I installed openjdk-8-jdk,  used wget to download apktool.jar to ~/bin, and enabled running it as executable.
I then copied lawnchair.apk to the chroot working directory:
/data/data/tech.ula/files/1/home/user/wd

Running "(sudo) java -jar ~/bin/apktool.jar d lawnchair.apk" within the working directory returns a file not found exception (permission denied), with or without sudo.
Ideally, I would paste the terminal input and output, but copy function isn't available in the userland terminal AFAIK.

I think part of the issue may be that a .proot-meta-file isn't created for a file copied into the chroot from a root file explorer, not sure though.

Let me know if I can provide any further details!

**Comment by mhous33** [comment]
@vprusa
Dude thank you!!!
I use JuiceSSH also, but was using vnc to connect.
Copying files from internal storage to chroot working directory through ssh works like a charm and creates the necessary proot-meta-file.
SSH through JuiceSSH is also just a better experience than vnc for terminal-only interaction imo.

**Comment by AdamMatthewLTM** [comment]
@vprusa , 

Thanks for your reply and sorry for my lateness. Yeah the proot meta files are necessary to get the correct permissions. I'll go ahead and close this issue.
