### ISSUE TITLE
No AltGr key combinations in Graphical session

### ISSUE THREAD

**Issue by matthiashoster** [CypherpunkArmory/UserLAnd#1910]
# Describe the bug

After starting a Graphical session I cannot enter AltGr key combinations on a physically attached German keyboard. Therefore I cannot enter symbols like '|{[]}~\\'. This makes apps running in a Graphical session nearly useless for programming, texing, ...

# Steps to reproduce the behavior:

1. Attach a German keyboard to the Android device.

2. Click on 'Ubuntu' app.

3. Select 'Graphical' mode.

4. Open a text editor, for example 'gedit'.

5.  Enter 'AltGr + <' on the keybord. The editor should show a '|' character but instead it only shows '<'. 

6. Same for the other AltGr key combinations.

# Screenshots

N/A

# Device Information

Device: Samsung Galaxy S24 Ultra.  
Android Version: Android 14.  
UserLAnd Version: 23.09.13.  
Device is not rooted.  
Device is not running LineageOS. 

In a terminal session all AltGr combinations work fine. On the other hand, when starting tightvnc manually from a terminal session and connecting via bVNC then the same issue occurs. 

Of course I can use the "send text" feature of bVNC (which you seem to have used for your Graphical session). But this feasible only for tiny edits and no serious workaround for running programming or tex sessions.

It appears to me to be rather a tightvnc issue. But since they stopped supporting their Linux version years ago, a bug fix for such a problem (which I understand was done for their Windows version) will probably never make it to Linux.

It would be really great if you could find a way to make this work out of the box. In the end it not only affects German users, but I suppose French, Spanish, and many other users will face the same issue with their keyboards...

**Comment by matthiashoster** [comment]
... I just wanted to be sure that I did not mess anything up at my end, while installing LXDE, gedit, and so on. But of course the problem already exists in the terminal window. 

And just to be extra sure I have installed your ready-made Vscode app - and the same problem here. When I try to enter '\' by pressing AltGr + ß (I am not sure what key that would be on a US keyboard, on mine it is right of the '0')  something odd happens and I am not even able to enter "Enter" anymore...

Finally, I am not sure a bug report is the right place for general feedback, but I just wanted to say: I love UserLAnd, great app, very impressive and fun :-)

**Comment by matthiashoster** [comment]
Sorry, it should read "... when I try to enter '\' by..."

**Comment by matthiashoster** [comment]
The editor here seems to eat my backslashes...

**Comment by matthiashoster** [comment]
A little update. I have installed "AVNC" rather than "bVNC" to connect to the tightvnc server manually started from a terminal session.

Now, I can enter all characters perfectly well  in "UXterm" and in  "Texmaker" for example. But funnily, in the same VNC session it still does not work in "gedit" or in "Rstudio".

It seems that my previous impression that the problem was due to tightvnc server was wrong. Rather it has something to do with the vnc viewer (since with bVNC still no special characters work). And in addition there is some other problem I do not understand, letting some applications work and others not...

**Comment by matthiashoster** [comment]
Now it works! The only thing I had to do was to activate "Right Alt -> Super" mapping in AVNC.
To summarize from scratch, what made it work for me were the following steps:

- UserLAnd/Apps: install app "Debian" with "LXDE" desktop and start "Terminal session".
- UserLAnd/Terminal session: install package "dbus-x11" by typing "sudo apt install dbus-x11" - otherwise many graphical applications will not work (including mousepad).
- UserLAnd/Filesystems: lookup "vnc password" for filesystem "Debian/apps" (via right-click, "edit").
- UserLAnd/Terminal session: start a vnc server on "localhost:1" by typing "vncserver". Since this is the first time it will ask for a password: provide the one you just have looked up (and "no", not view only).
- Android: install "AVNC" as vnc viewer (with "bVNC", which is integrated into UserLAnd, I did not manage to get AltGr to work).
- AVNC/Settings/Input/Key mappings: activate "Right Alt -> Super" (**this is the crucial thing**).
- AVNC: add a new server, name: "[whatever you like]", host: "localhost", username: "userland", password: "[the same you have just set]".
- AVNC: connect to the server by clicking on it.
- AVNC/VNC session: from the LXDE Menu open the text editor "Accessories/Mousepad", test the AltGr key combinations - they should work now!
- UserLAnd/Terminal session: shutdown vnc server by typing "vncserver -kill :1". Exit.

So happy now, cheers :-)

**Comment by jheymann-ish** [comment]
Running into similar issue with Galaxz S25 Ultra + Dex + physical keyboard attached via USC-C Dock. Running Termux w/ QEMU etc. in Terminal works pretty fine, while VNC does not. Trying to use VS Code ("deVStudio" via UserLAnd) does not allow to change VNC client itself, so it is a bit unconvinient to use "Alt Gr" keys like "@" in an integrated Terminal in VS Code. 
Workaround for me is to use English keyboard here and then by toggling keyboard language key by pressing "Shift + Space" . Then I can use the English layout for achieving "@" by pressing "Alt-2" for example... annyoing, but I will try to get AVNC working, question is which approach will be less convinient :/
