### ISSUE TITLE
Unable to start internet browser in lxde session on xsdl app with missing /dev/shm

### ISSUE THREAD

**Issue by vprusa** [CypherpunkArmory/UserLAnd#199]
Describe the bug:
Android does not have /dev/shm dir that causes failures to allocate tmp memory for browsers.

To Reproduce:
Have running UserLAnd session and ssh to it. Have lxde installed. Have firefox installed and/or chromium-browser installed with apk.
Start Xserver XSDL app and ```export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712 && startlxde &```

Related [bz](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1450169)

Device: Sansung A5 2017
Android Version: Oreo, 8.0, rooted
UserLAnd Version idk custom, latest
Filesystem: Ubuntu

Note: I have attempted to add /dev/shm dir and chmod 1777 as supersu but mounting in UserLAnd ssh session with ```mount -t tmpfs tmpfs /dev/shm``` ended up with ```cannot mount tmpfs read-only``` mounting as supersu is successful (supersu root ls ```drwxrwxrwt 2 root         root             40 2018-08-23 14:06```) but proot still can not access /dev/shm because of read-only permissions (```
drwxr-xr-x. 2 root root       40 Aug 23 12:01 shm```). I think I am misunderstanding proot's bind and permissions handeling or jail and running out of ideas how to workaround this without (or even with :/) superuser powers.
Considering it could be possible to use nested binding for missing /dev/shm I do not know how to mount tmpfs there with accessibility from proot filesystem.
Thank you.

**Comment by AdamMatthewLTM** [comment]
@vprusa ,

Thanks for your post. I'll have to do a little research to see if there's a workaround for this. I was able to successfully get firefox working just fine, so I just want to make sure: can you successfully start the browser and use it even without the tmp memory allocation?

Thanks for your time,
-Adam

**Comment by vprusa** [comment]
So.. after refreshment of the brain I have made it work.

First, to answer your question: I did not successfully start the browser without use of /dev/shm temporary memory, it always failed with error descried in bz above.

Second, what make it work was:
1. In UserLAnd's ssh session
```mkdir /support/shm```
2. add bind to support/execInProot.sh 
```-b $ROOTFS_PATH/support/shm:/dev/shm```
3. restart UserLAnd's session (to make sure proot rebind dirs)

I think the problem was in not having binded dir (```/dev/shm```) in proot's jail, though I am still not sure why adding ```mkdir /dev/shm && chmod 1777 /dev/shm``` did not work (I suppose I have missed something in support scripts or in proot's configuration).

Thanks for response. 
Regards.

**Comment by vprusa** [comment]
@JohnWang1023 Thanks for response, I was not aware that this is related to Firefox version (considering chromium failed as well) ..
I do not know how to bind or mount anything in /dev/ inside of proot without having permissions to /dev/ itself :-/

**Comment by mdouchin** [comment]
@vprusa could you write down the whole line of the file `support/execInProot.sh` with the -b flag ?

I have not been able to use ansible playbook, since it uses the module multiprocessing which needs /dev/shm. I would like to test if your /support/shm replacement can be used for other softwares too (such as python multiprocessing module or PostgreSQL database server)
