### ISSUE TITLE
Cant mount a filesystem as rw "permission denied" 

### ISSUE THREAD

**Issue by N304LX** [CypherpunkArmory/UserLAnd#205]
Anybody know's Wy can't put mount -o remount,rw /dev?, I'need to use chmod on ttyACM0 for use with arduino but don't works, any help?, any time I'got the message "permission denied"

**Comment by AdamMatthewLTM** [comment]
@N304LX ,

Thank you for your post. Can you please repost the issue according to the template guidelines provided on our github page? Thank you for your consideration.
-Adam
