### ISSUE TITLE
Crashing when SD Card is chosen as the storage location

### ISSUE THREAD

**Issue by th3or14** [CypherpunkArmory/UserLAnd#208]
**Describe the bug**
Application crashes after it tries to download required assets when SD Card is chosen as the storage location. I'm not sure if it's the same as #160. A workaround I've found out is to choose Device as storage location (Storage section in Android settings).

**To Reproduce**
Make sure SD Card is chosen as the storage location. In the application create and start a session (e.g., Debian over SSH). Wait for ten minutes (more or less) of `0 out of 17 complete`. There are several background notifications of downloading something, but status is still 0. At some point display shows a progress, one by one. (I suppose downloading terminates after some sort of timeout. Also I checked Download directories, both SD and Device, no new files there.) Finally the application crashes. Debug output from Android Studio:
```
E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-3
                  Process: tech.ula, PID: 6059
                  kotlin.io.NoSuchFileException: /data/user/0/tech.ula/files/debian: The source file doesn't exist.
                      at kotlin.io.FilesKt__UtilsKt.copyRecursively(Utils.kt:266)
                      at kotlin.io.FilesKt__UtilsKt.copyRecursively$default(Utils.kt:263)
                      at tech.ula.utils.FilesystemUtility.copyDistributionAssetsToFilesystem(FilesystemUtility.kt:25)
                      at tech.ula.utils.SessionController.extractFilesystemIfNeeded(SessionController.kt:83)
                      at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.doResume(ServerService.kt:195)
                      at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.invoke(ServerService.kt)
                      at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.invoke(ServerService.kt:24)
                      at tech.ula.utils.AsyncKt$async$2.doResume(Async.kt:12)
                      at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
                      at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
                      at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
                      at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
                      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
                      at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
                      at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
                      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
                      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)
```

**Expected behavior**
I can successfully create and start a session if I choose Device as storage location. Also in that case assets downloading progress is relatively instant and new files are visible in Download directory.

**Device Information**
Device: Huawei MediaPad M3
Android Version: Nougat, 7.0
UserLAnd Version 0.2.5 (and debugged current staging branch also)

**Additional context**
Well, if it's the same as #160 then I just want to state a possible solution for an unobvious/unknown crashing.

**Comment by MatthewTighe** [comment]
@th3or14 Could you post screenshots of the how you choose SD card as the storage location? I haven't had a phone that separates the two in a user-facing way in long enough that I forget what that looks like.

**Comment by corbinlc** [comment]
I have a couple of devices with SD card and, for UserLAnd, I am not seeing a choice for moving the app to the SD card where it would be if the app supported such a thing.  So, I am also curious how and where you are choosing the SD card.  Please provide a little more info and we will act upon this.

**Comment by corbinlc** [comment]
This is weird, because this is how you set where your app can be installed: https://developer.android.com/guide/topics/data/install-location
 
But we don't set that parameter in our android manifest:
https://github.com/CypherpunkArmory/UserLAnd/blob/staging/app/src/main/AndroidManifest.xml

And if you don't set it, it should default to allowing you to only install the app in internal storage and not being able to move it to the sdcard. 

So, going to walk away from this for now until we get some additional information that helps us move forward.

**Comment by th3or14** [comment]
The user interface is Huawei EMUI (5.0.1).

1.
![screenshot_20180829-204456](https://user-images.githubusercontent.com/37025359/44805724-ad5d0500-abcd-11e8-823f-6fc4c001be0f.png)

2.
![screenshot_20180829-204514](https://user-images.githubusercontent.com/37025359/44805730-b2ba4f80-abcd-11e8-8d47-12c97e4f1b74.png)

**Comment by corbinlc** [comment]
Interesting.  I don't have that option on the devices I have checked.  I guess we can try:
`android:installLocation="internalOnly"`
Which should be unnecessary, but manufactures like to make changes to Android

**Comment by corbinlc** [comment]
@MatthewTighe maybe the next time you roll a beta, you can add this to the manifest and check that it doesn't break a normal install.  Then we can get feedback as to whether this solves the issue.

**Comment by th3or14** [comment]
I tried to add this to the manifest, looks like it doesn't help. Same behaviour.
```
diff --git a/app/src/main/AndroidManifest.xml b/app/src/main/AndroidManifest.xml
index 1d10769..87163e5 100644
--- a/app/src/main/AndroidManifest.xml
+++ b/app/src/main/AndroidManifest.xml
@@ -1,6 +1,7 @@
 <?xml version="1.0" encoding="utf-8"?>
 <manifest
     xmlns:android="http://schemas.android.com/apk/res/android"
+    android:installLocation="internalOnly"
     package="tech.ula">
 
     <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
```

**Comment by MatthewTighe** [comment]
@th3or14 We find those environment variables at runtime dynamically, so it *shouldn't* matter. However, it looks like we're actually initializing variables in a few places using a few different methods, which could be leading to different results. Could you print the following and let me know what their result is?

1.) `Environment.getExternalStorageDirectory().absolutePath`
2.) `Environment.getExternalStorageDirectory().path`
3.) `Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).path`
4.) `Environment.DIRECTORY_DOWNLOADS`

Thanks for your assistance with this.

**Comment by th3or14** [comment]
@MatthewTighe 
```
I/System.out: 1.) Environment.getExternalStorageDirectory().absolutePath: /storage/7430-F5C4
I/System.out: 2.) Environment.getExternalStorageDirectory().path: /storage/7430-F5C4
I/System.out: 3.) Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).path: /storage/7430-F5C4/Download
I/System.out: 4.) Environment.DIRECTORY_DOWNLOADS: Download
```

**Comment by th3or14** [comment]
@MatthewTighe 

> Can you confirm that assets do not appear in your downloads directory if you've installed onto external storage?

Right. I notice downloading notifications background but no files appear in the directory.

> Are those environment variables the same if you install on device and external storage?

No, they are the following if I switch to internal storage as the default location.

```
I/System.out: 1.) Environment.getExternalStorageDirectory().absolutePath: /storage/emulated/0
I/System.out: 2.) Environment.getExternalStorageDirectory().path: /storage/emulated/0
I/System.out: 3.) Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).path: /storage/emulated/0/Download
I/System.out: 4.) Environment.DIRECTORY_DOWNLOADS: Download
```

I would try to use `getFilesDir()` for `getDownloadsDirectory()` but I don't know where to take `Context`.

**Comment by th3or14** [comment]
@MatthewTighe 

Sorry, I read a preview from email and totally missed the second part of your comment.

> Also, if you're able to build from source, would you be able to find the value of this.filesDir.path in a place where this represents a context like ServerService or SessionListFragment while installed on the sdcard?

```
I/System.out: this.filesDir.path: /data/user/0/tech.ula/files
```

**Comment by MatthewTighe** [comment]
@th3or14 Just to clarify, `I/System.out: this.filesDir.path: /data/user/0/tech.ula/files` is while installed on the sdcard not while installed on internal storage?

**Comment by th3or14** [comment]
@MatthewTighe Yes, on the sdcard. Checked it and reboot & uninstall & install once more.

**Comment by ibrado** [comment]
BTW, not sure if this has any bearing, but I don't remember UserLAnd asking for permission to access the SD card. Does it..? I can't access /mnt/media_rw/<some-id> from the shell, for example.

**Comment by MatthewTighe** [comment]
@ibrado
UserLAnd requests external storage permission the first time a session is activated.

**Comment by th3or14** [comment]
@MatthewTighe Got it. There are `onReceive` calls before crashing. Here's logcat.
```
08-30 20:20:19.338 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:19.339 6662-6662/tech.ula I/Choreographer: Skipped 29477 frames!  The application may be doing too much work on its main thread.
08-30 20:20:40.372 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:40.373 6662-6662/tech.ula I/Choreographer: Skipped 1261 frames!  The application may be doing too much work on its main thread.
08-30 20:20:41.494 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:41.495 6662-6662/tech.ula I/Choreographer: Skipped 66 frames!  The application may be doing too much work on its main thread.
08-30 20:20:42.275 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:42.276 6662-6662/tech.ula I/Choreographer: Skipped 45 frames!  The application may be doing too much work on its main thread.
08-30 20:20:43.020 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:43.021 6662-6662/tech.ula E/broadcast: file error
08-30 20:20:43.022 6662-6662/tech.ula I/Choreographer: Skipped 43 frames!  The application may be doing too much work on its main thread.
08-30 20:20:43.620 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:43.621 6662-6662/tech.ula E/broadcast: file error
08-30 20:20:43.622 6662-6662/tech.ula I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
08-30 20:20:44.218 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:44.219 6662-6662/tech.ula I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
08-30 20:20:44.798 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:44.799 6662-6662/tech.ula E/broadcast: file error
08-30 20:20:44.801 6662-6662/tech.ula I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
08-30 20:20:53.036 6662-6669/tech.ula I/art: Starting a blocking GC Instrumentation
08-30 20:20:54.401 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:54.402 6662-6662/tech.ula E/broadcast: file error
08-30 20:20:54.403 6662-6662/tech.ula I/Choreographer: Skipped 575 frames!  The application may be doing too much work on its main thread.
08-30 20:20:54.463 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:54.464 6662-6662/tech.ula E/broadcast: file error
08-30 20:20:54.535 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.558 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.578 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.599 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.621 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.643 6662-6662/tech.ula E/broadcast: status failed
    file error
08-30 20:20:54.671 6662-6662/tech.ula E/broadcast: status failed
08-30 20:20:54.672 6662-6662/tech.ula E/broadcast: file error
    
    --------- beginning of crash
08-30 20:20:55.297 6662-6712/tech.ula E/AndroidRuntime: FATAL EXCEPTION: ForkJoinPool.commonPool-worker-1
    Process: tech.ula, PID: 6662
    kotlin.io.NoSuchFileException: /data/user/0/tech.ula/files/debian: The source file doesn't exist.
        at kotlin.io.FilesKt__UtilsKt.copyRecursively(Utils.kt:266)
        at kotlin.io.FilesKt__UtilsKt.copyRecursively$default(Utils.kt:263)
        at tech.ula.utils.FilesystemUtility.copyDistributionAssetsToFilesystem(FilesystemUtility.kt:25)
        at tech.ula.utils.SessionController.extractFilesystemIfNeeded(SessionController.kt:83)
        at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.doResume(ServerService.kt:196)
        at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.invoke(ServerService.kt)
        at tech.ula.ServerService$startSession$1$wasExtractionSuccessful$1.invoke(ServerService.kt:24)
        at tech.ula.utils.AsyncKt$async$2.doResume(Async.kt:12)
        at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:42)
        at kotlinx.coroutines.experimental.DispatchedTask$DefaultImpls.run(Dispatched.kt:161)
        at kotlinx.coroutines.experimental.DispatchedContinuation.run(Dispatched.kt:25)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1383)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:256)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1123)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1961)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1909)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:128)
08-30 20:20:55.334 6662-6712/tech.ula I/Process: Sending signal. PID: 6662 SIG: 9
```

@ibrado Yeah, permissions are requested and granted in my case also.

**Comment by MatthewTighe** [comment]
@th3or14 
Awesome, thanks a ton for doing that. Hopefully that will be enough for me to put out a hotfix today, but I'll let you know if I need any more info.

The weird thing is, even though the download is failing, our code should have continued anyway. That's still a bug, but I'm scratching my head as to why you weren't seeing the progress dialog update that downloads had completed.

**Comment by th3or14** [comment]
@MatthewTighe 

> I'm scratching my head as to why you weren't seeing the progress dialog update that downloads had completed

Actually I noticed a progress in status, see the original post.

> At some point display shows a progress, one by one.

In other words after a long time it suddenly becomes `1 of 17`, `2 of 17` and so on. Then crashing.

**Comment by MatthewTighe** [comment]
@th3or14 
My bad, I must have missed that part.

I think what was happening is that the downloads directory on the sdcard didn't actually exist beforehand, so now I'm ensuring that it does before downloading anything. I'll put a release together once my changes are merged in.

We've seen it take a while for the play store to propagate releases, so if you wanna give it a shot you can build from staging. Note that if you build locally, you may not be able to upgrade from the play store with later versions.

Thanks again for all your help in getting this debugged.

**Comment by th3or14** [comment]
@MatthewTighe 
Fixes up to 814d0a5 affect nothing for me.
I overrode `onReceive` as I did it before and here is full logcat (SD storage case), it was somehow cut last time. [log-sd.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2337699/log-sd.txt)
And here is all the same but internal memory storage case. [log-internal.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2337694/log-internal.txt) (I interrupted after installing filesystem seemed to be finished and it was suggested to install other apps.)

**Comment by MatthewTighe** [comment]
@th3or14 
Yeah, it looks like what I was trying is handled by Android anyway.
[AOSP DownloadManager](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/app/DownloadManager.java)
Line 531:
```
        public Request setDestinationInExternalPublicDir(String dirType, String subPath) {
            File file = Environment.getExternalStoragePublicDirectory(dirType);
            if (file == null) {
                throw new IllegalStateException("Failed to get external storage public directory");
            } else if (file.exists()) {
                if (!file.isDirectory()) {
                    throw new IllegalStateException(file.getAbsolutePath() +
                            " already exists and is not a directory");
                }
            } else {
                if (!file.mkdirs()) {
                    throw new IllegalStateException("Unable to create directory: "+
                            file.getAbsolutePath());
                }
            }
            setDestinationFromBase(file, subPath);
            return this;
        }
```
I'll keep looking into it.

**Comment by Herzogs** [comment]
hello, I had what @th3or14 described above and it seems to solve it if I remove the sd card when installing the FS. It's like if the sd card is mounted it would not recognize the folder where it would download the files

**Comment by MatthewTighe** [comment]
@th3or14 
That's not the full list of changes. I'll edit my original post in a minute.

**Comment by MatthewTighe** [comment]
@th3or14 
I've rolled those changes into branch hotfix-v0.3.3 if you want to just clone that and build from there.

**Comment by th3or14** [comment]
@MatthewTighe Wow, now it works. Checked it twice from the scratch.

**Comment by MatthewTighe** [comment]
@th3or14 
With these most recent changes, or v0.3.2

**Comment by corbinlc** [comment]
Nice work @MatthewTighe and a **huge** thanks @th3or14 for playing along!

**Comment by th3or14** [comment]
I accepted changes from the comment and now checked hotfix-v0.3.3, it works too. Nice. You are welcome.
