### ISSUE TITLE
Hangs when trying to download assets

### ISSUE THREAD

**Issue by brice-v** [CypherpunkArmory/UserLAnd#209]
Samsung S8 Oreo(8.0)
Most recent updated app
After creating file system and connection, the app fails to download any assets after any given amount of time.

**Comment by th3or14** [comment]
I wonder if your storage location is internal or SD card, could you check?

**Comment by brice-v** [comment]
I have an SD card but the app is not installed there nor the file system. It appears after killing the service and retrying the downloads were able to proceed.
