### ISSUE TITLE
Unable to start xfce4 by vncserver

### ISSUE THREAD

**Issue by zaoqi** [CypherpunkArmory/UserLAnd#217]
I VIMed .vnc/xstaup

**Comment by ashutoshmaurya1122** [comment]
Cannot run xfce4 on vncserver. I use the command DISPLAY=:1 startxfce4 i get error like this 
(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.259: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.261: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.264: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.434: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.435: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.438: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.441: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.444: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.445: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.447: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.449: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.454: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.463: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.465: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.467: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:15.468: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:15.469: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:15.470: g_propagate_erro
: assertion 'src != NULL' failed
xfce4-session: No SSH authentication agent found
gpg-agent[24561]: WARNING: "--write-env-file" is an obsolete option - i
 has no effect
gpg-agent: a gpg-agent is already running - not starting a new one

(xfce4-session:24545): xfce4-session-WARNING **: 12:40:16.117: gpg-agen
 returned no PID in the variables

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.117: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.118: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.119: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.121: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.125: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.126: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.127: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.128: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.129: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.133: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.134: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.134: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.135: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.136: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.137: g_propagate_erro
: assertion 'src != NULL' failed

(xfce4-session:24545): xfce4-session-WARNING **: 12:40:16.139: xfsm_man
ger_load_session: Something wrong with /root/.cache/sessions/xfce4-sess
on-localhost:0, Does it exist? Permissions issue?

(xfce4-session:24545): xfconf-CRITICAL **: 12:40:16.140: xfconf_init()
ust be called before attempting to use libxfconf!

** (xfce4-session:24545): CRITICAL **: 12:40:16.140: dbus_g_proxy_call:
assertion 'DBUS_IS_G_PROXY (proxy)' failed

(xfce4-session:24545): GLib-CRITICAL **: 12:40:16.141: g_propagate_erro
: assertion 'src != NULL' failed
root@localhost:/home/user#

**Comment by AdamMatthewLTM** [comment]
@zaoqi and @ashutoshmaurya1122 ,

Thanks for your post. At the moment we are working on some graphical issues including with dbus errors. May I recommend this thread be closed and all updates regarding this issue be focused on issue #157 for the time being? 

Thanks for your time,
-Adam
