### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by maxbl4** [CypherpunkArmory/UserLAnd#218]
**Is your feature request related to a problem? Please describe.**
I would like to run docker inside userland. Right now I can install it, but it will not start, shows lots of errors in logs. I understand it may be quite hard, so would be glad if you assess how realistic this is.

**Comment by corbinlc** [comment]
docker probably cannot work until we support running as real root.

**Comment by zhoupro** [comment]
If we have root user, Can we run docker in UserLand?

**Comment by EnderNightLord-ChromeBook** [comment]
probably...

**Comment by EnderNightLord-ChromeBook** [comment]
> If we have root user

you mean super user?

**Comment by rajibhasan11** [comment]
With root it is also not possible to run docker as linux kernels must have namespaces features. https://github.com/moby/moby/issues/40121

**Comment by PeterTucker** [comment]
Bump

**Comment by BlitzJB** [comment]
Bump

**Comment by pugdev3** [comment]
Bump
