### ISSUE TITLE
Adobe flash player on Ubuntu while using Userland

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#232]
Dear specialists,
Please, is Adobe Flash player inside repositories of Ubuntu Bionics, because Userland is very probably using Ubuntu Bionics or unfortunately, nobody on The world have prepared ARM compatible Adobe Flash player, so it will not work?
I have started to use Ubuntu because I hope, that Adobe Flash player will be available also for ARM platform. Ubuntu for X86 platform contain relatively new versions of this plugin. Thank you very much for yours answer.

**Comment by JohnWang1023** [comment]
browser-plugin-freshplayer-pepperflash work on amd64 arm64 armhf i386 ppc64el s390x.
Package flashplugin-installer work on amd64 i386.
see https://packages.ubuntu.com/search?suite=bionic&section=all&arch=any&keywords=flash&searchon=names

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel and @JohnWang1023 ,

Would  both of you please be able to confirm that the pepperflash and flashplugins work within userland? I have had inconsistencies getting flash to work on my device. 

Thank you,
-Adam

**Comment by JanuszChmiel** [comment]
Dear Adam,
I can not test Firefox for now, since I Am very far from getting audio 
working. I could install pepperflash without issues.
But because I run ARM based system, I can not test Flashplugin because 
it do not exist for ARM architecture.

**Comment by lapsio** [comment]
Afaik flashplayer is impossible to get on ARM device. Unless you use some wizardry like Shumway.

**Comment by AdamMatthewLTM** [comment]
I can confirm that @lapsio is correct in regards to flash support being dropped. Given the limited success of various flash plugins (especially for 8.0) I'm going to suggest that temporarily people operate under the assumption that we will be unable to provide significant support in getting flash working. Therefore I will go ahead and close this thread until such time as either a straightforward alternative or workaround is found.

If anyone feels this thread should remain open, please let me know with your reasoning and I will go ahead and re-open it immediately.

Thank you all for your time and understanding in these matters,
-Adam
