### ISSUE TITLE
D-BUS implementation in Userland

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#233]
Dear specialists,
Because Userland is user space version of Linux, it will be very probably too complex and may be even impossible to implement sockeds here. So D-BUS interprocess communication do not work today. Because I want to help you, I have found amazing article, which may be show some work around.
It would be very interesting to try it out.
sudo sed -i 's/<listen>.*<\/listen>/<listen>tcp:host=localhost,port=0<\/listen>/' /etc/dbus-1/session.conf
Original article is here:
https://www.zdnet.com/article/how-to-run-run-the-native-ubuntu-desktop-on-windows-10/
Please, which negative effect may this work around introduce? Will be possible to communicate with Pulseaudio client for Android after using this work around?
Will be inter process communication too slow when TCP will be used?

**Comment by JohnWang1023** [comment]
I tried that and changed the /usr/share/dbus-1/session-local.conf but it still have the same issue.
Also some user already mentioned it in  https://github.com/CypherpunkArmory/UserLAnd/issues/67#issuecomment-401610212

**Comment by JanuszChmiel** [comment]
Oh no. So my attempt to help was not good idea, since it is much more 
complex as I could think.
So this approach will not repair D-BUS issue.
So I try The last chance.

What about this project, packages are made currently only for Fedora or 
Arch Linux only. But may be, that it can help.

https://lwn.net/Articles/731755/

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel and to all in this thread:

May I recommend all issues regarding dbus issues be discussed in issue #157 and this one be closed? There have been multiple threads regarding graphical errors and I am trying to consolidate them into the appropriate spaces while I try to work them out.

Thank you all for your time and consideration,
-Adam
