### ISSUE TITLE
Add shellinabox as a second SSH based service to control Userland terminal

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#238]
Dear specialists,
I have found very interesting SSH based service called shellinabox. I would like to please you if it would be possible to incorporate this second SSH based service to The Userland, so User would be able to use Connect bot or shellinabox. The main reason for my plea is The fact, that shellinabox allow user to connect by using their WEB browsers by typing ip address followed by : character and defined port number.
It would be good idea, since user can use Firefox, or Chromium on their Android to watch and interact with Userland terminal. shellinabox can be perfectly installed by using apt-get install shellinabox
There should not be difficulty related to service starting. What do you think about my idea?
this approach would also solve accessibility, since user can  use arrow keys on WEB page produced by shellinabox. Using standard Connectbot based terminal with screen reader is not very good while working with The device. Since working with browser support screen reader build in navigation keys. User can fast read data and type The terminal command on The edit field.
Thank you very much for yours opinions and for yours support.
With kindness regards.
Janusz Chmiel

**Comment by corbinlc** [comment]
Even though ConnectBot is specifically called out in the app (it won't be in the future), UserLAnd is compatible with any app that supports a SSH URI intent.  Is there a shellinabox app that supports such a thing?

If not, is your suggestion that we add a web intent to connect via the browser?

**Comment by JanuszChmiel** [comment]
Dear Mr Champion,
Unfortunately, I was overjoyed because of Shellinabox too soon. Since I 
can not activate any command, by other words, I can not find The way how 
to emulate Enter key, since in editable field of WEB page, which 
Shellinabox generate is no opportunity to generate Enter inside edit 
box. And connect button do not work. I thought, that this aproach will 
allow me to use Userland console much more effectively, but it was my 
wrong impression. I have also filled out The issue on Shellinabox GIThub 
repository to find out, how to activate some command.
Connect bot is for now The only one solution, which allow Me to use this 
environment from Android device. Because It is necessary to use Public 
key, Putty for WIndows do not allow me to use Userland from other 
WIndows machine.
But thank you very much for yours patience with my pleas.

**Comment by Herzogs** [comment]
Could not re-implement wShell for the use of UserLand?
