### ISSUE TITLE
Error extracting ./var/run

### ISSUE THREAD

**Issue by themipror** [CypherpunkArmory/UserLAnd#241]
This app take longer than 1hour to extract ./var/run and it never finish extracting, it never extract it.

**Comment by AdamMatthewLTM** [comment]
@th3or14 ,

My apologies for the delay. I am going to close this issue for the time being. If you are still experiencing issues with application extractions, please let me know and I will immediately re-open this thread. In your reply can you please include device specific information (hardware model and android version as well as which version of userland you are running along with which filesystem you are using) according to the template provided?

Thank you for your patience in these matters,
-Adam
