### ISSUE TITLE
Can't manage to sudo apt-get update on debian

### ISSUE THREAD

**Issue by KarlJackD** [CypherpunkArmory/UserLAnd#243]
I just recently installed debian on my samsung galaxy note 5 and I can't get apt-get update to work. I use sudo but it tells me the signature 
isn't verified and it doesnt want to download some specific package. 

What it tells me : 

user@localhost:~$ sudo apt-get update
Ign:1 http://cdn-fastly.deb.debian.org/debian stable InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian stable-updates InRel
ase [91.0 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stable Release [118
B]
Get:4 http://cdn-fastly.deb.debian.org/debian stable Release.gpg [
434 B]
Ign:2 http://cdn-fastly.deb.debian.org/debian stable-updates InRel
ase
Ign:4 http://cdn-fastly.deb.debian.org/debian stable Release.gpg
Hit:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Hit:6 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en
Hit:7 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stable/contrib Trans
ation-en
Hit:9 http://cdn-fastly.deb.debian.org/debian stable/non-free arm6
 Packages
Hit:10 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en
Ign:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Ign:6 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en
Ign:7 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stable/contrib Trans
ation-en
Ign:9 http://cdn-fastly.deb.debian.org/debian stable/non-free arm6
 Packages
Ign:10 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en
Hit:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Hit:6 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en
Hit:7 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages
Hit:8 http://cdn-fastly.deb.debian.org/debian stable/contrib Trans
ation-en
Hit:9 http://cdn-fastly.deb.debian.org/debian stable/non-free arm6
 Packages
Ign:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Hit:10 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en
Ign:6 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en
Ign:7 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stable/contrib Trans
ation-en
Ign:9 http://cdn-fastly.deb.debian.org/debian stable/non-free arm6
 Packages
Ign:10 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en
Ign:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Err:6 http://deb.debian.org/debian stable/main Translation-en
  BZ2_bzread: /var/lib/apt/lists/partial/deb.debian.org_debian_dis
s_stable_main_i18n_Translation-en.bz2 Read error (-5: DATA_ERROR_M
GIC)
Ign:6 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en
Hit:7 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages
Ign:8 http://cdn-fastly.deb.debian.org/debian stable/contrib Trans
ation-en
Hit:9 http://cdn-fastly.deb.debian.org/debian stable/non-free arm6
 Packages
Ign:10 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en
Ign:5 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages
Fetched 93.5 kB in 7s (13.3 kB/s)
Reading package lists... Done
W: GPG error: http://cdn-fastly.deb.debian.org/debian stable-updat
s InRelease: At least one invalid signature was encountered.
W: The repository 'http://deb.debian.org/debian stable-updates InR
lease' is not signed.
N: Data from such a repository can't be authenticated and is there
ore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user conf
guration details.
W: GPG error: http://cdn-fastly.deb.debian.org/debian stable Relea
e: At least one invalid signature was encountered.
W: The repository 'http://deb.debian.org/debian stable Release' is
not signed.
N: Data from such a repository can't be authenticated and is there
ore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user conf
guration details.
E: Failed to fetch http://deb.debian.org/debian/dists/stable/main/
18n/Translation-en  BZ2_bzread: /var/lib/apt/lists/partial/deb.deb
an.org_debian_dists_stable_main_i18n_Translation-en.bz2 Read error
(-5: DATA_ERROR_MAGIC)
E: Some index files failed to download. They have been ignored, or
old ones used instead.

I cant install man also.

**Comment by Herzogs** [comment]
could you try this?

sudo rm -rf /var/lib/apt/lists/*
sudo rm -rf /etc/apt/sources.list.d/*
sudo apt-get update

**Comment by iso9660** [comment]
The same happened to me.
After trying the proposed solution I get: GPG error: ..... : At least one invalid signature was encountered.

**Comment by KarlJackD** [comment]
Well I tried on my side too, hoping it would work but now the output is a little bit cleaner, even tho it still doesn't work. 

Here is the things I have done: 

user@localhost:~$ sudo rm -rf /var/lib/apt/lists/*
user@localhost:~$ sudo rm -rf /etc/apt/sources.list.d/*
user@localhost:~$ sudo apt-get update
Ign:1 http://cdn-fastly.deb.debian.org/debian stable InRelease
Get:2 http://cdn-fastly.deb.debian.org/debian stable-updates InRel
ase [91.0 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stable Release [118
B]
Get:4 http://cdn-fastly.deb.debian.org/debian stable Release.gpg [
434 B]
Ign:2 http://cdn-fastly.deb.debian.org/debian stable-updates InRel
ase
Get:5 http://cdn-fastly.deb.debian.org/debian stable-updates/main
rm64 Packages [5096 B]
Get:6 http://cdn-fastly.deb.debian.org/debian stable-updates/main
ranslation-en [4512 B]
Ign:4 http://cdn-fastly.deb.debian.org/debian stable Release.gpg
Get:7 http://cdn-fastly.deb.debian.org/debian stable/main arm64 Pa
kages [6940 kB]
30% [7 Packages 2312 kB/6940 kB 33%]                  255 kB/s 40s
Get:8 http://cdn-fastly.deb.debian.org/debian stable/main Translat
on-en [5393 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stable/contrib arm64
Packages [39.9 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stable/contrib Tran
lation-en [45.9 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian stable/non-free arm
4 Packages [50.8 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian stable/non-free Tra
slation-en [80.6 kB]
Fetched 12.8 MB in 14s (855 kB/s)
Reading package lists... Done
W: GPG error: http://cdn-fastly.deb.debian.org/debian stable-updat
s InRelease: At least one invalid signature was encountered.
W: The repository 'http://deb.debian.org/debian stable-updates InR
lease' is not signed.
N: Data from such a repository can't be authenticated and is there
ore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user conf
guration details.
W: GPG error: http://cdn-fastly.deb.debian.org/debian stable Relea
e: At least one invalid signature was encountered.
W: The repository 'http://deb.debian.org/debian stable Release' is
not signed.
N: Data from such a repository can't be authenticated and is there
ore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user conf
guration details.

**Comment by Herzogs** [comment]
First if you use apt clean and apt update not working?

If not working try
chown _apt /etc/apt/trusted.gpg.d/trustdb.gpg
chmod g + r /etc/apt/trusted.gpg.d/trustdb.gpg
apt update

**Comment by iso9660** [comment]
apt clean and apt update didn't solve the issue

I tried the second option but the file /etc/apt/trusted.gpg.d/trustdb.gpg doesn't exist.

**Comment by Herzogs** [comment]
The problem should be a missing the trustdb, download and install debian-archive-keyring (https://packages.debian.org/stretch/debian-archive-keyring) and installed with dpkg -i debian-archive-keyring_2017.5_all.deb

**Comment by Herzogs** [comment]
In /etc/apt/trusted.gpg.d and there is a version of wget in busybox (busybox wget)

**Comment by iso9660** [comment]
The keyring cannot be installed :( 

![captura de pantalla de user s x desktop localhost 51 en 2018-09-08 00 11 36](https://user-images.githubusercontent.com/2889851/45245256-f151b780-b2fb-11e8-8d84-ec4b1d179652.png)

**Comment by AdamMatthewLTM** [comment]
To all in this thread: 

The two separate issues of sudo and wget should have been resolved by this time. If anyone here is still experiencing issues with sudo please let me know as soon as possible and include all relevant information (hardware and software versions) and I will attempt to diagnose the problem. I will go ahead and mark this thread as high priority if anyone is still experiencing this issue. If sudo and wget work for everyone I will close this thread within the next few days.

Thank you all for your time and patience in these matters,
-Adam

**Comment by luumiem** [comment]
Hi,


I'm keep getting temporary failure resolving 'deb.debian.org. for (userland debian ssh)


I installed on galaxy s10 plus android 9




Also I cannot install any app

Example 

sudo apt-get install vim


Please see the log errors below.


-----------

~$ sudo apt-get update && sudo apt-get dist-upgrade

Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


‐‐------------


~$ sudo apt-get install vim
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libgpm2 vim-common vim-runtime xxd
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime xxd
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 6597 kB of archives.
After this operation, 31.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  xxd vim-common libgpm2 vim-runtime vim
Install these packages without verification? [y/N] y
Err:1 http://deb.debian.org/debian stable/main arm64 xxd arm64 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable/main arm64 vim-common all 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian stable/main arm64 libgpm2 arm64 1.20.4-6.2+b1
  Temporary failure resolving 'deb.debian.org'
Err:4 http://deb.debian.org/debian stable/main arm64 vim-runtime all 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian stable/main arm64 vim arm64 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/v/vim/xxd_8.0.0197-4+deb9u1_arm64.deb Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/v/vim/vim-common_8.0.0197-4+deb9u1_all.deb Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gpm/libgpm2_1.20.4-6.2+b1_arm64.deb Temporary failure resolving 'deb.debian.org'



Sent from my Samsung Galaxy smartphone.

**Comment by luumiem** [comment]
Are there a around to install vi, vim or nano editor on android 9?
