### ISSUE TITLE
NPM not working

### ISSUE THREAD

**Issue by pepepc** [CypherpunkArmory/UserLAnd#245]
Dear all,

I tried to install nodejs 8.10.0 and npm 3.5.2 on UserLand and it seemed to work properly. Indeed I can run node -v / npm -v and the version is shown correctly

Anyhow, the installation should not be correct since when I try to run the command 

> sudo npm install npm -g

The following error message appears on the screen:

Error: could not get uid/gid

at /usr/share/npm/node_modules/uid-number/uid-number.js:37:16
[...]

Does anyone figure out what the problem can be?

PD: I need this to install the Ionic framework which also shows the same error

Thanks

**Comment by corbinlc** [comment]
Can you provide all steps, starting from a new install, to reproduce this issue?  Like can you provide the exact command lines you used for installing node and npm?

**Comment by pepepc** [comment]
I am trying to install the Ionic framework over UserLand, but the installation fails in the NPM step:

```
_sudo apt-get install software-properties-common -y_
_curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -_
```

_```
sudo apt-get install nodejs -y_
_sudo npm install npm -g_
```

And here is where I get that error message. If I try to install Ionic with the command below, it shows the same issue:

_`sudo npm install ionic -g`_

**Comment by Malrok** [comment]
Hi,
I have successfully installed and am using npm on an Ubuntu session,but for that I had to use nvm
I have described the procedure here: 
https://medium.com/@themalrok/how-i-could-proudly-launch-an-ionic-serve-on-my-android-phone-6d0dfbd4aec9

**Comment by AdamMatthewLTM** [comment]
Thanks for finding this workaround @Malrok , I'm going to go ahead and close this thread for the time being. If anyone is still having difficulty please comment here and I'll re-open it ASAP.
-Adam

**Comment by SoumyadeepChatterjee96** [comment]
I just downloaded Userland and chose Debian and when I installed nodejs the installation went fine but when i am trying to install NodeRed, it returns with 'bash: npm: command not found' and I seem to find no related issue from which I can get any kind of help.

Please Help!

**Comment by stephenprater** [comment]
@SoumyadeepChatterjee96 It appears you have a separate issue.  Please open a new issue and fill in our issue template so we can help you.

**Comment by pepepc** [comment]
> Hi,
> I have successfully installed and am using npm and ionic on an Ubuntu session,but for that I had to use nvm
> I have described the procedure here:
> https://medium.com/@themalrok/how-i-could-proudly-launch-an-ionic-serve-on-my-android-phone-6d0dfbd4aec9

It tried to follow the post but I have not managed to reinstall or rebuil the pakage node-sass. Every time I try to do it the system fails. 

Has anyone managed to make ionic work following this procedure?

Thanks
