### ISSUE TITLE
Inclusion in F-Droid

### ISSUE THREAD

**Issue by Poussinou** [CypherpunkArmory/UserLAnd#255]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you? It looks very promising :)

**Comment by licaon-kter** [comment]
@MatthewTighe Please reopen this.

You'll need a fdroid flavour that excludes the closed sourced Crashlytics integration.

Ref: https://github.com/CypherpunkArmory/UserLAnd/commit/fde73618900201b316d34c5907ac2890539f5907#diff-39e7d8c00954e920b98e7636f0ac30b2

Ref: https://f-droid.org/wiki/page/tech.ula/lastbuild_43

**Comment by licaon-kter** [comment]
ACRA?

**Comment by MatthewTighe** [comment]
That's the plan. Hope to release an updated version using it instead of Crashlytics today.

**Comment by licaon-kter** [comment]
Right, builds fine, but, is there any issue if I set this: https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/tech.ula.yml#L119 ?

**Comment by MatthewTighe** [comment]
Are you referring to setting the Tracepot endpoint to a blank string? There isn't any _technical_ issue, but the crash logs we receive from the app go a long way towards helping us debug them. Is there any way for me to upload our secret somewhere (secret) so that it could still be part of the F-Droid release build?

**Comment by licaon-kter** [comment]
No, no secrets in F-Droid, everything must be known.

One option, albeit more coding from your side, as F-Droid itself does, pop-up a dialogue asking the user to send an e-mail with the info, if they wish.

**Comment by MatthewTighe** [comment]
That's fine then. F-Droid users can also come here.

**Comment by MatthewTighe** [comment]
@licaon-kter Do you know of a way to check acceptable libraries? ACRA hasn't been as useful as I'd hoped, and I'm thinking of switching to Sentry. It all _looks_ FLOSS compatible, but it'd be nice to check before making the change

**Comment by licaon-kter** [comment]
Bugsnag not good enough?

**Comment by MatthewTighe** [comment]
@licaon-kter  I could look into on Monday. I just know already that Sentry matches my needs really well. Would it prevent inclusion on F-Droid though? I didn't see among the listed issue packages.

**Comment by licaon-kter** [comment]
@MatthewTighe Didn't know about Sentry until now, but looks ok, license wise, and I guess it's ok if its libs are in one of the [allowed mavens](https://gitlab.com/fdroid/fdroidserver/blob/master/fdroidserver/scanner.py#L99).

**Comment by licaon-kter** [comment]
FYI since https://github.com/CypherpunkArmory/UserLAnd/commit/8393595accdc59ead2f252ac7633ec86c6e85a22#diff-39e7d8c00954e920b98e7636f0ac30b2R24 you define versionCode elsewhere, so fdroid update check can't autoupdate.
