### ISSUE TITLE
I Can't Install Linux

### ISSUE THREAD

**Issue by DCT54Studio** [CypherpunkArmory/UserLAnd#258]
Hello, my device is: reeder/sofia3gr
But my device can't install linux with errors. Error is: "Failed to execute Command" 
I think that is system read only on my device. Thank you.
![img_20180918_102137](https://user-images.githubusercontent.com/28977114/45671408-0a453e80-bb2e-11e8-9ea7-2e6e441a9f88.jpg)

**Comment by AdamMatthewLTM** [comment]
@DCT54Studio ,

I apologize for the inconvenience but could you please reply here with the following information as best as you can:

1) What is your phone's Make and Model number?

2) Did you download UserLAnd through the app store without any errors?

3) Which filesystem are you using for VNC? Debian or Ubuntu?

Thank you for your time and consideration,
-Adam
