### ISSUE TITLE
Error: GDBus.Error:org.freedesktop.DBus.Error.Spawn.PermissionsInvalid: The perm  ission of the setuid helper is not correct

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#269]
steps to reproduce.
sudo service dbus start
sudo apt update
you will see
Error: GDBus.Error:org.freedesktop.DBus.Error.Spawn.PermissionsInvalid: The perm
 ission of the setuid helper is not correct 
If no when performing apt update, you will see this error when installing other packages.
such as
apt install espeak
May be, that this little bug is also not remarkable, it is The result of The complexity of running Linux in userspace.
I have previously installed LXDE
apt install task-lxde-desktop
Gnome
apt install task-gnome-desktop

**Comment by AdamMatthewLTM** [comment]
@JanuszChmiel ,

This is a late reply but can you please confirm you're still running into this issue with the current version of UserLAnd ?

**Comment by zeeshan9128** [comment]
I also have this issue in ubuntu when i try to install blueman or start xfce4
