### ISSUE TITLE
Add a desktop

### ISSUE THREAD

**Issue by DallasTheCat** [CypherpunkArmory/UserLAnd#271]
Add a desktop to the app so I can emulate a full PC.

**Comment by ashutoshmaurya1122** [comment]
You can install lxde desktop using command "sudo apt-get install lxde" or "sudo apt-get install lxde-core".Last command install only base-desktop environment.

**Comment by AdamMatthewLTM** [comment]
There are a number of different desktop environments available to use in conjunction with UserLAnd (many are very resource intensive and may not be fully supported such as KDE or Gnome). Leaving the choice as to which graphical environment they desire is a core principle of the app. 

That being said, I'll leave this thread open for now with the following offer:
If anyone is suggested in UserLAnd supporting a specific desktop environment or has suggestions for what features it should have, please comment here. 

Thanks,
-Adam

**Comment by AdamMatthewLTM** [comment]
I'm going to close this thread for the following reason:

Startup application launchers will soon be available, and desktop environments may be included with them at a certain point so this feature is in fact being implemented.

If anyone feels this thread should remain open, please comment here with your reasoning and I will go ahead and re-open it ASAP.

Thank you for your time and consideration,
-Adam

**Comment by Naoko0319** [comment]
How can I install Xfce?

**Comment by mirkokral** [comment]
sudo apt install xfce4

**Comment by mirkokral** [comment]
> How can I install Xfce?

`sudo apt install xfce4`
Worked for me.

**Comment by NotOkayGit** [comment]
this is an old one. i barely knew linux when i made it.
yeah
`sudo apt install xfce4`
that should work.
