### ISSUE TITLE
Add custom filesystem option

### ISSUE THREAD

**Issue by josephworks** [CypherpunkArmory/UserLAnd#273]

**Comment by MatthewTighe** [comment]
Closing this issue until details are added.

**Comment by josephworks** [comment]
Basically, add support for more operating systems...

Joseph R.

**Comment by corbinlc** [comment]
We are going to add some more.  Can you tell us which one(s) you want?

**Comment by josephworks** [comment]
I don't know, is it possible to add an ISO to install a custom distro.

Joseph R.

**Comment by josephworks** [comment]
If not, I was thinking of Kali, Manjaro, and ChromeOS.

Joseph R.
