### ISSUE TITLE
Filesystems->delete follows symlinks into /sdcard/

### ISSUE THREAD

**Issue by muehlber** [CypherpunkArmory/UserLAnd#275]
Deleting a filesystem in the UserLAnd GUI deletes that filesystem and recursively follows symbolic links within the filesystem into the /sdcard/ directory; files underneath linked directories are deleted. I just deleted almost everything on my mobile...

- create a directory 'test' in your internal storage, create some files underneath.
- create a filesystem 'debian' in UserLAnd
- log into 'debian' and 'ln -s /sdcard/test ./test; exit'
- delete the 'debian' filesystem in UserLAnd
- ... and find 'test' empty.

I did expect only 'debian' to be removed but my files in /sdcard/, wich are shared among differend UserLAnd filesystems, to remain untouched.

Device: Moto X4
Android Version: 8.0.0
UserLAnd Version 0.3.4

**Comment by corbinlc** [comment]
We will work on this in the not too distant future.  We just call `deleteRecursively` (https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/delete-recursively.html) but we can do something more clever that deletes recursively, but doesn't not follow any symbolic links.

**Comment by dsvilko** [comment]
Aaaaa! I was just hit by this bug and lost the complete content of my internal phone storage! Some of it was a critical work-related data that wasn't yet backed-up! To have know about this bug and not to at least provide a warning before the delete is beyond irresponsible, if the fix was not yet ready!
Medium priority? What would you then classify as a critical bug?!

**Comment by MatthewTighe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When deleting file systems, don't follow sym links outside of the filesystem.](https://trello.com/c/vfqazXZD/597-when-deleting-file-systems-dont-follow-sym-links-outside-of-the-filesystem)

**Comment by MatthewTighe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When deleting file systems, don't follow sym links outside of the filesystem.](https://trello.com/c/vfqazXZD/597-when-deleting-file-systems-dont-follow-sym-links-outside-of-the-filesystem)

**Comment by MatthewTighe** [comment]
Release is being made to production to fix this issue momentarily.
