### ISSUE TITLE
shared memory can not be created

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#289]
When I have started to use GTK based apps which communicate with Xserver XSDL, I have found out, that after some period of time, running app generates Cc or C++ memory allocation bugs such as.
Shared memory file can not be created.
Pulseaudio can not allocate shared memory.
If I get error that shared memory file can not be created. Can be this complex issue debugged and repaired, or unfortunately, this problem is really caused by The fact, that Android components allocates too much RAM and there is too small amount of MB for Userland?
If it is the cause.
I can try to root my device and I can try to remove system APPS which are not mandatory such as Google Play services, which allocates 30 MB of RAM or more even if Google Play screen is not The active screen or in The background.
If The problem is caused by The fact, that there is not enough memory.
Does somebody of you know, if swapon command can be run in userspace environment and if so, if some other swap file related command could be exclusively used by Userland sub processes to allocate virtual memory only for those processes? Not for whole Android including various Android specific services? 
I think, that Android device manufacturers are enabling swap file on internal chips of devices. May be, that there are even more than one swap file with various sizes at A time.
But sure, virtual memory mechanism of ARM and other CPUS can not be overloaded. So I Am afraid, that to let system run stable, only two swap files on various media can be used at A time.
But it is only my assumption, somebody of us who deeply knows Linux and Android kernel and virtual memory mechanism of ARM and other CPUS will correct my misunderstanding of this problem.

Thank you very much for yours answer.

**Comment by corbinlc** [comment]
Android doesn't have normally shared memory support.  As such a workaround is required, but this workaround does not yet work inside chroots like UserLAnd.

**Comment by bubnikv** [comment]
I don't know much about the topic, but maybe the shared library replacement from Termux may be used somehow?

https://github.com/termux/libandroid-shmem

**Comment by corbinlc** [comment]
We have added shared memory support.  Postgresql is working now, for example.

**Comment by JanuszChmiel** [comment]
Oh you are excellent. It would be very interesting to experiment abit 
with other complex apps, which are using shared memory including 
gnome-shell. Sure, The best devices to try this complex app would be 
devices which have more than 2 GB of free RAM.
By The way, how did you developed so complex think? Did you incorporated 
some new .so library, or you have modified Proot?
And which distros support shared memory creation? Debian and Ubuntu?
Really, thank you very much again. Very well done.
