### ISSUE TITLE
Problema na distribuição da linguagem para a distro

### ISSUE THREAD

**Issue by Joseanosousa** [CypherpunkArmory/UserLAnd#290]
When I as a user in Debian
I give the command `sudo apt-get install locales`
So I change the language to ** UTF8 **
All right, but then the language is only in Portuguese in root, the user on

**Comment by Herzogs** [comment]
Good morning to change the language you followed these steps? because it worked for me
1 - `apt install debconf` and do `sudo dpkg-reconfigure locales`
2-  in the menu you chose the locale that you wanted me for example (es_AR.UTF8) 
3-  and put this in your terminal ( change for your locale)
```
user@localhost:~$ echo "export LC_ALL=es_AR.UTF8" >> .bashrc
user@localhost:~$ echo "export LANG=es_AR.UTF8" >> .bashrc
user@localhost:~$ echo "export LANGUAGE=es_AR.UTF8" >> .bashrc
```

**Comment by Joseanosousa** [comment]
Muito obrigado! Resolveu meu problema.
________________________________
