### ISSUE TITLE
Internal monitor mode support

### ISSUE THREAD

**Issue by mirzaatifbaig** [CypherpunkArmory/UserLAnd#299]
So,We can have a Chroot/proot on android running eh.But can it support Monitor mode aka rfmon inside it.I have a kernel with injection support and a device that supports it but can't use it as the app won't allow it.

**Comment by AdamMatthewLTM** [comment]
@mirzaatifbaig ,

I apologize if I am reading your question incorrectly, so please let me know if this answers it sufficiently:

Android devices limit raw network traffic to be visible only by root, and I am uncertain if wireless network traffic applies to this as well. 

However, a current active area of research for the UserLAnd app which is being worked on is issue #200 , in which methods for interacting with the Android's API for certain things such as location information are being looked at. 

If it is possible to enable monitor mode within an Android device in UserLAnd via the API, I will post an update to that thread. Therefore may I suggest this thread be closed and all future updates be made on issue #200 ? 

Thank you for your time and patience in these matters,
-Adam

**Comment by mirzaatifbaig** [comment]
That's right.I must have been thinking in other direction but it is Quite Possible.I think another app named termux has it.And I must say this is currently the fastest Linux installation along with the most stable one I have yet encountered.So,Thanks for your wonderful work.I am closing this issue for now and will be waiting on other one.
