### ISSUE TITLE
Slow mirrors

### ISSUE THREAD

**Issue by mirzaatifbaig** [CypherpunkArmory/UserLAnd#300]
The default mirrors appear to be super slow.

**Comment by AdamMatthewLTM** [comment]
@mirzaatifbaig ,

Thank you for your post. The default mirrors appear to be working fine for me right now (I am in the southeast United States) and have tested the connections over two different internet providers. 

Can you please 1) confirm you are still having this lag issue, and 2) provide more information you feel is relevant?

Thank you for your time,
-Adam

**Comment by mirzaatifbaig** [comment]
I am having this issue still.The thing is I am living in East Asia right now where the speed for these particular mirrors appear to be very slow,Way too slow actually.But one can easily edit the sources.lst.But not before updating and  upgrading as I think that will cause issues.In my case it took about 27 hours to run apt update only.After which I turned to Ubuntu which had an average speed.I think instead of regional mirrors You should use The main one.I am closing this now As this appear to be not related to the app.

**Comment by corbinlc** [comment]
What device are you using?  I guess we should figure out a way to get people pointed at the right mirrors by default.  We are US based, so we might have not made a good choice for everyone.  Would be good to fix this.

**Comment by mirzaatifbaig** [comment]
Thanks but I changed them a long time ago.I don't think I should've posted it but for beginners it is a pain.I think including the main mirror would be wise or implementing a simple script(There are loads of made already).Also I am no developer or a programmer so don't ask me complex Question.I am currently using it on Pixel 3 XL(Not rooted) along with my test device Samsung note 3(Rooted).
