### ISSUE TITLE
I am not allowed to access the / dev folder

### ISSUE THREAD

**Issue by Joseanosousa** [CypherpunkArmory/UserLAnd#306]
I am having trouble accessing the / dev folder it says I am not allowed
I hope you guys solve this, because it is giving package installation error because it does not have stdin permission.

**Comment by Herzogs** [comment]
which package are you trying to install and it gives you that problem and for the doubts before the installer you put "sudo"?

**Comment by corbinlc** [comment]
You are running as an android app which does not have root permissions.  On android simply doing `ls /dev` returns a permissions denied.  This causes a lot of warnings or errors, but normally is not blocking progress.  Is there something more specific you are trying that is not working?

**Comment by donomii** [comment]
I can't mount fuse filesystems because they try to access /dev/fuse.  This would add a lot of functionality to userLAnd, since it is much easier to just mount a filesystem with software and personal data than to install it all and keep the data in sync.

**Comment by Joseanosousa** [comment]
Thank you anyway, everything worked out!

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________
