### ISSUE TITLE
bVNC - Connection Failed

### ISSUE THREAD

**Issue by mitzemerald** [CypherpunkArmory/UserLAnd#309]
I tried installing lxde, lxde-core and libreoffice in separate occasions and crashes at the end of each installation. After that I can't open the distro anymore and keep failing to connect to bVNC. Although one time I managed to complete the installation for lxde-core but soon stop working after inputting "exec startlxde".

So basically what I do is input:
sudo apt-update
sudo apt-get install (lxde, lxde-core, libreoffice)

The error message I got from bVNC is:
Error! 
Connection failed. Connection to VNC server failed with reason: failed to connect to /127.0.0.1 (port 5951) from /:: (port 53888): connect failed: ECONNREFUSED (Connection refused) java.net.ConnectException: failed to connect to /127.0.0.1 (port 5951) from /:: (port 53888)• connect failed: ECONNREFUSED (Connection refused) at libcore.io.loBridge.connect(loBridge.javal 38) at java. net. PlainSocketlmpl.socketConnect(Plain Socketlmpl.java:129) at java.net.AbstractPlainSocketImpl.doConnect( AbstractPlainSocketlmpl.java:357) at java.net.AbstractPlainSocketImpl.connectToA ddress(AbstractPlainSocketlmpl.java:201) at java.net.AbstractPlainSocketImpl.connect(Ab stractPlainSocketImpl.javal 83) at java.net.SocksSocketImpl.connect(SocksSock etlmpl.java:356) at java.net.Socket.connect(Socketjava:616) at java.net.Socket.connect(Socket.java:565) at java.net.Socket.(Socket.java:445) at java.net.Socket.(Socket.java:217) at corniiordanov.bVNC.RfbProto.setParameters( RfbProto.java:344) at corniiordanov.bVNC.RfbProto.(RfbProto.java: 328) at corniiordanov.bVNC.RemoteCanvas.startVnc Connection(RemoteCanvas.java:448) at corniiordanov.bVNC.RemoteCanvas.access$ 200(RemoteCanvas.java:99) at corniiordanov.bVNC.RemoteCanvas$2.run(Re mntpranvac iava•95171 ('.A, icprl 
ACKNOWLEDGED 
........

Although It's possible that I'm doing something wrong since for the most part I have no idea what I'm doing and I will say sorry in advanced if my issue will seem be misplaced here. I'm just trying to get libreoffice working on my phone. I can't root my phone because the bootloader's locked.

I'm using Huawei Mate 10 lite with Android 8.0.0

**Comment by corbinlc** [comment]
This is supposed to work.  I have used lxde-core on a very similar device.  Does using vnc before installing any extra packages work?

**Comment by emidiomorgia** [comment]
Same issue for me as I wrote in #161. Mate 10 pro android 8 after installing lxde or some packages the connection is lost forever. If I can install lxde before stopping forever the window frame of terminal in vnc mode is frame less without buttons or title bar. I had this issue since the first beta

**Comment by Tropeas** [comment]
I have the same issue. After first install , I see messages saying stop and then restart session, 
When I am trying to connect with vnc to lxde after stop it fails ... I have log to assign

**Comment by corbinlc** [comment]
This was due to #398 .  We added a work around for most of the Huawei 8.0 issues, but really the best solution if possible is to upgrade to EMUI 9.0 on your device, that seems to fully solve these issues.

**Comment by unsponsoredgeek** [comment]
I have a similar problem with my Razer Phone 1 running Android 8.

**Comment by DerpyPlayz18** [comment]
Countinously crashing for me on pixel 4a, I don't even have time to install cmake before it crashes.

**Comment by denisyurin** [comment]
I have this issue on Galaxy Tab S8 Ultra, once a graphical environment is installed than at some random point it crashes with bvnc connection failed error: Connection to VNC server failed with reason: failed to connect to /127.0.0.1 (port 5951) from /:: (port 44322): connect failed: ECONNREFUSED (Connection refused) ....
