### ISSUE TITLE
bvnc setup not save

### ISSUE THREAD

**Issue by jpph** [CypherpunkArmory/UserLAnd#310]
each time I launch app , I have to set mouse mode to pan. I didn't find a way to make it stiky

**Comment by corbinlc** [comment]
Can you file an issue against bvnc?  That team should be able to solve this much faster than we can.

**Comment by jpph** [comment]
Done, opened issue 143 on bvnc github website. Thank you

**Comment by corbinlc** [comment]
Thank you.  Please follow up here with anything you learn if you think it will help others.  Also if they are not helpful in a reasonable amount of time please tell us.  We have worked with their developer before.
