### ISSUE TITLE
Is AMD64 and I3 architectures Stable

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#311]
I use a chromebook. I found this. I wanted to try it and when I use bVNC I cant find any apps I click and found the menu and went to apps NONE. Then I went to debain. There was apps but I can't lauch anything.

**Comment by stackerlon** [comment]
I tried installing armhf and i3 architecture, then i installed firefox:armhf and other i3 packages, they just won't ran and it is really hard time removing the architectures. It may be the problem with multiarch support.

**Comment by AdamMatthewLTM** [comment]
The supported architectures for UserLAnd's linux filesystems are:

x86 , x86_64, generic ARM (armhf), and ARM 64. 

@EnderNightLord-ChromeBook and @stackerlon , I am unfamiliar with apple's hardware, so can you please give me the exact model numbers of the devices you're trying to run UserLAnd on?

**Comment by stackerlon** [comment]
Amd64 and i386 won't work on userland.
Armhf is causing update problems, it always shows Err downloading some package files. And firefox arm64 just works fine in ubuntu and iceweasel in debian.

**Comment by EnderNightLord-ChromeBook** [comment]
A HP chromebook X360 11 GE with a intel celeron

**Comment by corbinlc** [comment]
@EnderNightLord-ChromeBook  I believe you have quite bit working on your chrome book now based on #455  .  Does that mean we can close this.

**Comment by EnderNightLord-ChromeBook** [comment]
yes but keep #455 open
