### ISSUE TITLE
Automatic Desktop Installer

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#313]
This feature would be nice. You would be able to install Gnome, KDE, Xfce4, Lxde and for The AMD based boards. Unity on ubuntu.

**Comment by corbinlc** [comment]
We are thinking about making it so Lxde is our default...instead of just twm, but giving people a choice seems like a good place to end up.

**Comment by AdamMatthewLTM** [comment]
@EnderNightLord-ChromeBook ,

I am in the process of writing up automatic desktop environment launchers for UserLAnd. This has been a requested feature in multiple threads, so for the time being I am going to close this one. If you feel it should remain open, please let me know your reasoning and I will re-open it ASAP. 

Thank you for your time and consideration,
-Adam

**Comment by EnderNightLord-ChromeBook** [comment]
I think twm should still be an option to choose...
