### ISSUE TITLE
Iptable or a way to open ports. 

### ISSUE THREAD

**Issue by MarsWalker** [CypherpunkArmory/UserLAnd#333]
Hello,

I'm trying to configure Webmin to run on my phone,

I'm running as root and when I do:
sudo iptables -I INPUT 1 -p tcp --dport 10000 -j ACCEPT
I get:
**root@localhost:/tmp# sudo iptables -I INPUT 1 -p tcp --dport 10000 -j ACCEPT
iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.**

I'm trying to run a small webserver with php support and CIFS :)

Any ideia on how can I open port 80 and 10000 on userland on ubuntu ?

Thank you for tis great software.

**Comment by corbinlc** [comment]
Ports below 1000 are restricted on Android.  Please run your server on a higher port number, like 8080.  This is now working well for many people.
