### ISSUE TITLE
Apps cannot be run if their session or filesystem have been renamed

### ISSUE THREAD

**Issue by wwender** [CypherpunkArmory/UserLAnd#337]
I use one custom app. 
I installed one (paid) app: Firefox that was working as expected

After rebooting the pone I am not able to start the Firefox App any-more: I always get the "Error message/Flash message": "Apps cannot be run if their session or filesystem have been renamed".

I deleted the Firefox App and the filesystem (apps) and installed the Zork App. However the message is the same.

**Comment by mashrin** [comment]
I came across this same issue while using the app today.

**Comment by saschadaniels** [comment]
Same issue her after rebooting tablet.

**Comment by MatthewTighe** [comment]
Can those experiencing this issue confirm that they have received the 0.5.1 update? 

To clarify, you still will not be able to rename apps sessions and filesystems. However, deleting the filesystem should should allow you to create a new one from scratch without issue. Also, renaming the session to the type of app that it was using and the filesystem to "apps" should get them back in working order as well.

I'm seeing some unexpected behavior in general around apps right now, so expect 0.5.2 in the next couple days with some additional improvements.

**Comment by wwender** [comment]
I updated to 0.5.2. I deleted the app filesystem and then reinstalled/deployed the firefox app. But I get the same error.

**Comment by MatthewTighe** [comment]
Okay, please update me with your device information and Android version. Do you remember what version of UserLAnd you were using when you first attempted to use Firefox?

Uninstalling and reinstalling UserLAnd would likely fix the issue as well.

**Comment by wwender** [comment]
@MatthewTighe: Yes there is one custom session I use that was there before installing the app(Firefox) and that is there after deleting the app filesystem

**Comment by MatthewTighe** [comment]
@wwender Your custom session won't matter. It's only if the session that had been created to run Firefox was still present.

**Comment by MatthewTighe** [comment]
One thing I could think of that may solve the issue in the interim is manually refreshing apps on the apps the page.

**Comment by wwender** [comment]
@MatthewTighe: the session/app with Firefox disappeared after I deleted the filesystem (apps).

**Comment by MatthewTighe** [comment]
@wwender And what about manually refreshing the apps? If that solves the problem I should be able to put a fix out today.

**Comment by wwender** [comment]
@MatthewTighe: Yes! that works. After manual refreshing the apps page I could start the app.

**Comment by wwender** [comment]
OK I guess this issue is solved now. If I don't read anything else I would close that issue from my side.
