### ISSUE TITLE
Apt-get update failed with GPG error

### ISSUE THREAD

**Issue by opabravo** [CypherpunkArmory/UserLAnd#347]
root@localhost:~# apt update
```

Ign:1 http://cdn-fastly.deb.debian.org/debian stable InRele
se
Get:2 http://cdn-fastly.deb.debian.org/debian stable-update
 InRelease [91.0 kB]
Hit:3 http://cdn-fastly.deb.debian.org/debian stable Releas
Get:4 http://cdn-fastly.deb.debian.org/debian stable Releas
.gpg [2434 B]
Err:2 http://cdn-fastly.deb.debian.org/debian stable-update
 InRelease
  At least one invalid signature was encountered.
Ign:4 http://cdn-fastly.deb.debian.org/debian stable Releas
.gpg
Reading package lists... Done
W: GPG error: http://cdn-fastly.deb.debian.org/debian stabl
-updates InRelease: At least one invalid signature was enco
ntered.
E: The repository 'http://deb.debian.org/debian stable-upda
es InRelease' is not signed.
N: Updating from such a repository can't be done securely,
nd is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and us
r configuration details.
W: GPG error: http://cdn-fastly.deb.debian.org/debian stabl
 Release: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian stable Rele
se' is not signed.
N: Updating from such a repository can't be done securely,
nd is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and us
r configuration details.
```

**Comment by corbinlc** [comment]
I wonder if this issue was never really solved... https://github.com/CypherpunkArmory/UserLAnd/issues/243

**Comment by corbinlc** [comment]
Can you provide more information about what device and android version you are running?

**Comment by opabravo** [comment]
Sure, Mailed.

**Comment by AdamMatthewLTM** [comment]
@opabravo ,

Can you confirm you are still running into the GPG errors?

**Comment by opabravo** [comment]
@AdamMatthewLTM ,

Unfortunately, it still returned the same error after I reinstalled the app.

**Comment by nidusin** [comment]
Having same issue updating Ubuntu

Australia
Samsung Note 5
Android 7.0

Messages:
 ~$ sudo apt-get update
Hit:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Get:2 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease [83.2 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease [88.7 kB]
Err:1 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
  At least one invalid signature was encountered.
Get:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease [74.6 kB]
Err:2 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
  At least one invalid signature was encountered.
Err:3 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
  At least one invalid signature was encountered.
Err:4 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://ports.ubuntu.com/ubuntu-ports bionic InRelease: At least one invalid signature was encountered.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by akilgb** [comment]
I got a similar problem but i don't knnow if it was related to GPG or some ting else. I'm a newbie on this kind of apps but i have some basic knowledge on linux

**Comment by user6800** [comment]
Still getting this error. Anyone find a solution?

**Comment by akilgb** [comment]
I've not found any solution
I wonder if the app was dead and buried or our problem is extremely complicated

**Comment by akilgb** [comment]
usuario@localhost:~$ sudo apt-get update
Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done    
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
usuario@localhost:

**Comment by akilgb** [comment]
usuario@localhost:~$ sudo apt update
Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done    
Building dependency tree... Done
All packages are up to date.
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
usuario@localhost:~$

**Comment by corbinlc** [comment]
That looks like a DNS issue.  I will get back with some suggestions later.

**Comment by corbinlc** [comment]
That is not GPG error @akilgb

**Comment by nidusin** [comment]
My issue is resolved after removing and reinstalling userland entirely. Ubuntu is now updating normally

**Comment by akilgb** [comment]
What else can it be? It happens all the time I've reinstaled many times. I tried using Ubuntu and Debian
