### ISSUE TITLE
With the official release of Userland, I think its appropriate to ask this question!

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#350]
Not really an issue but a general question. For those of us who started with the first beta release until now, most of your systems was created the "manual" way of choosing a file system and then creating a custom session using default information. So with the new app section, there is an option to choose a distribution from there as well. So are there any differences in choosing and launching a custom file system versus using the app page to create it? i.e. does the automated method install anything differently?

**Comment by corbinlc** [comment]
No differences in how they are installed.  The only difference is how they are presented to users and the sessions and the filesystems will be named in a specific way when launched from the app page.  So, if just using the apps page, you cannot have two Debian filesystems, but when creating them in the more manual fashion, you can have as many as you want.
