### ISSUE TITLE
Setting screen resolution for linux running under UserLAnd

### ISSUE THREAD

**Issue by nele2** [CypherpunkArmory/UserLAnd#353]
In Samsung Dex (samsung galaxy S8) running ubuntu with xfce4 I could not find a way to change screen resolution (would love to have 1920x1080):

xdpyinfo | grep dimensions returns current resolution of 1024x768 pixels (347x260 milimeters)
xrandr throws a permission error
bVNC viewer costume settings did not change resolution

Please help if there is a way to change resolution.

![screenshot_20181020-185159_bvnc free](https://user-images.githubusercontent.com/42851682/47309587-19d80b80-d635-11e8-845f-3bcee9d7fdb1.jpg)

**Comment by stackerlon** [comment]
Use xserver xsdl app, you can easily change resolution. I can run 2220×1080 resolution with the app.

I had this problem to when I used bvnc app, then switched to xsdl.

**Comment by corbinlc** [comment]
See #215 
You should created a /home/user/.vncrc file as suggested.  We should make this default to something good though.

**Comment by nele2** [comment]
Thank you for support. I have not tried xsdl app, but I did use the -geometry to change resolution. First I tried creating the .vncrc file but resolution did not change and then in the /home/user/.vnc folder I have added to xstartup file -geometry 1920x1080 on the line x-window-manager (viz. screenshot). It woked and I am very happy now :)
Thank you!
![screenshot_20181024-183035_bvnc free](https://user-images.githubusercontent.com/42851682/47446606-df4cab00-d7bb-11e8-90a8-8bb2f2ebfa73.jpg)

**Comment by Silithas** [comment]
> Thank you for support. I have not tried xsdl app, but I did use the -geometry to change resolution. First I tried creating the .vncrc file but resolution did not change and then in the /home/user/.vnc folder I have added to xstartup file -geometry 1920x1080 on the line x-window-manager (viz. screenshot). It woked and I am very happy now :)
> Thank you!
> ![screenshot_20181024-183035_bvnc free](https://user-images.githubusercontent.com/42851682/47446606-df4cab00-d7bb-11e8-90a8-8bb2f2ebfa73.jpg)

How did you get display? tis is what i get https://media.discordapp.net/attachments/403741067335434240/560627808511197205/Screenshot_20190328-015524_UserLAnd.jpg?width=443&height=910

**Comment by nele2** [comment]
You should:
1. edit/create /home/user/.vncrc with $geometry = "1280x1024";
2. find and edit xstartup file (under your home folder and user /home/user/.vnc/) add line #x-window-manager -geometry 1280x1024 &
I am running xfce4 and the screenshot was taken on samsung s8 under dex with resolution of 1920x1080 which was the native resolution of the monitor.
I hope that helps

**Comment by Silithas** [comment]
How do i do 1 and 2? Brand new to linux, so don't know my way around yet :P

Also, i get the "GKT warning, cannot find display" Which is why my desktop is black with a black firefox. Do you know the answer there? and which vnc do you use? I followed the tutorial here, but that display part wouldn't apply for me.

**Comment by nele2** [comment]
I use bVNCFree and ConnectBot with UserLAnd. After installing these apps I have installed Ubuntu. After installing Ubuntu or Debian and running it from the session manager your distribution should start with bVNC and you will see command prompt in xwindows (don't know what lihgtweight window manager they are using as default is called). Then you run sudo install xfce4. After that you get a windows enviroment you are use to form linux. There you find the folders, create/edit folders and file configurations and vola!

**Comment by Silithas** [comment]
There's no .vnc folder or file in my home/user directory though.

**Comment by nele2** [comment]
It should be there .vnc folder is a hidden folder. In file explorer under View menu check show hidden folders.

**Comment by twaik** [comment]
@corbinlc 
I think better solution will be creating an app implementing XServer in android userspace, but not using any compressing. I implemented something like that in Lorie (Termux::X11), but I need to implement some things like touchpad event parser (I think it will be based on libinput's code). We can try to make it together. I have a few ideas to improve an app but have no time. Contact me in Telegram (@twaik) if you want to discuss it.

**Comment by hwassermann** [comment]
I had a problem with having my geometry reset on every restart of the session.  The value I specified kept getting overwritten.  As a workaround, I ended up making the ~/.vimrc file read-only by running chmod -w .vimrc
