### ISSUE TITLE
Extraction error

### ISSUE THREAD

**Issue by Remonter76** [CypherpunkArmory/UserLAnd#354]
Hi, in general today I stumbled upon this error when unpacking files:
 Extracting: Exec: java.lang.RuntimeException: Error while executing ExecLocal: java.io.IOException: ... 

Write someone how to solve this problem. My device: Meizu M5 Note

**Comment by AdamMatthewLTM** [comment]
@Remonter76 , can you please provide us with more detail (including if you are still running into this error with the latest UserLAnd app version downloaded)? I'd like to know how to reproduce this issue you are having on my device.

Thanks,
-Adam
