### ISSUE TITLE
OG pixel XL, hung on downloading required assets 0/0

### ISSUE THREAD

**Issue by PatrickRJadwin** [CypherpunkArmory/UserLAnd#355]
Per request of the developer on Google play, I tried resetting my internet connection and checking GitHub permissions. Neither seemed to solve this issue, so I was told to post about the issue here

When I try to create a VNC or SSH session on any of the available apps, I get hung on downloading required assets, 0 of 23

Thanks

**Comment by corbinlc** [comment]
@MatthewTighe  you might be the best one to look into this.  Can you provide some suggestions for debugging this?

**Comment by corbinlc** [comment]
![image](https://user-images.githubusercontent.com/1421245/47375996-6d367200-d6a6-11e8-85c0-16069faa0bfc.png)

**Comment by corbinlc** [comment]
![image](https://user-images.githubusercontent.com/1421245/47376042-84755f80-d6a6-11e8-9621-bb7aafbd1dce.png)

**Comment by MatthewTighe** [comment]
@PatrickRJadwin When you start the downloads, quickly swipe down your notification bar and check if the system-wide download manager reports downloading anything. Additionally, check your download directory through the files app or similar file browser and check if files labeled `UserLAnd-<distribution_you_are_downloading-for>-<asset_name>` exist.

**Comment by PatrickRJadwin** [comment]
@MatthewTighe Sorry for the late reply, I just checked and this is not happening, I'm assuming this might be the permissions for reaching github then?

**Comment by AdamMatthewLTM** [comment]
@PatrickRJadwin ,

This issue should have been solved. Can you please confirm you are still not running into the extraction issue on your device?

**Comment by PatrickRJadwin** [comment]
@AdamMatthewLTM fixed!! :+1:
