### ISSUE TITLE
Can't mount fuse filesystems

### ISSUE THREAD

**Issue by donomii** [CypherpunkArmory/UserLAnd#356]
**Is your feature request related to a problem? Please describe.**

I can't mount fuse filesystems because I don't have permissions to access /dev/fuse. 

**Describe the solution you'd like**

To be able to mount fuse filesystems

**Describe alternatives you've considered**

rewrite fuse so I can use LD_PRELOAD to intercept filesystem calls and send them to fuse.  This is probably not going to work well with some programs that  e.g. make mmap calls

**Additional context**

This would add a lot of functionality to userLAnd, since it is much easier to just mount a filesystem with software and personal data than to install the programs locally all and keep the data in sync.

**Comment by AdamMatthewLTM** [comment]
@donomii ,

Thanks for your post. I'll look into the feasibility of messing around with the fuse FS to get it to work in UserLAnd, but it'll be a little bit of a low priority for the time being. For now, please keep this post open in case anyone else expresses interest here, and i'll update it when progress is made or if there's any new information.

To eliminate problems with unknown variables in the future, can you please tell me what your phone model and Android OS version is?

Thanks for your time and patience in these matters,
-Adam

**Comment by donomii** [comment]
Phone model: Mi MAX 2 (MDE40)
android: 7.1.1 NMF26F (MIUI Global 9.6 | Stable 9.6.3.0(NDDMIFD)

**Comment by monkeyfork** [comment]
please up priority for getting SSHFS to work (i take it that means getting fuse to work).  Being able to able to mount remote file system via SSHFS would greatly ease my particular method of work-flow.  UserLAnd is extremely useful to me right now, very much appreciated.

**Comment by corbinlc** [comment]
I have created a new issue #910 that is meant to cover all the issues related to running as an emulated root user instead of a real root users.  Two parts of that are blocking using fuse 1) cannot access some directories or files owned by real root, like `/dev` and 2) cannot use `mount` for much of anything.  Please follow #910, as that is where we are going to talk about running a real root.
