### ISSUE TITLE
How to get sounds working on userland?

### ISSUE THREAD

**Issue by stackerlon** [CypherpunkArmory/UserLAnd#357]
I know it is small issue, but without sound it does not feel like a Linux machine. So, how can I get sounds working on userland or it is not supported right now?

**Comment by AdamMatthewLTM** [comment]
@stackerlon ,

Sorry for the delay, I'm redirecting all sound setup inquiries to this thread here:

issue #252 

and I'll mark this thread as a duplicate and close it, with all updates being posted there. In short, sound is still something that's being worked on at the moment but it will be supported soon. I apologize for the inconvenience, but I can't provide an ETA just yet on sound setup.

Thank you for your time and patience in these matters,
-Adam
