### ISSUE TITLE
make it possible to resize the vnc screen resolution

### ISSUE THREAD

**Issue by kimusan** [CypherpunkArmory/UserLAnd#362]
**Is your feature request related to a problem? Please describe.**
The vnc server runs in only 1024x768 resolution with is really useless on a high-res mobile phone screen
**Describe the solution you'd like**
It would be nice if the vnc server resolution could be set to match the actual screen resolution or configured by the user in the settings. 

**Describe alternatives you've considered**
I have currently fixed this locally by adding my own tightvncserver.conf in ~/.vnc/ and have the $geometry = "XxY"; in the file

**Comment by AdamMatthewLTM** [comment]
@kimusan ,

Just out of curiosity, have you tried the 'force resize' option in the upper right hand corner for the SSH option, and is something like that equivalent to what you're looking for?

**Comment by kimusan** [comment]
Not sure which functionality you are referring to? Do you mean in juicessh when you refer to the ssh app? I have not found a function that gives me full resolution for the vnc desktop - not in bvnc nor real vnc viewer. Best it can do is fill the screen but res is still low.

**Comment by albcal** [comment]
Hi! I cant change screen resolution, i made the file tightvncserver.conf in .vnc with $geometry = "1920x1080";  and it does not work.

**Comment by corbinlc** [comment]
From now on, new filesystems will have dimensions that match your device screen.  If you want to modify that, please change the `~/.vncrc` file.
