### ISSUE TITLE
Install kali linux

### ISSUE THREAD

**Issue by RuiRibeiro001** [CypherpunkArmory/UserLAnd#365]
How to install kali linux ??It always gives me error when trying to install

**Comment by AdamMatthewLTM** [comment]
@RuiRibeiro001 , I am in the process of working on a kali install script at the moment, but I am going to close this thread for now. When the script is released and you are still experiencing issues, please file a bug report according to the template so I can diagnose the problem if there is one.

Thank you,
-Adam
