### ISSUE TITLE
Could not extract filesystem

### ISSUE THREAD

**Issue by dln949** [CypherpunkArmory/UserLAnd#369]
Installed Userland 1.0 on a Samsung Galaxy Tab S2 model SM-T813 tablet running Andriod 8.1.0/LineageOS 15.1-20181029-NIGHTLY-gts210vewifi.  

After giving Userland storage permissions and then creating an Ubuntu filesystem and then a related Ubuntu session, I started the session/filesystem combination in Userland.  

Userland then attempted to download the 23 files for about 10 - 15 minutes (always showing that 0 of 23 files were downloaded).  After that period of time, Userland presented this message to me:  "Could not extract filesystem.  Something went wrong.  Try deleting the filesystem and trying again."  

My tablet's internet connection worked great for all other apps.  

What is wrong?  How do I fix this to make Userland work on this device?  

I have attached the PRoot_Debug_Log to this posting.  (In order to attach the file, I had to add a .txt extension to the filename.)  

Thanks for any help with this.  

[PRoot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2528131/PRoot_Debug_Log.txt)

**Comment by corbinlc** [comment]
I am curious if one of the assets was corrupted or not fully downloaded, does this repeat if you uninstall the app and then try it again?

**Comment by dln949** [comment]
uninstalling and reinstalling solved the problem, thanks.
