### ISSUE TITLE
Can't use other VNC and ssh apps.

### ISSUE THREAD

**Issue by sr13579** [CypherpunkArmory/UserLAnd#374]
While starting a new session the app only opens the pre-defuned app by default. I want to use other ssh and VNC app  How to fix this problem? I couldn't find an option for changing the default app.

**Comment by WisdomWolf** [comment]
I haven't done anything with VNC yet, but for SSH it opens JuiceSSH for me.  That allowed me to see that the destination for the SSH command is localhost:2022.  I used that to make a new saved connection in JuiceSSH.  I was also able to SSH in from another device on my network using <device IP address>:2022.

**Comment by AdamMatthewLTM** [comment]
@sr13579 ,

I am unsure about what issue you are having specifically. Do you mean to say you wish to switch between SSH and VNC sessions in the same filesystem? To do so please kill the session in the 'sessions' button by holding down the active session and pressing kill. Then switch over to the 'apps' button, and hold down which filesystem or app you wish to launch, and select either VNC or SSH.

Please tell me if this solves your issue or if I have misunderstood it, and thank you.
-Adam

**Comment by sr13579** [comment]
I would like to use another app for VNC and SSH. But UserLand is always
redirecting me to a specific app. Please fix this issue.

**Comment by MarkoM2** [comment]
I use another VNC Client as follows:

- I start the session in Userland
- it asks to install the default VNC Client App, I hit the back button to refuse
- I open another VNC Client App and connect to the still running VNC server (address is weird, I checked it once from the default VNC Client App --> ```localhost:51```)

I guess this could also work with other SSH Client Apps and ```localhost:2022```, though I haven't tried.

**Comment by AdamMatthewLTM** [comment]
We are currently working to implement alternate VNC and SSH clients, and since this is a request multiple people have had I am going to close this thread. If you experience issues with the new clients, please create a brand new thread so that we can debug it there. Thank you.
