### ISSUE TITLE
Multi-arch or Qemu Support?

### ISSUE THREAD

**Issue by mirzaatifbaig** [CypherpunkArmory/UserLAnd#376]
So,any of you are able to successfully run qemu or other emulators on this.I know qemu but it is in gui as an app in playstore.Maybe you should give it a look and find out if we could run other than lousy arm code.

**Comment by AdamMatthewLTM** [comment]
@mirzaatifbaig ,

I am able to successfully install and run qemu via the commandline on my device. I am using an Android Samsung Galaxy J3 running 7.0. Please use the issue filing template so that I can better assist you with your problem.

**Comment by mirzaatifbaig** [comment]
Nevermind I am closing this as I was able to use it.Speed ain't great tho.
