### ISSUE TITLE
Cannot run Octave or R without sudo

### ISSUE THREAD

**Issue by mats1729** [CypherpunkArmory/UserLAnd#378]
After starting Octave or  R, the connection to the server is closed and any further attempts to attach to the server are refused.

If  Debian is installed first and Octave is installed  manually using apt, it isn't even possible to start Debian again, once an attempt at starting Octave has been made. That is, it is possible to log in, but then the connection is closed immediately afterwards. I find this rather strange. It is also very inconvenient, as the only way to proceed appears to be to delete the filesystem and install everything again. The same goes for R.

However, if Octave or R is started using sudo, it seems that they will behave normally, except that "octave --no-gui" will not work. Octave always tries to start the GUI. Using graphics requires an Xserver, though, and I haven't got that to work yet.

I have used both ConnectionBot and Termux as remote terminals, as well as bVNC. Using bVNC the initial Octave windows do appear, but the connection is closed before the main Octave window is visible.

I include some error messages and warnings, although the problem seems to be related to permissions rather than other bugs.

Looking into PRoot:Debug_Log, I found a few error messages.
Early in the log
  proot info: loader: /data/data/tech.ula/files/1/support/prooted-8450-2kRVf5
  proot info: Detected broken PTRACE_POKEDATA - enabling workaround
At the very end of the log
  handle_tracee_event(Tracee *, int):
  ./tracee/event.c:517: int handle_tracee_event(Tracee *, int): assertion "!IS_IN_SYSENTER(tracee)" failed
  proot warning: signal 6 received from process 8450

Trying to connect to the server from a Termux terminal, after Octave failure
(the UserLAnd session service is still running) 
  $ ssh -p 2022 user@localhost
  user@localhost's password:
  ....
  Welcome to Debian in UserLAnd!
  Connection to localhost closed by remote host.
  Connection to localhost closed,

Trying to reconnect to the server using ConnectBot, after Octave failure
(the UserLAnd session service is still running) 
  Connecting to localhost:2022 using ssh
  Connection lost
  failed to connect to localhost/127.0.0.1 (port 2022) from /:
  :(port 49870): connect failed: ECONNREFUSED (Connection refused)
The last port number varies from session to session.
If the UserLAnd service is killed and ConnectBot closed, it is possible to log in, but then the connection is immediately closed.

During installations using apt, the following error is displayed at some stage.
E: Setting in Start via TCSAFLUSH for stdin failed! -tcsetattr (13: permission denied) 

Device: Huawei VTR-L29
Android Version: 8.0.0
UserLAnd Version 1.0.0
Additional context

**Comment by corbinlc** [comment]
There is a lot of weird behavior and reduced performance on newer Huawei devices because the kernel has a broken POKEDATA and the workaround is expensive and not fully robust.  It might take a while to sort this out.

**Comment by EnderNightLord-ChromeBook** [comment]
We may be able to work around this...

**Comment by corbinlc** [comment]
Closing this, because I am trying to group all the Huawei device problems together.

**Comment by corbinlc** [comment]
See #398.
