### ISSUE TITLE
Are mozc packages gone?

### ISSUE THREAD

**Issue by Mitsuruhamamoto** [CypherpunkArmory/UserLAnd#379]
I usually install a mozc package as a Japanese input method, and after installing UserLAnd I try to get it by apt-get, but received an error of packages being not found.
Are they gone, or did I do something wrong?

**Comment by AdamMatthewLTM** [comment]
@Mitsuruhamamoto ,

It doesn't look like the mozc package is available through the repos right now. I don't know if they'll include support for them later or not, but if you'd want to put in a request for different language characters in this thread I'll leave this open as an enhancement and see if future support for that won't be implemented.

To be clear, mozc just creates japanese characters over the keyboard right, and displays the characters on screen? It doesn't do actual translational work?

**Comment by Mitsuruhamamoto** [comment]
Thank you for your suggestion. Yes, mozc is just like a typing tool of Japanese characters. It doesn't do any translational work, but it converts one Japanese character set to another( conversion of Kana into Kanji).
Emacs has its own Japanese input method, but it is rather primitive and not very efficient, so we need a more　sophisticated input method like mozc. I wish they will include support for them.

**Comment by corbinlc** [comment]
What is the specific package name?  Also, is this under Debian, Ubuntu or Kali?  

For Debian, there appear to be various packages with `mozc` in the name.  There is one exactly called `mozc` in debian, but it is only a source package that can build one of many things.  So, we need the specific package name.  

In general though, what packages you can get is controlled simply by /etc/apt/sources.list and what packages are available at the described repo.  One possibility is that the the package you want is not available for your phones architecture (just a random thought).  

Please provide a little more info and I will look into it.

**Comment by corbinlc** [comment]
No additional information was ever provided.  As such, I am closing this issue.
