### ISSUE TITLE
Bluetooth mouse and keyboard response are slow on Samsung DeX

### ISSUE THREAD

**Issue by jdrch** [CypherpunkArmory/UserLAnd#384]
When using UserLAnd via bVNC in Samsung DeX, Bluetooth mouse and keyboard responsiveness _within the bVNC window_ are slow.

**Steps to reproduce the behavior:**

- Start DeX by connecting Note9 to HDMI adapter with Bluetooth mouse and keyboard connected
- Start UserLAnd in DeX
- Start Ubuntu instance in DeX
- Move Bluetooth mouse and keyboard within bVNC window.

**A clear and concise description of what you expected to happen.**

I expected mouse and keyboard performance to be smooth.

**Device Information**

Device: Verizon Samsung Galaxy Note9 512 GB
Android Version: Oreo 8.1
UserLAnd Version: Latest as of 2018-11-04

**Other information**

Unfortunately I've already uninstalled UserLAnd and do not have the time to reinstall purely for troubleshooting purposes at this time.

**Comment by corbinlc** [comment]
Any issue related to bVNC will have to be filed against it.  It has its own github page.
