### ISSUE TITLE
Nmap error: nmap: netutil.cc:3285: int route_dst_netlink(const sockaddr_storage*...

### ISSUE THREAD

**Issue by tokyoneon** [CypherpunkArmory/UserLAnd#385]
#### Describe the bug:

Using privileged scan types (-sU) with Nmap returns the following error:

	nmap: netutil.cc:3285: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL` failed.

#### To Reproduce:

1. Create a Debian App.
2. Add Kali repos:

		echo 'deb https://http.kali.org/kali kali-rolling main contrib non-free' >> /etc/apt/sources.list

3. Add Kali signing key:

		wget -q -O - https://www.kali.org/archive-key.asc | apt-key add -

4. Update and install Nmap:

		apt-get update && apt-get install nmap -y

5. Perform Nmap scan as root:

		nmap -Pn -n -sU -A --top-ports 10 <target ip address>

#### Screenshot:

![nmap_error](https://user-images.githubusercontent.com/33106572/48093117-5ffba600-e1c3-11e8-8196-c3d101878c70.png)

#### Device Information:

Device: Nexus 6P
Android Version: 8.1.0
UserLAnd Version 1.0.0

#### Some network/routing info:

	# android/userland can see the router
	$ ping 10.42.0.1

	PING 10.42.0.1 (10.42.0.1) 56(84) bytes of data.
	64 bytes from 10.42.0.1: icmp_seq=1 ttl=64 time=12.3 ms
	64 bytes from 10.42.0.1: icmp_seq=2 ttl=64 time=14.0 ms
	64 bytes from 10.42.0.1: icmp_seq=3 ttl=64 time=13.3 ms
	64 bytes from 10.42.0.1: icmp_seq=4 ttl=64 time=3.62 ms
	64 bytes from 10.42.0.1: icmp_seq=5 ttl=64 time=106 ms
	64 bytes from 10.42.0.1: icmp_seq=6 ttl=64 time=67.10 ms
	64 bytes from 10.42.0.1: icmp_seq=7 ttl=64 time=3.54 ms
	64 bytes from 10.42.0.1: icmp_seq=8 ttl=64 time=8.27 ms

	# normal routing table; only one gateway
	$ route -n 

	Kernel IP routing table
	Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
	10.42.0.0       0.0.0.0         255.255.255.0   U     0      0        0 wlan0

	# dns requests go over 10.42.0.1
	$ cat /etc/resolv.conf 
	nameserver 10.42.0.1

	# access to internet without errors
	$ curl 'https://wtfismyip.com/json'

	 {
	   "YourFuckingIPAddress": "185.220.100.252",
	   "YourFuckingLocation": "Germany",
	   "YourFuckingISP": "F3 Netze e.V.",
	   "YourFuckingCountryCode": "DE"
	}

**Comment by corbinlc** [comment]
Hmm... looks like it had trouble getting the name associated with the network interface.  Can you enable proot logging (from settings enable it and turn the verbosity level to 9), then rerun the failing commands and then grab the PRoot_Debug_Log file from your (real or emulated) sdcard and send it to us one way or the other?

**Comment by tokyoneon** [comment]
Thanks! Here you go:
[PRoot_Debug_Log.txt.zip](https://github.com/CypherpunkArmory/UserLAnd/files/2577700/PRoot_Debug_Log.txt.zip)

**Comment by corbinlc** [comment]
Sorry, can you provide the list of commands you ran when you were creating that debug log file.  I am seeing a bit more than just the `nmap` call.  If you don't remember exactly, can you delete the old debug log (from the settings) and repeat what you did and provide both the PRoot_Debug_Log and the copy and paste of what you ran in the term and what responses you got.

**Comment by corbinlc** [comment]
PRoot logs are very low level so I need to understand what is going on at a higher level to unravel it.  If will probably ultimately be trying flow out myself, but if you could provide this one more piece of data for now, that would help.

**Comment by tokyoneon** [comment]
Sorry about that,  I wasn't sure if the 50M came from older logs or generated after increasing verbosity. Attached is an updated log. Here's every command I ran:

1. entered ssh password via ConnectBot
2. `$ su` need root for nmap
3. `$ nmap -Pn -n -sTUV --reason -T4 -A --top-ports 15 -vv 10.42.0.1`
4. `$ cd /sdcard`
5. `$ python3 -m http.server 9999` created an http server to access the debug log from another device on the network

**Comment by tokyoneon** [comment]
@corbinlc is there anything I can do to help with this?

**Comment by corbinlc** [comment]
Not now.  I am sorry.  This specific issue is a little lower down in the priority list right now.  That being said, I will update you as soon as I am looking at it and as soon as I need anything.  Thanks!

**Comment by corbinlc** [comment]
@tokyoneon we still don't have a solution for this, but we saw your article.  It is well written.  Can we get your permission to use part of the step by step instructions in our README?

**Comment by BestPinguin** [comment]
So how did you fix this issue? I have the same problem with UserLand on Debian and Kali. I didn't find any answer about it, help me please 😅

**Comment by tokyoneon** [comment]
@BestPinguin from what I understand, while it's possible to open a "root" terminal within the UserLAnd OS, you're not actually root in the Android OS. To run privileged Nmap scans (e.g., `-sS` and `-sU`) or switch the Wi-Fi interface to monitor mode for Wi-Fi hacking, actual root is required. You may want to have a look at [this](https://secwiki.org/w/Running_nmap_as_an_unprivileged_user) and [this](https://linux.die.net/man/7/capabilities) which came up in a quick Google search, but I haven't tried finding a workaround since opening this issue last year. Sorry!

**Comment by reksores** [comment]
@tokyoneon same problem here...so i need root my telephone to solve this issue ... ooofffff :(

**Comment by rawnnja** [comment]
Hi, i have the same problem and im root ( root checker basic say so). In termux nmap run without a problem

**Comment by kianoosh21** [comment]
I'm having this issue and I've been searching for this for a while but there were no useful instructions I'm running kali linux nethunter on my phone and every time I try to use nmap I come across this error: 

nmap: netutil.cc:3285: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL` failed.

**Comment by captago** [comment]
![IMG_20200728_232012](https://user-images.githubusercontent.com/64353864/88723509-4cc40300-d129-11ea-9888-275c5506d4ad.jpg)

**Comment by TheTangledMind** [comment]
> 
> #### Screenshot:
> 
> ![nmap_error](https://user-images.githubusercontent.com/33106572/48093117-5ffba600-e1c3-11e8-8196-c3d101878c70.png)
> 

I am having the same issue using Kali-nethunter. My device is rooted.

**Comment by TheTangledMind** [comment]
![Screenshot_20210319-091454_NetHunter Terminal.jpg](https://user-images.githubusercontent.com/68653547/111704652-9c5f6680-8893-11eb-914f-96026d6553ea.jpg)

incase my screenshot provides any more info

**Comment by chouaibai** [comment]
oooooooh, there is any solution?????

**Comment by sinagolmoradi** [comment]
Hello 👋

I have this error when running nmap on termux with root mode, please help.


nmap: netutil.cc:3197: int route_dst_netlink(const sockaddr_storage*, route_nfo*, const char*, const sockaddr_storage*): Assertion `p != NULL' failed.

**Comment by sinagolmoradi** [comment]
nmap: netutil.cc:3197: int route_dst_netlink(const sockaddr_storage*
Please 🙏 help me

**Comment by R0x7e** [comment]
'--unprivileged' adds this parameter to solve the problem

**Comment by yerkodigo** [comment]
> '--unprivileged' agrega este parámetro para resolver el problema

This worked for me! Thanks!
