### ISSUE TITLE
important VNC question

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#386]
Dear specialists,
If I will install VNC is it possible to press keys on external keyboard when I will run some X related apps such as Firefox? Is it possible to type normally startx to run some desktop environment? Keyboard is very important for Me.

**Comment by null1024** [comment]
I'm currently using a bluetooth keyboard with UserLAnd on my S9. If your keyboard works normally in other applications on your phone, it should work in your VNC client (I'm using bVNC, the one UserLAnd tries to open by default as of this post).

same thing with a mouse, but I haven't had great mouse-click response with a real mouse in bVNC

**Comment by lewisdonofrio** [comment]
why use vnc just use XDSL and use real X11 forwarding.....just wonderin

**Comment by corbinlc** [comment]
External keyboards work for many users in XSDL and VNC.  As such, I am closing this issue.  If you still have an issue, please open a new issue with more details so we can look into it.
