### ISSUE TITLE
direct touch display support on X graphical session

### ISSUE THREAD

**Issue by JanuszChmiel** [CypherpunkArmory/UserLAnd#387]
Dear specialists,
Could somebody of us try to analyse, if The following .so library and approach, which is being discussed on SDA developers forum is secure? Does their .so library support all GPU chips or only MTK? Does their approach requires rooted devices? I Am dreaming about direct screen usability, because VNC and Xserver XSDL is based on network communication on TCP/IP.
Here is thread link.

https://forum.xda-developers.com/showpost.php?p=35205246
If this approach also requires rooting devices, is it possible to use VNC in combination with Bluetooth keyboard or USB keyboard connected to The device?

**Comment by corbinlc** [comment]
We are not going to look into this in the foreseeable future.  As such, I am closing this issue.  If anyone else wants to pick it up and research it, please do so.
