### ISSUE TITLE
Assigned ressources to session

### ISSUE THREAD

**Issue by schniewmatz** [CypherpunkArmory/UserLAnd#388]
How are ressources assigned when a session is started and can I set them?  
It's related to #314 as this is also crucial for heavy desktop environments:  
So far I have not found a way to get information about or even set the resources that are available to the session running e.g. for Ubuntu. I do not know how UserLAnd manages ressourcs or if it in some way can assign ressource dynamically. If not, I would find it usefull if ressources could be assigned, at least the RAM. On newer phones often 4GB or more are available and using 2.5-3 of them would be very benficial to make a full Desktop experience on mid to high-end phones e.g. with Gnome possible.  

I'd like to be able to assign available ressource when starting a session, maybe with a first suggestion and a display how much RAM is currently available.

If UserLAnd already manages ressources in a very intelligent way, I'd be happy if you use this Issue to provide some details ;-)

And by the way: Where is the button for coffee donations?

**Comment by schniewmatz** [comment]
Ah I finally managed to install Debian with lxde and to connect via the Xserver XSDL App and it seems that the full RAM is available to Debian, in this case it show 2077 MB of 3604 MB used while running apt. I guess that the 2077 MB used RAM incllude the RAM that is used by Android, right?
So basically this is solved, nevertheless I'm still interested to understand how you actually run Debian in Android without using a VM with fixed ressources.

**Comment by stephenprater** [comment]
@schniewmatz We run on top of a project called [PRoot.](https://github.com/proot-me/PRoot) - It's basically a chroot-like based on the `ptrace()` function call.
