### ISSUE TITLE
Extracting Error

### ISSUE THREAD

**Issue by albcal** [CypherpunkArmory/UserLAnd#389]
Hi! I have a problem, during the extracting process this error appears.

ERROR: Id.so: object 'libTcpOptimizer.so' from...

I'm using a galaxy s9+, any clue? thankyou

**Comment by MatthewTighe** [comment]
A PRoot debug log would be helpful. You can turn debug logging on in the settings menu and then retrieve the log from /sdcard/PRoot_Debug_Log.txt or /mnt/sdcard/PRoot_Debug_Log.txt of your Android filesystem and not the filesystem you're installing through UserLAnd. Note that this will pretty severely worsen performance.

**Comment by albcal** [comment]
Hi! sorry for the late i lost my phone, this is the log regarding libtcpoptimizer.so, i'am running in a g9650 s9+ with snapdragon cpu and android 8.

:[H[JERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0002:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0003:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0004:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0005:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0006:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0007:spawn /usr/bin/vncpasswd
0008:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0009:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0010:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0011:Using password file /root/.vnc/passwd
0012:VNC directory /root/.vnc does not exist, creating.
0013:Password: 
0014:Verify:   
0015:Would you like to enter a view-only password (y/n)? n
0016:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0017:rm: cannot remove '/tmp/.X51-lock': No such file or directory
0018:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0019:rm: cannot remove '/tmp/.X11-unix/X51': No such file or directory
0020:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0021:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0022:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0023:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0024:
0025:Can't find file /root/.vnc/localhost:51.pid
0026:You'll have to kill the Xtightvnc process manually
0027:
0028:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0029:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0030:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0031:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0032:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0033:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0034:xauth:  file /root/.Xauthority does not exist
0035:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0036:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0037:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0038:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0039:
0040:New 'X' desktop is localhost:51
0041:
0042:Creating default startup script /root/.vnc/xstartup
0043:Starting applications specified in /root/.vnc/xstartup
0044:Log file is /root/.vnc/localhost:51.log
0045:
0046:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
0047:ERROR: ld.so: object 'libTcpOptimizer.so' from LD_PRE



any clue ? i want to run this thanks

**Comment by corbinlc** [comment]
I know what causes that.  But, the log shows you are passed the extraction point and have even launched a vnc server.  Does that error block you?  If so, does SSH work?

**Comment by albcal** [comment]
Hi! the first times it stayed in error, but days later, after this error the vnc started and i was able to run the gui but many times that error appears on terminal.

**Comment by corbinlc** [comment]
Ok, so it is not blocking anymore, but nuisance.  I know what causes this issue and can solve it.  I am getting my samsung s9  back tomorrow so I can try this out.

**Comment by albcal** [comment]
As i can see this error dont interfy with the operation of the distro.

**Comment by corbinlc** [comment]
I use an s9 every day now.  This appears to have been solved.

**Comment by GMANNMODS** [comment]
![Screenshot_20240108-135139](https://github.com/CypherpunkArmory/UserLAnd/assets/50033246/30867f81-022b-4ff9-8bfd-a0904120a0fc)
 
I did this as a temp solution in the new terminal you have the option to run a prescript when the terminal opens... this works for me as long as the shit still works this takes the annoying error away and can be removed easily.

**Comment by GMANNMODS** [comment]
![Screenshot_20240108-135222](https://github.com/CypherpunkArmory/UserLAnd/assets/50033246/36dcfd8c-a33a-4189-9381-3ed8001f4f2d)


It's runs this everytime it opens initially stopping preload then starting it again...
