### ISSUE TITLE
Installation notes (and a question)

### ISSUE THREAD

**Issue by whiffee** [CypherpunkArmory/UserLAnd#395]
I tried to read about UserLAnd installation, but everything I could find was a little too general for someone with no VNC experience. So after some frustrating blind alleys, here are the basics:

1.Download the UserLAnd app and open, grant two screens of permissions.
2.Choose Ubuntu app.
3.Wait for file system and 23 assets to download.
4.Installation is then transferred to bVNC installation screen.
5.At bVNC screen, install and open, allow permissions.
6.At the bVNC New Connection screen, bVNC server is set at 5900, VNC password is set at Keep, which is okay.
7.Press connect, but get "VNC server or port empty. Cannot connect".

This was a puzzler. Turns out that the terminal has to be connected from the server side.  So

8. Go into ULA, tap Session, then tap the Ubuntu line. The terminal is activated. Notice that although only 1024x768, the terminal responds to pinch zoom.

When bVNC and ULA are stopped and restarted, is the setup still alive? Yes, just start ULA, select sessions, and the Ubuntu line.

Note: When the Octave application button is pressed, all the above apply, even the number of assets. However, in this case the version of Octave which you get is 4.0.3, whereas if you download Ubuntu and then install Octave through apt-get, you get version 4.2.2. BUT: There appears to be a serious bug in bVNC (or armhf version of Octave 4.2.2) which makes the keyboard unusable with gui on my setup, though if launched with --no-gui Octave works okay.

Question: Is it possible to install an alternative VNC client?

Comments from people who actually know something are definitely welcome.

Android device is Galaxy TabS 10.1 SM-T800, Android is 6.0.1, UserLAnd is 1.0.0, bVNC is 4.0.1.

**Comment by corbinlc** [comment]
We haven't tested with many VNC clients, but we really should.  

Maybe you could contribute something to our wiki or readme?
