### ISSUE TITLE
Please Add Distribution

### ISSUE THREAD

**Issue by mkevinam** [CypherpunkArmory/UserLAnd#400]
Please Add Distribution. Distribution Name Is Kali Linux

**Comment by projectextremum** [comment]
`Will never be added`.

Kali Linux is not a distribution for general usage. Clickbait blogposts promote themselves with that name. For actual penetration testing, you need to know programming & system internals. If you know them, I am pretty sure you can do it all without Kali Linux, and if you know how it works, you can install it yourself for limited functionality in `proot`. [Which is the maximum capability of it without root].

I am suggesting to close this issue with a flag `unfortunate` or in reddit style `another script kiddie found`.

**Comment by projectextremum** [comment]
I don't think it will be of any usefulness. Perhaps Kali repository can be enabled in debian. Leave that to users. other things are low level stuff that wont work with fake root hacks. Adding a rootfs and maintaining that will result in some extra burden. And I am sure these kids won't turn into authentic issue tracker entries or loyal customers either.

**Comment by corbinlc** [comment]
Added Kali yesterday.  It is VNC only until we solve or workaround an issue with connect bot.
