### ISSUE TITLE
Ubuntu 18.10

### ISSUE THREAD

**Issue by whiffee** [CypherpunkArmory/UserLAnd#404]
hi All,

Ubuntu 18.10 is out. ports.ubuntu.com/ubuntu-ports/dists/cosmic/ shows that there is a armhf.
Will this be coming to UserLAnd soon? (hope-hope).

thanks,
GB

edit 181120: I got what I needed by a different route (sources.list).

**Comment by whiffee** [comment]
See previous edit.

**Comment by EnderNightLord-ChromeBook** [comment]
What are you trying to say?
