### ISSUE TITLE
Cannot get UserLAnd R session up

### ISSUE THREAD

**Issue by Hiwasgehtab** [CypherpunkArmory/UserLAnd#405]
Hi, I'm new to this world and would love to get R running on my smartphone. I am running android 8.0.0 on anl huawei p10 plus.
I hit start r session, get an error at some point that I need to run dpkg --configure -a (which I did using sudo otherwise I get an error), I did this from a debian session. Then closed this, started R again, it does the installing of packages like icu-devtools etc. Then at the end I get connection failed. The sessions say vnc above it. 
Do you have an idea what is going wrong or where I could stsrt troubleshooting?

**Comment by stackerlon** [comment]
Problem with oreo running Huawei devices is that nothing works you can setup session but you cannot get it to run. See #398

**Comment by corbinlc** [comment]
I am closing this as I am using #398 to track all huawei specific related issues for now.
