### ISSUE TITLE
Installing vscode does not work

### ISSUE THREAD

**Issue by halowodegit** [CypherpunkArmory/UserLAnd#415]
https://github.com/headmelted/codebuilds
But on my root device is ok

**Comment by halowodegit** [comment]
Device is Android8.1

Runtime informationn:
 xlib: extension"XInputExtension"missing on display"localhost: 51". xlib: extension"RANDR"missing on display"localhost: 51".
 Trace/breakpoint trap.

**Comment by sangowen** [comment]
You'll probably want to change the default TightVNC server to TigerVNC server to get RANDR support.
TigerVNC started as a branch of TightVNC. AFAIK, while TightVNC stop its development at ~ 2006, TigerVNC is still maintained. It supports a lot more other features and it requires config. no further from TightVNC config.

``` sh
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension
```
and then change /support/startVNCServerStep2.sh line 31-32
```
tightvncserver -kill :51
tightvncserver :51 -geometry ......
```
to
```
vncserver -kill :51
vncserver :51 -geometry ... -localhost no
```
YMMV but afterwards I could use xrandr or any program that requires RANDR or render extension.
For me it was probably required by compton/ranger/rofi/.... It was a long list that I can't remember.

I've also tried installing vscode a couple of days ago but didn't have time to resolve its package dependency issue, but you seem to have already passed that stage.
If you break your VNC during the transition, you can always ssh back to change the starting scripts.

**Comment by sangowen** [comment]
After installation, I've gotton this by running the ```code-oss --verbose```.
[21504:1124/021538.690189:ERROR:bus.cc(395)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

**Comment by halowodegit** [comment]
@sangowen
I did not replace vncserver.
I think it is a permission issue. for example, it can't be mounted /dev
May require access to system modules

I tried two devices.
Samsung note 2(root,but its kernel is too old)
redmi note 5 pro(noroot，start code-oss will be interrupted)

but rooted redmi is ok
