### ISSUE TITLE
Nmap Doesn't work in Userland

### ISSUE THREAD

**Issue by sr13579** [CypherpunkArmory/UserLAnd#417]
How to run NMAP in Userland?

**Comment by projectextremum** [comment]
can you describe what error you are getting while trying to install / run `nmap`?

If you are just another guy fascinated to crack some random network, then neither `userland` nor `nmap` is for you.

**Comment by AdamMatthewLTM** [comment]
I am closing this thread because there are multiple duplicate threads asking for more specific help with the nmap package. In the future when filing issues on github please use the template provided, and thank you.
