### ISSUE TITLE
Is available RAM problem ? (may be related to issue #289)

### ISSUE THREAD

**Issue by AuntieE** [CypherpunkArmory/UserLAnd#423]
My phone is an Honor 5C with Android 7. I have been trying to get an lxde desktop for days now, with the help of Corbin. 
   I've about come to the conclusion that my inability to move from the CLI to the DE is lack of memory on my phone. Here's why : 
Having received no answer from bVNC, as yet, I thought I’d see about starting LXDE from the command line, rather than by closing it in UserLAnd and opening it again (since that doesn’t work). Today, I updated and upgraded my Ubuntu, then began work on LXDE, first with the help of this site, by Guillermo Garron https://www.garron.me/en/go2linux/how-to-install-startx.html, written in 2008. Using his information, I did sudo apt install xinit, then installed nano with which I made the .xinitrc file with just one line : exec startlxde. But when I typed in startx again, the connection to the X server was refused. Now I’m using the help of a different site, https://superuser.com/questions/671169/starting-and-stopping-x11-and-lxde-from-command-line, which is newer – 2013, revised in 2015. I’ll check and make sure that LXDM actually exists in my file system: /etc/init.d/lxdm start. It does exist, but in /etc/, there is no folder for init.d. So I cd’ed to /etc/, did sudo lxdm start and got this error message:
![screenshot_20181124-103504](https://user-images.githubusercontent.com/45310194/48967778-15ad5e00-efe6-11e8-828c-abf2f8eb5066.png)
Note that lightdm IS present in the etc folder. The message is the same received by someone with Ubuntu in a VM on Windows XP, although I don’t get more info about the system bus. 
The source for that is: https://www.reddit.com/r/linuxquestions/comments/7uh0kz/ubuntu_is_failing_to_boot_after_an_xp_virtual/
**Could it be a question of the available RAM on my telephone?** (Or is the RAM in bVNC what matters?) I have 3.64 Go free in the internal memory and 17.47 Go on the SD Card. There is a total of 1.7 Go of RAM, with only 538 Mo free. And that’s not much! Android OS itself uses 743 Mo. Even after “freeing RAM” with Avast, there are still only 538 Mo free. I just forced Avast to stop and will now do a complete reboot. And now I have only 41 Mo more, or 579 Mo of available RAM.
  Having read various issues, here I think I'll try ssh rather than vnc and, if that doesn't work, I'll delete bVNC and try VNC Viewer. At least I'm having fun while waiting for iiordanov from bVNC concerning the reasons for an inability to connect and whether or not I need Java (and what sort) for the DE (see issue 289).
   Thanks for all the help you can give !

**Comment by dragonSilverString** [comment]
Glad you got this working.  Seems like it was harder for your device than for many.  We will try to learn something from your experience and improve going forward.

**Comment by corbinlc** [comment]
Glad you got this working. Seems like it was harder for your device than for many. We will try to learn something from your experience and improve going forward.
