### ISSUE TITLE
How can I acess files of UserLAnd /home?

### ISSUE THREAD

**Issue by underfilho** [CypherpunkArmory/UserLAnd#428]
Where is located /home/username (the standard directory)? I need this because I can't execute files in sdcard, but in /home/username I can and I don't know where is that it, the only way that I can create codes and execute currently, is to create in sdcard, and in the UserLAnd copy this file to /home/username

Device Information

Device: Xiaomi Redmi 4X
Android Version: 7.1.2
UserLAnd Version 1.0.2
MIUI 9.6.5
UserLAnd using Debian SSH

**Comment by corbinlc** [comment]
They are in internal storage at /data/data/tech.ula/files/N/home/username where N is the Nth filesystem you have setup (an autogenerated number).

**Comment by corbinlc** [comment]
This is not an easy directory to get to.  So, you may want to copy files to the sdcard and then into the filesystem or vice versa.

**Comment by corbinlc** [comment]
Do you have any remaining question or request?  If so please file a new issue for that or reopen this one if it is still on the same topic.
