### ISSUE TITLE
Connect using VNC on another machine on the network.

### ISSUE THREAD

**Issue by maxolasersquad** [CypherpunkArmory/UserLAnd#434]
**Is your feature request related to a problem? Please describe.**
Nope.

**Describe the solution you'd like**
Ability to connect from another machine on the network.

**Describe alternatives you've considered**
Screen casting services like Chromecast can make viewing the UserLand better, but still no way to use external mouse and keyboard.

**Additional context**
Currently one can use a VNC application installed on the Android device to interact with the UserLand GUI. It would be beneficial to also be able to connect using VNC on another machine on the network

**Comment by corbinlc** [comment]
You should be able to.  We need to document this, but we use display :51 .  Please try to connect from another machine on the same network using your phones IP address on that network and using display :51 (if you have to specify the port, display :51 is on port 5951).  Please provide feedback as to whether this works or not.

**Comment by null1024** [comment]
Yeah, it works out of the box for me.
it should just be
- connect to same network as target machine
- get your phone's local IP address
- connect with your VNC client with (your phone's ip address)::5951
- enter the VNC password you set up, and that's it

there's also a direct connect method via the ADB utility with USB debugging enabled on your phone, where you can do
adb devices
adb forward tcp:5000 tcp:5951

and from there, you can just connect to 127.0.0.1 from your VNC client

**Comment by corbinlc** [comment]
@null1024 thanks for the follow up.  Let me leave this open for a bit.  It will remind me to put this in the wiki we are going to start.

**Comment by maxolasersquad** [comment]
It took me a bit to test this out. I can confirm that this works using the Remmina VNC client.

**Comment by corbinlc** [comment]
https://github.com/CypherpunkArmory/UserLAnd/wiki/FAQ

**Comment by Poincare1** [comment]
Does not work as of 03/31/2019 with Debian install and latest Userland (v2.4.0).  On a laptop or desktop connected to the same WIFI, trying to connect to the device ip and post 5951, nothing happens. VNCViewer just reports a timeout error, same for other attempted connections from VNC clients from devices on the same network.  Connecting **from the device itself** works, but connecting from another device, on the same network, does not.  Please advise.

**Comment by Simeon2001** [comment]
VNC not connecting

**Comment by mhofert** [comment]
I tried various things (also the adb trick), couldn't get any to work. Please be specific in what you are doing (give clear one-by-one instructions with the actual commands you are using).

**Comment by speefak** [comment]
It Works ;)

1 First check if VNC is available from LAN ( nmap -p 1-65535 <DeviceIP> ). Result :
=> PORT     STATE SERVICE
=> 5951/tcp open  unknown
2. Then connect via VNC client ( Vinagre or others ) to VNC session 
=> connection ip syntax is  : <DeviceIP>::5951 ( twice colon ! )

**Comment by raduprv** [comment]
I managed to get my desktop VNC to connect to my phone, but it asks for a password. I never set any password (never asked to), so I can't connect from my computer to my Linux desktop on the phone.
Any idea what the default vnc password is?
