### ISSUE TITLE
Change working directory in Octave 

### ISSUE THREAD

**Issue by DavidFahrenheit** [CypherpunkArmory/UserLAnd#436]
Hi, 
I used to have the GNURoot Debian version of Octave prior to the issues with Android Oreo. 
Now I'm trying to use Octave on UserLAnd with Connectbot. Everything loads up ok, but I don't seem to be able to change the working directory to where my .m scripts are on my phone (S7 Edge).
Is this a known issue or is there a simple solution for this?
Thanks

**Comment by janesda** [comment]
If you are in **/home/username** and you are used to working in **GNURoot/home**, try typing at Octave prompt **_cd /sdcard/GNURoot/home_** as a quick work around.

**Comment by DavidFahrenheit** [comment]
Thanks, that works great
