### ISSUE TITLE
Graphics in Octave

### ISSUE THREAD

**Issue by janesda** [CypherpunkArmory/UserLAnd#437]
Plot commands from an Octave to GNUplot are not passed across
eg. >> x = 1:9; plot(x,x.^2)
produces:
error: __gnuplot_get_var__: Can not make FIFO (Function not implemented)
error: called from
    __gnuplot_get_var__ at line 59 column 7
    __gnuplot_has_terminal__ at line 36 column 25
    __gnuplot_drawnow__>gnuplot_default_term at line 356 column 5
    __gnuplot_drawnow__ at line 77 column 10
>>
Expected behavior: A plot in GNUplot
Screenshots not applicable

Device Information
Device: Galaxy Tab A
Android Version: Oreo, 8.1.0
UserLAnd Version  1.0.2
Additional context: Debian with both ssh & vnc

**Comment by corbinlc** [comment]
We should be able to fix this.  I need to get my newer Samsung device back to debug better.  It will be a little bit.

**Comment by pyrocto** [comment]
I get this error from the app.  Trying to run octave by installing it with apt-get on Debian gives a different error: "cannot enable executable stack as shared object requires: Permission denied"

**Comment by pyrocto** [comment]
@corbinlc How should I send you the debug file?

**Comment by MatthewTighe** [comment]
@pyrocto You can attach files directly to Github comments by dragging it into the comment window or pasting it from the clipboard.

**Comment by pyrocto** [comment]
@MatthewTighe on desktop.  Not sure how to do either of those from my phone.  Tried running Firefox in userland to get drag & drop but it didn't work either (will file a ticket).  Currently trying to install chromium to try the same thing.  Also I'm thinking I might be able to respond to the email for this ticket with an attachment.

**Comment by pyrocto** [comment]
I managed to get the file off my phone, but github says the file size limit is 10Mb for an attachment and even gist won't let me upload it.  You can get it with this Google Drive link: https://drive.google.com/file/d/1uMSz1r0QzBD9nwvReUnHOJzxasOlTccb/view?usp=sharing

**Comment by janesda** [comment]
Like Mike Stay, I couldn't send it to github as the message was too large,
so I am sending you a link to the file on Google Drive

https://drive.google.com/file/d/16PmVpr1OMJv3m6XZ4uZ3ePtUIepzx8Ky/view?usp=drivesdk

Thanks again.

**Comment by corbinlc** [comment]
This has been fixed for a while.  A recent change broke things again, but I just fixed this a 2nd time.
