### ISSUE TITLE
Numpy doesnt work anymore

### ISSUE THREAD

**Issue by patrick-erhard** [CypherpunkArmory/UserLAnd#440]
Describe the bug

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

Screenshots

Device Information

Device: [e.g. Pixel XL 2]
Android Version: [e.g. Oreo, 8.0]
UserLAnd Version [e.g. 0.1.2]
Additional context

HI,
After a new hard release of my Samsung TAB 2006 
python-numpy doesnt work anymore.

Type python
then import numpy

... numpy itself calls ctype using a "import ctype".
This results in a "Memory Error"

Faithfully yours

**Comment by EnderNightLord-ChromeBook** [comment]
a may be device error... works for me... (using samsung J 6)

**Comment by patrick-erhard** [comment]
No, it's must be a recent Android modification, it worked before on my Samsung.
The problem happens simply if you type python -m ctypes.
A simple fix which seems to work is, 
In file :
/usr/lib/python2.7/ctypes/__init__.py

Comment the line 276, which is :
    CFUNCTYPE(c_int)(lambda: None)
