### ISSUE TITLE
OpenSUSE (feed)

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#443]
I Want To Create A Pull Request For OpenSUSE... where would the distro files be? and could you give me some tips?

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks very much!

**Comment by EnderNightLord-ChromeBook** [comment]
how's the brief coming up?

**Comment by corbinlc** [comment]
I put adding Arch Linux as a distro ahead of that, but I finished.  I will add it soon.

**Comment by EnderNightLord-ChromeBook** [comment]
Wow your amazing... I'm looking forward to it... I will try to add openSUSE support... would you like to help?

**Comment by EnderNightLord-ChromeBook** [comment]
right...

**Comment by corbinlc** [comment]
Ok please take a look at this:
https://github.com/CypherpunkArmory/UserLAnd/wiki/Adding-a-Distribution
which references this:
https://github.com/CypherpunkArmory/UserLAnd/wiki/Adding-an-App

That should help you get started.

I also created this empty repo for you to clone, https://github.com/CypherpunkArmory/UserLAnd-Assets-OpenSUSE .

Tell me what is not clear and such as you go through the process.

One thing I know I need to add is how to test your new app/distribution, but this should get you a long ways.

**Comment by EnderNightLord-ChromeBook** [comment]
Could you add me as a collaborator for OpenSUSE Port?

**Comment by EnderNightLord-ChromeBook** [comment]
Thank you

**Comment by EnderNightLord-ChromeBook** [comment]
Hey Corb Started On /Script Files...

**Comment by EnderNightLord-ChromeBook** [comment]
Hey corben... can you give me a quick tutorial on how to create the .gz files?

**Comment by corbinlc** [comment]
You have to create a chroot for the given disto.  This is normally done using commands like `deboostrap` or `arch-bootstrap` and such depending on the distro type (you will see this in the `buildArch.sh` file).  I am not sure how best to do this on openSUSE.  Maybe something like this would help... https://marc.waeckerlin.org/computer/blog/bootstrap_opensuse

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks Corbin! That Helps A Load!

**Comment by EnderNightLord-ChromeBook** [comment]
Ok main files are in alpine...

**Comment by EnderNightLord-ChromeBook** [comment]
Hey corbin finished file systems for x86 and x86_64... I don't know much about arm and arm64...

**Comment by EnderNightLord-ChromeBook** [comment]
The script you gave me is outdated... It wont work... Can you find anything else?

**Comment by EnderNightLord-ChromeBook** [comment]
Hey corbin I have the the arm openSUSE chroots... But the smallest (jeOS) is 500mb unpacked... this will be a big OS for userLAnd...

**Comment by EnderNightLord-ChromeBook** [comment]
> What is the size of the tar.gz files? Are you bootstrapping this, or are you downloading a particular image to create it?
> 
> As far as finding a new script, I just googled for that one. I have never used openSUSE. I would simply just look at more google results if I was looking further.

OpenSUSE is not very easy to chroot... well on a chromebook I will use my ubuntu pc for building... but still I don't think that will help OpenSUSE is hard so just use the images...

**Comment by corbinlc** [comment]
OpenSUSE might not be a good fit for UserLAnd as it seems not obvious how to bootstrap a small image currently.  If I or someone does research on how to do this and finds something useful, we can start looking at this again.
