### ISSUE TITLE
Exporting Display to XSDL?

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#45]
I tried using export Display=:0 startlxde and switching to xsdl but it doesnt connect to run lxde. I have a feeling im doing something wrong. Anyone have any input?

**Comment by corbinlc** [comment]
I found that using DISPLAY=localhost:0 worked but not without localhost.  Need to research what is expected here and why one would work and not the other.

**Comment by corbinlc** [comment]
Btw.. we have future plans to take care of launching into xsdl for you as another client option.

**Comment by Root-voidX** [comment]
Yes it seems using DISPLAY=localhost:0 worked. This is interesting! I can say this issue is closed as of now.

**Comment by corbinlc** [comment]
I am going to open this back up.  So 1) people see it and 2) because I want to research what is happening here.

**Comment by Root-voidX** [comment]
Sounds good @corbinlc. I honestly think they having to specify localhost actually has to do with the fact that this is already being done from a ssh connection maybe?

Also have you figured out how to get video acceleration? Before using libgl1_mesa_swx11 for software rendering worked. I have installed the updated version libgl1_mesa_dev for stretch but i still cant get rendering?

**Comment by pantumaca** [comment]
Mmmm... i do not think so.

In termux and archlinux was the same; "localhost" is required to export the session (we talked about this in the original threath months ago).

**Comment by Root-voidX** [comment]
Nope in arch linux all i needed as D=:0 startlxde and it worked...

**Comment by pantumaca** [comment]
For me that never worked. I must use "localhost" or the export command fails.

In that case i have said nothing.

**Comment by schoec1** [comment]
I would like to get back to the video acceleration issue. Using lxde with xsdl or VNC clients works really well on my Samsung S8 with Oreo and the DEX dock with the new app, that's really great! However, I guess the video acceleration issue is responsible for some applications not running properly, e.g. firefox. When I start firefox, I see a lot of errors like 
   Xlib: extension "XInputExtension" missing on display "localhost:1.0"
or
   Crash Annotation GraphicsCriticalError: |[C0][GFX1-]: Failed 2 buffer db=0 dw=0 for 0, 0, 812, 542 (t=4.40868) |[C61][GFX1-]
and pages cannot be rendered. Also, libreoffice is not starting, unfortunately I couldn't find the error messages yet ...
Probably we should open a separate issue for that one?

**Comment by pantumaca** [comment]
Libreoffice returns "no proc mounted". You can see that message launching it from terminal.

**Comment by drhuffman12** [comment]
Which ever syntax is decided/needed, please be sure to add it to a guide, how-to, wiki, etc. :)

**Comment by Root-voidX** [comment]
So apparently, libgl1mesa6 package replaces libgl1-mesa-swx11, which was used in Debian Jessie to use render graphics correctly in x11. It installs without a hitch, but the system won't render any graphics like glxgears or Firefox. There is a fix for Firefox but that actually disabled any acceleration within Firefox (a temp fix).

Anyone have any idea on this?

**Comment by hkgoldenmra** [comment]
`export DISPLAY=:0`
requires full upper case of DISPLAY; display, Display, ... are not suitable.
127.0.0.1 or localhost is default, if IP is not assigned.

**Comment by Root-voidX** [comment]
@hkgoldenmra export command is not required. 
'DISPLAY=:0 startlxde'
Works fine, I've only needed to specify localhost if accessing userland in another app via ssh.

**Comment by AwsomeGamer2019** [comment]
Nothing working

**Comment by nakele** [comment]
@AwsomeGamer2019 @FTWJAY 
Samsung S8 Pie > Debian > xfce it works no problem on VNC

The XSDL android app is not working anymore on Pie apparently. That's not a problem with Userland app but rather XSDL android app problem. It;s another developer.

**Comment by Timbological** [comment]
Should the getting started page of the wiki page be changed to reflect this?

I'm thinking that DISPLAY=localhost:0 will work wherever DISPLAY=:0 will work but not vice-verse, correct me if I'm wrong.

Thanks
