### ISSUE TITLE
Atheros wifi network adapter "almost" recognized

### ISSUE THREAD

**Issue by niente0** [CypherpunkArmory/UserLAnd#452]
Hi, I'd like to use an external wifi network adapter based on Atheros AR9271. I installed userLAnd, then Ubuntu. I ran "**apt-get install firmware-atheros**" to install proper firmware (after adding a non-free repo in source.list).
Then if I type "**usb-devices**" I get this output:
```
T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 1
D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=01 MxPS=64 #Cfgs=  1
P:  Vendor=1d6b ProdID=0002 Rev=03.18
S:  Manufacturer=Linux 3.18.20-gefffda4 ehci_hcd
S:  Product=EHCI Host Controller
S:  SerialNumber=msm_hsusb_host
C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=480 MxCh= 0
D:  Ver= 2.00 Cls=ff(vend.) Sub=ff Prot=ff MxPS=64 #Cfgs=  1
P:  Vendor=0cf3 ProdID=9271 Rev=01.08
S:  Manufacturer=ATHEROS
S:  Product=UB93
S:  SerialNumber=12345
C:  #Ifs= 1 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 6 Cls=ff(vend.) Sub=00 Prot=00 Driver=(none)
```
It means that _**the usb device is recognized**_, but the problem is that in last line I have "Driver=(none)" (I read that Ubuntu should have integrated drivers for this adapter).
I tried installing "usbutils" and running "**lsusb**" but I just get an error: "Unable to initialize libusb: -99".

What can I do to use my wifi adapter on userLAnd? And more important question: **is it possible to use it with userLAnd**?
Thank you for your help

**Comment by EnderNightLord-ChromeBook** [comment]
I haven't seen usb support yet... It might work, we might have to leave this to the devs...

**Comment by corbinlc** [comment]
I don't believe this can work without running as real root (we run as a fake root user when you do `su` or `sudo`) and have tagged it as such.  We plan on eventually adding support for running as real root if you want to and you have rooted your device.

**Comment by corbinlc** [comment]
I have added this to #910 .  It is a list of feature requests that probably cannot be solved properly without running as a real root user.  Please follow and comment there.  I am closing this issue.
