### ISSUE TITLE
JuiceSSH cannot long time connect

### ISSUE THREAD

**Issue by c4dr01d** [CypherpunkArmory/UserLAnd#459]
I install the Arch Linux at UserLAnd,when I starting service,login into ssh.After 30 minutes about,JuiceSSH hint: Connect Failed every time,then JuiceSSH force shutdown the session.

**Comment by lmorda** [comment]
I also just installed UserLAnd with a Debian distro, tried to connect with JuiceSSH, and it's taking about three minutes to login.

**Comment by corbinlc** [comment]
@c4dr01d does this issue only happen with JuiceSSH?  If you connect via ConnectBot, does the same thing happen?  Also can you provide what device you are using and what version of Android you have?

**Comment by corbinlc** [comment]
What device do you have?

**Comment by c4dr01d** [comment]
My device is Huawei devices

**Comment by corbinlc** [comment]
Ah man.  So many of our issues are Huawei devices.  Please see #398.  Can you tell me specifically what device?

**Comment by c4dr01d** [comment]
Huawei ChangXiang 7 plus TRT-TL10A

**Comment by corbinlc** [comment]
I am marking this as duplicate and closing this, just because I am trying to steer all Huawei specific problems to #398.  If we fix #398, but not this issue, please open it back up.  I am hoping the same underlying issue will be found in each case.

**Comment by tiger1217** [comment]
Hallo I already have the same problem and my device is Samsung Galaxy S9 I hope  that some one give me a solution for this problem  
Thanks
