### ISSUE TITLE
Password set in new app password dialog not working

### ISSUE THREAD

**Issue by lmorda** [CypherpunkArmory/UserLAnd#460]
When creating a new app, the Password that I entered into the please enter the relevent required information dialog during the setup process does not appear to be working when I try to SSH into the Linux image.

I created a Debian app on my Google Pixel XL running Android 8.0.  Everything worked correctly.  As soon as the app launched, JuiceSSH was brought up to the foreground as expected.  JuiceSSH then asked for the password for the username I created.  I entered the password and the login failed.  Tried this whole process multiple times and still experiencing the same issue.  Also tried other SSH clients and still experiencing the failed password problem.

I also tried entering the default password "userland" with no success.

**Comment by corbinlc** [comment]
We have not heard of this issue.  Is it possible that you entered your password incorrectly when originally creating the filesystem (we should probably make the form ask you to confirm what you entered)?  Can you try again from scratch and tell us how it goes?  If that does not work...is there something special about your password, like special characters.

**Comment by lmorda** [comment]
Yeah no problem tried again three more times and same problem.  Nothing special about password and not sensitive info:

Username
operator
Password
operator
VNC Password
operator

I'm on a Google Pixel XL running Android 8.0 but not sure that makes a difference.  I could try another device too when I get into work on Monday.

**Comment by corbinlc** [comment]
that particular username and password do not work for me either (all others i have ever used have worked).  maybe the username and password cannot be the same.  let me see what the rules are

**Comment by corbinlc** [comment]
`useradd: group operator exists - if you want to add this user to that group, use -g.`

So it looks like that is already an existing group and by default a new user is created with a group name that matches their username.  

So, you cannot user `operator` as your username.  I will add an internal card for improving our form validation.

**Comment by corbinlc** [comment]
I assume that will solve your issue.  I am going to close this, but please reopen it if this specific issue is not resolved.

**Comment by lmorda** [comment]
I also saw this error:

Extracting: chsh: user 'operator' does not exist

**Comment by lmorda** [comment]
Ok perfect I should have tried that for you !  Thanks
