### ISSUE TITLE
Ubuntu fails to install

### ISSUE THREAD

**Issue by casept** [CypherpunkArmory/UserLAnd#461]
Setup of the Ubuntu app fails on a Galaxy Tab 2 running an unofficial build of LineageOS 14.1. It gets stuck during filesystem setup (as can be seen in the screenshot) and installation never completes. Ubuntu installed perfectly on my phone (running Lineage 15.1), so it's probably a device-specific issue.

* Go to apps -> Ubuntu and fill out the username/password
* Wait for the rootfs download to complete and for installation to start
* Observe how filesystem setup hangs

Expected behavior: Installation working as intended

Screenshots:
![screenshot_20181207-224048](https://user-images.githubusercontent.com/21053871/49674360-001e4680-fa72-11e8-8011-022fb93195f2.png)
![screenshot_20181207-224421](https://user-images.githubusercontent.com/21053871/49674371-0b717200-fa72-11e8-9c09-a962ebaa46b4.png)

Device Information:
* Device: Samsung Galaxy Tab 2 7.0 (aka `espressowifi` or `p3110`)
* Android Version: 7.1.2 (LineageOS 14.1 unofficial)
* UserLAnd Version: 1.0.3 from F-Droid

Additional information:

This is the proot log at verbosity level 9:
[PRoot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2658875/PRoot_Debug_Log.txt)

**Comment by corbinlc** [comment]
Very thorough issue.  Thanks for that.  Is this repeatable?  If you wipe all UserLAnd data, uninstall it and then reinstall it such that it has to download all the assets again, does the problem occur again?

**Comment by casept** [comment]
Unfortunately wiping UserLAnd data (or reinstallation) doesn't seem to change anything, it still hangs at the same place.

**Comment by EnderNightLord-ChromeBook** [comment]
ok... have you tried installing debain?

**Comment by casept** [comment]
Yes, and arch as well. Both hang.

**Comment by xie-dongping** [comment]
Same issue on LineageOS 14.1 (lineage-14.1-20181110-nightly-n2awifi) with Galaxy Tab n2awifi. Tried Arch and Debian.

Clearing data and reinstalling didn't help either (tried 3 times).

**Comment by corbinlc** [comment]
Ok.  Sounds like a real issue.  I don't have that specific device, so this might take a bit.

**Comment by soukron** [comment]
Same issue here in a different device with different distros.

**Comment by corbinlc** [comment]
We never got a device that showed this specific issue and we have made many changes since last January.  Closing this, but please reopen it if this problem still occurs in the latest version.
