### ISSUE TITLE
Alpine Linux (feed)

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#463]
![image](https://user-images.githubusercontent.com/31677287/49677198-52974b80-fae2-11e8-8cd0-d05c57ef99f7.png)

^ top: inside the alpine linux chroot

![image](https://user-images.githubusercontent.com/31677287/49677202-588d2c80-fae2-11e8-903f-81e0ec40432b.png)

bottom: chroot setting up
Thank You Very Much Corbin

**Comment by EnderNightLord-ChromeBook** [comment]
Milestone 1 Uploaded!!!!
: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/Alpine-V1.0/assets/Alpine-Milestone-1

**Comment by EnderNightLord-ChromeBook** [comment]
x86 and 86_64 uploaded:

x86: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/master/assets/x86

x86_64: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/master/assets/x86_64

**Comment by EnderNightLord-ChromeBook** [comment]
arm versions uploaded: 

aarch64: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/master/assets/aarch64

armhf: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/master/assets/armhf

**Comment by corbinlc** [comment]
We need the `buildArch.sh` or similar to bootstrap the base image or to download the image or whatever.  People will want to know how the filesystem was created and we will want to be able to update this.  Right now your `buildArch.sh` is just the one from Debian.  

For the x86 and x86_64 ones, I am guessing you are using the script I provided right?

But for armhf and arm64, you are just downloading an image from somewhere...is that right?  That image appears to be too big as we want something really stripped down and then we can add packages from there.

You should be able to modify the script I provided to work for armhf and arm64.  The trick is you need to use qemu.  For debian or ubuntu you can use `qemu-debootstrap` which automatically copies the correct version of qemu into your chroot for you.  Alternatively, you can manually copy qemu into the filesystem, before you chroot into it for the first time.  An example of that can be found here:
https://github.com/CypherpunkArmory/UserLAnd-Assets-Kali/blob/master/scripts/buildArch.sh

**Comment by EnderNightLord-ChromeBook** [comment]
Hey corbin can you add access for me to centOS and fedora?

**Comment by corbinlc** [comment]
I already added you as a collaborator for both.  You can also just fork them and then make Pull Requests.  This is what you will have to do in the future once we are shipping these distros and want to make sure nothing breaks.

**Comment by EnderNightLord-ChromeBook** [comment]
good Idea...

**Comment by EnderNightLord-ChromeBook** [comment]
thanks

**Comment by EnderNightLord-ChromeBook** [comment]
Ok Everyone! Alpine linux is ready to release into the world!

Changes:

buildArch.sh can detect your arch from the installer...

buildArch.sh: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/blob/master/scripts/buildArch.sh

rootfs: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/tree/master/assets

Coming Soon!:

Fedora 29 and 28:

armhf: 28 minimal base

aarch64: 29 base

86_64: 29 base

**Comment by corbinlc** [comment]
I think there is still confusion about what 'buildArch.sh' is supposed to do, but getting closer.  'buildArch.sh' does not run on the target device (phone or chomebook) necessarily, instead it runs on the build server, which will be x86_64.  So, you cannot use 'uname' to tell you what to do.  In your case, you need to use '$1' again to help you know what you are building.  So, 'MACHINE_TYPE' should be based on '$1'.

**Comment by corbinlc** [comment]
Other things... we need to support all 4 Android supported processor types, you have two commented out.
Also, notice the other 'buildArch.sh' scripts do a few extra steps after creating the tar files.  If those steps aren't clear, please ask me about them.
Thanks

**Comment by EnderNightLord-ChromeBook** [comment]
ok got it... thanks I will get to work...

**Comment by EnderNightLord-ChromeBook** [comment]
will the code that detects your architecture be able to be used?

**Comment by EnderNightLord-ChromeBook** [comment]
Oh yes I remember... I will use the $1 for the arch...

**Comment by EnderNightLord-ChromeBook** [comment]
once i finish a os... i will know how everything works...

**Comment by EnderNightLord-ChromeBook** [comment]
ok now check the buildArch.sh... 👍 

: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/blob/master/scripts/buildArch.sh

**Comment by corbinlc** [comment]
It is still using 'uname' and not doing the extra steps at the end.  Have you tried to use it to build all architectures worth of tar files?

**Comment by corbinlc** [comment]
It is still using 'uname' and not doing the extra steps at the end.  Have you tried to use it to build all architectures worth of tar files?

**Comment by EnderNightLord-ChromeBook** [comment]
going on holiday I will work on this in two weeks...

**Comment by EnderNightLord-ChromeBook** [comment]
ok got back I can start work again... we got back early...

**Comment by EnderNightLord-ChromeBook** [comment]
Ok holidays are over and so I'm getting ready to get back into it. Corb I need you to work on opensuse when you can and I'm going to finish alpine linux. Then we can start on fedora

**Comment by EnderNightLord-ChromeBook** [comment]
Hey corb does it meet standards yet?

**Comment by EnderNightLord-ChromeBook** [comment]
Arm and Aarch64 are a challenge cause your script only works with the arch your using... so if you have an arm device then could you help?... I will try to see whats going wrong in buildArch.sh and have a look at other OS implementations for this app.

**Comment by EnderNightLord-ChromeBook** [comment]
the arm things I got now are alpine mini rootfs by the way.

**Comment by EnderNightLord-ChromeBook** [comment]
here is a demo of x86_64:

https://drive.google.com/file/d/1APIEWjjT9X0G_etSpNd23vGLeV2x6LEA/view?usp=drivesdk

**Comment by EnderNightLord-ChromeBook** [comment]
Ok I have done some modifications to the `buildArch.sh` it looks much nicer and should work... If not could you teach me a few lessons?


https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/blob/master/testing/buildArch.sh

**Comment by corbinlc** [comment]
It looks closer.  Close enough, that I will have to try it out to see what is missing.  I will tell you what I find.  It will probably be first thing next week.  

One quick thing for now, why is it the `testing` directory instead of the `scripts` directory.  

I guess two quick things, have you run the script and seen it create the needed assets, like `libdisableselinux.so`?

**Comment by EnderNightLord-ChromeBook** [comment]
I'm sorry but I dont  have much tools for this I will try and use it on my chromebook... see if I can do it... just gimme some time.

**Comment by EnderNightLord-ChromeBook** [comment]
Oh and your question... it was a test script. I will now remove the old one and replace.

**Comment by EnderNightLord-ChromeBook** [comment]
ok... there you go... the testing has been moved to full script

**Comment by EnderNightLord-ChromeBook** [comment]
Sorry I can't test it on my chromebook...

**Comment by EnderNightLord-ChromeBook** [comment]
I might just let you test it...

**Comment by EnderNightLord-ChromeBook** [comment]
hey corbin hows testing going?

**Comment by corbinlc** [comment]
Today I spent 2+ hours reviewing and debugging what you had so far.  Honestly, it had some serious issues.  Nearly every step had an error for one or all architectures.  I am not sure if you never saw these, or just ignored them, but they were almost all problematic.  In addition the script still didn't even attempt all the steps that are found in the other buildArch.sh scripts.  For example, it didn't try to build `libdisableselinux.so`.  There were more issues beyond that.  If you look at the repo now, it is much closer to what I think is correct, but I still have more testing to do before it can be released.

I have a feeling you are early in your learning and I appreciate you wanting to contribute, so I going to provide some advice that is hopefully not to harsh and proves useful...

Ideally for us, or any open source project that someone wants to contribute to, we would like the contributor to understand what they are doing and if they don't already to do a little research and then ask questions on what remains unclear.  Then we would like that person to do the work and then create a PR once they have built what they think is best and have tested to be correct.  In addition, normally contributors don't say they are "done" or "ready" or whatever until that is close to being accurate.  The back and forth between you and me and my team has been costly time wise.  Please try to be more independent and considerate of other people's time.  I know what you are trying to do is cool and that you would like to show off your efforts and the result, but please make sure it is something worth showing off.  

Lastly, and this is with regards to other github issues, not this one, please don't comment on another issue unless you have a feeling that your comment is helpful.  We actually get notifications whenever anyone comments on any issue, so we can respond, and you have created a lot of notifications for very short phrases, that often don't assist in solving the issue.  In a similar vein, please don't speak for us...for example 1) making a help wanted issue saying we need help with something or 2) saying "we" are going to delete someone's issue if they don't follow the template and 3) other uses of "we" language.  You maybe right, but please leave such things to us.

I know I am coming at you with a lot and this is my fault for not being more involved sooner.  I honestly do hope this helps.

**Comment by EnderNightLord-ChromeBook** [comment]
sorry for all the trouble I have caused. I just wanted to help and expand my knowledge. And I am only young so I might just leave userLAnd alone. Thanks For Teaching Me. And Sorry Again.

**Comment by corbinlc** [comment]
You could leave the project, but if you are willing to take the feedback, you could stay and modify how you engage with us.  You did a great job creating inkscape and your desire to help is valued.  
If you do stay, I propose a small challenge that I am willing to support that would help us both.  It would look something like this...
You: Try to bootstrap fedora for arm64 (we will worry about other architectures and other steps later).  You do this fairly independently (of course you can use stackoverflow, google, etc) and you point us at your script when it is ready.
Me: I will respond when possible on slack (sometimes a day or two delayed) to specific questions.  I will teach, but only if you have done some searching yourself and listen to my suggestions.
If you are up for the challenge...
Hints: 1) look at febootstrap and 2) doing this from a fedora virtual box or otherwise makes this easier.
Lastly, you are early on and we are in no rush, so please don't simply try to google the final answer, try to understand the steps and build your knowledge up from there.    
What do you think?

**Comment by EnderNightLord-ChromeBook** [comment]
I will stay... thanks for the support corbin. I will continue to contribute and I will take you feedback and only comment when I have something useful to say. Thank You

**Comment by corbinlc** [comment]
Please stop using "we" language.  When you say "We will get it working" you are saying that you and my team have discussed the issue and that we are in agreement on it.  
Also, I feel like some of the other comments recently don't actually help the conversation along.
I am going to start tagging issues with "help wanted" if we want people to help out, that way it is more clear, where we want someone to jump in.

**Comment by EnderNightLord-ChromeBook** [comment]
Ok got it I get what you mean.

**Comment by EnderNightLord-ChromeBook** [comment]
And yes I know I have a lot to work on.
