### ISSUE TITLE
Add Fedora Repo

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#465]
Hey @corbinlc  could you make a repo for fedora...

I have the layouts for fedora armhf, x86, x86_64 and arm64 / aarch64...

Website: https://nmilosev.svbtle.com/quick-and-easy-fedora-minimal-chroot

My Plans And .part files: https://github.com/EnderNightLord-UserLAnd-Projects/UserLAnd-Fedora-Project

**Comment by EnderNightLord-ChromeBook** [comment]
Corbin could you add a repo for fedora?

**Comment by EnderNightLord-ChromeBook** [comment]
I could do centOS... I used it for a year... it's quite good so I could do that as well... I just need to finish alipine... It's number 1 priority to me...

**Comment by corbinlc** [comment]
Sounds like `febootstrap` can be used to create fedora or centos.  That should make this simple and similar to what is done for the Debian based systems.

**Comment by EnderNightLord-ChromeBook** [comment]
oh yeah... I'm building ubuntu 18.10 for userLAnd at the moment... this is quite easy they have some base images...

: https://github.com/EnderNightLord-UserLAnd-Projects/UserLAnd-Ubuntu-18.10-Project

**Comment by EnderNightLord-ChromeBook** [comment]
> Sounds like `febootstrap` can be used to create fedora or centos. That should make this simple and similar to what is done for the Debian based systems.

yes I tried that on my fedora machine...

**Comment by corbinlc** [comment]
We already support ubuntu in userland and have scripts for building everything already.

**Comment by EnderNightLord-ChromeBook** [comment]
XD right...

**Comment by EnderNightLord-ChromeBook** [comment]
I also thought of getting gentoo working... I have the rootfs for it... 

: https://github.com/EnderNightLord-UserLAnd-Projects/UserLAnd-Gentoo-Project

**Comment by corbinlc** [comment]
I hated supporting gentoo in the past (original GNURoot project), only because I never took the time to fully understand how their package filtering and installation works.  

I would love for someone who understands it better (possibly you) to create a good base image with things configured in a reasonable way for a new user to be able to get started.

**Comment by EnderNightLord-ChromeBook** [comment]
yes i'm getting better with building images... But need to get better with making the buildArch.sh...

I don't know much about branching... and detecting arches...

**Comment by corbinlc** [comment]
The architecture is always passed in as and argument.  See how the existing `buildArch.sh` files look at `$1` or `${1}`?  Those both mean the first argument provided to the script.

**Comment by EnderNightLord-ChromeBook** [comment]
so basically I used your script (it worked well got all the arches) and now I don't know how to let the buildArch.sh know which arch the device is on...

**Comment by EnderNightLord-ChromeBook** [comment]
> The architecture is always passed in as and argument. See how the existing `buildArch.sh` files look at `$1` or `${1}`? Those both mean the first argument provided to the script.

Ok I see that makes sense...

**Comment by corbinlc** [comment]
I am confused by that.  `buildArch.sh` is a script that is used for creating the `tar.gz` files and such.  That script I gave you for alpine linux needs to be modified to take the place of `buildArch.sh` for alpine, as they serve the same purpose.

**Comment by EnderNightLord-ChromeBook** [comment]
I know that...

**Comment by EnderNightLord-ChromeBook** [comment]
so basically... I just need to do what you said about that ( buildArch.sh files look at $1 or ${1} )
and add it in...

**Comment by corbinlc** [comment]
I think so.  There are a few more things done in the `buildArch.sh` scripts that probably need to be ported over to your script, but once you have the tar.gz files all built nicely...the rest is normally easy.

**Comment by EnderNightLord-ChromeBook** [comment]
thanks... But some of the arches are different

arm64 is now aarch64 and arm is now armhf...

**Comment by EnderNightLord-ChromeBook** [comment]
... I have just hash tagged some of the debain commands just In case...

: https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/blob/master/scripts/buildArch.sh

**Comment by corbinlc** [comment]
Right.  See how I handle the way it is  named different in different places...
```
case "$1" in
    arm) export DEBOOTSTRAP_ARCH=armhf
        ;;
    arm64) export DEBOOTSTRAP_ARCH=arm64
        ;;
    x86) export DEBOOTSTRAP_ARCH=i386
        ;;
    x86_64) export DEBOOTSTRAP_ARCH=amd64
        ;;
    all) exit
        ;;
    *) echo "unsupported arch"
        exit
        ;;
esac
```

**Comment by corbinlc** [comment]
So, the asset directory called `arm` is really `armhf` and such.

**Comment by EnderNightLord-ChromeBook** [comment]
I see

**Comment by EnderNightLord-ChromeBook** [comment]
I just made some changes

**Comment by EnderNightLord-ChromeBook** [comment]
armhf) export DEBOOTSTRAP_ARCH=armv7h
        ;;
    aarch64) export DEBOOTSTRAP_ARCH=arm64

**Comment by EnderNightLord-ChromeBook** [comment]
aarch64) export DEBOOTSTRAP_ARCH=aarch64

**Comment by corbinlc** [comment]
Cool.  Looks like what I had to do here: https://github.com/CypherpunkArmory/UserLAnd-Assets-Arch/blob/master/scripts/buildArch.sh

**Comment by EnderNightLord-ChromeBook** [comment]
yes basicly I thought that alpine is more like arch so I made some changes for it...

**Comment by EnderNightLord-ChromeBook** [comment]
I found a problem in archlinux

: x86) export ARCH_BOOTSTRAP_ARCH_OPT=i686

when its supposed to be

: x86) export ARCH_BOOTSTRAP_ARCH_OPT=i386

or am I incorrect?

**Comment by EnderNightLord-ChromeBook** [comment]
cool I will work on alpine today...

**Comment by EnderNightLord-ChromeBook** [comment]
what do you need me to finish on alpine?

**Comment by corbinlc** [comment]
For alpine, I need a `buildArch.sh` that can recreate the files you have put in the repo.  Right now, the file has just been copied from our Arch Linux script and not updated.  That is the biggest need.

**Comment by corbinlc** [comment]
I have added a Fedora and CentOS repository.

**Comment by corbinlc** [comment]
As for Arch Linux.  i686 is correct.  i386 is just a predecessor for that, but all 32bit intel processors have been i686 compatible for over a decade.  So if people say i386, they probably really are talking about i686 compatible processors.

**Comment by EnderNightLord-ChromeBook** [comment]
> For alpine, I need a `buildArch.sh` that can recreate the files you have put in the repo. Right now, the file has just been copied from our Arch Linux script and not updated. That is the biggest need.

This will be finished very soon... I have the plans.
