### ISSUE TITLE
Userland help!

### ISSUE THREAD

**Issue by m4rkito** [CypherpunkArmory/UserLAnd#469]
userland does not support non-standard ASCII characters, how can I solve it?

**Comment by EnderNightLord-ChromeBook** [comment]
you can create a pull request to add it...

**Comment by EnderNightLord-ChromeBook** [comment]
here is a tutorial to create a pull request:

1: find fork on the top of the page

2: add the additions

3: go back to userLAnd and go to pull requests and press Compare Across Forks. and find your user name

**Comment by corbinlc** [comment]
Not everyone is expected to be a programmer or otherwise know how to solve the issue they ran into.  We are not going to be one of those FOSS projects where people are told to fix it themselves or get other rough answers when they have a legitimate question.

**Comment by corbinlc** [comment]
@m4rkito can you give me an example of what doesn't work?  Remember, we need to be able to reproduce the situation that is not working.

**Comment by corbinlc** [comment]
I am closing this one, as we already have #456 and are waiting for more details from you there.
