### ISSUE TITLE
I need Update and fix all bugs

### ISSUE THREAD

**Issue by loverboy0004** [CypherpunkArmory/UserLAnd#477]
UserLand have many issues 
->pip is not working …
i post earlier with details
->npm is not able to install any package give error see blow…
npm WARN saveError ENOENT: no such file or directory, open '/home/h
arry/package.json'
npm notice created a lockfile as package-lock.json. You should comm
it this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/harr
y/package.json'
npm WARN harry No description
npm WARN harry No repository field.
npm WARN harry No README data
npm WARN harry No license field.
->python colorama and ctype files give errors…
same error as i use pip
->auto crash …
after sometime connectbot give error connection close .. also give same error when i received any call or sms 
-> please update GNURoot as well because ot was the best ever …
GNURoot not supporting android oreo please do nothing with UserLand because it has many bug it take at least a month for new update only if the creator is agreed but best way for him to update GNURoot and Problem solve

**Comment by MatthewTighe** [comment]
Please post individual bugs following our issue template.
