### ISSUE TITLE
Ubuntu Won't Install on Mi A2 Running Oreo or Pie

### ISSUE THREAD

**Issue by woodydeck** [CypherpunkArmory/UserLAnd#478]
Debian installs, but for some reason, Ubuntu hangs randomly and won't install. I've reset the phone, reinstalled many times, but can't get it to work.

There are a couple symptoms: 

1) On initialization, it downloads the packages and randomly toggles between packages out of order. So it will toggle between package 4 and 13 and 2 and 6. 

2) When starting a process, it starts off as normal, but then beachballs. It never starts. You also can't kill the process during this time.

3) If you toggle the logs, the beachball goes away and you can try unsuccessfully again.

**Comment by corbinlc** [comment]
Maybe open up one issue per thing of interest.  For example 1) Dropbox support, 2) RStudio app.  Then this issue can just be about Ubuntu not working on an Mi A2.

**Comment by woodydeck** [comment]
Np, removed the irrelevancies. However, if I did that first it gets called spam. :-)

**Comment by woodydeck** [comment]
F-Droid Version 2.1.0? Can I install this simultaneously to the current version in the play store?

I haven't been able to successfully image my Pie device, and I don't have another Android. I am currently using it to run R scripts all day and I don't want to undo the work I did until I get back from my business trip. It's my only way to run R all day currently.

**Comment by corbinlc** [comment]
We never got a device that showed this specific issue and we have made many changes since last January. Closing this, but please reopen it if this problem still occurs in the latest version.
