### ISSUE TITLE
on host auntentification

### ISSUE THREAD

**Issue by olgaklischuk** [CypherpunkArmory/UserLAnd#483]
Hello! I have installed UserLAnd app and installed all packages for RGUI, but now it requested to turn on to local host. Which host I can use as foder directory for finishing instalment of R and which password I must use when use userland host. Thank you for feedback!

**Comment by corbinlc** [comment]
We never received any additional info and cannot proceed with this issue.  As such, I am closing this issue.  Please reopen it with more details if you are still having an issue.
