### ISSUE TITLE
Please add option for real root access

### ISSUE THREAD

**Issue by bencejuhaasz** [CypherpunkArmory/UserLAnd#487]
All other full root chroot apps stopped working on android 9, this is the only one working. It would be great if I could use a full chroot with root access on android 9 too. If you provide description about the containerization method, maybe I can try replace it myself, but I don't know this alternative "non-root chroot method" yet.

**Comment by MatthewTighe** [comment]
Please update your issue to follow the issue template or we will close the issue within 3 business days.

**Comment by bencejuhaasz** [comment]
I've found other apps(nethunter) for chroot, handling FBE was the problem,  simply using your app with root wouldn't solve it, you can close it
