### ISSUE TITLE
Add more Apps

### ISSUE THREAD

**Issue by nightpavell** [CypherpunkArmory/UserLAnd#498]
# Really love your app
It's very useful - running GIMP through it without any problems on my Note 9, please add support of Inkscape (vector graphics editor) and GMedit (code editor for game maker; it has build for Linux) - and I`ll be so happy)))

**Comment by corbinlc** [comment]
Those can currently be installed via `apt` or `pacman` or whatever the appropriate package manager is.  If you would like to add an app, and have the skill please see this https://github.com/CypherpunkArmory/UserLAnd/wiki/Adding-an-App .  If you are unable to do this, those seem like reasonable requests, though I am not sure when we will add them.

**Comment by EnderNightLord-ChromeBook** [comment]
I will have a look at adding a few of your requests

**Comment by EnderNightLord-ChromeBook** [comment]
Ok mate pull request in for ya so inkscapes on the way.

**Comment by nightpavell** [comment]
woa, that's nice)

**Comment by EnderNightLord-ChromeBook** [comment]
your welcome you can check out the pull here.

: https://github.com/CypherpunkArmory/UserLAnd-Assets-Support/pull/85

also check out some of my other projects

: https://github.com/EnderNightLord-UserLAnd-Projects

**Comment by corbinlc** [comment]
I will test this out and add it if it all looks good.  Will probably be first thing next week.

**Comment by EnderNightLord-ChromeBook** [comment]
Thanks Corb

**Comment by EnderNightLord-ChromeBook** [comment]
ok night... inkscape has been added!

**Comment by nightpavell** [comment]
wow, thanks! I tested it few days ago, seems to working well)

**Comment by EnderNightLord-ChromeBook** [comment]
glad to be of service.

**Comment by corbinlc** [comment]
If GMEdit is still of interest please file a new issue.  I am closing this as there has been no conversation or action related to it in quite a while.
