### ISSUE TITLE
Finishing Up Alpine

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#503]
the last touches are being added so alpine will be here soon

![image](https://user-images.githubusercontent.com/31677287/50791296-4e9b5b00-1326-11e9-9ff4-06ede663356b.png)

**Comment by MatthewTighe** [comment]
Cool

**Comment by EnderNightLord-ChromeBook** [comment]
...

**Comment by EnderNightLord-ChromeBook** [comment]
Ok Matthew things should be sorted
