### ISSUE TITLE
Reports Of Android 9 Not Working

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#504]
# Describe the bug

userLAnd on android nine (pie) does not work with these things:

1. lauching a desktop with VNC

or 

2. launching apps

# Steps to reproduce the behavior:

install desktops 

try to launch apps

# Device Information

Device: All devices with android 9
Android Version: 9 pie
UserLAnd Version: 2.0
Whether the device is rooted: no
Whether the device is running LineageOS: Just Android (at the moment)

**Comment by corbinlc** [comment]
This is not accurate.  Our team has three devices running some flavor of Android 9.0 and on those devices things work well.  We would need more specific information for this issue to help us.  Are you personally seeing this issue and have some information that could help us?

**Comment by corbinlc** [comment]
Looking into this further, we get about 10% of our installs from Android 9.0 users.  Those users have about the same retention rate as users for other versions of Android (actually higher than average).  I don't think there is something systematically broken on Android 9.

**Comment by gmkbenjamin** [comment]
I'm having the same issue. It worked once or twice then doesn't want to work anymore. Tried reinstalling the app. The app hangs at starting service.

**Comment by corbinlc** [comment]
@gmkbenjamin Please start a new issue and follow the template seen here https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D
This issue was closed and never had any specific info in it.

**Comment by klaus7** [comment]
I had the same issue, could resolve it by deinstalling and reinstalling bVNC. Maybe this information is helpful for someone else..

**Comment by gutclone** [comment]
I have two Android 9
I'm having trouble working on uesrland
The problem is the failure to extract the files of the system

**Comment by gutclone** [comment]
I have two Android 9
I'm having trouble working on uesrland
The problem is the failure to extract the files of the system

**Comment by gutclone** [comment]
Help help mi
![received_3500338726658608](https://user-images.githubusercontent.com/47323188/63018638-434a7800-be91-11e9-8243-24a45e3a0500.jpeg)

**Comment by EnderNightLord-ChromeBook** [comment]
If you are in the DEV version try and switch back to stable. Then try again. Try clearing out support files and other linux operating systems, or maybe try a different operating system and see if that works.

**Comment by decodergit** [comment]
I had the same issue. But it us ok, if I start ssh session and manually start vncserver command.
