### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Kymonlucky** [CypherpunkArmory/UserLAnd#505]
When I opem the debian filesystem with ssh  with userland default terminal this is what it says:

/data/data/tech.ula/files/support/dbclient: Connection to username@localhost:2022 exited: Connect failed: Connection refused

[Process completed (code 1) - press Enter]

### Describe the bug
_**/data/data/tech.ula/files/support/dbclient: Connection to username@localhost:2022 exited: Remote closed the connection**_

Connection keeps closing or crashing when I tried to reconnect.

### Steps to reproduce the behavior:

When lxde is about to finish installing it says connection lost and when I tried to reconnect.

### Device Information

Device: Huawei Nova 2i
Android Version: 8.0
UserLAnd Version 2.1.0
Rooted device? No
LineageOS? No

### Additional context
When I tried to delete the filesystem and reinstall new, everything is fine but after a few minutes it will back again to a connection lost.

### Proot_Debug_Log

[H[J[13067] Jan 09 14:31:36 Running in background
[13134] Jan 09 14:31:39 Child connection from 127.0.0.1:44292
[13134] Jan 09 14:31:43 Password auth succeeded for 'username' from 127.0.0.1:44292
./tracee/event.c:517: int handle_tracee_event(Tracee *, int): assertion "!IS_IN_SYSENTER(tracee)" failed

**Comment by Kymonlucky** [comment]
I try it too but still doesnt worj

**Comment by EnderNightLord-ChromeBook** [comment]
ok... did you try a different OS? (ubuntu, kali, archlinux, alpine-testing)

**Comment by Kymonlucky** [comment]
I tried 2 Os debian and ubuntu

**Comment by EnderNightLord-ChromeBook** [comment]
try kali and arch

**Comment by Kymonlucky** [comment]
Will do it, thanks!. But I just wanna add that "Connection Refused" Happens
when I install lxde or any desktop environment

**Comment by Kymonlucky** [comment]
When Lxde is about to finish installing It always crashed and when I tried
to reconnect it says "Connectio Refused"

**Comment by EnderNightLord-ChromeBook** [comment]
Hmm Gimme A Few Hours To Figure Out.

**Comment by Kymonlucky** [comment]
Ok Thanks!

**Comment by Kymonlucky** [comment]
I tried to make a new filesystem again and tried to install lxde again but when Lxde is about to finish installing it says "Connection Lost" and when I reconnect it says:

ata/data/tech.ula/files/support/dbclient: Caution, skipping hostkey check for localhost

username@localhost's password:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

/data/data/tech.ula/files/support/dbclient: Connection to username@localhost:2022 exited: Remote closed the connection

[Process completed (code 1) - press Enter]

**Comment by corbinlc** [comment]
Let's back up.  Can you @Kymonlucky use the provided issue template and provide more info?  The template included what device you are using and what version of Android you are using and things like that.  
After that is provided we will have to see why the ssh server is being prematurely killed.

**Comment by corbinlc** [comment]
I am guessing you have a relatively new Huawei device.

**Comment by Kymonlucky** [comment]
Describe the bug
/*data/data/tech.ula/files/support/dbclient: Connection to
username@localhost:2022 exited: Remote closed the connection*

Connection keeps closing or crashing when I tried to reconnect.

*Steps to reproduce the behavior:*

When lxde is about to finish installing it says connection lost and when I
tried to reconnect.

*Device Information*

Device: Huawei Nova 2i
Android Version: 8.0
UserLAnd Version 2.1.0
Rooted device? No
LineageOS? No

Additional context
When I tried to delete the filesystem and reinstall new, everything is fine
but after a few minutes it will back again to a connection lost.

**Comment by Kymonlucky** [comment]
### Describe the bug
_**/data/data/tech.ula/files/support/dbclient: Connection to username@localhost:2022 exited: Remote closed the connection**_

Connection keeps closing or crashing when I tried to reconnect.

### Steps to reproduce the behavior:

When lxde is about to finish installing it says connection lost and when I tried to reconnect.

### Device Information

Device: Huawei Nova 2i
Android Version: 8.0
UserLAnd Version 2.1.0
Rooted device? No
LineageOS? No

### Additional context
When I tried to delete the filesystem and reinstall new, everything is fine but after a few minutes it will back again to a connection lost.

**Comment by MatthewTighe** [comment]
Providing us with a PRoot debug log would likely be helpful for this issue. You can turn on PRoot debug logging in the settings page of the UserLAnd app. After turning it on, perform the steps you normally would that lead to the crash. You can then find the PRoot debug log at `/mnt/sdcard/PRoot_Debug_Log`.

**Comment by corbinlc** [comment]
This is a known issue with Huawei devices.  It is proving to be difficult to solve.  Please see #398.  I can already replicate that same issue and need to figure out the best solution.  As this is known and duplicate.  I am closing this issue and I encourage you to watch how #398 progresses.

**Comment by MikeTermux1** [comment]
i've tried a lot but what i found is, go to your notification bar, scroll down to find tech.ula session, and press "Acquire Wakelock"..and now, your can even go to other app and the remote aa what we can that i dont know, wont stop the session.
