### ISSUE TITLE
python 2.7 multiprocessing SemLock fails

### ISSUE THREAD

**Issue by abthefish** [CypherpunkArmory/UserLAnd#507]
# Describe the bug
-----
From "/usr/lib/python2.7/multiprocessing/synchronize.py"
sl=self._semlock=multiprocessing/synchronize.py
OSError: [Errno 13] Permission denied
-----
Running debian ssh session, connected through vncserver with xfce4 wm.
Non-usrland solutions often call for creation of fixed permissions on /dev/shm.
Userland debug log shows valid proot bind of "/dev/shm", permissions 'drwxrwxrwt.'
Other apps (ssh, firefox) using /dev/shm fine.
Fails as 'non-root' user, with or without sudo.

# Steps to reproduce the behavior:
Install userland debian ssh, vncserver, python, pip, (etc...)
Run any example code using python2 multiprocessing, such as:
https://stackoverflow.com/questions/34764535/why-cant-matplotlib-plot-in-a-different-thread
e.g. python mprocDemo.py
See Traceback error.

# Device Information

Device:  Pixel XL 2
Android Version: 9.0
UserLAnd Version [1.0.3]
Python Version [2.7.13]
Rooted device? No
LineageOS? No

# Additional context
Working with a Tkinter python app, so I haven't stripped it outside of a vnc graphical env.  I can if necessary.

# Gratitude
Thank you.  Userland is a wonderful piece of work!

**Comment by corbinlc** [comment]
Anything requiring semaphores (uses semget system call) does not work currently.  Some experimentation has been done so far on how to solve that.   It is one of the more difficult issues for us to solve, so it might be a while.

**Comment by abthefish** [comment]
Thank you corbinlc.  This confirms what I (unfortunately) found with additional searches.
Closing this issue, though I'll include a few bits below in case they are useful to anyone landing here:

Simplified code to re-create the issue:
-----
#!/usr/bin/env python
import multiprocessing

def main():
    #Create a queue to share data between process
    q = multiprocessing.Queue()

if __name__ == '__main__':
    main()
-----

Issuing the code via Termux sheds some light (confirmed by corbinlc):

"ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770."

leading to:
https://github.com/termux/termux-packages/issues/570
"""
fornwall commented on Nov 30, 2016:
Android does not support sem_open() or related functions, so there is not much to do from the Termux side here - support for multiprocessing on Python would need upstream work.
"""

For the time being,  moving my  code  from 'multiprocessing' to 'threading' seems a valid path.
Thanks again for your answer and making our phones capable of real work!
