### ISSUE TITLE
openssh-server support?

### ISSUE THREAD

**Issue by Merith-TK** [CypherpunkArmory/UserLAnd#508]
OpenSSH support, i dont like dropbear, never have had a good expirience with it.

# Describe the solution you'd like 
I want for ``openssh-server`` to be working properly, like a option when you setup a SSH container, where it gives you two checkboxs, to pick between openssh and dropbear

**Comment by corbinlc** [comment]
I understand your request to have a choice of `dropbear` vs `openssh-server`, but that will have fairly low priority for right now.  We will continue starting `dropbear` until we get some bigger issues solved.  That said, this is how you could start `openssh-server` as well.

```
apt update
apt install -y nano

apt install -y openssh-server
nano /etc/ssh/sshd_config
Modify, these two things...
Port 22 to 2223
UsePrivilegeSeperation no

service ssh restart
```

**Comment by monkeyfork** [comment]
I'm running the ubuntu image on pixel2 in GUI (twm) mode.  I'd like to also have ability to ssh in so was trying the above to get openssh-server to work.  So far no joy.  I _think_ "UsePrivilegeSeperation" should be "UsePrivilegeSeparation" but still no joy either way, with error saying UsePrivilegeSeperation (either spelling) is bad option.  Before I got to that error there was issue of having to create /run/sshd dir.    Any ideas?

**Comment by DovaMerith** [comment]
> I'm running the ubuntu image on pixel2 in GUI (twm) mode. I'd like to also have ability to ssh in so was trying the above to get openssh-server to work. So far no joy. I _think_ "UsePrivilegeSeperation" should be "UsePrivilegeSeparation" but still no joy either way, with error saying UsePrivilegeSeperation (either spelling) is bad option. Before I got to that error there was issue of having to create /run/sshd dir. Any ideas?
> -edit- some of above is bogus, i had another misspelling that i injected, after correcting now getting option recognized. This is what i see when I restart ssh;
> -------- scroll from "service ssh restart" -------
> /etc/ssh/sshd_config line 127: Deprecated option UsePrivilegeSeparation
> Could not load host key: /etc/ssh/ssh_host_rsa_key
> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
> Could not load host key: /etc/ssh/ssh_host_ed25519_key
> 
>     * Restarting OpenBSD Secure Shell server sshd                                  /etc/ssh/sshd_config line 127: Deprecated option UsePrivilegeSeparation
>       Could not load host key: /etc/ssh/ssh_host_rsa_key
>       Could not load host key: /etc/ssh/ssh_host_ecdsa_key
>       Could not load host key: /etc/ssh/ssh_host_ed25519_key
>       -------- end of scroll from "service ssh restart" --------------------
>       However, even with those complaints, 'ps aux' does show a sshd now.  but when I try to login
>       with "ssh -l myUserName -p 2223 10.0.0.33"
>       i get; "Connection closed by 10.0.0.33"
>       ( i can VNC into UserLAnd on this nexus 5x so ip is good)
> 
> 
> Sorry for earlier corrupt reporting. Any ideas?

Try
``ssh <user>@<ip> -p 2223``
I have not tried this yet, 
and the `-i` i beleive is specifically for ssh-keys (i may be wrong on that)

**Comment by monkeyfork** [comment]
no joy on that method of trying to login via ssh on UserLAnd with added
openssh-server sshd daemon.
btw, the option I was using was "-l" (lower case L), not "-i" (lower case
EYE)

**Comment by AndrewScibek** [comment]
Can you do your ssh command with -vvv?

**Comment by monkeyfork** [comment]
yup.  this is from machine that i use to ssh to lots on local LAN and all
sorts of remotes;
------------------ debug from -vvv when attempt connect to UserLAnd on
pixel2 (ANDROID 8.1) from a xubuntu boxen on same switch
--------------------------
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to 10.0.0.33 [10.0.0.33] port 2223.
debug1: Connection established.
debug3: Incorrect RSA1 identifier
debug3: Could not load "/home/MyUserName/.ssh/id_rsa" as a RSA1 public key
debug1: identity file /home/MyUserName/.ssh/id_rsa type 1
debug1: identity file /home/MyUserName/.ssh/id_rsa-cert type -1
debug1: identity file /home/MyUserName/.ssh/id_dsa type -1
debug1: identity file /home/MyUserName/.ssh/id_dsa-cert type -1
debug1: identity file /home/MyUserName/.ssh/id_ecdsa type -1
debug1: identity file /home/MyUserName/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/MyUserName/.ssh/id_ed25519 type -1
debug1: identity file /home/MyUserName/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.11
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.6p1
Ubuntu-4ubuntu0.1
debug1: match: OpenSSH_7.6p1 Ubuntu-4ubuntu0.1 pat OpenSSH* compat
0x04000000
debug2: fd 3 setting O_NONBLOCK
debug3: put_host_port: [10.0.0.33]:2223
debug3: load_hostkeys: loading entries for host "[10.0.0.33]:2223" from
file "/home/MyUserName/.ssh/known_hosts"
debug3: load_hostkeys: loaded 0 keys
debug1: SSH2_MSG_KEXINIT sent
Read from socket failed: Connection reset by peer
------------------------ end of debug info
----------------------------------

Thanks for looking,
dj

**Comment by AndrewScibek** [comment]
My quick guess would be to try this https://stackoverflow.com/a/17138131

**Comment by monkeyfork** [comment]
Andrew, looks like dpkg-reconfigure can't determine the run-level;
--------- debug from running dpkg-reconfigure openssh-server -----------
doug@localhost:~/.ssh$ dpkg-reconfigure openssh-server
/usr/sbin/dpkg-reconfigure must be run as root
doug@localhost:~/.ssh$ sudo dpkg-reconfigure openssh-server
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based
frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm
line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
invoke-rc.d: could not determine current runlevel
-------------- end of debug msg--------------------------
any other ideas?

Cheers
dj

**Comment by MatthewTighe** [comment]
Did you try `sudo dpkg-reconfigure openssh-server`?

**Comment by monkeyfork** [comment]
yup, that's shown in 3rd line of debug

**Comment by AndrewScibek** [comment]
@monkeyfork I missed `/etc/ssh/sshd_config line 127: Deprecated option UsePrivilegeSeparation` earlier. 
In OpenSSH 7.5 they removed the ability to use that config option. It is needed to be able to run it within PROOT(@corbinlc knows why much better than I do). You can install OpenSSH 7.4 or earlier to get around this issue. 

In Debian the default is 7.4p1 and i was able to authenticate and connect to see the MOTD. I was having issues getting the shell to appear but i assume that is just another config(/etc/profile) issue.

**Comment by AndrewScibek** [comment]
Another question we have is what features do you want that openssh has that dropbear doesn't have? We have had a few requests to include openssh and would like to know your usecase.

**Comment by monkeyfork** [comment]
dropbear is an unknown for me.  I'm using the ubuntu image for UserLAnd in
the GUI (TWM) mode.  It appears in the install method that the image can be
made to run in either GUI __OR__  SSH.  I certainly like the GUI (now that
I've learned TWM) especially when VNC in to my nexus5x from my LAN.
however sometimes I'll need to SSH in from embedded hosts that are TTY
only, so I want to have SSH capability also.  I joined this thread when I
saw someone requesting a howto for openssh-server (which i'm very familiar
with and trust).  I'd be very willing to try dropbear but I need a howto
for my already GUI environment.

Additionally, I don't want to do anything that would preclude the use of
SSHFS to mount remote filesystems if you get fuse working.  SSHFS is
extremely helpful to me and I'd like to see it work on UserLAnd but I have
zero idea how hard that is to accomplish.

btw... my nexus5x is basis for an always on vehicle computer that is
sometimes 4G, sometimes wifi-LAN connected.  My primary phone is a pixel2
and I'm trying same UserLAnd tweaks on that platform.

**Comment by AndrewScibek** [comment]
Heres how we start it. https://github.com/CypherpunkArmory/UserLAnd-Assets-Debian/blob/master/assets/all/startSSHServer.sh 

You just need to do the setup once. Afterwards you just need to run `dropbear -E -p 2022`

**Comment by monkeyfork** [comment]
Thanks will try very soon and report.
BTW, I've got notification on my pixel2 that ANDROID 9 is ready to
install.  Do you have any idea if UserLAnd will still work after that?

**Comment by monkeyfork** [comment]
I removed openssh-server from my ubuntu UserLAnd GUI instance and tried the
"sudo /support/startSSHServer.sh" which executes without error.  ps aux |
grep dropbear shows that an instance of dropbear is running with same
options as shown in script.  attempt to connect from
LAN fails;
(xenial)pi@localhost:~$ ssh -vvv doug@10.0.0.33 -p 2222
OpenSSH_7.2p2 Ubuntu-4ubuntu2.5, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug2: resolving "10.0.0.33" port 2222
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 10.0.0.33 [10.0.0.33] port 2222.
debug1: connect to address 10.0.0.33 port 2222: Connection refused
ssh: connect to host 10.0.0.33 port 2222: Connection refused

I also tried to connect from inside the phone with
ssh doug@10.0.0.33 -p 2222
same result.

**Comment by AndrewScibek** [comment]
I think you are connecting to the wrong port

Dropbear starts on port 2022

**Comment by corbinlc** [comment]
Notice that your port number `ssh doug@10.0.0.33 -p 2222` does not match the port number in the script `2022`

**Comment by monkeyfork** [comment]
ah ha (mumble mumble)  just a test to see if you're reading.. in other
words, my bad.
Yup, works fine now, many thanks.
(question about do we expect that UserLAnd will continue to work on ANDROID
9 still stands, do you know I will be first one?)

**Comment by MatthewTighe** [comment]
Yes, UserLAnd runs on Android 9. My daily driver is a pixel 2 XL with Android 9 and is my primary testing device.

Seems like this issue is resolved, so I'm going to close it.

**Comment by SoumyadeepChatterjee96** [comment]
I just downloaded Userland and chose Debian and when I installed Openssh and the whole default setup was completed I tried starting the service but it returns with 'sshd re-exec requires execution with an absolute path'.
Please Help!

**Comment by Merith-TK** [comment]
Run `which sshd` so you know it's absolute path, and then run the command using that patg

**Comment by corbinlc** [comment]
I should have closed this one a while ago.  openssh-server now works.  @SoumyadeepChatterjee96  that is normal behavior (UserLAnd or not), and @Merith-TK is 100% correct.  You need to use the full path `/path/to/sshd` instead of `sshd`.

**Comment by xaser3d** [comment]
Unable to instal or update python 3.6.9-1  18.04 freezes everytime i try to update or install packages

**Comment by linkazoo** [comment]
@corbinlc Bumping into this thread and trying to use openssh-server alongside dropbear to connect my phone from my laptop, when you said "openssh-server now works", did you refer to use openssh-server 7.4 with "UsePrivilegeSeperation no"? or you meant it works generally for newer version without option "UsePrivilegeSeperation"?

**Comment by efa** [comment]
any news on support of current openssh-server?
Won't start with default "/etc/ssh/sshd_config".
The proposed workaround work but its still say "Deprecated option UsePrivilegeSeparation" on startup.
Debian 10
