### ISSUE TITLE
Could not inslall Rstudio free server for Linux

### ISSUE THREAD

**Issue by olgaklischuk** [CypherpunkArmory/UserLAnd#509]
#Troubles with installing R version 3.5 and R studio via UserLAnd app
 
I have some troubles with installing R version 3.5 and R studio via
UserLAnd app on my tablet Asus ZenPad 8.0 with Android version 7.0 and
with 4 cores processor MediaTek MT8163, 64bit and with free space of
3,84 Gb. When I write command via VNC client/server model in Ubuntu
server:

`#user@localhost$ apt-get update
user@localhost$ apt-get install r-base r-base-dev`
I have received the answer:
E:Can't unlock administration directory
When I have tried installed new version of Rstudio server fo Linux by clicking the command:
`# user@localhost$ wget https://download2.rstudio.org/rstudio-server-1.1.463-amd64.deb`
obtained next error:
bash: wget: command not found

I have thought, that UserLAnd created a working directory on my tablet
filesystems, but it didn't so.
Please tell me some advice on finalizing the process of creating
filesystems of Ubuntu or how by command code create the filesystem for
R 3.5 app and R.studio of the version 1.1.463 released in 2018-10-29.
This installment I want to do for educational and scientific purposes!
For future precious advices very thankfull to you!

# Device Information

Device: [Asus ZenPad 8 ]
Android Version: [ Nougat, 7.0]
UserLAnd Version [ 0.1.3]
Device is rooted

**Comment by MatthewTighe** [comment]
Can you confirm that you're running UserLAnd version 0.1.3? That version is massively outdated.

**Comment by olgaklischuk** [comment]
Yes, I can.

**Comment by Herzogs** [comment]
when you use the apt statement you must put sudo forward and in wget it puts forward BusyBox and then the wget would take you

**Comment by MatthewTighe** [comment]
I would also recommend upgrading to the latest stable or beta version.

**Comment by EnderNightLord-ChromeBook** [comment]
yeah I must say that is old...

**Comment by corbinlc** [comment]
Regardless of what version you are running, we install a very minimal filesystem.  If a basic command is not found, like `wget`, you will need to `sudo apt update && sudo apt install wget` and that should do it for you.

**Comment by olgaklischuk** [comment]
Thank you very much for all tips: all were successfully performed. The problem was that I haven't put ahead <sudo> and have not initially installed the <wget> package. But know I have a problem when I perform the next command for installing Rstudio 64bit server:
<user@localhost$sudo gdebi rstudio-server-stretch-1.1.463-amd64.deb>
then I obtained the error message:
<gdebi error, file not found: rstudio-server-stretch-1.1.463-amd64.deb>.
Do I have to address my question to Rstudio developers or this error appeared due to the absence of specific commands?
Than you very much!

**Comment by corbinlc** [comment]
do you have that file `rstudio-server-stretch-1.1.463-amd64.deb` in your current directory?

**Comment by olgaklischuk** [comment]
No, I do not. So I must install this file before Rstudio server 1.1.463 64 bit, must I?

**Comment by corbinlc** [comment]
Never used Rstudio, but I think you need to do that `wget` command you referenced in your issue.

**Comment by olgaklischuk** [comment]
Excuse, me please, by this code I can get the working directory in Debian, can I:
`user@localhost$ sudo apt-get cd folder-path`.

**Comment by MatthewTighe** [comment]
Apps installed manually on the filesystem will not appear in the apps list in the UserLAnd.

**Comment by MatthewTighe** [comment]
If your posted issue is resolved, please close this issue ticket. If you would like RStudio added to apps, open a new "Feature Request" issue.
