### ISSUE TITLE
Illegal State!

### ISSUE THREAD

**Issue by yunus70** [CypherpunkArmory/UserLAnd#513]
I have to reinstall debian every week. What is that mistake.
![screenshot_2019-01-11-10-02-23](https://user-images.githubusercontent.com/21973784/51024163-092a9800-1589-11e9-9bf0-4ce433ca82ea.png)

**Comment by MatthewTighe** [comment]
Please update your issue to follow the `Bug Report` issue template, or it will be closed in the next week.

**Comment by MatthewTighe** [comment]
[Here](https://github.com/CypherpunkArmory/UserLAnd/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by corbinlc** [comment]
@yunus70 When you tried to file a new issue, were you not presented with the template?  When I file new issues, it provides me the template automatically.  @MatthewTighe, I am just asking because I am curious why people ask what the template is, when you request they follow it.

**Comment by MatthewTighe** [comment]
@corbinlc I assume because there's no way to view it without posting a new issue, or unless they know where to look in the repository for the markdown file.
