### ISSUE TITLE
Run the i386 environment on the aarch64

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#516]
My problem is that I want to run an i386 or x86 environment on the aarch64 environment. Is this possible? Especially as there are programs that do this, for example [**ExaGear Windows Emulator**][e], which provides an i386 environment on [**raspberry pi 2 & 3**][rpi] that works with ARM64 processor ...

**Required:** What I want is to install [**wine**][w] on a 32-bit environment ...

Thanks ...

[e]: https://eltechs.com/product/exagear-desktop/
[w]: https://www.winehq.org
[rpi]: https://www.raspberrypi.org

**Comment by EnderNightLord-ChromeBook** [comment]
it is possible but only in emulation/ qemu... try limbo x86 emulator uses isos and images...

**Comment by foodmaher** [comment]
@EnderNightLord-ChromeBook

But QEMU emulator are very slow .. 😫😫

As I mentioned earlier, there are programs like exagear running the Linux i386 or i686 environment on Android or Raspberry pi very quickly. How do they do that?

**Comment by foodmaher** [comment]
See how the gear windows emulator developed using the i386 Linux environment on Android to run Wine x86 on Android and it works quickly unlike Qemu emulators
 ---
! [photo1](http://d.up-00.com/2019/01/154728750796721.png)
! [photo 2](http://d.up-00.com/2019/01/154728779426451.png)
