### ISSUE TITLE
Extracting error  ./var/run

### ISSUE THREAD

**Issue by nesteroff561** [CypherpunkArmory/UserLAnd#517]
Hi everyone. sorry for my English, it's not my native language. so, I was faced with the problem of unpacking ./var / run on my Xiaomi Redmi 6 (4GB\64GB). I waited all night for it to unpack, but no, it's still unpacking. root was not obtained, however, on my old Huawei MYA-U29 everything works fine. I tried from re-creating the container to flashing my phone. my phone runs on android 8.1.0, help me. this is the best application to run Linux without root that doesn't work unfortunately on my new phone.

**Comment by MatthewTighe** [comment]
Can you provide a PRoot debug log? You can see how to do that in our [wiki](https://github.com/CypherpunkArmory/UserLAnd/wiki/Generating-PRoot-Debug-Logs).

**Comment by xqtr** [comment]
Same model, same problem. The PRoot debug log:
`[H[Jproot warning: can't sanitize binding "/data/user/0/tech.ula/files/3/support/": No such file or directory
proot warning: can't sanitize binding "/data/user/0/tech.ula/files/3/support/nosudo": No such file or directory
proot warning: can't sanitize binding "/data/user/0/tech.ula/files/3/support/userland_profile.sh": No such file or directory
proot warning: can't sanitize binding "/data/user/0/tech.ula/files/3/support/ld.so.preload": No such file or directory
proot warning: can't sanitize binding "/data/user/0/tech.ula/files/3/tmp": No such file or directory
proot warning: can't canonicalize /data/user/0/tech.ula/files/3/support/: No such file or directory
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot error: can't create temporary directory: No such file or directory
proot info: Please set PROOT_TMP_DIR env. variable to an alternate location (with write permission).
proot error: can't create glue rootfs
proot info: binding = /data/data/tech.ula/files/support/version:/proc/version
proot info: binding = /data/data/tech.ula/files/support/uptime:/proc/uptime
proot info: binding = /data/data/tech.ula/files/support/stat8:/proc/stat
proot info: binding = /storage/emulated/0:/sdcard
proot info: binding = /:/host-rootfs
proot info: binding = /proc/12649/mounts:/etc/mtab
proot info: binding = /mnt
proot info: binding = /data
proot info: binding = /proc
proot info: binding = /dev
proot info: binding = /sys
proot info: binding = /data/data/tech.ula/files/3:/
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot error: '/support/extractFilesystem.sh' not found (root = /data/data/tech.ula/files/3, cwd = /data/data/tech.ula/files/3, $PATH=(null))
fatal error: see `proot --help`.
`

**Comment by corbinlc** [comment]
Are people still getting this issue with this device?

**Comment by xqtr** [comment]
> Are people still getting this issue with this device?

didn't try again... and couldn't wait. I am using termux and its fine for what i want.

**Comment by IJOSHANDROIDYT** [comment]
I still have the same device and never charge during this process of extraction in ./var/run , quisiera usar Linux en mi Android, pues lo quisiera para hacer un trabajo remoto de mi escuela, me dificulta usar mi computadora y este dispositivo (Xiaomi Redmi 6). Please if someone can help me support even in termux.

**Comment by corbinlc** [comment]
If people are still hitting this issue, please open a new issue and provide a new PRoot log.  We had some recent changes that seems to be helping many Redmi device users.
