### ISSUE TITLE
Kill sessions before deleting

### ISSUE THREAD

**Issue by keaneokelley** [CypherpunkArmory/UserLAnd#52]
https://github.com/CypherpunkArmory/UserLAnd/blob/830a782835b84becdaa8c46f3724b5fbd5716ce9/app/src/main/java/tech/ula/SessionListActivity.kt#L263

Sorry for all the issues today, just trying to help out and didn't think a one line addition was worth a PR.

Sessions that are deleted will still run until forcefully closed. Add `stopService(session)` before the above line to ensure the session is killed before it is deleted.

**Comment by MatthewTighe** [comment]
Feel free to PR for whatever. We're still working on figuring out exactly how we want our github workflow to function, but if you create a PR for something please create an issue for it first.

**Comment by MatthewTighe** [comment]
Resolved by #51
