### ISSUE TITLE
Move file from mobile storage

### ISSUE THREAD

**Issue by zeeshan9128** [CypherpunkArmory/UserLAnd#526]
I want to know how to move a follow from mobile storage to the userland rep

**Comment by MatthewTighe** [comment]
Please update your comment to follow the `Help` issue template or it will be removed within the week.

**Comment by Herzogs** [comment]
What you want to ask is how to move a file from the SD card to the HOME? If so, you would have to do `mv /sdcard/file.txt $HOME`
