### ISSUE TITLE
Request package

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#527]
The libffi-dev package is required to complete the Forest-SDK package install procedures to run the QVM or so-called quantum virtual machine on the userland application the your own     

**Note:** When you try to install the
`sudo ./forest-sdk-2.2.1-linux-deb.run` 
this error occurs
    
    The following packages have unmet dependencies: 
    libffi-dev : Depends: libffi6 (= 3.2.1-6) but 3.2.1-9 is to be installed
    E: Unable to correct problems, you have held broken packages. 
    *** Please run 'apt-get update' before installation ***

**Comment by Herzogs** [comment]
You install libffi-dev?

**Comment by foodmaher** [comment]
@Herzogs I have a problem because of the libffi-dev package and it is listed above. I do not know why. But tell me there is a broken package or the like. Do you know what the solution is?

**Comment by foodmaher** [comment]
@Herzogs 
**When you try to install them individually, this problem appears ..**
     root@localhost:/# sudo apt install libffi-dev
      Reading package lists... Done
      Building dependency tree
      Reading state information... Done
      Some packages could not be installed. 
      This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
     The following information may help to resolve the situation:

     The following packages have unmet dependencies:
     libffi-dev : Depends: libffi6 (= 3.2.1-6) but 3.2.1-9 is to be installed
     E: Unable to correct problems, you have held broken packages.

**Comment by Herzogs** [comment]
In Ubuntu install libffi-dev is OK, do you use Kali?
