### ISSUE TITLE
VNC session crashes

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#53]
When I'm opening VNC session I'm getting message "Limbo crashed" after few retries "Limbo keeps crashing"

I'm not sure why it tries to use Limbo?... I mean it's QEMU for Android which is quite unstable as hell?... Maybe I just need to install some other app? Does UserLAnd just launches default system VNC client or something?

**Comment by MatthewTighe** [comment]
Are you referring to 
https://play.google.com/store/apps/details?id=fr.energycube.android.app.com.limbo.emu.main.armv7 ?

**Comment by lapsio** [comment]
yes. UserLAnd tries to launch it when I start VNC session

**Comment by corbinlc** [comment]
UserLAnd doesn't specifically launch bVNC it just sends out a URI intent.  It looks like limbo is picking it up.  Please install bVNC too and then Android should ask you which app you want to handle the intent.

**Comment by MatthewTighe** [comment]
Limbo doesn't seem to have an intent filter that should catch it either... Labeling this as a bug so we can figure out how to avoid similar situations.

**Comment by corbinlc** [comment]
It probably has a library project with it's own manifest.  The final
manifest can be an combination of multiple manifest files. Will have to
dig.  Did installing bvnc work for you?

**Comment by lapsio** [comment]
Yeah it worked. Srr for lack of answer
