### ISSUE TITLE
Illegal State - Failed to copy assets

### ISSUE THREAD

**Issue by yunus70** [CypherpunkArmory/UserLAnd#539]
# Describe the bug

I have to install debian again and again when this problem comes (see screenshot) I have to reinstall all programs. The good thing is with userland i can access my internal memory.
Whenever I install debian session it does not start after a week and an error message appears (see screenshot).

# Steps to reproduce the behavior:
1.Install debian session start with vnc.
2. Install mate desktop by (sudo apt-get install mate-desktop-environment)
3. when the installation is finished then close the session and restart the debian session it should start the desktop environment mate
4.Exit mate (click the mate icon on the top left and click on exit exit the debian session close userland
5.After a week when you start debian session an error message appears (see screenshot).

# Screenshots

![51024163-092a9800-1589-11e9-9bf0-4ce433ca82ea](https://user-images.githubusercontent.com/21973784/51372121-6e880700-1afc-11e9-9559-6a78e1e251d2.png)

# Device Information

Device: Samsung Galaxy Note 4
Android Version: Marshmallow 6.0.1
UserLAnd Version 2.2.0
My device is not rooted
My device is not running custom rom.

translated by Google

**Comment by MatthewTighe** [comment]
Thanks for reposting your issue with additional information. I'll start looking into this today.

**Comment by yunus70** [comment]
I think the new update has solved the problem. I can now start debian session without errors.

**Comment by yunus70** [comment]
Version 2.2.2 fixed my problem.
