### ISSUE TITLE
Feature Request - Add native XSDL support

### ISSUE THREAD

**Issue by ankushlohiya001** [CypherpunkArmory/UserLAnd#540]
XSDL sever is working all fine, but can you please add xsdl inside the userland, as you already added a terminal,,
ie.
Same that we get in debian noroot,,

**Comment by Marcus0086** [comment]
Source code is available. So if u r a SE then add it urselves.

**Comment by corbinlc** [comment]
@ankushlohiya001, that is on our roadmap.  Can you please update your feature request to follow the provided template. 
@Marcus0086, it is ok for people to make feature requests.  I think people know they can contribute.

**Comment by Marcus0086** [comment]
Hey hey @corbinlc so when Fedora 28 or 29 is coming

**Comment by MatthewTighe** [comment]
@Marcus0086 Please keep conversation relevant to posted issues.

**Comment by EnderNightLord-ChromeBook** [comment]
this would be posslible... I have seen people add different apps and smashed them into 1... so the other app is an asset.

**Comment by EnderNightLord-ChromeBook** [comment]
I will do some research on this... and check back in with you guys.

**Comment by lewisdonofrio** [comment]
No need to add it to this project, the two projects are both actively updating on my note8, just my 2cents.
