### ISSUE TITLE
Bug report - [App crashing on start]

### ISSUE THREAD

**Issue by ankushlohiya001** [CypherpunkArmory/UserLAnd#546]
# Describe the bug

A clear and concise description of what the bug is, and what expected behavior is. Include whether the bug occurs **before** 
or **after** entering a terminal or vnc client session.

# Steps to reproduce the behavior:

Go to 'UserLand'

Click on any of distribution, ie. Debian

it starts loading , then crashes, without any error message

See error

# Screenshots

# Device Information

Device: [Redmi 5]
Android Version: [Oreo, 8.1]
UserLAnd Version [2.2.2]
Whether the device is rooted : No
Whether the device is running LineageOS : No

# Additional context

**Comment by EnderNightLord-ChromeBook** [comment]
what phone are you using?

**Comment by corbinlc** [comment]
I have seen many bad reviews from the Redmi 5.  We could use your help, as we don't have that specific device and it looks like it is popular.  Can you enable PRoot logging from the app settings and change the verbosity to 9 before you click on the app?  Then, can you send us the PRoot_Debug_Log after it crashes?

Does the app crash altogether, or does the filesystem extract fail or what?
If it ends up being the former, do you see any crash reports for Redmi 5's @MatthewTighe?

**Comment by EnderNightLord-ChromeBook** [comment]
165 NZ dollars or 98.82 Euros In USA... so a very cheap product.

**Comment by corbinlc** [comment]
We never received enough info to debug this issue.  Recent versions have helped with some Redmi issues.  I am closing this.
