### ISSUE TITLE
System refuses connection and crashing

### ISSUE THREAD

**Issue by MariuszPL55** [CypherpunkArmory/UserLAnd#549]
After install of latest version of nodejs with npm I wanted to install angular cli, but I can't because lack of permission, I granted full permissions and then tried again.. when install process was close to the end then boom, crash and then it is impossible to connect to terminal, need to kill whole service and start it again.

**Comment by Marcus0086** [comment]
Use another ssh application like termius and then connect. 
Things to remember: your ip (localhost)
Port : (2022 usually)
and ur username. It'll be like (user@localhost)
first connect to ur default service and type command passwd there then set a password as it will be required during remote access.
Now open termius and add ssh connection like i said earlier. Now connect and enjoy without crash.

**Comment by MatthewTighe** [comment]
Please update your issue to follow the bug report template found [here](https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=feature_request.md&title=Feature+Request+-+%5BYOUR+FEATURE+REQUEST%5D) or it will be removed in a week.
