### ISSUE TITLE
Nothing will download

### ISSUE THREAD

**Issue by T4O2M0** [CypherpunkArmory/UserLAnd#559]
Describe the bug
I open the app, tap any linux distro or app to download and its stuck at downloading assets forever

Go to 'apps'

Click on 'any app or distro'

See error

Device Information
Device: [LG G7]
Android Version: [8.0]
UserLAnd Version [2.2.1]
Not rooted
Not running lineageOS

Additional context
Download manager shows the downloads "queued"

**Comment by T4O2M0** [comment]
So you just gonna tell me to update it and then not help me?

**Comment by EnderNightLord-ChromeBook** [comment]
This is to get the best information. If you want help just stick to the template and we can help you.

**Comment by Marcus0086** [comment]
Hey hey @T4O2M0 just unistall userland and then reinstall it. Now clickbon any distro and let it download all the assests and also let it to unzip them. Remember during the downloading and unzipping don't click on screen just let it as it is. Don't do anything on screen or u just increase the screen off time to 30 min. If u got a descent internet of 300-500kbps then it will download in no time.

**Comment by Marcus0086** [comment]
Now just close the issue.

**Comment by T4O2M0** [comment]
@Marcus0086 still having the same results :( could it be my phone?

**Comment by Marcus0086** [comment]
Hmm @T4O2M0 maybe. But wait for tomorrow bcz my friend got the same phone as u mentioned in that comment. So let me first check it. Then i will be able to help you. Thank you

**Comment by Marcus0086** [comment]
Hey @T4O2M0 do you have any other descent smartphone in your house. If yes, so then install userland on it and observe if anything happens.

**Comment by T4O2M0** [comment]
@Marcus0086 The only other phone I have is an iPhobene 5c :/ although I do have a android tablet thats semi old, should I try that?

**Comment by Marcus0086** [comment]
Hmm are specs not descent enough

**Comment by T4O2M0** [comment]
My lg g7 should be more than decent enough but im not sure about the tablet.

**Comment by Marcus0086** [comment]
Then give it a try.

**Comment by corbinlc** [comment]
I have not heard of issues with that device.  @MatthewTighe is the best one to help debug downloading problems.  Now that you have updated your issue, he will probably respond in the next couple of days with some questions to help resolve this.

**Comment by MatthewTighe** [comment]
@T4O2M0 Does the download manager work normally? The download manager is an Android framework component. Once we queue downloads with it, we have no control over those downloads until they are completed. If they are being queued and not making progress, there's nothing we can do about that.

**Comment by T4O2M0** [comment]
@MathewTighe I do have problems downloading from the play store, does that mean it is my phone?

**Comment by MatthewTighe** [comment]
It sounds like that's a problem with your download manager at least. Have you tried turning your phone off and on again?

Try downloading this [textFile](https://github.com/CypherpunkArmory/UserLAnd/files/2804428/textFile.txt) (by just tapping it) and let me know if that fails as well.

**Comment by lewisdonofrio** [comment]
Mine downloaded "instantly" but I'm still unable to access it, what should I do, I do not want to lose the 6gb of data (configed setup from last two months)

**Comment by xenpac** [comment]
Hmm... i am new to linux on android.
i understand that "UserLand" can be used without being rooted.
it will create a sandbox/fake root environment in which it runs a linux distro.
It has access to sdcard, wifi,vibration and keep app from sleeping.

So i tried to use Kali linux, it starts downloading.......at 25 it starves....sitting there forever.
it says: 25 of 28....so it waits for more data.

i think that the app is sleeping as whenever i active the phones screen by pressing the power button, 
it seems to continue downloading.

wonder howto stop it from sleeping.........

**Comment by MatthewTighe** [comment]
@xenpac  The last assets that are being downloaded are the largest. They are each about 20MBs I believe. If you have a slow enough network connection, these could just be taking a long time to finish. The reason you are likely seeing the number update when you reactivate your phone screen is because a download has completed while your screen was off.
