### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by 18227077056** [CypherpunkArmory/UserLAnd#561]
1.Sometimes it will download 45/27 files or more
2.Can not download
3.It works slowly
4..........

**Comment by EnderNightLord-ChromeBook** [comment]
Please stick to the issue template or we will have to close this.

**Comment by Marcus0086** [comment]
"https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D" use it from here

**Comment by corbinlc** [comment]
@18227077056 I am one of the developers and it is true that we want people to provide info as shown in the template.  After you provide the needed info, we will respond with more questions/comments that should help work towards a resolution of your problem.  Thanks in advance!
