### ISSUE TITLE
Ubuntu desktop not working 

### ISSUE THREAD

**Issue by zeeshan9128** [CypherpunkArmory/UserLAnd#563]
I tried downloading ubuntu-desktop and when it launches it say system is unable to boot as systemd in init (pid-1)

**Comment by corbinlc** [comment]
Please provide more info by following the template seen here https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D

We need exact steps followed and information about your device and android version so we can reproduce this.

**Comment by EnderNightLord-ChromeBook** [comment]
I tried this. ubuntu-desktop is just a tweaked version of gnome... it was introduced in 18.04.

**Comment by XeGrox** [comment]
"sudo systemctl daemon-reload" returns

System has not been booted with systemd as init system (PID 1). Can't operate.

Although "readlink /sbin/init" returns
/lib/systemd/systemd

**Comment by corbinlc** [comment]
This issue has not been updated to follow the template.  Please reopen it when it has been updated.
