### ISSUE TITLE
Feature Request - Add Ubuntu 18.10

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#569]
# Describe the problem your feature request solves.

People Asking For It.

# Describe the solution you'd like 
My plan is to have a LTS then after the next LTS switch to
the next LTS. And as for latest releases 1 a year which I can handle.

# Describe alternatives you've considered
* starting on fedora

# Additional context
none

**Comment by corbinlc** [comment]
We plan on having CI/CD rebuild the tar.gz files nightly once we get the infrastructure setup.

**Comment by EnderNightLord-ChromeBook** [comment]
Can I Be In The Adding OS's Sector?

**Comment by corbinlc** [comment]
What do you mean?

**Comment by EnderNightLord-ChromeBook** [comment]
Can I Be Part Of Maintaining The OS's Part Of UserLAnd

**Comment by corbinlc** [comment]
Ah I see.  That is not a paid role (we aren't big enough for it to be).  It is a small part of what I do at UserLAnd.  Our goal is to make it possible for people to contribute such work if they would like, such as what you have done.

**Comment by EnderNightLord-ChromeBook** [comment]
And by the way I needed to deleted the rootfs from the assets... And I have another problem... I can't build aarch64 or armhf on my x86_64 Based Devices :(

**Comment by lewisdonofrio** [comment]
you can do it for yourself, just run "do-release-upgrade -d" and it will take you from 18.04 to 18.10, even though I'm holding off till 19.04 is out in three months....

**Comment by stackerlon** [comment]
"do release-upgrade -d won't work" under userland for me but that is fine for me cuz I already have 18.10 on my lap.

**Comment by yunus70** [comment]
You can try [https://linuxconfig.org/how-to-upgrade-ubuntu-to-18-10-cosmic-cuttlefish](url)
I have updated debian 9 to debian 10. It will also work on ubuntu.

**Comment by corbinlc** [comment]
To clean things up, I am going to steer all new distro requests to this new feature request #581
