### ISSUE TITLE
Help - Someone Took Collaborator Off Me On Alpine

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#570]
# Describe the issue you are having.
I just want to know why someone removed me from alpine

**Comment by corbinlc** [comment]
Sorry.  I was cleaning up our github account.  I removed all outside collaborators as it was charging us money to have them added in that fashion.  Please fork and make pull requests, like you do for the other repos.

**Comment by EnderNightLord-ChromeBook** [comment]
ok thanks for telling me.

**Comment by EnderNightLord-ChromeBook** [comment]
And I Was Just In The Middle Of Debbuging My Code And Then. You Aren't Allowed!!!
