### ISSUE TITLE
We Need You! Anyone With A arm64 / aarch64 

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#572]
# Describe the issue you are having.

we need some people with aarch64 / arm64 processors to help
build alpine linux for userLAnd 

To help go to the repo: [Download Alpine .zip](https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/archive/master.zip)

and rename it to UserLAnd-Assets-Alpine

then go to you terminal and build!

`cd UserLAnd-Assets-Alpine` 

`sudo sh scripts/buildArch.sh aarch64` 

`sudo sh scripts/installArch.sh aarch64`

Delete `apk-tools-static-2.10.1-r0.apk` in the UserLAnd-Assets-Alpine if there

and 

`sudo sh scripts/buildArch.sh armhf` 

`sudo sh scripts/installArch.sh armhf`

and upload to the arm64 and arm (arm = armhf - aarch64 = arm64)

and create pull request.

**Comment by corbinlc** [comment]
You can use qemu.  No physical devices are needed.  I will look at adding that to the script tomorrow.

**Comment by EnderNightLord-ChromeBook** [comment]
oh thanks so much corbin!
