### ISSUE TITLE
SFTP gives "No such file or directory" on every operation

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#58]
I installed `openssh-sftp-server` in order to get `sshfs` to work however it throws `No such file or directory` on every operation.

Manual connection with `sftp` results in the same behavior

    lapsio@linux-qzuq ~/SSHFS> sftp -P 8122 phone 
    lapsio@phone's password: 
    Connected to phone.
    sftp> dir
    remote readdir("/home/lapsio"): No such file or directory
    sftp> dir /
    remote readdir("/"): No such file or directory
    sftp> ^D
    lapsio@linux-qzuq ~/SSHFS>

I used `socat TCP4-LISTEN:8122,fork TCP4:localhost:2022` to expose dropbear on `0.0.0.0:8122`

**Comment by lapsio** [comment]
Interestilingly only listing doesn't wok (both dir and ls). Downloading and uploading files, creating directories etc works just fine

**Comment by lapsio** [comment]
Just in case someone is REALLY REALLY desperate, I managed to get sftp to work with this utter crappy, performing worse than taking photos of base64 printed on inkjet and then OCRed, but at least working sftp server implementation in python:

https://github.com/rspivak/sftpserver

It's also probably vulnerable as hell. But as temporary solution it's somewhat acceptable i guess...

**Comment by AdamMatthewLTM** [comment]
@lapsio ,

May I please ask for which options you provided initially to get sshfs to run in the first place, and what connection method/options you are using to attempt to connect to the server with it so I may test and confirm?

Thank you,
-Adam

**Comment by lapsio** [comment]
I'm connecting via sshfs to UserLAnd. I installed openssh-sftp-server to pair with existing dropbear server in UserLAnd. However issue can be replicated using plain sftp client (not sshfs). All in all openss-sftp-server doesn't work in UserLAnd giving "no such file or directory" error on every `dir` command.

**Comment by AdamMatthewLTM** [comment]
@lapsio , 

With your current latest version of userland could you please confirm for me that you are still experiencing the command-specific issues within an sftp server? I am testing a new version at the moment which appears to fix this issue on my phone, however I need to confirm it is still a bug for others.

**Comment by lapsio** [comment]
yes it's fixed
