### ISSUE TITLE
Kali install error - Pixel Phone

### ISSUE THREAD

**Issue by techtheory** [CypherpunkArmory/UserLAnd#584]
Trying to install Kali on Pixel phone. Getting the following errors trying to launch the session:

UserLand has entered an illegal
state!
Bad state transition: Incorrect Sessi
on Transition(event=Asset Download
Complete(download Assetid=5153),
state=Incorrect Session Transition(eve
nt=Asset Download Complete(download
dAssetld-5152), state-tech.ula.model
.state.Extraction Failed@d0eb750))
Please restart the app and contact a
developer

UserLand has entered an illegal
state!
Failed to extract filesystem.
Please restart the app and contact a
developer

Setting up filesystem...
Extracting: tar: write: Broken pipe

Please let me know if you need any more information. Thanks!

**Comment by techtheory** [comment]
Never mind. I cleaned out all of my attempt, including uninstalling UserLAnd and reinstalling. Tried again. Worked fine. Thank you.

**Comment by thinkthinkgo** [comment]
me to
