### ISSUE TITLE
Help - [How to change the resolution of VNC?]

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#585]
I am trying to change the resolution of VNC.

What I've tried: None ... :( Sorry

**Comment by MatthewTighe** [comment]
We'll need more information than that, including what VNC app you're using etc.

**Comment by ptrm** [comment]
For Ubuntu, I managed to change my X11 resolution by editing `/support/startVNCServerStep2.sh`:
Just replace:
```bash
tightvncserver :51
```
With e.g.
```
tightvncserver :51 -geometry 1644x800
```

Running `tightvnc --help` will show you more options. Hope this helps, but it might depend on an image you used.

**Comment by lewisdonofrio** [comment]
Why use VNC?  I use XDSL and life is good.....just figured I'd inquire.

**Comment by corbinlc** [comment]
Please see #215 or #353.  I prefer creating a `.vncrc` file with the geometry setting and then killing the app and then restarting it. 
 Changing it in `/support/startVNCServerStep2.sh` can get blown away by an asset update as our app creates that file.
