### ISSUE TITLE
Connetbot isue

### ISSUE THREAD

**Issue by abdoxfox** [CypherpunkArmory/UserLAnd#586]
I can't connect via ssh to connect who can help??

**Comment by corbinlc** [comment]
Please follow the bug report template found [here](https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D). This generally works for people, so we need to know what is special about your situation.  Also, there is a built in SSH client now, does that work?

**Comment by corbinlc** [comment]
No addition information was provided and it has been quite a while.  As such, I am closing this issue.  Please reopen the issue with more details if you would like help.
