### ISSUE TITLE
how do I access  local storage

### ISSUE THREAD

**Issue by lewisdonofrio** [CypherpunkArmory/UserLAnd#591]
type mount in xfce and you see this:

http://paste.ubuntu.com/p/xpgVKVrNK5/

When I try to ls the /data mount I get "Permission denied"?

![screenshot_20190205-000046_xserver xsdl](https://user-images.githubusercontent.com/3161117/52254100-ad2e0780-28d9-11e9-838e-931635222dcb.jpg)

What I expected was to be able to read and write to the /data/media mount so I can pass files into and out of this chrooted setup

# Device Information

Device: [e.g. Note8]
Android Version: [e.g. Oreo, 8.0]
UserLAnd Version [e.g. 2.2.1]
Build guide and photos at http://www.tinyurl.com/donofriodexnote8
Whether the device is rooted **NOT**
Whether the device is running LineageOS **NO**

**Comment by lewisdonofrio** [comment]
How did it get mounted in the first place if I cannot mount it? 

![jd-05-512](https://user-images.githubusercontent.com/3161117/52273524-1cc2e780-2918-11e9-91e6-14d585181b8e.png)

**Comment by lewisdonofrio** [comment]
I mean I use ssh right now to ship files in and out of the chroot'ed daily driver, just I use wsl and I have /mnt/c and /mnt/t that I use when I cp /mnt/c/User/donofrio/Download/*.iso . or something like that.... just feels clunky and extra steps....I mean I dunno if UserLAnd folks could make the homedir a mount in android (or locall reource mounting like rdp does)

**Comment by foodmaher** [comment]
@lewisdonofrio As I said earlier, it is possible that the reason is in the Android operating system itself, which prevents you from accessing files /data and beyond files because there is a protection system that prevents you from accessing data files, which makes the application userland unable to view or modify the components File /data because it is protected from view and edits from the Android system itself

**WARRING:** I am not an expert in this application. If you see that my answer is insufficient or does not solve your problem, you can ask for help from someone else

**Comment by lewisdonofrio** [comment]
Any hope?

**Comment by MatthewTighe** [comment]
UserLAnd never gets mounted. If you want to move files out of UserLAnd, just copy them to the /sdcard binding in your filesystem.

**Comment by lewisdonofrio** [comment]
All I need to know is how can I reach outside of the chroot setup.  I see mount points that are mounted but I get access denied when I try to ls the directories?

**Comment by MatthewTighe** [comment]
I just told you how to reach outside the filesystem. There is no reason to mount anything if you're just trying to move files.

**Comment by lewisdonofrio** [comment]
I guess that is as good as I could ask for:
![image](https://user-images.githubusercontent.com/3161117/53460130-0f29ea80-3a0a-11e9-8195-c0c8d12ea87f.png)

**Comment by Ebrat222** [comment]
I Use Ubuntu Linux And I Use This Command

```bash
cd ../sdcard/download && ls
```

And it's Working

![Screenshot_20251218-213842.png](https://github.com/user-attachments/assets/1409588b-c2bf-4937-b1ce-d0bab41330b8)

**Comment by Ebrat222** [comment]
Here 👉 cd ../sdcard/download/'New Folder'  && ls > Any hope?
