### ISSUE TITLE
Arch Linux : Permission denied

### ISSUE THREAD

**Issue by XeGrox** [CypherpunkArmory/UserLAnd#592]
[xenron@localhost ~]$ sudo
/usr/local/bin/sudo: line 8: /dev/stderr: Permission denied
[xenron@localhost ~]$ ls /dev
ls: cannot open directory '/dev': Permission denied

Proot log when I run 'sudo' 
https://drive.google.com/file/d/1Qj7banoFRXbQJwk4LFv1p9GB1IpgRqoT/view?usp=drivesdk

This happened after I built [polybar](https://github.com/jaagr/polybar) overnight

Emui 9 : Android 9
Arch Linux

Edit: Reuploaded file

**Comment by EnderNightLord-ChromeBook** [comment]
@XeGrox The Link To The Proot Log You Gave Said (FILE NOT FOUND).

**Comment by corbinlc** [comment]
Why are you running `sudo` without a following command?  Did you mean to use `su`?

**Comment by corbinlc** [comment]
Getting permission denied for `/dev` is expected.

**Comment by XeGrox** [comment]
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so: Bad address
sudo: fatal error, unable to load plugins

I got this error while building polybar

**Comment by corbinlc** [comment]
@XeGrox can you do this `which sudo` and provide the result?  Also, can you check if the file that `which` command points you at is a bash script?  The reason I ask is we initially set things up such that `sudo` is replaced with a script called `nosudo` (which we bind into your system and call it `sudo` again).  It sounds like something went wrong with that.

**Comment by XeGrox** [comment]
The problem is that trizen (aur wrapper I'm using) is using sudo from /usr/bin/sudo instead of /usr/local/bin/sudo (default sudo)
