### ISSUE TITLE
Bug report - [Blocked from accessing my SD card]

### ISSUE THREAD

**Issue by H3RSKO** [CypherpunkArmory/UserLAnd#598]
After downloading userLAnd and successfully installing Kali Linux, I am no longer able to access the SD card on my phone.

I was able to see the card listed on the android storage settings tab, but when I clicked into it nothing was accessible, although it did show the space used and amount remaining etc. A third party file management app was not able to find the card at all.

After turning the phone off and on again, the sd card no longer shows up anywhere.  

# Device Information

Device: Moto X Pure, 
Android Version: Android 7.0
UserLAnd Version: Not sure, but just installed it yesterday
Whether the device is rooted: Not rooted

**Comment by corbinlc** [comment]
If it was related to UserLAnd, I would have no idea why or how to debug that.  Sorry I don't have a suggestion.  Maybe remove and reinsert the sdcard or try another sdcard or something like that.

**Comment by H3RSKO** [comment]
Weird coincidence then. I removed the SD card and restarted but still no luck. 

It's about time to get a new phone anyways i guess . . . .

**Comment by MatthewTighe** [comment]
Yeah, unless Android itself is broken on your device for some reason, there's no way that we could have caused this as far as I know. When was the last time you remember being able to browse the files on your SD card?

**Comment by H3RSKO** [comment]
I was definitely able to access it two days earlier. I didn't really do much in that time period that would have effected it.

**Comment by MatthewTighe** [comment]
We may have dismissed this a little too quickly. Do you remember if you ever deleted a filesystem through our app, or during a session called `rm -r`?

**Comment by H3RSKO** [comment]
Nope. My entire history up to that point:

1  sudo apt update
    2  sudo apt upgrade
    3  sudo apt install routersploit
    4  ls
    5  cd routersploit
    6  routersploit
    7  quit
    8  exit
    9  ls
   10  cat routersploit.log
   11  exit
   12  routersploit
   13  exit
   14  routersploit
   15  exit
   16  history

This is on KaliLinux which is the only App I installed with UserLand

**Comment by MatthewTighe** [comment]
Alright, then I still don't think your issue is related to anything we're doing.

**Comment by H3RSKO** [comment]
Ok. Thanks anyways.

**Comment by corbinlc** [comment]
I have not heard further reports of this and I don't think there is anything else we can do to assist.  As such, I am closing this issue.

**Comment by jonasyumi** [comment]
Did u fix ut bro??

**Comment by khenty** [comment]
I am using Android 14 on a Lenovo P12 Pro tablet. I'm running Debian from UserLand, and I can't see the sdcard in the filesysem anywhere. I tried three different sdcards, one Samsung and two SanDisk, same result on all of them. Is sdcard just not visible from UserLand? If it is visible, where should I look?
