### ISSUE TITLE
Performance issue with the latest UserLand update.

### ISSUE THREAD

**Issue by dsvilko** [CypherpunkArmory/UserLAnd#600]
Ubuntu run through Userland was alerady slower than the Ubuntu run through termux installer. For example it took 11s to run Inkscape (almost 3 times as long as with termux). As the latest Userland changelog mentioned performance improvements due to a new Proot beta, I was hopefull that this performance difference would be improved. Unfortunately it now takes 25s to open Inkscape, making it more then twice slower than with the old Proot and for most disk IO intensive processes up to 10 times slower than termux.
What where the benefits upgrading to Proot beta as I am seeing a significant drop in performance?

**Comment by corbinlc** [comment]
The changes to PRoot were to make PRoot do less disk access and to have that access be mostly async with regards to how we emulate file ownership and permissions (something termux's proot does not do).  We are going to further refine this, but this current changes "should" speed things up in almost all cases.

Can you provide a little more info by following the bug report template found [here](https://github.com/CypherpunkArmory/UserLAnd/issues/new?template=bug_report.md&title=Bug+report+-+%5BYOUR+BUG+TITLE%5D)?

**Comment by corbinlc** [comment]
Also, can you see if this is repeatable?  What I mean is we do some migration between the old way things are handled to the new way the first time every file is opened, which might make things slower the first time.  If you open inkscape up say 10 times in the beta release and measure that time, is it actually slower each time compared to doing it 10 times with the production release?  Lastly, how do you launch inkscape...by clicking on the icon on the apps page or from the command line?

**Comment by MatthewTighe** [comment]
For more clarity:
When you say Inkscape is taking longer to open, is that **after** or **before** the terminal opens?

**Comment by dsvilko** [comment]
The first thing I did when I saw a new update is once again check the time from clicking on a inkscape icon in xfce to inkscape window apearing on the desktop. I have ignored the first run (was something like 15s) and measured a few repeated (hopefully cached) runs. They were  repeatable at close to 11s. After upgrading the Userland, it's now twice as long.

**Comment by lewisdonofrio** [comment]
I wait for a while as well...it is less of a wait when you click away from the console, it take me 15 seconds to get my full xfce4 desktop session going.... and 1-3 seconds or more for each invocation of application/ping - my rough build guide is at http://www.tinyurl.com/donofriodexnote8

**Comment by corbinlc** [comment]
This is fixed for new filesystems. It involved a major PRoot change that is not compatible with the version being used previously. We are going to create a path for migrating through major PRoot changes in the not so distant future. But, the performance is much better now.  Probably about as good as it will get.

**Comment by lewisdonofrio** [comment]
so if I uninstall and rebuild then it should be golden....awesome news, I'll try this weekend.....wish I had an asset that would cp the file so if it didn't work I could go back but for now I'll just jump and try it....thank you for all you good folks do, with this project you REALLY make a difference in my life, just sayin.

**Comment by corbinlc** [comment]
thanks.  we are going to create backup and restore functionality per your request in the not too distant future.  we started talking about it more seriously this week and will probably put it in the next two week sprint
