### ISSUE TITLE
Feature Request - [Join a GNU nano code editor]

### ISSUE THREAD

**Issue by SunbossRS** [CypherpunkArmory/UserLAnd#602]
I tried to do some development on my UserLAnd kali,but there isn't any code editor in this system. I wish developers can add a GNU nano editor,please~ ;-)
![pre0](https://user-images.githubusercontent.com/38691765/52522282-1b017700-2cbe-11e9-9199-ba015dc7ff7c.png)

**Comment by XeGrox** [comment]
sudo apt install nano
