### ISSUE TITLE
Latest Update Doesn't Work On Asus 101PA Chromebook

### ISSUE THREAD

**Issue by coot2** [CypherpunkArmory/UserLAnd#606]
# Describe the bug
The latest release doesn't work on Chromebook Asus 101PA. It works fine on Asus C302. It appears to pull down the tar files on the 101 PA but when it tries to untar these to the file system there is a "Bad Address" message. Ultimately after it goes through the motions of expanding the tar files I can't log in.  Can't get to terminal

# Steps to reproduce the behavior:
Install on Asus 101PA from Google Play Store and try to create Ubuntu or Debian file systems

Device: [Asus Chromebook C101PA]
Android Version: [7.1.1]
UserLAnd Version [2.3.1]
Whether the device is rooted - no
Whether the device is running LineageOS - no

# Additional context
Latest version on Asus C101PA (ARM) that I downloaded is broken. Indicates error when it tries to extract tarballs for both Debian and Ubuntu. Issue is with SSH session. I have reinstalled Userland 3 times - same problem. I even completely wiped the Chrome OS (powerwashed)  and reinstalled it along with Android - problems was still there. When I launch session - I can't log in with password that I set up. This worked for the previous version which did not have the XSDL connect option . There is no issue on my Intel Chromebook with same version of Android (7.1.1). I only use the SSH interface so I can't speak to other connect options.

**Comment by EnderNightLord-ChromeBook** [comment]
Chromebooks Aren't Officially Supported. When Running On A Chromebook You Run Into A Few Problems. Like TWM Doesn't Come Up In VNC. I Don't Know Why...

**Comment by EnderNightLord-ChromeBook** [comment]
And It's Working Fine For Me (HP x360 11GE Chromebook)

**Comment by Herzogs** [comment]
I have the same problem with Bad Address, my tablet is a Acer Iconia with Android 5.0.1

**Comment by coot2** [comment]
I suspected Chromebooks were not officially supported but works pretty good as a console development environment for me on both the ARM (Asus 101PA) and Intel based (Asus C302) and still works with the latter.

**Comment by coot2** [comment]
A bit of additional information:  I have an old Android Nexus 7 tablet running 6.0.1 Android. I installed UserLand on this and it is exhibiting the same "Bad Address" message and prevents me from logging in once it went through the motions of untaring the tarballs.  I fined it interesting that this installed and works fine on my Intel Chromebook but fails on Herzogs's Acer, the Nexus 7, and the Asus 101PA - all ARM machines. A small sample size but interesting nonetheless.

**Comment by MatthewTighe** [comment]
We're investigating issues around bad tarballs right now. @corbinlc may be able to provide more info.

**Comment by coot2** [comment]
As of today I am able to correctly download and extract the assets for both Ubuntu and Debian on my C101PA - the same PC that I opened this ticket on. Tarball issue corrected?

**Comment by corbinlc** [comment]
It was a PRoot issue.  The tar ball was not corrupted.  Thanks for the update.
