### ISSUE TITLE
Can Not use on 2. Account

### ISSUE THREAD

**Issue by Proxtx** [CypherpunkArmory/UserLAnd#607]
I am using Android 9 and it returns an error

**Comment by EnderNightLord-ChromeBook** [comment]
Please Use The Issue Template Otherwise This Post Will Be Closed.

**Comment by MatthewTighe** [comment]
Please update this issue to follow the issue template provided [here](https://github.com/CypherpunkArmory/UserLAnd/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).
