### ISSUE TITLE
Help - userland stops installing after 27 out of my 28 packs are installed

### ISSUE THREAD

**Issue by gajjugithub** [CypherpunkArmory/UserLAnd#609]
The assest of file stopped after 27 out of 28 files get installed
![screenshot_20190209-193949](https://user-images.githubusercontent.com/47491498/52530807-fc889380-2d30-11e9-8b86-81633f5e531a.png)

This should include things like:
- What you are trying to accomplish
- What you have tried so far

# Describe how your task behaves in a regular Linux environment

This can be omitted if it is not applicable, but leave the header in.

**Comment by SunbossRS** [comment]
Oh,this problem i got it,too.

If we get this problem,maybe it is the factors of these:
- Put UserLAnd at the background and do other things
- The download manager is too fast and UserLAnd can't track the download manager suddenly.

So The solution idea is:
- Restart the app and keep watch the screen download the files until it is setting up the filesystem.

**Comment by gajjugithub** [comment]
Thanks for your suggestion, I will work the same and will inform you if it
works.

**Comment by RawSlugs** [comment]
I had this issue, had to keep UserLand in the foreground and go to a different wifi network as the one I tried originally was too slow and not stable..

Make sure you are on a fast and stable network

**Comment by SunbossRS** [comment]
~~Make sure you have enough time to download and configure the filesystem...~~  
~~You need to find your free time to do this thing~~

**Comment by corbinlc** [comment]
I can confirm this issue.  If the app is put into the background while downloading it will often get hung.  This used to not be true.  Looks like we broke this while fixing a different issue.  We will fix it.

**Comment by EnderNightLord-ChromeBook** [comment]
Could It Have Been When @MatthewTighe Fixed #571 ?

**Comment by corbinlc** [comment]
I am not sure, but I think this change was part of the bigger refactor that preceded that by a couple of weeks.

**Comment by EnderNightLord-ChromeBook** [comment]
probably...

**Comment by MatthewTighe** [comment]
This should be solved by #615.
