### ISSUE TITLE
Can simplify to not use VNC? Text console is good enough.

### ISSUE THREAD

**Issue by pbreneman** [CypherpunkArmory/UserLAnd#61]
I've used GNUroot before for similar things.  I don't need a GUI to occasionally adjust the temp on a thermostat.  www.TurboControl.com/userland.htm is the new page (links to old page)

**Comment by Root-voidX** [comment]
Ssh with connectbot is just command line though?

**Comment by bet** [comment]
Does userland not have a local terminal, like gnuroot did, and termux does?

**Comment by Root-voidX** [comment]
Not at this moment.

**Comment by AdamMatthewLTM** [comment]
@pbreneman ,

Thank you for filing this request. The current default command line may be accessed through the ssh service with connectbot, however the developers have indicated that keeping the option for VNC open and available is necessary for users who wish to utilize a graphical interface.

@bet ,

In regards to having a local terminal, the developers have indicated that this may not be the direction UserLAnd will be going, **however** I am recommending this thread be remained open for consideration for others if they wish for this request to be implemented. Therefore, I am flagging this request as a low priority/enhancement.

Thank you all for your understanding,
-Adam

**Comment by bet** [comment]
A shame. But if we want a unix environment without needing connectbot, there's always Termux --- and since it cleverly adds ctrl and tab to whatever keyboard you use, it's especially good to use to ssh into userland
