### ISSUE TITLE
Feature Request - [YOUR FEATURE REQUEST]

### ISSUE THREAD

**Issue by thdarknes** [CypherpunkArmory/UserLAnd#612]
# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 

Ex. I'm always frustrated when [...]

# Describe the solution you'd like 

# Describe alternatives you've considered

# Additional context

**Comment by corbinlc** [comment]
Why are you opening issues without content?  We have a very small team of developers on our free and open source project.  Please don't.
