### ISSUE TITLE
Acquire wake lock crash

### ISSUE THREAD

**Issue by XeGrox** [CypherpunkArmory/UserLAnd#614]
Acquire wake lock action from the terminal notification causes the app including the running service to crash after updating to the latest version (2.3.0 to 2.3.1)

Emui 9

**Comment by MatthewTighe** [comment]
I can confirm this is reproducible. Not sure what would've changed in that version to break it, but we'll take a look. @luongthomas can you take this one?

**Comment by luongthomas** [comment]
I'll investigate what's causing this crash

**Comment by lewisdonofrio** [comment]
I've been seening these as well even in most recent 2.3.4

**Comment by slycooper724** [comment]
It happened to me too.

**Comment by lewisdonofrio** [comment]
same with 2.3.7 ;(

**Comment by luongthomas** [comment]
Release v2.3.8 is being made to production to fix this issue momentarily.

**Comment by lewisdonofrio** [comment]
it fixed the issue...tnx
