### ISSUE TITLE
Bug report - All Distros Wont Extract

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#616]
# Describe the bug
Just installing alpine then when It came to extract it failed to extract any files
then I tried ubuntu then the same thing happens..

# Steps to reproduce the behavior:
Install Any OS 

Then When It Starts To Extract It Fails To Extract everything.

# Device Information

Device: Samsung J4+
Android Version: 8.1
UserLAnd Version: 2.3.3 (Latest) 
Not Running Lineage

**Comment by corbinlc** [comment]
Can you switch to the latest production version 2.3.2?

**Comment by EnderNightLord-ChromeBook** [comment]
Yes Sure.

**Comment by EnderNightLord-ChromeBook** [comment]
Cool Yes It Is... Do You Know What The Problem Is With 2.3.3?

**Comment by EnderNightLord-ChromeBook** [comment]
Xfce4 Working On Alpine UserLAnd

![image](https://user-images.githubusercontent.com/31677287/52614793-b2054380-2ef7-11e9-9dda-8071e6809032.png)

**Comment by EnderNightLord-ChromeBook** [comment]
Issue Has Been Solved...
