### ISSUE TITLE
Requesting Feature : Extra Keyboard Row

### ISSUE THREAD

**Issue by Chidhambararajan** [CypherpunkArmory/UserLAnd#617]
I have been using termux for a long time , but I recently shifted to UserLand because of its ability to give root access, but I find a small draw back in this app . 

The extra keyboard row feature in termux has 2 rows which is really useful but UserLand has only 1 such row.. is there a way to add the same ??

Termux screen shot highlighting the same
![](https://i.imgur.com/HknqtBz.jpg)

UserLand screenshot with the absence of the 2nd row
![](https://i.imgur.com/0ASVYgo.jpg)

Kindly add the same feature or explain the way to add the same

Thanks In Advance

**Comment by EnderNightLord-ChromeBook** [comment]
You Should Try ConnectBot With UserLAnd It Works Very Well.

**Comment by Herzogs** [comment]
sorry the question does not exist a way to assign the keys that we want? for example in Termux there is to edit the file termux.properties

**Comment by ch2925** [comment]
write your termux.properties here:/host-rootfs/data/data/tech.ula/files/home/.termux/termux.properties

**Comment by xamarama** [comment]
"Permission denied". /host-rootfs

**Comment by Herzogs** [comment]
1. `cd /host-rootfs/data/data/tech.ula/files/home/`
2. `mkdir -p .termux`
3. `cd .termux`
4. `busybox vi termux.properties`
5. Into the file put: `extra-keys=[['ESC','TAB','CTRL','ALT','UP','DOWN','LEFT','RIGHT']]` or keys what you use

**Comment by xamarama** [comment]
Thanks. It is work

**Comment by corbinlc** [comment]
We added an extra row and @Herzogs provided how to customize it.  I am closing this now
