### ISSUE TITLE
Feature Request - Add Support for Moving the App to the SD Card

### ISSUE THREAD

**Issue by slycooper724** [CypherpunkArmory/UserLAnd#620]
# Feature Request Solves:
Running out of storage when using (Installing filesystems) the UserLAnd app.

# Proposed Solution:
The proposed solution is to be able to move the app to external storage via the built in android app manager.

# Alternative Solutions:
Being able to, in app, tell it to, when your installing a linux filesystem, store it on the sd card.

# Additional Context:
I am using Android 8.0.0

**Comment by MatthewTighe** [comment]
@corbinlc will have more details on this. There are issues with storing the filesystem on the SD card, as they are usually FAT storage. This means that, for example, you normally can't use executables on it.

**Comment by corbinlc** [comment]
This is covered in an older issue #160.

**Comment by corbinlc** [comment]
Please follow developments there.  Since this is a duplicate, I am going to close this one.
