### ISSUE TITLE
Help - Can't find file system (debian) location on my phones file browser

### ISSUE THREAD

**Issue by slycooper724** [CypherpunkArmory/UserLAnd#621]
# Issue:
I am trying to find the location of the filesystems stored on my phones internal storage.
I have tried looking in the android folder, and have had no luck finding any folder containing the UserLAnd files.

# How Task Behaves in Linux:
n/a

**Comment by MatthewTighe** [comment]
Android hides app-specific files by default. You won't be able to access them using something like a file browser for that reason. Exporting filesystems is a feature on the roadmap, and you can track progress on that feature from #162.
