### ISSUE TITLE
Mint Linux 

### ISSUE THREAD

**Issue by mapdaddy1** [CypherpunkArmory/UserLAnd#629]
I really like Mint which is based on Ubuntu. Is it possible to add this as a selection? Or is there a way to load images that I've downloaded? 

Thanks,
Mark

**Comment by EnderNightLord-ChromeBook** [comment]
Hey that's a good idea. Mint is my favorite linux OS.

**Comment by lewisdonofrio** [comment]
"Re: Will Linux Mint eventually support Arm?

Post by gm10 » Sun Jan 20, 2019 6:43 pm

    ammonharper wrote: ⤴
    Sun Jan 20, 2019 6:40 pm
    Dex is a desktop OS extension on the phone. I'm using the beta with Ubuntu 16 currently. I'd like to see Mint however it seems like it's dead before the discussion starts. So meh... 

Have you tried adding the Mint 18 repos and simply installing the relevant meta-package you're interested in? Most things should work regardless, but I'm not sure about Cinnamon itself."
(https://forums.linuxmint.com/viewtopic.php?t=276840)

**Comment by EnderNightLord-ChromeBook** [comment]
This Will Be On My Agenda Once I Get CentOS And Fedora Working...

**Comment by corbinlc** [comment]
No progress has been made on this, that I know of.  Also, I have added this to the wish list here: #581 
That is where I am tracking all distro requests.  Since I have added it there, I am going to close it here.
