### ISSUE TITLE
App Request - Intellij IDE

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#631]
# Describe the problem
The problem is to support and install advanced code editors like intellij Idea
# What is required or solution
I need to support codes editor (intellij idea) on Userland and also support Android studio on Userland if can maybe because it works on the same codes editor (intellij idea).
# What I've tried
I will not hide that me have already downloaded and install intellij on the application Termux and I suffer from slow speed and problems, I tried to ask the assistant here to of add to the list of applications and also solve problems related to speed and other.
**Note:** The issue has been modified to fit the recommended template
Thank you

**Comment by EnderNightLord-ChromeBook** [comment]
I could try and add it for you?

**Comment by foodmaher** [comment]
@EnderNightLord-ChromeBook 
Thank you so much for the service
Do you will be added in the next version of the trial version
**And: ** Can you add Android studio to it or it needs high playback requirements

**Comment by EnderNightLord-ChromeBook** [comment]
I'm going to have to make a script to make it download the latest version and if it updates I will use that... This may be a challenge... But I Will Try.

**Comment by foodmaher** [comment]
@EnderNightLord-ChromeBook 
If you mean intellij I already own it on Termux but it does not work well so I asked from here in order to work quickly and not have problems

But if you mean that the challenge will be difficult for Android studio I just suggested that you managed to aggravate it would be great but if you can not add Android studio, it is ok because I do not need much unlike intellij because he and a few others are only from They support the Kotlin language

And excuse me on my bad language and sometimes incomprehensible 😁😁

**Comment by EnderNightLord-ChromeBook** [comment]
Sorry iv never used android studio.
