### ISSUE TITLE
Failed to extract filesystem (Beta version)

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#634]
# Failed to extract filesystems

- I tried to scan and reinstall it but it also does not work
- I also tried to clear support files but it does not work too

# Describe how your task behaves in a regular Linux environment
- The problem is only related to userland

# Additional documents
![screenshot_2019-02-13-19-13-13](https://user-images.githubusercontent.com/27397889/52731019-64efa300-2fc5-11e9-839a-3866e162f743.png)
**Edit:** It seems that the problem appears only in the trial version because I downloaded the default version and work well Did you continue to use the trial version because it has the latest features or use the default version

**Comment by corbinlc** [comment]
Can you create a new filesystem and try again?  We updated PRoot after you ran into this issue.

**Comment by foodmaher** [comment]
@corbinlc Yes, the trial version is running after the update where Debian has been successfully installed..
