### ISSUE TITLE
Change to static ip 

### ISSUE THREAD

**Issue by zeeshan9128** [CypherpunkArmory/UserLAnd#636]
Name of the issue:- change dhcp to static ip

I'm trying to change my dhcp ip in ubuntu 18.04 userland to static ip 
Steps:- 
Install webmin [ $:sudo apt install webmin ]
change to root [$:su]
Start webmin [ #:/etc/init.d/webmin start]
Check status [#: /etc/init.d/webmin staus ]
Open any browser go to localhost:10000
Then it will open login interface 
Admin: root
Password: your root password
After login you have to go to 
Networking > Network configuration > network interface and change you ip according to connected device 
There are three devices 
lo,dummy0,rmnet_data
But when i change any of the following
It gives the error
Failed to save interface : SIOCSIFADDR: Permission denied SIOCSIFFLAGS: Permission denied SIOCSIFNETMASK: Permission denied SIOCSIFBRDADDR: Permission denied SIOCSIFFLAGS: Permission denied SIOCSIFFLAGS: Permission denied
How do i solve this because i want yo test apache server but without static ip it doesnt works

**Comment by lewisdonofrio** [comment]
Why use static....I've had my dail driver session running for four months now and it's kept the same dhcp address that my router gives out.  just wonderin.

**Comment by zeeshan9128** [comment]
I'm a noob i  just wanted to install apache server but to connect it to my domain I've to change it to static but if it works with dhcp can you tell me how?  Thanks in advance

**Comment by zeeshan9128** [comment]
You can also tell me how to install apache web server in ubuntu userland

**Comment by lewisdonofrio** [comment]
you just type in a terminal window.

**SNIPPED**
user@localhost:~$ sudo apt-get install apache2     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
Suggested packages:
  apache2-doc apache2-suexec-pristine | apache2-suexec-custom ufw
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap
0 upgraded, 8 newly installed, 0 to remove and 0 not upgraded.
Need to get 1405 kB of archives.
After this operation, 6076 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
**SNIPPED**

**Comment by zeeshan9128** [comment]
I know how to install it but how to get it on the web so that anyone can access it

**Comment by lewisdonofrio** [comment]
are you having issues getting to your defined vhosts?  guessing outside scope for this type of talk, you're welcome to join me and many others in hexchat or another irc client on freenode.org in the ##httpd channel, or #ubuntu
