### ISSUE TITLE
Bug report - CRITICAL! Complete phone internal storage delete!

### ISSUE THREAD

**Issue by dsvilko** [CypherpunkArmory/UserLAnd#638]
# Describe the bug

Deleting a filesystem (through the UserLAnd UI filesystems tab) that has a link to a sdcard deletes the complete internal storage, with no warning!
BEWARE! I have lost all my data! This is a know bug what I wasn't aware of because it was long time since there was any activity on it. This is not a medium-priority, but definitively a critical bug. 

# Steps to reproduce the behavior:

Delete a UserLand filesystem, loose everything on your phone.

# Screenshots

Picture an empty phone screenshot. That's what you get.

# Device Information

Not device dependent.

# Additional context

What more do you want?

**Comment by dsvilko** [comment]
The delete function should immediately be disabled until this is fixed! You have just informed people that they should delete their old filesystems and reinstall to get a performance boost, knowing that this bug exists. Still can't believe.

**Comment by XeGrox** [comment]
Im pretty sure they meant the remove button from the filesystems tab, not deleting everything from the command line.

**Comment by yunus70** [comment]
my internal memory was also deleted.

**Comment by dsvilko** [comment]
Yes, the remove button from the filesystems tab deleted everything, following the home folder link to the /sdcard. If I had deleted the filesystem through the command line, I would be more careful. You can't say that this was the expected behavior.

**Comment by corbinlc** [comment]
I think it only files symbolic links you created.  By default it won't delete anything outside of the filesystem.  We need to have it not follow symbolic links at you created.

**Comment by dsvilko** [comment]
There should at least be a warning to manually remove the symlink before removing the filesystem. Untill then, the remove button should be disabled.

**Comment by MatthewTighe** [comment]
I'm going to close this, as it's a duplicate of #275. Our bug reporting infrastructure was less robust when that issue was first opened, so it must have slipped under my radar. I'll shift this to high-priority and release a fix for it this week.
