### ISSUE TITLE
No /etc/tty0

### ISSUE THREAD

**Issue by lucamaggioni** [CypherpunkArmory/UserLAnd#645]
---
name: Bug report
about: Create a report to help us improve
title: 'Bug report - no /dev/tty0'

---

# Describe the bug
I'm using Ubuntu 18 over huawei p20 and I've installed lxde.
On startx I receive an error complaining that there's no /dev/tty0.
The bug occurs after entering a terminal or vnc client session.

# Steps to reproduce the behavior:
su - 
Apt install lxde
startx
... This raise an error saying there's no /dev/tty0 file or dir. 

# Screenshots

# Device Information
Device: huawei p20 pro
Android Version: 9.0
UserLAnd Version 2.3.5
The device is not rooted.
The device is not running LineageOS

# Additional context

**Comment by XeGrox** [comment]
/dev is not accessible without root
You might want to use vnc instead and run startlxde

**Comment by corbinlc** [comment]
Normally the errors/warning printed out related to tty devices are not blocking.  Can you provide all the output from when you tried to install the package?

**Comment by corbinlc** [comment]
No output was provided and hence we could never help.
