### ISSUE TITLE
Feature Request - Add Offline Feature

### ISSUE THREAD

**Issue by GetRektBoy724** [CypherpunkArmory/UserLAnd#654]
# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 
 I'm always frustrated when offline 

# Describe the solution you'd like 
I want i can run kali without internet access
# Describe alternatives you've considered

# Additional context

**Comment by lewisdonofrio** [comment]
Working for me.....note airplane mode....
![screenshot_20190221-105619_userland](https://user-images.githubusercontent.com/3161117/53182833-43e01100-35c8-11e9-853d-86fb6bb6c158.jpg)
my build guide at http://www.tinyurl.com/donofriodexnote8

**Comment by MatthewTighe** [comment]
Once Kali is installed it can be used offline like it would be normally. Of course you wouldn't be able to access network features. What is you're trying to accomplish?

**Comment by shmshd** [comment]
illogical feature request!
