### ISSUE TITLE
Mariadb-server installation Error

### ISSUE THREAD

**Issue by overdrive69** [CypherpunkArmory/UserLAnd#66]
Hello,
when i try to install mariadb-server, i get the following error.
 Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by hkgoldenmra** [comment]
I have the same error when installing mariadb-server.
I discovered that the error is triggered from /usr/sbin/mysqld and returns [segmentation fault](https://3.bp.blogspot.com/-NOFne997UU4/WzDigfBJNoI/AAAAAAACeJI/dRn_I54p5mQJQSi285EV5AGazdm4QjvfgCKgBGAs/w0/linux-on-android-10a-12a.png)

**Comment by overdrive69** [comment]
do you had any success to install the mariadb-server?

**Comment by AdamMatthewLTM** [comment]
@overdrive69 ,

My apologies in the delay to your filed issue. I can confirm that the installation of mariadb-server fails for myself as well with the same error code. I am unfamiliar with this software and therefore may need to ask you some questions if we are to successfully install this in userland.

Just to absolutely confirm (I will test this myself as well), are you able to install the software on a debian-based system (ubuntu should work too for this)? Please let me know, and thank you for your patience,
-Adam

**Comment by overdrive69** [comment]
Yes have running mariadb server on a debian based system.

greets

**Comment by AdamMatthewLTM** [comment]
@overdrive69 ,

Thanks for your response. After doing some testing using various suggestions from forums addressing this software bug, I have not been able to replicate any of their successes. The three suggestions which were made were:

1) That this is a version conflict issue which may be solved by doing some repository cleaning magic with the following commands:

*  sudo apt-get remove --purge mariadb-server mariadb-client 
* sudo apt-get autoremove
* sudo apt-get autoclean
* sudo apt-get install mariadb-server mariadb-client

2) @hkgoldenmra , that this is a conflict issue with mysql and may be solved by removing mysql **which I do not recommend unless you are prepared to do a complete userland reinstall**

3) That theoretically this software may not install if it detects insufficient system resources such as a specific amount of RAM or disk space. At the moment I have no way of confirming if this is the case or not.

If anyone is able to do so, please attempt options 1 and 2 to determine if they may provide a fix in a specific situation for installing this software. Thank you all for your help in attempting to resolve this matter.

**Comment by poVoq** [comment]
I have the same error (after installing Dialog and apt-utils).

Strange is that MySQL which is prettry much the same as MariaDB (the latter is a fork of the former) doesn't show the same error. However it also doesn't seem to work as it fails to autoconfigure and to determine the runlevel.

**Comment by corbinlc** [comment]
`sudo apt update && sudo apt install mariadb-server` now works.
