### ISSUE TITLE
Help - Error "Assets need to be copied to your filesystem, but it looks they have not been downloaded"

### ISSUE THREAD

**Issue by eaglersdeveloper** [CypherpunkArmory/UserLAnd#661]
# Describe the issue you are having.

After file downloading, app tries extract they, but gives the error:

![screenshot_2019-02-26-14-33-00](https://user-images.githubusercontent.com/40228953/53407338-682b5b80-39d5-11e9-9aaa-b5ad8df56b80.png)

I can't find log. Where is it?! 

# Describe how your task behaves in a regular Linux environment

Linux hasn't booted yet.

**Comment by MatthewTighe** [comment]
Can you try `Clear All Support Files` from the options menu?

**Comment by eaglersdeveloper** [comment]
Yes, I tried. This didn't work.

**Comment by MatthewTighe** [comment]
What about uninstalling and reinstalling?

**Comment by eaglersdeveloper** [comment]
I tried only only deleting application data.

**Comment by SunbossRS** [comment]
@eaglersdeveloper I just saw there was a 'storage space was not more' icon on the top of the screen...  
Maybe your storage space was full. You can delete sone no-need files....

**Comment by corbinlc** [comment]
I am closing this issue as we have improved our install flow and we believe that 1) making sure you have enough space on your device and 2) uninstall and reinstalling the app will fix your issue (and hopefully already has).  Please reopen this issue or file a new one if you are still having problems.
