### ISSUE TITLE
Bug report - How do I ssh into this chrooted setup, 22, 2022, nothing working externally.

### ISSUE THREAD

**Issue by lewisdonofrio** [CypherpunkArmory/UserLAnd#662]
# Describe the bug

When I try to ssh into my chrooted setup I cannot except on the local device only.  In that I mean at work when I tried I get denied like this...

# Steps to reproduce the behavior:

Go to 'UserLAnd' start ubuntu session

then 'from logged in console'

![screenshot_20190226-191600_userland](https://user-images.githubusercontent.com/3161117/53457694-4e077280-3a01-11e9-8b7a-ce394e9a73c7.jpg)

donofrio@LTAL0111:~$ ssh user@192.168.29.148
ssh: connect to host 192.168.29.148 port 22: Connection refused
donofrio@LTAL0111:~$ ssh user@192.168.29.148:2022
ssh: Could not resolve hostname 192.168.29.148:2022: Name or service not known
donofrio@LTAL0111:~$ ssh user@192.168.29.148:2022
ssh: Could not resolve hostname 192.168.29.148:2022: Name or service not known
donofrio@LTAL0111:~$ ssh user@192.168.29.148
ssh: connect to host 192.168.29.148 port 22: Connection refused
donofrio@LTAL0111:~$

# Screenshots

Then what is even more weird is when I start ssh, it stops?

![screenshot_20190226-192700_userland](https://user-images.githubusercontent.com/3161117/53457727-624b6f80-3a01-11e9-8f0b-02ca8b03e1ca.jpg)

# Device Information

Device: [e.g. Note8].  
Android Version: [e.g. Oreo, 8.0].  
UserLAnd Version [e.g. 2.3.7].
Build guide at http://www.tinyurl.com/donofriodexnote8  
Whether the device is *NOT* rooted.  
Whether the device is *NOT* running LineageOS 

# Additional context

interesting this is all along I'm able to ssh into my chroot from es file manager using 127.0.0.1....please tell me how??

![screenshot_20190226-200914_es file explorer](https://user-images.githubusercontent.com/3161117/53458048-89ef0780-3a02-11e9-9c3b-64e04e0eb2c3.jpg)

**Comment by AndrewScibek** [comment]
Try doing `ssh user@192.168.29.148 -p 2022`

**Comment by lewisdonofrio** [comment]
That worked, but why didn't :2022 work?

(this screenshot was from my Windows 10 WSL ubuntu 18.04 - build guide at http://www.tinyurl.com/donofrioworkdesk) ssh'ed into note8 running inxi (took like 10 mintuies to complete...crazy long for simple process - where is that backup/restore/proot performance update script coming along @corbinlc )
![inxi-from-ssh-into-note8](https://user-images.githubusercontent.com/3161117/53458671-10a4e400-3a05-11e9-879e-9abce1a1a459.PNG)

**Comment by AndrewScibek** [comment]
Thats just how ssh works. You could also do something along the lines of 
`ssh ssh://user@192.168.29.148:22` 

```ssh connects and logs into the specified destination, which may be specified as either [user@]hostname or a URI of the form ssh://[user@]hostname [:port]. The user must prove his/her identity to the remote machine using one of several methods (see below).```
From [man](https://man.openbsd.org/ssh)

**Comment by lewisdonofrio** [comment]
I was doing that "donofrio@LTAL0111:$ ssh user@192.168.29.148:2022" but only -p worked....just seems hinky

**Comment by AndrewScibek** [comment]
No you literally have to put ssh:// in front of it. Weird i know.

**Comment by AndrewScibek** [comment]
Feel free to join our slack channel if you haven't already if you have any other issues like this.
