### ISSUE TITLE
How to install ngrok  kali (userland)  Illegal instruction 

### ISSUE THREAD

**Issue by Talben1994** [CypherpunkArmory/UserLAnd#669]
# Describe the issue you are having.

This should include things like:
- What you are trying to accomplish
- What you have tried so far

# Describe how your task behaves in a regular Linux environment

Describe how the task you are trying to accomplish behaves in a regular Linux environment, if applicable.

**Comment by Talben1994** [comment]
Illegal instruction 
Ngrok (in thé kali of apk userland)

**Comment by corbinlc** [comment]
Please fill in the template.  Please provide what commands you used and the exact output that shows the error.  Also, please provide what device you are using and what version of Android.  Please look at the original template.

**Comment by corbinlc** [comment]
No addition information was ever provided.  We cannot duplicate this, so I am closing it.
