### ISSUE TITLE
Dbus issues while trying Desktop Environments

### ISSUE THREAD

**Issue by MoreThanHidden** [CypherpunkArmory/UserLAnd#67]
Dbus + shared object issues, ran into this trying to get a working desktop environment, have tried lxqt,  xfce4 and gnome all with similar issues.

**Few Examples:**
- xfce4: `Gdk-WARNING **: shmget failed: error 38 (Function not implemented)`

![image](https://user-images.githubusercontent.com/1351964/42033092-45792b98-7b0e-11e8-9f1c-b4b5228ce479.png)
![image](https://user-images.githubusercontent.com/1351964/42033139-6fb17b04-7b0e-11e8-944b-80745b64437d.png)

- qTerminal: `error while loading shared libraries: libQt5Gui.so.5: cannot enable executable stack as shared object requires: Permission denied`
- terminator: `dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken`

Have been using JWM as a desktop for the time being as it seems to be working fine.

**Comment by MoreThanHidden** [comment]
Alright looking into this further, dbus service isn't running:
```
user@localhost:~$ sudo service dbus status
[FAIL] dbus is not running ... failed!
user@localhost:~$ sudo service dbus start
[....] Starting system message bus: dbusUnknown group "network" in message bus configuration file
. ok
user@localhost:~$ sudo service dbus status
[FAIL] dbus is not running ... failed!
```

**Comment by sstt011** [comment]
@MoreThanHidden my dbus starts successfully but I still have this problem... The error still occurs...

**Comment by AdamMatthewLTM** [comment]
I can confirm that the dbus issues no longer affect my particular device(android samsung running 7.0). I am closing this thread, if people are STILL have issues with dbus please move all of your comments and issues filed to #157 and I will re-open that thread. 

Thank you all for your time and understanding,
-Adam
