### ISSUE TITLE
Feature Request - No-Root Offline Backup and Restore

### ISSUE THREAD

**Issue by scratchkernel171** [CypherpunkArmory/UserLAnd#673]
# Describe the problem your feature request solves.
While installing any Distro the source files have to be downloaded again and again, which is time consuming.

# Describe the solution you'd like 
I would like an Offline install feature by using cloned repository files, and a Backup and Restore feature
to restore my Distro anytime without Internet. And just like the App itself, a No-Root solution would be awesome.

# Describe alternatives you've considered
I've considered using Titanium Backup, but that's not a solution for Non-Rooted devices.

# Additional context
I've tried adding Distro Assets to the Download and Private Data (root) directories, but the app neglects it and continues a fresh installation.

**Comment by lewisdonofrio** [comment]
sounds like someone else that wants this support - https://github.com/CypherpunkArmory/UserLAnd/issues/162
