### ISSUE TITLE
UserLAnd becomes awfully laggy after some time

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#68]
After some time of using UserLAnd it becomes terribly unresponsive. Killing and restarting service helps. I know it doesn't tell much and is hard to reproduce but. I'd like to ask for suggestions about how to debug such thing. I usually have `socat` and `pulseaudio` running in background via `screen`

When proot becomes unresponsive, killing pulseaudio and socat doesn't help. Only restarting UserLAnd service. When it's unresponsive ssh session sometimes crashes or hangs during normal operation. Simple ls command takes few seconds and even printing empty line in shell takes around 0.5-1 second which is quite bad considering how simple operation it is. CPU load is also significant and phone overheats on "idle"

After restarting UserLAnd service everything is back to normal

**Comment by AdamMatthewLTM** [comment]
@lapsio , 

Thanks for posting this. I have had difficulty replicating the lag issues you are having, but as you said doing so may be difficult. I've tested out leaving the application on with services running in the background for approximately one hour at a time on different Android versions, but did not notice any particular lag on my end.

Is there a specific use case you could recommend that I may be able to duplicate and confirm that this issue happens consistently? 

Regardless of my personal ability to duplicate this, I am going to mark this as high priority until further notice and recommend it remain open until a confirmation of a bug is made and a confirmation of a fix is implemented.

Thanks,
-Adam

**Comment by lapsio** [comment]
I experienced this issue twice since installation of UserLAnd. It occured for the first time after around 1 day and second time around 2 days since UserLAnd boot. In both cases I noticed something is wrong because of crazy phone temperature.

In both cases I did something like this:
I have autorun.sh script added to config.fish (equivalent of .bashrc, I'm using fish shell)

<I'll post content of script here as edit from phone>

pulseaudio has configured only dummy output and simple tcp server enabled (to be used with PuleDroid or Simple Protocol Player from Play Store. Basically to play pulseaudio stream over localhost on Android).

Then I'm launching `cmus` in screen (with exported PULSE_SERVER=tcp:localhost:4713 over because UserLAnd seems to have problems with `DBus` and `/dev/shm` so applications can't see pulseaudio server automatically) and detaching from it so that it runs in background together with socat and pulseaudio server and then I'm disconnecting from UserLAnd. At this point there's no active ssh sessions to UserLAnd and there are 3 `screen` detached sessions in background.

Then I'm enabling Simple Protocol Player to listen to music. After some time I'm stopping it but I don't see any reason to stop cmus or pulseaudio so they just run in background as I believe decoding mp3 is not too much of battery drain so I don't care.

After few days of this cmus playing music phone gets really hot. When I'm connecting to UserLAnd it's terribly laggy, sometimes ssh connection even crashes. Stopping cmus, killing pulseaudio and socat and stopping all screen sessions doesn't help. As I said only restarting UserLAnd service makes it usable again.

**Comment by yourpleasure** [comment]
I came across this problem too. And I found a walk around. Changing screen direction sloved my situation. I think this might be a output problem. May this help.

**Comment by yourpleasure** [comment]
I came across this problem too. And I found a walk around. Changing screen direction sloved my situation. I think this might be a output problem. May this help.

**Comment by lapsio** [comment]
I noticed that when I kill service and start it again socat process persists in weird hanged state. I can't start new socat because it fails on address in use, trying to kill socat does nothing and it doesn't forward connections. Only kill -9 actually kills it so that I can relaunch it.

**Comment by lapsio** [comment]
Something I didn't mention before - I had pulseaudio misconfiguration that led to restarting PA server every around 5 seconds. If it did that for 2 days I'd say it generated A LOT of processes which crashed. Maybe there are some issues with handling thousands of processes?

**Comment by AdamMatthewLTM** [comment]
I am closing this thread for the following reason:

With ULA version 0.5.1 there shouldn't be any lag issues with devices running android 7.0 and higher. I have done testing across multiple versions and phone models, and was unable to replicate the issue even leaving the devices on for days at a time.

If this problem still persists, please let me know and I will re-open this thread ASAP and include as much information as possible.

Thanks for your time and patience,
-Adam

**Comment by rflmota** [comment]
I'm also facing similar behaviour on remote accessing ssh to an android sleeping and with screen turned off. Is it because app is running in background? is there any way to overcome this problem? How can I debug it?

**Comment by lapsio** [comment]
@rflmota if after unlocking screen everything goes back to normal then it's standard behavior. It's because Android downclocks CPU and iirc disables all cores except 1 when device is sleeping. 

On rooted devices with Linux chroot it can be observed with top - when device is asleep top sees only 1 core instead of 4 visible when device is awake (some linux tools glitch because of that since they're not prepared for "disappearing" cores). UserLAnd doesn't prevent device from sleeping so when screen goes off it may downgrade performance quite heavily.

There are 2 ways to prevent that - 1 use app like Awake to keep screen on or BlackScreen to keep screen on even though it's off (makes sense only for OLED), 2 - use app that prevents device from sleeping. There are some apps that do that but be aware that it drains battery A LOT.

I was referring to app becoming sluggish permanently - even with screen on. Haven't noticed such behavior for quire a while now so I assume it's been fixed.

**Comment by rflmota** [comment]
@lapsio , you're probably right, I will do some more tests and report if the issue persists. Thank you for your support.

**Comment by rflmota** [comment]
Another thing I noticed, an unusual behavior (at least for me), that could possible be related, is that the remote shell ssh session sometimes seems to "hang" for a long time, but quickly updates the terminal output if a key is pressed for instance... Could this be explained by the same conditions?
