### ISSUE TITLE
Feature Request - Compare it to Tmux

### ISSUE THREAD

**Issue by koppa** [CypherpunkArmory/UserLAnd#680]
Tmux is the currently most well known Android App for running Linux tools in Android.

By default it ships it own package manager and many tools are compatible. There is also the possibility to run a `proot` for a chroot environment.
Visitors of this project would be interested how both UserLAnd compares to Tmux, and why they should choose one or the other.

I would for now add small paragraph into the wiki and maybe add a reference to the landing page and Readme

**Comment by corbinlc** [comment]
I don't want to make a comparison in the readme, as I don't really want to maintain it there.  Also, the ways that UserLAnd will be different is not fully known outside of the paid development team.  How they are different will be more stark and more apparent before the end of this year.  I will let others talk about how the are different, pros and cons and such.
