### ISSUE TITLE
HELP!! Ubuntu 18.04 rootfs failed to uninstall after factory data reset.

### ISSUE THREAD

**Issue by JasonsDoomGitHub** [CypherpunkArmory/UserLAnd#682]
The issue is that I know have an extra 3gb of used up memory in internal storage [/storage/emulated/0], making it a total of 6 used up gigabytes. And that is after I factory data reset the device (Samsung Galaxy j7).I figured since you only need to uninstall app to uninstall the Linux Distribution, I just went right ahead and relayed factory data reset through GUI. Initially I was settings up config_file for udev rules or something related to that package,  can't remember the specific name but it was related. Long story short, there were a few errors when the packages were downloaded, wifi connection lagged. I then manually fixed the issues and proceed to install a Desktop environment and that's when the ssh terminal froze. My question is how to I delete those residual files from my android phone. On android OS, the Internal memory partition reads that there is and additional subdir that is similar to dir /storage/emulated (enc_emilated) and that's where the additional 3gb of files are or so I think since Userland loads onto external drive right? But there are files in ext4 that shows it contains a good amount of mb. But I'm not sure how to go about this. I installed Ubuntu again and through CLI uses cmd fdupes and fslint to search for residual files and there is a bunch of files pertaining to /data directorie and similar root files i.e. ./data ./etc ./usr  ect... I'm running android OS v.8.1.0 on Samsung Galaxy j7 sm_j727r4 ,, not rooted 
So to whom ever this may intrest I would really appreciate the help. Seems like the solution to this should be to delete all residual files on host-rootfs using the root ssh but that will take forevermore....
Sorry if it seems like a Roockie question but that's because I am.. but I must prevail!!!
Yours truly 
-jasonsdoom

**Comment by JasonsDoomGitHub** [comment]
Thanks for the quick response and regarding the issue, I update the post..

**Comment by corbinlc** [comment]
Just simply uninstalling the app should be all that is needed.  The filesystems are only created in internal storage, not on the emulated or real sdcard partition.  A factory data reset should definitely blow away anything from UserLAnd.  Are you sure it is something from UserLAnd taking up all that space?

**Comment by JasonsDoomGitHub** [comment]
Yes, it is definitely related to UserLand. 
A couple hours ago I reinstalled the app and was trying to delete the duplicate packages and all its files but we are talking about at least 4gb. Originally the phone has 16gb of available storage and when I first bought the device it had at least 13 GB of available storage minus the 2ish GB of used storage for the host-rootfs. To no avail, I uninstalled the app and boom now it went from 6gb to 8gb of used internal storage. Honestly either there's a script that is mounted onto the host-rootfs or some how after uninstalling again, the contents of UserLAnd stayed on device due to the fact that right before I relayed a factory data reset I had unlocked the OEM bootloader because I was updating the phone via OAT. (Idk why I unlocked it) but ever since then I noticed the issue. Here i will take a snapshot of devices storage. You will see that there's really nothing that should take that much space. I literally have 2 apps. I was using X-plorer file manager and was browsing the rootfs and yeah definitely it has to be it. How am I so positive we'll in one .text file there were scripts related to Ubuntu (bionic beaver) were the key words that made me so sure it's part of UserLAnd which is by the way an Extraordinary App. Since postings this I went into devices developers settings and toggled off the OEM bootloader switch. Another thing I was also doing at the time of this unfortunate setback was looking into how to mount Ubuntu onto the device itself some what like Anbox. But didn't really start doing it. Because of present issue. Like I mentioned, I tried installing app to use proot.sh to go into file system as root user to fix the issue but there's a lot....... can I some how use the cmd like (purge) to erase multiple packages I know that either cmd (fslint) or (fdupes) can find residual files or duplicates. But like mentioning before, its 7gb.

**Comment by JasonsDoomGitHub** [comment]
Or the issue could pertain to a Fusefs module bridging the kernel to the partition that UserLAnd occupies when it is installed.

**Comment by corbinlc** [comment]
You cannot install fusefs in UserLAnd.  That requires real root permissions.

**Comment by JasonsDoomGitHub** [comment]
$ cd
$ pwd
/data/data/com.termux/files/home
$ cd /
$ ls -l
total 3324
dr-xr-xr-x 93 root root 0 Jan 1 2017 acct
-rw-r--r-- 1 root root 226 Dec 31 1969 android.hardware.drm@1.0-service.widevine.rc
-rw-r--r-- 1 root root 43351 Dec 31 1969 audit_filter_table
drwxr-xr-x 2 root root 40 Dec 31 1969 bt_firmware
lrwxrwxrwx 1 root root 50 Dec 31 1969 bugreports -> /data/user_de/0/com.android.shell/files/bugreports
drwxrwx--- 8 system cache 4096 Mar 10 03:41 cache
lrwxrwxrwx 1 root root 13 Dec 31 1969 charger -> /sbin/charger
drwxr-xr-x 3 root root 0 Dec 31 1969 config
lrwxrwxrwx 1 root root 17 Dec 31 1969 d -> /sys/kernel/debug
drwxrwx--x 58 system system 4096 Mar 10 15:52 data
-rw------- 1 root root 1173 Dec 31 1969 default.prop
drwxr-xr-x 17 root root 4180 Jan 1 2017 dev
drwxr-xr-x 3 root root 4096 Dec 31 1969 dsp
drwxrwx--x 32 radio system 4096 Mar 10 03:41 efs
lrwxrwxrwx 1 root root 11 Dec 31 1969 etc -> /system/etc
dr-xr-x--- 4 system system 16384 Dec 31 1969 firmware
dr-xr-x--- 4 root system 16384 Dec 31 1969 firmware-modem
-rwxr-x--- 1 root root 2147104 Dec 31 1969 init
-rwxr-x--- 1 root root 3201 Dec 31 1969 init.container.rc
-rwxr-x--- 1 root root 1823 Dec 31 1969 init.environ.rc
-rwxr-x--- 1 root root 79041 Dec 31 1969 init.rc
-rwxr-x--- 1 root root 3029 Dec 31 1969 init.recovery.qcom.rc
-rwxr-x--- 1 root root 11262 Dec 31 1969 init.usb.configfs.rc
-rwxr-x--- 1 root root 5721 Dec 31 1969 init.usb.rc
-rwxr-x--- 1 root root 4285 Dec 31 1969 init.wifi.rc
-rwxr-x--- 1 root root 497 Dec 31 1969 init.zygote32.rc
-rwxr-x--- 1 root root 847 Dec 31 1969 init.zygote64_32.rc
drwxr-xr-x 12 root system 260 Jan 1 2017 mnt
-rw-r--r-- 1 root root 96291 Dec 31 1969 nonplat_file_contexts
-rw-r--r-- 1 root root 6543 Dec 31 1969 nonplat_hwservice_contexts
-rw-r--r-- 1 root root 12086 Dec 31 1969 nonplat_property_contexts
-rw-r--r-- 1 root root 9003 Dec 31 1969 nonplat_seapp_contexts
-rw-r--r-- 1 root root 1821 Dec 31 1969 nonplat_service_contexts
drwxr-xr-x 3 root root 60 Dec 31 1969 oem
drwxrwx--x 16 root system 4096 Jan 1 2017 persist
-rw-r--r-- 1 root root 21779 Dec 31 1969 plat_file_contexts
-rw-r--r-- 1 root root 5768 Dec 31 1969 plat_hwservice_contexts
-rw-r--r-- 1 root root 4399 Dec 31 1969 plat_property_contexts
-rw-r--r-- 1 root root 1161 Dec 31 1969 plat_seapp_contexts
-rw-r--r-- 1 root root 39043 Dec 31 1969 plat_service_contexts
-rw-r--r-- 1 root root 2088 Dec 31 1969 postrecovery.do
drwxrwx--x 2 system system 40 Jan 1 2017 preload
dr-xr-xr-x 489 root root 0 Dec 31 1969 proc
-rw-r--r-- 1 root root 1509 Dec 31 1969 publiccert.pem
drwxr-xr-x 3 root root 60 Dec 31 1969 res
drwx------ 2 root root 40 Jan 16 23:35 root
drwxr-x--- 2 root root 200 Dec 31 1969 sbin
lrwxrwxrwx 1 root root 21 Dec 31 1969 sdcard -> /storage/self/primary
-rw-r--r-- 1 root root 742378 Dec 31 1969 sepolicy
-rw-r--r-- 1 root root 691 Dec 31 1969 sepolicy_version
drwxr-xr-x 5 root root 100 Mar 10 15:52 storage
dr-xr-xr-x 12 root root 0 Jan 1 2017 sys
drwxr-xr-x 24 root root 4096 Jan 1 2017 system
lrwxrwxrwx 1 root root 16 Jan 1 2017 tombstones -> /data/tombstones
-rw-r--r-- 1 root root 5739 Dec 31 1969 ueventd.rc
lrwxrwxrwx 1 root root 14 Dec 31 1969 vendor -> /system/vendor
-rw-r--r-- 1 root root 524 Dec 31 1969 verity_key
-rw-r--r-- 1 root root 624 Dec 31 1969 vndservice_contexts
$ -
This is on termux terminal. Without and linux Distribution. 
Can you tell me what you think about it.

**Comment by JasonsDoomGitHub** [comment]
This is the (ls -r) relay from the ~$cd / directory 
I want to send you the (ls-R) output but I don't want to unintentionally forget to exclude any info that will be useful to ........ 
Do keep in mind I am a noob to the whole concept of developing and modifying. So I have little knowledge on how to read or write code but I am determined nevertheless. Honestly I just need a little push to get me going on the right path to fixing the issue. I would love to keep using Userland but first I need to delete the excessive amount of residual files so I can start fresh. But I'm afraid that the Distribution is just going to use up all of the storage that is currently available. I don't have a laptop, only a Samsung Galaxy j7 and my brain.
But here you go 
$ pwd
/data/data/com.termux/files/home
$ cd /
$ pwd
/
$ ls -r
vndservice_contexts
verity_key
vendor
ueventd.rc
tombstones
system
sys
storage
sepolicy_version
sepolicy
sdcard
sbin
root
res
publiccert.pem
proc
preload
postrecovery.do
plat_service_contexts
plat_seapp_contexts
plat_property_contexts
plat_hwservice_contexts
plat_file_contexts
persist
oem
nonplat_service_contexts
nonplat_seapp_contexts
nonplat_property_contexts
nonplat_hwservice_contexts
nonplat_file_contexts
mnt
init.zygote64_32.rc
init.zygote32.rc
init.wifi.rc
init.usb.rc
init.usb.configfs.rc
init.recovery.qcom.rc
init.rc
init.environ.rc
init.container.rc
init
firmware-modem
firmware
etc
efs
dsp
dev
default.prop
data
d
config
charger
cache
bugreports
bt_firmware
audit_filter_table
android.hardware.drm@1.0-service.widevine.rc
acct
$

**Comment by JasonsDoomGitHub** [comment]
Unbelievable woow.. Damn I think I know what is taking up 6gb of memory but still not 100% sure. Need another perspective on this.
So as it turns out the preinstalled apps that come with the phone apparently take up around 3.5gb plus the kernel etc is around 2ishgb. 
Damn if that's really true then that's a bunch of bs. 
Seriously I don't know why companies advertise false information. They really should say "hey this here phone has 16gb but you only get to use half that"

**Comment by JasonsDoomGitHub** [comment]
Yea, my bad. Had to hit the books really quick. but what if it was possible, what if...
Let's say it did happen some how some way on a phone with no root. And there really are residual files and folders left behind. Would I be able to delete every single trace of ubuntu that was left behind?
And how would I delete every single trace of residual files and folders left behind by ubuntu but with root privileges?
Sorry but not all information that is online isnt always accurate but it's all trial and error. But back to the main issue, I did find either a .text file or a .sh file pertaining to Ubuntu. And this is after hard factory resetting and even updating firmware literally half a hour later. Is there any output I can send you or post that would be useful to read and identify if there really isn't, like cmd ~$ la-R or similar? you never know, I mean this is Linux. I would really appreciate the help.

**Comment by corbinlc** [comment]
Our app installs and uninstalls like a normal app, so any failure for it to be removed by an uninstall or a factory data reset would be a problem with Android and outside of our control.  If really interested, our files live under `/data/data/tech.ula` .   If there are files there, but you have UserLAnd uninstalled, then Android failed the uninstall for some reason.

**Comment by corbinlc** [comment]
btw... you are correct.  Even Android plus preinstalled apps is getting bloated.  So you can have a lot of our disk taken up right out of the box.
