### ISSUE TITLE
closed session after dpkg - -configure - a

### ISSUE THREAD

**Issue by the-sniper1990** [CypherpunkArmory/UserLAnd#689]
I am running kali Linux. I tried to get the xfce4 desktop environment but it didn't work so I tried to run apt-get install xfce4 but it told me to run 
dpkg - -configure - a after I ran the output was :
Setting up man-db (2.8.5-2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the
 dialog based frontend cannot be used. at /usr/share/perl5/D
ebconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
Building database of manual pages ...

Connection Lost

**Comment by lewisdonofrio** [comment]
Not sure how you got the broken dpkg request, if you run it again does it get better.  I run Ubuntu and xfce4 fwiw - http://www.tinyurl.com/donofriodexnote8

**Comment by corbinlc** [comment]
@the-sniper1990 please update based on the template the bot pointed you at.  There is more information required before we can help.

**Comment by corbinlc** [comment]
No info was every provided.  Closing this.
