### ISSUE TITLE
Firefox crash

### ISSUE THREAD

**Issue by kristianpaul** [CypherpunkArmory/UserLAnd#691]
# Describe the bug

A clear and concise description of what the bug is, and what expected behavior is. Include whether the bug occurs **before** 
or **after** entering a terminal or vnc client session.

# Steps to reproduce the behavior:
Download Firefox
Connect from your computer or locally via VNC

Run firefox

# Screenshots

https://imgur.com/a/gzsx0uH

# Device Information

Device: Nokia 2.1
Android Version: 9
UserLAnd Version from f-droid

**Comment by corbinlc** [comment]
Ignore the bot, you provided enough info, except can you tell me what distro you are using and the exact commands you used to install and run firefox.

**Comment by lewisdonofrio** [comment]
crashes like this https://github.com/CypherpunkArmory/UserLAnd/issues/470 or black screen issue - https://github.com/CypherpunkArmory/UserLAnd/issues/403 ?

**Comment by corbinlc** [comment]
A few questions have been asked, without reply.  As such, I am closing this.  Please chime in on the existing firefox related issue, if they are appropriate.  Or, if your issue is unique, please reopen this issue with more info, so we can continue forward.
