### ISSUE TITLE
Can't ifconfig wlan huawei

### ISSUE THREAD

**Issue by RobotAm91** [CypherpunkArmory/UserLAnd#696]
Huawei Mate 20 Pro, Android 9

Hi! I have a problem With wifi, I can Download, but I can't config wlan0. I updated the firmware, and iwlwifi and doesn't work

/data/data/tech.ula/files/support/dbclient: Caution, skipping hostkey check for localhost

Me@localhost's password:
Welcome to Kali in UserLAnd!
Me@localhost:~$ ifconfig wlan0
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.114  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 xxxxxxxxxxxxxxxxx
prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 229109  bytes 295258644 (281.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 151831  bytes 18815424 (17.9 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

Me@localhost:~$ ifconfig wlan0 up
SIOCSIFFLAGS: Permission denied
Me@localhost:~$ sudo airmon-ng start wlan0/usr/sbin/airmon-ng: 114: [: 0: unexpected operator
ls: cannot open directory '/sys/class/ieee80211/': Permission denied

ls: cannot open directory '/sys/class/net': Permission denied

PHY     Interface       Driver          Chipset

null    p2p0            ??????          non-mac80211 device? (report this!)
null    wlan0           ??????          non-mac80211 device? (report this!)

Me@localhost:~$

**Comment by corbinlc** [comment]
`/sys` is not an accessible directory unless you are running as real root.  UserLAnd does not support running as real root yet.  Please look for future updates where we support running as real root (when this comes you will need to have a rooted device to take advantage of it).
