### ISSUE TITLE
Android Pie shuts down UserLAnd after about 12 hours

### ISSUE THREAD

**Issue by jrvarma** [CypherpunkArmory/UserLAnd#705]
After upgrading my Samsung Galaxy Note 8 to Android P, I find UserLAnd shuts down after about 12 hours. I have a cron job which writes to a file every half an hour, and I can see that the entries stop somewhere in the night. Never had this problem in the same phone in Android Oreo. Is there some extra permission required in Android 
P?

**Comment by EnderNightLord-ChromeBook** [comment]
um... just pretty much storage... If you want it on all night just try an app called: https://play.google.com/store/apps/details?id=eu.aboutall.android.tools.kepscreenon

Then just plug in your device so it doesn't run out of charge.

**Comment by jrvarma** [comment]
# Describe the bug

After upgrading  to `Android P`, I find `UserLAnd` shuts down after about 12 hours. I use only terminal (`ssh`) clients and no `vnc` clients.

# Steps to reproduce the behavior:

1. Start `UserLAnd` session, `ssh` into it and start some daemons. For example:

    * I usually have an `emacs` daemon running with a few files open so that I can start an `emacsclient` any time very quickly and see all the open files immediately.

    * I have a `cron` job which writes to a file every half an hour.

2. Run commands in the terminal as and when needed during the day.

3. At night, plug the phone into the charger and go to bed. 

4. Check the phone in the morning: 

    * Find that `UserLAnd` is not running. 

    * Look at the output from the `cron` job (after restarting `UserLAnd`) to find that entries stop sometime during the night.

# Screenshots

Not applicable

# Device Information

Device: Samsung Galaxy Note 8.  
Android Version: Pie 9.0.  
UserLAnd Version: 2.3.8.  
Whether the device is rooted: No
Whether the device is running LineageOS: No

# Additional context

* `UserLAnd` has been granted all permissions sought by it.

* I do not mind `Android` shutting down the `ssh` client (and I may shut it down myself) so long as the `UserLAnd` session is running and all the daemons are running.

* Never had this problem in the same phone in `Android Oreo`.

**Comment by jrvarma** [comment]
> um... just pretty much storage... If you want it on all night just try an app called: https://play.google.com/store/apps/details?id=eu.aboutall.android.tools.kepscreenon
> 
> Then just plug in your device so it doesn't run out of charge. and don't forget to pull down the brightness.

I do not care about the screen at all. I just want the daemons to keep running in the background.

**Comment by EnderNightLord-ChromeBook** [comment]
Hmm... i'm not sure how to do that. lemme look around uncle googles place for answers.

**Comment by stackerlon** [comment]
My userland is still working on pie, about 30 hours passed. Did you whitelisted userland in power setting? Also there is new Google feature Digital wellbeing which automatically kills every single app when it detects that user is not using the phone (most likely at night times), I removed this feature.

**Comment by jrvarma** [comment]
My problem went away after upgrading to UserLAnd 2.4.0. 

UserLAnd ran without shutdown for around 36 hours; then I restarted the phone and ran it again without shutdown for around 36 hours. 

Issue may be closed.
