### ISSUE TITLE
Bug report - Nothing works on MiBox Android 8.0

### ISSUE THREAD

**Issue by RonCan** [CypherpunkArmory/UserLAnd#709]
# Describe the bug

Simply trying to add any distro or application fails. The downloads completes but then I get the error `[H[Jtar: can't change directory to '/': Function not implemented` after verifying assets

# Steps to reproduce the behavior:
Fresh install of UserLand. Nothing special just try to add any distro or application

# Device Information

Device: [Xiaomi MiBox].  
Android Version: [Oreo, 8.0].  
UserLAnd Version [2.3.8].  
Not Rooted  
Stock

# Additional context

N/A

**Comment by corbinlc** [comment]
"Function not implemented" is almost certainly a PRoot error.  We should be able to fix this.  Can you go to settings within the app and enable PRoot debugging and set the PRoot debug verbosity to 9?  Then can you try to add a distro and see the same error?  After that there should be a PRoot_Debug_Log file on your device.  Often it is /sdcard/PRoot_Debug_Log.  If you can find that and send it to us, we should be able to help.

**Comment by RonCan** [comment]
@corbinlc thanks for a great tool. Please find the [debug log](https://pastebin.com/x62PjC2b) here.

**Comment by EnderNightLord-ChromeBook** [comment]
found another Function Error: 

tar: can't change directory to '/': Function not implemented (line 179... It's the only one.)

**Comment by RonCan** [comment]
@EnderNightLord-ChromeBook is there something I can do about this? Or is it something that needs to be fixed in the framework?

**Comment by MatthewTighe** [comment]
This is likely related to issues we've had with downloads and extraction. We're currently working on updating the process to follow a new flow that we hope will fix issues like this. Expect it to be releases within a week or so.

**Comment by corbinlc** [comment]
Sorry, the new reference to this issue got me to look at this again.  From the PRoot log, it looks like you device does not allow the `chdir` system call.  We have not had to work around that one before in PRoot.  That is a very basic system call.  I suppose we would to replace `chdir` with `open` plus `fchdir`.  Chaining system calls (turning one call into two or more) is ugly, but can be done.

**Comment by corbinlc** [comment]
@RonCan this took a long time for me to get to, understand and fix.  My apologies.  Recently a bunch of Samsung devices got upgraded to versions of Android that show this issue and so became of interest to fix it more urgently.  See #1014 .  I just fixed that issue in v2.6.3 (it may take a few hours until you see an option to update to that version).  Please give it a whirl.  Again, sorry I didn't dedicate the energy needed to solve this months ago.
