### ISSUE TITLE
Help - [Understanding Sudo, Tsu etcetera]

### ISSUE THREAD

**Issue by Areahints** [CypherpunkArmory/UserLAnd#718]
Whenever i login im asked to input password twice

```
kc@localhost:
Password:
```
then i get this
```
su: Authentication failure
Welcome to Ubuntu in UserLand
```
when i tried using sudo i remember setting the same password as the default login 
how do i fix this?

**Comment by Areahints** [comment]
all i need is instructions on how to remove su or su errors

**Comment by corbinlc** [comment]
I cannot simply reproduce this issue.  We will need you to follow the template and provide more info (like what version of Android you are running and what device you are using) to be able to take a shot at helping you.

**Comment by corbinlc** [comment]
I am closing this for now.  Please reopen it when/if you have the time to provide more information.
