### ISSUE TITLE
run R without vnc

### ISSUE THREAD

**Issue by rindj** [CypherpunkArmory/UserLAnd#720]
I'm running R occasionally.  I don't need graphics often and would prefer to use just the console (no VNC window).  Isn't there a Linux switch that will avoid opening the VNC window? I don't really like bVNC, is there a way to use a different terminal?

**Comment by SunbossRS** [comment]
I don't like bVNC too....   
  
You can try VNC Viewer then watch localhost:5951

**Comment by corbinlc** [comment]
Sure, if you long press on the app, then click app info, you can then change how you connect.  If you choose SSH instead of VNC, then it will just use a terminal.
