### ISSUE TITLE
Bug report - [after downloading assets the app shuts down]

### ISSUE THREAD

**Issue by sarigama** [CypherpunkArmory/UserLAnd#734]
# Describe the bug
the brand new update(the one youve changed the way to download assets) made my debian(ssh) session unable to launch. it downloads 2 assets but copying them(?) to the local storage shuts the app down

# Steps to reproduce the behavior:
i click my custom debian(ssh) session and everything goes autoatically
so i also tried both making another session and simply launching debian app but the result is similar .. downloads but copy makes things go wrong

# Device Information

Device: [Weko View Prime].  
Android Version: [7.1.2].  
UserLAnd Version [2.5.0].  
Whether the device is rooted.  no

**Comment by MatthewTighe** [comment]
Is there an error message?

**Comment by MatthewTighe** [comment]
This should be fixed in 2.5.1, which is rolling out now.
