### ISSUE TITLE
Feature Request - Ubuntu 19.04 TLS (for beta testers)

### ISSUE THREAD

**Issue by lewisdonofrio** [CypherpunkArmory/UserLAnd#737]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the problem your feature request solves.
No problem just would like to test 19.04 before it's released to ensure it works as good as 18.04 does on my note8

# Describe the solution you'd like 
here is the location to "Disco" http://cdimage.ubuntu.com/ubuntu-base/daily/20190325/

this link describes speed increases that I'd like cause even after newest proot it's still slow considering I have 8 cores on my note8
https://www.phoronix.com/scan.php?page=article&item=ubuntu-1904-first&num=1

# Describe alternatives you've considered
Please consider this - I mean i might just try a do-release-upgrade but figured I'd see if you folks could just wave your hands and then I could select 19.04 and rebuild my session. 

Please add any other context or screenshots you think might help us resolve your issue.

**Comment by EnderNightLord-ChromeBook** [comment]
A while ago I have tried to make rootfs for 18.10 but failed to build properly. I would like to help with this project.

**Comment by lewisdonofrio** [comment]
19.04 will be live in three days - fwiw.

**Comment by corbinlc** [comment]
I have added this to #581, as such, I am closing this issue.  Please follow that one.  Btw... right now we only support one flavor of each distro.  We have plans for multiple flavors in the future (somewhat distant) and to allow custom ones (probably closer) built by the user or grabbed from say dockerhub.  We will talk about this all more at #581.
