### ISSUE TITLE
Bug report - [It does not move from Verifying assets]

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#739]
# Describe the bug
After 2.5.1, I stopped working from Verifying assets ...
I also cleared the cache and I did clear all support files, but I can't fix it.

# Steps to reproduce the behavior:
1. Go to 'Sessions'

2. Click on 'my Session'

3. Scroll down to 'N/A'

# Screenshots
![Screenshot_20190328-164118_UserLAnd](https://user-images.githubusercontent.com/43949163/55196997-8367d180-51f4-11e9-81dc-96f5a53dbf96.jpg)

# Device Information

Device: [Galaxy S9+(SCV39)].  
Android Version: [Pie(9.0)].  
UserLAnd Version [2.5.1].  
Whether the device is rooted.  
No

Whether the device is running LineageOS 
What lineageOS ?

**Comment by lewisdonofrio** [comment]
Welcome fellow dex user (mysetup is http://www.tinyurl.com/donofriodexnote8) I'm guessing if you kill the program from settings and try again it should work...

**Comment by Zel9278** [comment]
> Welcome fellow dex user (mysetup is http://www.tinyurl.com/donofriodexnote8) I'm guessing if you kill the program from settings and try again it should work...

Thanks comment

I also tried to kill, but I remained with Verifying assets.

**Comment by MatthewTighe** [comment]
How long have you waited to see if it completes?

**Comment by MatthewTighe** [comment]
I can't seem to reproduce this one. Does clearing support files seem to succeed, i.e. it doesn't crash? 

Are new files downloaded after you clear support files?

**Comment by Zel9278** [comment]
Yes, the session was from a previous version
I waited maybe 30 minutes

> How long have you waited to see if it completes? Did the session exist prior to 2.5.1?

I will not crash at all
No new files are added ...


> I can't seem to reproduce this one. Does clearing support files seem to succeed, i.e. it doesn't crash?
> 
> Are new files downloaded after you clear support files?

**Comment by MatthewTighe** [comment]
Just to clarify, nothing is downloaded after you try to clear support files and start the session again? It should download 2 files. The steps should be:

You:
1. Clear support files
2. Click session to start it

Automatically done:
3. Session fetches asset lists
4. Session generates download requirements
5. Session downloads 2 files
6. Session verifies assets
7. Session starts

Some of those steps may happen too quickly to really see, but they should all be there. If assets aren't being redownloaded, you may have to try uninstalling.

**Comment by Zel9278** [comment]
> Just to clarify, nothing is downloaded after you try to clear support files and start the session again? It should download 2 files. The steps should be:
> 
> You:
> 
> 1. Clear support files
> 2. Click session to start it
> 
> Automatically done:
> 3. Session fetches asset lists
> 4. Session generates download requirements
> 5. Session downloads 2 files
> 6. Session verifies assets
> 7. Session starts
> 
> Some of those steps may happen too quickly to really see, but they should all be there. If assets aren't being redownloaded, you may have to try uninstalling.

It has been downloaded, but it remains as Verifying assets.
https://drive.google.com/file/d/1h9uqcnLRHmprts8sMgfqspbQ83p8jTUW/view?usp=drivesdk

**Comment by MatthewTighe** [comment]
Yeah, that's super strange. I'll look into it but without being able to reproduce I can't guarantee anything. If there's nothing on your filesystem worth preserving, it would be useful to me to know if uninstalling and reinstalling the entire application resolved the problem.

**Comment by Zel9278** [comment]
> Yeah, that's super strange. I'll look into it but without being able to reproduce I can't guarantee anything. If there's nothing on your filesystem worth preserving, it would be useful to me to know if uninstalling and reinstalling the entire application resolved the problem.

Ok, I will try to reinstall once.

**Comment by corbinlc** [comment]
@Zel9278 any update here?  Did re-installation help?

**Comment by RithikRoshan107** [comment]
verifying assets for more than 2 hours ...still....what should i do now???plz 
blob:https://web.whatsapp.com/aa736d3c-314c-4604-b389-d8dd8cdb2446

**Comment by RithikRoshan107** [comment]
![Screenshot from 2019-08-26 13-19-09](https://user-images.githubusercontent.com/54120178/63674525-3a816c80-c7d6-11e9-90f7-924ebe45eae8.png)
verifyinf assests more than 2 hrs and still....what should i do now...?

**Comment by corbinlc** [comment]
@RithikRoshan107 if the latest version (2.6.3) still shows this issue, please file a new issue.  The latest version fixed a couple of causes of this type of problem.  I believe the original issue being reported was fixed a while back.
