### ISSUE TITLE
Bug Report - Right-clicking issue found

### ISSUE THREAD

**Issue by Alfy102** [CypherpunkArmory/UserLAnd#742]
Connected a wired mouse on OTG. Right-click menu will cancel when moving the mouse to select the options in the menu. Had to hold down the right click button and quickly hover to the menu item and release the right-click in order to select an item.

But this must be done fast before android register the right-click hold as a "Back" request from the mouse right-click.

Device: Samsung Note 8
Android Version: Android 9 
UserLAnd Version 2.4
Non-rooted
Installed Ubuntu with LXDE.

**Comment by lewisdonofrio** [comment]
are you talking about within the gui of userland itself, or within your OS like inside Ubuntu? (my build is http://www.tinyurl.com/donofriodexnote8 fwiw)

**Comment by Alfy102** [comment]
> are you talking about within the gui of userland itself, or within your OS like inside Ubuntu? (my build is http://www.tinyurl.com/donofriodexnote8 fwiw)

It is within the OS. 

 Right click and hold for a few seconds does seem to invoke Userland hover GUI within the OS.

**Comment by lewisdonofrio** [comment]
and by os I was asking about the proot/chroot/userland hosted os not with android itself?

**Comment by Alfy102** [comment]
Yeah it is within Ubuntu, the right click menu disappeared on the hosted OS right after I move my cursor to select an item.

**Comment by lewisdonofrio** [comment]
this is what I get when I right click in ubuntu using xfce4 (my daily driver de)
![Screenshot_20190402-115233_XServer XSDL](https://user-images.githubusercontent.com/3161117/55417521-d7e5b680-553e-11e9-8b05-3662e2a0a304.jpg)

**Comment by Alfy102** [comment]
After using it several times, I can say that it is not an OS fault. It's more to the way the included VNC handles mouse instructions. 

BTW, I was really interested in the link you gave me on the XFCE installation. Might give that one a go.

**Comment by MatthewTighe** [comment]
Are you connecting through XSDL or VNC? In either case, right-clicks should be handled by apps on the client side. XServer XSDL is the only x server I know of on Android, but if you're using VNC you could try switching to a different client app to see if it has different behavior.

**Comment by Alfy102** [comment]
Yeah, I'm using bVNC Free that was recommended installation by Userland. I'll try to get this to work through XSDL and see how the right click behaves.

**Comment by Alfy102** [comment]
Look like I am unable to proceed with solving this issue on Xserver SDL due to constant restart error on Android 9.0 as mention here [#62](https://github.com/pelya/xserver-xsdl/issues/62). 
Userland development team acknowledged this issue as [#97](https://github.com/pelya/xserver-xsdl/issues/97)

So I'll have to wait for update from Xserver SDL

**Comment by lewisdonofrio** [comment]
What countdown?  I cannot get xfce to render if I do not have xdsl foreground, if background and console in foreground it will just wait till I click on xdsl and bring it maximized, then I get gui....

**Comment by corbinlc** [comment]
Ugh.  You are correct @Alfy102. XSDL does not work on Android 9.0 and that is out of our control.  If you are willing there are other ways to connect.  You could use a different VNC client.  We are running on display 51 or port 5951 depending on what it requests.  You might have to specify 127.0.0.1 or you might get away with localhost.  You can also connect from a computer on the same network using your phones ip address and the same display or port numbers specified.  We are just trying to understand if the issue is in UserLAnd or in the client.

**Comment by Alfy102** [comment]
Ok, I found where the problem lies. 

I installed vncserver on my Linux client and VNC Viewer on my android 9.0 phone. After logging in using Localhost:1, I connected a wired mouse and all mouse behaviour is as normal including the right clicks. 

I think bVNC does not handle right click instructions correctly for now.

**Comment by corbinlc** [comment]
Would you file an issue against bvnc (https://github.com/iiordanov/remote-desktop-clients/issues)?

**Comment by Alfy102** [comment]
Roger. Thanks for the help.
