### ISSUE TITLE
Bug report - [Wget and Curl error]

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#748]
# Describe the bug
When I installed wget and curl and tried it, I got an error.

# Steps to reproduce the behavior:
1. Install wget and curl
2. Download something
(curl [url])(wget[url])
3. Error

# Screenshots
![Screenshot_20190403-131421_VNC Viewer](https://user-images.githubusercontent.com/43949163/55452369-6e36dc80-5612-11e9-80da-ac2f631c68c3.jpg)

# Device Information

Device: [Galaxy s9+(SCV39)].  
Android Version: [9.0 pie].  
UserLAnd Version [2.5.2].  
Running Ubuntu

**Comment by corbinlc** [comment]
We are not able to replicate this at this time...
We have tried this on UserLAnd 2.5.2 and 2.5.3 using a Samsung Galaxy S9 (SM-G960U1) running Android 9.0.  This is not exactly the same, but is very close and as close as our team can get right now.
Are there any other commands you ran in that filesystem between when you install the filesystem and when you saw these errors?  Please be as complete as you can, maybe start from scratch and record all your history up until you see the issue.

**Comment by corbinlc** [comment]
We have not heard back in over a week.  We don't know what to do to help.  If you are still having an issue, please reopen this and answer the questions I sent last.

**Comment by Zel9278** [comment]
Sorry I'm late
The reason why wget and curl can not be used was because "software-properties-common" was installed.
