### ISSUE TITLE
Help - Setting time or date or timezone

### ISSUE THREAD

**Issue by Blocked** [CypherpunkArmory/UserLAnd#749]
# Describe the issue you are having.

System timezone(lxde/Debian) is set to UTC and I can't change it to anything else.

What I've done:

Set    

    TZ=[MY ZONE]; export TZ

to `.profile`. ssh seems to show correct date and tz. But vnc/lxde always shows utc.

Tried to access Time and date from lxde menu > Got insufficient permissions. No such file or directory.

Tried `hwclock` in ssh: unable to open `/dev/rtc`

# Describe how your task behaves in a regular Linux environment

Easily set date and time from menu.

**Comment by Herzogs** [comment]
Do you use dpkg-reconfigure tzdata?

**Comment by Blocked** [comment]
@Herzogs 

Thanks. That worked.
