### ISSUE TITLE
Feature Request - [CLOUD-9 IDE for userland]

### ISSUE THREAD

**Issue by Marcus0086** [CypherpunkArmory/UserLAnd#754]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the problem your feature request solves.

•Like Firefox browser , octave and other additional apps in Userland can we create a specialised app only for cloud9 ide server.

# Describe the solution you'd like 

•So it is actually a web based ide so what i want is to install it locally than i can have it working on my smartphone. It is based on node and npm so maybe it can work.

# Describe alternatives you've considered

•I haven't tried yet because of the less device storage and internet requirement so i leave it to you guys.

**Comment by corbinlc** [comment]
Can you provide the commands necessary to manually get cloud9 installed and running?  If you can do that, creating an app is not too hard.

**Comment by Marcus0086** [comment]
@corbinlc okk. So first clone their repo search c9sdk github and u will find it. Clone it then install some dependencies ( clang , gcc , python , tmux , ncurses , openssl , libssl-dev , npm) . Now open c9sdk directory and go to scripts directory then (chmod +x install-sdk.sh) and then (./install-sdk.sh) . Now wait for more than 2 hours. 
What's my issue was that it worked fine but during the tmux compilation something went wrong and after 1 hr it failed. So i leave issues to you. 
Thank you.

**Comment by corbinlc** [comment]
Oh so there is no existing package?  We are probably not going to take on the task of building it ourselves, especially without a known working recipe.  If you think the error you ran into is the fault of UserLAnd, maybe we should discuss that error first.

**Comment by Marcus0086** [comment]
@corbinlc ok thank you very much. There is no fault in Userland its just aarch64 architecture itself.
U can close it now.
