### ISSUE TITLE
Help - Restore the exported filesystem

### ISSUE THREAD

**Issue by pferdefreund** [CypherpunkArmory/UserLAnd#755]
# Describe the issue you are having.
I have seen that it is possible to export a filesystem. I use Debian on my smartphone with your app and it works fine as long i have networking at start (see my bug-report).
Is there a possibility to import the exportet filesystem ?
I thin an export makes no sense if there is not the possibility to restore thies export.

# Describe how your task behaves in a regular Linux environment

In a normal LInux-environment i normally make a full backup with tar (without /proc and /sys and when i kill my system through extreme experiments i simply restore my tar-file, write the bootloader (lilo) new and everything works as before. That is what would be nice to have with Userland too.

**Comment by pferdefreund** [comment]
i used the template for this help. I can't see what is missing - can you tell me, what is missing ?

**Comment by Herzogs** [comment]
if you want to import the filesystem that you had previously exported you have to create a new filesystem and in hidden options press "select backup for import"

**Comment by stephenprater** [comment]
@pferdefreund No worries - the issue bot is sometimes a little aggressive.   Let us know if @Herzogs advice didn't help you through your issue.

**Comment by MatthewTighe** [comment]
Additionally, the bot hasn't been updated yet to remove its posts once users fix their posts. It looks like your comment has definitely been updated to follow the format. Thanks for playing along with it!

**Comment by pferdefreund** [comment]
Ok i found, what Herzogs wrote in the menues. Everything is clear now. Thank you and greetings from germany
