### ISSUE TITLE
Cannot reopen sessions without data connection

### ISSUE THREAD

**Issue by ROWEND36** [CypherpunkArmory/UserLAnd#765]
It is what it is. I went to download Gnuroot which i had been using for over a year on my former phone and was redirected to userland. I installed it and loved it up until I tried to use it at a place wheremy wifi connection was weak. That's when I realised that I could not reopen sessions until assets were verified which needs internet. Is this normal( in which case, I would be disappointed) or is it a bug?

**Comment by corbinlc** [comment]
We just fixed that issue, can you tell us what version you have?  Also, please check for an update in the Play Store and see if a newer version is available.

**Comment by corbinlc** [comment]
I have not heard back and we believe we fixed this issue recently.  As such, I am closing this.  If you have more information to add, please do so and reopen this.

**Comment by liskin** [comment]
Can we perhaps add a configuration option to skip checking for asset updates altogether? Or check for it only on wifi? I can't see why I'd need to wait a couple dozens of seconds and waste my not at all unlimited data when all I need is to open a Debian terminal. :-/

**Comment by corbinlc** [comment]
This is a decent idea.  Please open a new issue with this feature request, instead of replying to a closed issue.

**Comment by liskin** [comment]
Ok, will do. It did seem related and I'm not a huge fan of opening new issues in repos that already have hundres of unsolved ones. Sorry.

**Comment by corbinlc** [comment]
It is just that making a comment on a closed issue, is unlikely to get seen or handled properly.  I and others normally don't look at closed issues when working through the backlog.  Also, reopening this issue would be inappropriate, given the issue that user was facing is already solved. Lastly, there are only 135 open issues - no biggie ;)

**Comment by ROWEND36** [comment]
Nice, I just downloaded the update. You guys are awesome. Thanks a lot.
