### ISSUE TITLE
Bug report - [unable to login without internet]

### ISSUE THREAD

**Issue by sendoh-7-akira** [CypherpunkArmory/UserLAnd#766]
# Describe the bug
i'm getting a "permission denied" error when trying to login without internet access

# Steps to reproduce the behavior:
1- turns airplane mode on (wifi is off)
2- start the ssh service from within UserLAnd
3- choose an ssh client to login and the error appears.

# Screenshots

![Screenshot_2019-04-12-12-38-46-448_org connectbot](https://user-images.githubusercontent.com/46089361/56080851-f2594300-5e0e-11e9-8999-8115d1ac6942.png)

# Device Information

Device: Redmi Note 7.  
Android Version: Pie 9.0
UserLAnd Version 2.5.4.  
device not rooted.  
Running on stock firmware

**Comment by corbinlc** [comment]
That is a known issue with ConnectBot, please use our built in terminal, it works for me without a network connection.  Please file an issue against ConnectBot if you want to see it improved.  I already have, but a nudge wouldn't hurt.
