### ISSUE TITLE
Feature Request - [We Need Update]

### ISSUE THREAD

**Issue by Sweetharry1992** [CypherpunkArmory/UserLAnd#769]
# Update please
**We need all of these things please update userland and add thsse things:**
* Add and edit Extra Keys like termux
* Please update the proot for Android v8+
* please make UserLand Api like Termux Api 
* please add the audio driver and video driver like orginal ubuntu have in windows 
* Please Add Server Ubuntu for runing servers or apps even when you are offline

**Comment by corbinlc** [comment]
We require that you follow our template to make sure that we have the proper info to move forward.  Also, we require that you only file only 1 bug or feature request per issue.  I am closing this one.  Please reopen individual ones that follow the template.  

Also, our PRoot works well on Android 8 and Android 9.  If it is not working for you specifically, please add more info about how in that issue.
