### ISSUE TITLE
Feature Request - [Add DSL]

### ISSUE THREAD

**Issue by MyOctagon** [CypherpunkArmory/UserLAnd#771]
# Describe the problem your feature request solves.
A clear and concise description of what the problem is that This app do not have DSL which is a linux distribution.The size of the image of DSL is only 50mb.

# Describe the solution you'd like 
Just add DSL Linux

# Describe alternatives you've considered
No alternatives

Please add any other context or screenshots you think might help us resolve your issue.

**Comment by corbinlc** [comment]
Is damn small linux still an active project?  All images and info posted here http://damnsmalllinux.org is not currently available.

**Comment by corbinlc** [comment]
Yes, it looks like there are two major issues... 1) DSL was abandoned quite a while ago.  2) It is only for x86 family processors, while we need to support ARM processors as well.  Both of these are show stoppers and we will not be able to add DSL to UserLAnd.

**Comment by corbinlc** [comment]
What about using Alpine Linux instead?  It is lightweight, supports ARM, and is very much being maintained.

**Comment by MyOctagon** [comment]
What is the size?

**Comment by MyOctagon** [comment]
how about adding slitaz os or kolibri os
