### ISSUE TITLE
Bug report - [YOUR BUG TITLE]

### ISSUE THREAD

**Issue by whriteblock** [CypherpunkArmory/UserLAnd#782]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug:<python-pip

A clear and concise description of what the bug is, and what expected behavior is. Include whether the bug occurs **before** 
or **after** entering a terminal or vnc client session.

# Steps to reproduce the behavior:

A list of **exact** steps to reproduce the behavior. If we cannot follow the steps to recreate the issue, we won't be able
to help you.

For example:

# Screenshots

# Device Information

Device: [e.g. Pixel XL 2].  
Android Version: [e.g. Oreo, 8.0].  
UserLAnd Version [e.g. 0.1.2].  
Whether the device is rooted.  
Whether the device is running LineageOS 

Please add any other context you think might help us resolve your issue.

**Comment by corbinlc** [comment]
I don't see any information in this bug report.  I am closing this.  Feel free to add some info and then reopen it.
