### ISSUE TITLE
Question - Is it possible to open privileged ports?

### ISSUE THREAD

**Issue by quique251** [CypherpunkArmory/UserLAnd#784]
Hello.
I'm trying to set up some server software inside UserLand/Debian. Right now everything works, but the open ports get displaced to the 20xx range. Is it possible to get the "normal" ports? I'm looking specifically to open 53, 80 and 443.
I've searched for some manual, or for some other issue about it, but I haven't found anything.
Thanks :)

**Comment by corbinlc** [comment]
For right now, you cannot open low numbered ports.  Android restricts access to the first 1000 ports.  We are going to take on some work to allow UserLAnd to run as the real root user, only if you want it to and if you have rooted your device.  If that was done, then you would be able to use the lower port numbers, but for right now, it is not possible.

**Comment by quique251** [comment]
Thanks for the answer, very informative :)
And thanks for the good job you are doing.
