### ISSUE TITLE
Shared memory error in Xfce + Debian

### ISSUE THREAD

**Issue by dbahiense** [CypherpunkArmory/UserLAnd#792]
# Describe the issue you are having.
I installed the App Xfce -> Debian. Everything runs well.
I was able to install WSJT-X downloading it via wget and installing the .deb file.
But when I want to run it, it gives me the following error message:

**Shared memory error**
Unable to create shared memory segment.

I'm running UserLand in a Samsung Galaxy J2 Pro (SM-J250M)

# Describe how your task behaves in a regular Linux environment
WSJT-X runs A-OK to me in Ubuntu 18.04 and Xubuntu 18.04.

**Comment by stephenprater** [comment]
@dbahiense /dev/shm does not yet work in UserLAnd.  There is a tracking issue at #256 but there is (as of yet) no ETA for this work.

**Comment by dbahiense** [comment]
> @dbahiense /dev/shm does not yet work in UserLAnd. There is a tracking issue at #256 but there is (as of yet) no ETA for this work.

OK. Now I see your answer. Thanks! Sad that it doesn't work...
