### ISSUE TITLE
Help - [Shared memory error in Xfce + Debian]

### ISSUE THREAD

**Issue by dbahiense** [CypherpunkArmory/UserLAnd#793]
# Describe the issue you are having.

I installed the App Xfce -> Debian. Everything runs well.
I was able to install WSJT-X downloading it via wget and installing the .deb file.
But when I want to run it, it gives me the following error message:

**Shared memory error**
Unable to create shared memory segment.

I'm running UserLand in a Samsung Galaxy J2 Pro (SM-J250M)

- What I'm trying to accomplish: To run WSJT-X in the UserLand environment.
- What I have tried so far: I'm stuck.

# Describe how your task behaves in a regular Linux environment

WSJT-X runs A-OK to me in Ubuntu 18.04 and Xubuntu 18.04.

**Comment by stephenprater** [comment]
Duplication of #792

**Comment by dbahiense** [comment]
> Duplication of #792

Hi stephenprater!
It was duplicated because the bot was saying that #792 had an error in the template. I tried to edit #792 without success and then closed #792 and wrote #793. Is there any problem with the bot?
And more important: now that you closed #793 too we don't have any opened issue that describe my problem. Should I reopen #792 or you do it with #793 that is with a more acurated use of the template?
Thanks!
