### ISSUE TITLE
Bug report - [Ngrok throwing illegal instruction]

### ISSUE THREAD

**Issue by usama7628674** [CypherpunkArmory/UserLAnd#794]
# Describe the bug

Everything is working fine ngrok downloads fine but it's not running upon executing `./ngrok http 8080` it throws `illegal instruction`

# Steps to reproduce the behavior:

Download userland app and install kali.
Download ngrok for arm platform from [here](https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip)
After downloading unzip the zip file.
Execute `./ngrok http 8080`.

# Device Information

Device: LG-G3 (D-851) 
Android Version: android 6.0
UserLAnd Version 2.5.6  
device is not rooted
No LineageOS is running.

**Comment by EnderNightLord-ChromeBook** [comment]
what kind of application is this? And what does it do?

**Comment by usama7628674** [comment]
@EnderNightLord-ChromeBook It expose your localhost server to WAN.Read here https://ngrok.com

**Comment by usama7628674** [comment]
@EnderNightLord-ChromeBook It works fine on termux

**Comment by usama7628674** [comment]
@EnderNightLord-ChromeBook Nevermind I fixed it.

**Comment by JoblessMe** [comment]
> @EnderNightLord-ChromeBook Nevermind I fixed it.

how??

**Comment by MmxKnows** [comment]
You can download Linux (ARM) version of the ngrok client here. It may solve this issue. 😉 https://ngrok.com/download
