### ISSUE TITLE
UserLand app error

### ISSUE THREAD

**Issue by raif-py** [CypherpunkArmory/UserLAnd#798]
[Error.zip](https://github.com/CypherpunkArmory/UserLAnd/files/3125097/Error.zip)
Please watch this video (zip mp4)
Aplication division error

**Comment by MatthewTighe** [comment]
Can you host the video somewhere instead? Downloading random zip files is a security concern.

Also, please edit your issue to follow the issue template so that we can best help you.

**Comment by corbinlc** [comment]
The zip file was never hosted elsewhere and the template was never followed.  I am closing this.  If this problem still exists on the latest version (2.6.3) and you are willing to do as @MatthewTighe requested, then please reopen the issue.
