### ISSUE TITLE
Open Ubuntu Lxde but Debian starts

### ISSUE THREAD

**Issue by TungstenCarbideProjectile** [CypherpunkArmory/UserLAnd#816]
Samsung Note 9 installed Debian first with lxde and started using "start lxde &"
At some point starting debian began opening lxde automatically (all tight vnc).

(In the past Used to use gnu root with xsdl but i see it is not supported and tight vnc works fine and more easily. )

I then installed ubuntu file system with xfce4 and started it using command line to start xfce i forget the command something like startxfce4& or something. It worked but firefox was black. 

At some point the lxde and xfce showed up on userland home screen. 

I deleted ubuntu and reinstalled with lxde to see if firefox would run.  Now i cannot get ubuntu to run lxde gui. 

When i click lxde or xfce from userland menu only debian opens. IS there a way to select the file system that will be opened with lxde or xfce userland home button? 

IS there a way to start lxde in ubuntu command line? 

Is installing lxde/xfce in terminal still necessary with the home screen buttons? O notice if i click xfce debian will run in xfce even tho i installed only lxde in debian command line in the beginning. 

Thank you for your time.

**Comment by MatthewTighe** [comment]
All apps except 'Distribution' apps run on Debian. Adding the ability to select different filesystems for apps is a potential roadmap item, but low priority for now. If you want LXDE on Ubuntu you'll need to install it manually.

**Comment by TungstenCarbideProjectile** [comment]
I understand, how can i launch lxde in ubuntu command line?



- Chris

I
- B.S. MET
- 817.381.0182
- Christopher.toner@engineer.com

________________________________

**Comment by MatthewTighe** [comment]
Follow the steps in the [wiki[(https://github.com/CypherpunkArmory/UserLAnd/wiki/Getting-Started-in-UserLAnd)

**Comment by TungstenCarbideProjectile** [comment]
I know your but that's obviously the first place i checked and it says on the app just like in the doc xsdl NOT SUPPORTED.

- Chris Toner
- B.S. MET
- 817.381.0182
- Christopher.toner@engineer.com

________________________________

**Comment by corbinlc** [comment]
Please note that XSDL is not supported on newer version of Android not because we don't want to support it, but because the XSDL app has not been updated in a long time and does not work on Android 9.  We disable it as a selection because of this.  We are not the developers of that app.

**Comment by TungstenCarbideProjectile** [comment]
Right but i asked a clear question, then i was directed to a doc that told me to use xserver. Which is not supported I'm fine with that.

HOW DO I CHOOSE WHICH FILE SYSTEM OPENS WHEN CHOOSING A DESKTOP FROM THE USERLAND MAIN MENU?

- Chris Toner
- B.S. MET
- 817.381.0182
- Christopher.toner@engineer.com

________________________________

**Comment by corbinlc** [comment]
`sudo apt-get update`
`sudo apt-get -y install lxde`
`echo '/usr/bin/startlxde' > ~/.vnc/xstartup`
Then exit and kill your current session/server (long press to see this option).
Then start the app or session again, but make sure it is setup to use VNC as the connection method.

**Comment by corbinlc** [comment]
You can do similar for xfce4.

**Comment by TungstenCarbideProjectile** [comment]
Thank you so much,  you are the best, i will try it soon. And let you know it is working. I'm a big fan by the way. From gnu root to userland, really really appreciate your work,  thank you.

**Comment by TungstenCarbideProjectile** [comment]
Well that certainly worked to get the desktop visible but Firefox is still just a black screen has there been any improvements on that issue i believes already filed correct?

**Comment by MatthewTighe** [comment]
No, there has been no further work on those issues as of yet. Follow those issues to stay up to date. Closing this as the original issue has been resolved.

**Comment by TungstenCarbideProjectile** [comment]
Thank you
