### ISSUE TITLE
cannot update or install any app on debian or ubuntu

### ISSUE THREAD

**Issue by luumiem** [CypherpunkArmory/UserLAnd#824]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug

A clear and concise description of what the bug is, and what expected behavior is. Include whether the bug occurs **before** 
or **after** entering a terminal or vnc client session.

# Steps to reproduce the behavior:

A list of **exact** steps to reproduce the behavior. If we cannot follow the steps to recreate the issue, we won't be able
to help you.

For example:

# Screenshots

# Device Information

Device: [e.g. Pixel XL 2].  
Android Version: [e.g. Oreo, 8.0].  
UserLAnd Version [e.g. 0.1.2].  
Whether the device is rooted.  
Whether the device is running LineageOS 

Please add any other context you think might help us resolve your issue.
Hi,

I'm keep getting temporary failure resolving 'deb.debian.org. for (userland debian ssh)

I installed on galaxy s10 plus android 9

Also I cannot install any app

Example 

sudo apt-get install vim

Please see the log errors below.

-----------

~$ sudo apt-get update && sudo apt-get dist-upgrade

Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

‐‐------------

~$ sudo apt-get install vim
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libgpm2 vim-common vim-runtime xxd
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  libgpm2 vim vim-common vim-runtime xxd
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 6597 kB of archives.
After this operation, 31.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  xxd vim-common libgpm2 vim-runtime vim
Install these packages without verification? [y/N] y
Err:1 http://deb.debian.org/debian stable/main arm64 xxd arm64 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable/main arm64 vim-common all 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian stable/main arm64 libgpm2 arm64 1.20.4-6.2+b1
  Temporary failure resolving 'deb.debian.org'
Err:4 http://deb.debian.org/debian stable/main arm64 vim-runtime all 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian stable/main arm64 vim arm64 2:8.0.0197-4+deb9u1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/v/vim/xxd_8.0.0197-4+deb9u1_arm64.deb Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/v/vim/vim-common_8.0.0197-4+deb9u1_all.deb Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gpm/libgpm2_1.20.4-6.2+b1_arm64.deb Temporary failure resolving 'deb.debian.org'

**Comment by freebrowser1** [comment]
I had this problem last week.

I found an answer and tried this:

```
sudo apt-get clean all
sudo apt-get update
sudo apt-get dist-upgrade -y
# and optionally
sudo apt-get autoremove
```

From:  https://www.linuxquestions.org/questions/linux-newbie-8/failed-to-fetch-4175609026/

and that worked. But I ran towards other problems: lots of apps give 'Error 13 Access denied'.
Even the very basic 'top' command issues an error message.

**Comment by luumiem** [comment]
emma@localhost:~$ su
root@localhost:/home/emma# sudo apt-get clean all
root@localhost:/home/emma# sudo apt-get update
Err:1 http://deb.debian.org/debian stable InRelease
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian stable-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch http://deb.debian.org/debian/dists/stable/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stable-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@localhost:/home/emma#

**Comment by luumiem** [comment]
sudo apt-get clean all sudo apt-get update sudo apt-get dist-upgrade -y # and optionally sudo apt-get autoremove

Does not fix my issues

**Comment by Herzogs** [comment]
you tried to restart the modem? And can you put your source.list? with `cat /etc/apt/source.list`

**Comment by luumiem** [comment]
No such file what should i do? Default debian installation does not come with any editor .

emma@localhost:~$ su
root@localhost:/home/emma# cat /etc/apt/source.list
cat: /etc/apt/source.list: No such file or directory
root@localhost:/home/emma#

**Comment by luumiem** [comment]
Found the file:

root@localhost:/etc/apt# cat sources.list
deb http://deb.debian.org/debian/ stable main contrib non-free
#deb-src http://deb.debian.org/debian/ stable main contrib non-free
deb http://deb.debian.org/debian/ stable-updates main contrib non-free
#deb-src http://deb.debian.org/debian/ stable-updates main contrib non-free

**Comment by luumiem** [comment]
I uninstall userland and reinstall debian still having the same issues. Maybe userland debian does not work on android galaxy s10 exynos version.

**Comment by luumiem** [comment]
Any update how to fix this issues or have anyone tested on galaxy s10 exynos version?

Debian install just fine but after installed i cannot run the apt update or install.

Alway failed with this error.

Temporary failure resolving 'deb.debian.org'
Reading package lists... Done
W: Failed to fetch

**Comment by corbinlc** [comment]
We are still unable to replicate this issue.  

Could you try changing your dns settings in /etc/resolv.conf ?  Right now, it is just pointing at Google's DNS, but maybe you cannot get to it on the network you are on??

**Comment by luumiem** [comment]
Dont think it google dns issues.
Something blocking userlands from connect to the internet.

I changed dns ip but does not resolve the issue.

Is userland tested on galaxy s10 plus exynos?

Have no issue installing on my xiaomi mi pad 4 with the same wifi connection

**Comment by luumiem** [comment]
Dont think it google dns issues.
Something blocking userlands from connect to the internet.

I changed dns ip but does not resolve the issue.

Is userland tested on galaxy s10 plus exynos?

Have no issue installing on my xiaomi mi pad 4 with the same wifi connection

**Comment by corbinlc** [comment]
We don't have a Galaxy s10 plus exynos.  The closest we have is a galaxy s9, but it looks like most recent s10 reviews show 5 stars.  I am guessing it is more specific than what device you are using.

**Comment by luumiem** [comment]
Found the issues for some reason the 'Disconnect Pro for Samsung' app blocking userland internet connection on my s10 phone.

After disable and re-enable the 'Disconnect Pro app for samsung' resolves userland issues.

**Comment by corbinlc** [comment]
Oh, interesting.  Thanks for the info.

**Comment by arawasu-userland** [comment]
Taking long time to solve this issue, but finaly found the problem
It is due to ISP or wifi. When I use different provider, I could connect normally

I am not sure yet how to solve for all connection. Does it have relation with DNS setting in Userland?

**Comment by islamrobi** [comment]
> I had this problem last week.
> 
> I found an answer and tried this:
> 
> ```
> sudo apt-get clean all
> sudo apt-get update
> sudo apt-get dist-upgrade -y
> # and optionally
> sudo apt-get autoremove
> ```
> 
> From: https://www.linuxquestions.org/questions/linux-newbie-8/failed-to-fetch-4175609026/
> 
> and that worked. But I ran towards other problems: lots of apps give 'Error 13 Access denied'. Even the very basic 'top' command issues an error message.

this solved my issue.

**Comment by Kahabk** [comment]
I have a issue I can't update using sudo apt apdate I try that code but didn't working
Some index files failed to download. They have been ignored, or old ones used instead. What is the problem I multiple time installed and I also installed old version userland that also encounter same problem
