### ISSUE TITLE
Feature Request - [Add new distribution - Voidlinux]

### ISSUE THREAD

**Issue by noloop** [CypherpunkArmory/UserLAnd#826]
# Describe the problem your feature request solves.
It would be nice to have [voidlinux](https://voidlinux.org/) on your phone.

# Describe the solution you'd like 
See voidlinux in the Userland distributions available.

# Describe alternatives you've considered
N/A

**Comment by corbinlc** [comment]
I have added this to #581 .  #581 is a list of all the distros that have been requested, but have not been provided yet.  Please follow that issue to see progress.
