### ISSUE TITLE
Feature Request - Linux kernel 5.1

### ISSUE THREAD

**Issue by GeorgeKitsopoulos** [CypherpunkArmory/UserLAnd#835]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 

Due to initramfs not being fully supported on arm chroot environments some system functions and programs do not work as expected.

# Describe the solution you'd like 

The inclusion of Linux kernel 5.1 or above would fix a lot of these issues.

# Describe alternatives you've considered

N/A

**Comment by corbinlc** [comment]
We don't provide or modify the kernel of your device.  We simply use the kernel already on your device + PRoot to make things work.
