### ISSUE TITLE
desktop error on userland 2.5.9 and cannot install flashplayer

### ISSUE THREAD

**Issue by FreeDreamWings** [CypherpunkArmory/UserLAnd#839]
# Describe the bug

1. 

When I updated userland to 2.5.9,there are many bugs on xfce and lxde in debian.I updated userland and opened xfce via vnc,it downloaded 2 files.And then it opened but there are some bug on desktop and file manager.The desktop did not show the wallpaper and when I opened some hide folders,the file manager flashback(for example,I opened /home/username/.mozilla/firefox/xxx.default/ or opened /usr/ ).And the folders' icon did not show in the file manager.The bugs did not happen on userland2.3.5.

2. 

And I cannot install flashplayer.I cp libflashplayer.so /usr/lib/mozilla/plugins/.But firefox did not show the flashplayer plugin.

# Steps to reproduce the behavior:

I have writen above.

# Screenshots

![Screenshot_20190519_212747_com iiordanov freebVNC](https://user-images.githubusercontent.com/20186813/57983072-5dd2a800-7a80-11e9-8875-c054001bbbfb.jpg)

# Device Information

Device:Huawei honor v9(in China)/or named Huawei honor 9 pro in other area.  
Android Version:Android9.0 EMUI9.1 (9.1.0.180).  
UserLAnd Version 2.5.9.  
Whether the device is rooted.  not root
Whether the device is running LineageOS. no 

Please add any other context you think might help us resolve your issue.
Flashplayer error may be due to CPU model. I used i386 and amd64 libflashplayer.so.Once I installed a flashplayer.deb from http://archive.canonical.com/pool/partner/a/adobe-flashplugin/.And dpkg log showed something that say arm64...I think it may be due to the CPU model.

**Comment by FreeDreamWings** [comment]
I have tried userland another versions. I 
 found the desktop error began from version 2.5.3.I thought it may be due to the new update "New download flow",because when I update to version2.5.3 and click "xfce"Button,it will download 2 new files and   then enter the vnc.

**Comment by corbinlc** [comment]
We are aware of this issue.  It is related to a change to PRoot.  I will have an update by EOD tomorrow.

**Comment by corbinlc** [comment]
I have just released a new version of PRoot. You should see it installing new files the next time you start an app or session (if it is already running you should stop it and restart it to get it to download new files).

The issues was that the PRoot change added shared memory support, but not perfect support. Once shared memory was partially supported, programs that could benefit from it started using it. But, the implementation had a few flaws in it. All issues seen when recreating the mentioned issues have now been solved.

Please file new issue for any problem that remains.
