### ISSUE TITLE
Several issues after Android update on samsung T825

### ISSUE THREAD

**Issue by planck2007** [CypherpunkArmory/UserLAnd#840]
# Describe the bug
After the update I have observed two issues: 
1. xfce desktop does not start properly (in particular xfce-panel will not start) 
2. Libreoffice does not work properly. The program starts but the content of the various windows is empty (just a grey background)

# Steps to reproduce the behavior:
You need a Samsing T825 device with the very last official android (8.0.0, build version n. R16NWT825XXU3BSD1) and Userland with Ubuntu + xfce + Libreoffice installed.

When The session is started xfce does not start properly (no panel, no taskbar). When Libreoffice il launched via terminal the resulting application window is grey. It is possibl to access menus but opening a document results again in a grey window

# Device Information

Device: Samsung T825 (Galaxy tab  S3)  
Android Version: Oreo, 8.0.0  build version n. R16NWT825XXU3BSD1
UserLAnd Version 2.5.9
No root on device

**Comment by corbinlc** [comment]
We are aware of this issue.  It is related to a change to PRoot.  I will have an update by EOD tomorrow.

**Comment by corbinlc** [comment]
I have just released a new version of PRoot. You should see it installing new files the next time you start an app or session (if it is already running you should stop it and restart it to get it to download new files).

The issues was that the PRoot change added shared memory support, but not perfect support. Once shared memory was partially supported, programs that could benefit from it started using it. But, the implementation had a few flaws in it. All issues seen when recreating the mentioned issues have now been solved.
