### ISSUE TITLE
 service postgresql failed failed

### ISSUE THREAD

**Issue by sabri-zaki** [CypherpunkArmory/UserLAnd#849]
i have Galaxy s6 running on Android 7.0 Nugat and this is my issue:
kali@localhost:~$ service postgresql start     [....] Starting PostgreSQL 11 database server: main[....] Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o -c config_file="/etc/postgresql/11/main/postgresql.conf" exited with status 1: 2019-05-25 10:37:14.452 UTC [24613] FATAL: private key file "/etc/ssl/private/ssl-cert-snakeoil.key" has group or world access 2019-05-25 10:37:14.452 UTC [24613] DETAIL: File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root. 2019-05-25 10:37:14.453 UTC [24613] LOG: database system is shut down pg_ctl: could not start serv[FAILamine the log output. ... failed!
 failed!

kali@localhost:~$ pg_ctlcluster 11 main start  Error: /usr/lib/postgresql/11/bin/pg_ctl /usr/lib/postgresql/11/bin/pg_ctl start -D /var/lib/postgresql/11/main -l /var/log/postgresql/postgresql-11-main.log -s -o  -c config_file="/etc/postgresql/11/main/postgresql.conf"  exited with status 1:
2019-05-25 10:40:58.975 UTC [25337] FATAL:  private key file "/etc/ssl/private/ssl-cert-snakeoil.key" has group or world access
2019-05-25 10:40:58.975 UTC [25337] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
2019-05-25 10:40:58.975 UTC [25337] LOG:  database system is shut down
pg_ctl: could not start server
Examine the log output.

**Comment by corbinlc** [comment]
You need to change permissions of the mentioned file.  
`chmod 600 /etc/ssl/private/ssl-cert-snakeoil.key`
This is required because we don't emulate file ownership perfectly.

**Comment by sabri-zaki** [comment]
@corbinlc i used your command and it's worked  but metasploit is not connected to database and when I use :
msfdb init it's show this error :
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

**Comment by qian9008** [comment]
can't use service…  in proot
