### ISSUE TITLE
Bug report - [Downloading Assets]

### ISSUE THREAD

**Issue by lordmickey11** [CypherpunkArmory/UserLAnd#852]
'#' Userland downloading requires assets... reports 
Shows "0 out of
![Screenshot_20190525-131359_UserLAnd]
 3 complete"
instead of "0 out of 28 complete" what could be the problem old.. 

(https://user-images.githubusercontent.com/51022369/58369204-02c10b00-7eef-11e9-976b-2d3e35506475.jpg)

**Comment by corbinlc** [comment]
We download less files now.  There are no longer 28 assets to download.
