### ISSUE TITLE
Tab is noting

### ISSUE THREAD

**Issue by omer-raif** [CypherpunkArmory/UserLAnd#853]
I don't have the top floor. how do I fix it
![PicsArt_05-27-04 36 05](https://user-images.githubusercontent.com/50047969/58423440-cb449100-809d-11e9-9c90-d09fc19e51a8.png)

**Comment by luongthomas** [comment]
The space you are referring to is called the `extra keys row` and it can be toggled on and off by holding the `volume up button` and pressing `Q` at the same time.  Refer to the [termux wiki](https://wiki.termux.com/wiki/Touch_Keyboard) for more information

**Comment by omer-raif** [comment]
Thank you very much :) Solved
