### ISSUE TITLE
Help - [need ubuntu 16.04]

### ISSUE THREAD

**Issue by Admiral128** [CypherpunkArmory/UserLAnd#858]
# Describe the issue you are having.
Hey, 
I need to have ubuntu 16.04 on my phone
But the current version of Ubuntu on UserLand is 18.04
Please help me to install it through UserLand or other apps 
Also my phone LG G6 is not rooted
Thanks 😊

# Describe how your task behaves in a regular Linux environment
I trying to run an exe code with mono and it works only with 16.04 version of ubuntu

**Comment by EnderNightLord-ChromeBook** [comment]
May I just ask... why do you need 16.04? Does a specific application run on 16.04?

**Comment by EnderNightLord-ChromeBook** [comment]
- You will have to use the lower-level Debian tools (apt), not the graphic Ubuntu ones. So you will have to understand them. If things go wrong, trying to fix thing without understanding what you are doing will make the situation much worse.

- You will have to downgrade step by step: to 17.10, then 17.04, 16.10, 16.04. Quite time-consuming.

- You will have to understand on each upgrade what were the complex changes (e.g. migrating from sysv to systemd), and carefully see how to manually downgrade them.

- Ubuntu likes to change more things on each release than Debian. This will of course mean more potential problems in downgrading.

**Comment by Admiral128** [comment]
I'm newbie u doubt I can do something like that ... Is there any other way to do that?? 
GNURoot Debian use to allow me to work with my task . But it seems not working in Android 5 and above

**Comment by EnderNightLord-ChromeBook** [comment]
That's pretty much the only ways I know of... Sorry... I'll try to find out another way.

**Comment by corbinlc** [comment]
@Admiral128 just so I understand, why do you need 16.04?

**Comment by Admiral128** [comment]
@corbinic hey, because I need to run this program with it and the developer said it only works in official 16.04 version.
https://youtu.be/uvwk5-FVaC4
I do installed mono of course but it can't run. It in 18.04

**Comment by lewisdonofrio** [comment]
Abandon all ye hope of getting to "the root directory of your phone" Userland doesn't provide that, I mean if you've rooted (shutters at that talk in the 21st century) your device then perhaps but if it is not rooted you'll not be able to access the root directory on your device.

**Comment by corbinlc** [comment]
I have added the request for 16.04 to #581 .  As such, I am closing this issue.
