### ISSUE TITLE
Feature Request - [Allow selecting architecture to be able to run Raspbian armhf binaries on aarch64 UserLAnd]

### ISSUE THREAD

**Issue by tigran123** [CypherpunkArmory/UserLAnd#867]
# Describe the issue you are having.
The importance of GNURoot Debian is due to the fact that it can run Raspbian binaries and therefore execute one of the most important software packages created on this planet. Now, UserLAnd is supposed to be better and superior and so it should be able to run Raspbian binaries also. But, alas, it cannot:

```
$ file cp
cp: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=7527ff4479e970d9bda0929ccd8d2c0a0511b78c, stripped
$ ldd cp
	not a dynamic executable
$ l /lib/ld-linux-aarch64.so.1 
lrwxrwxrwx. 1 tigran tigran 28 Feb  6 21:17 /lib/ld-linux-aarch64.so.1 -> aarch64-linux-gnu/ld-2.24.so
$ l /lib/ld-linux-armhf*
/bin/ls: cannot access '/lib/ld-linux-armhf*': No such file or directory
```

Here is the corresponding session log from GNURood Debian:

```
# ldd /bin/cp
	/support/libdisableselinux.so (0xf7437000)
	libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xf740b000)
	libacl.so.1 => /lib/arm-linux-gnueabihf/libacl.so.1 (0xf73f5000)
	libattr.so.1 => /lib/arm-linux-gnueabihf/libattr.so.1 (0xf73e1000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xf72f1000)
	/lib/ld-linux-armhf.so.3 (0x0f000000)
	libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xf7295000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xf7281000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xf725e000)
# l /lib/ld-linux-armhf.so.3 
lrwxrwxrwx. 1 root root 30 Jun 18  2017 /lib/ld-linux-armhf.so.3 -> arm-linux-gnueabihf/ld-2.19.so*
# u
Linux localhost 3.10.84-g21e6a83 #1 SMP PREEMPT Wed Jul 20 15:25:57 KST 2016 armv8l GNU/Linux

```

And this is from LG G4, i.e. the architecture is the same as on the first session (Samsung Galaxy TAB S4).

# Describe how your task behaves in a regular Linux environment

N/A

**Comment by corbinlc** [comment]
GNURoot was used for a lot more that that.  Regardless, the limitation you are running up against is that PRoot architecture and the architecture of the binaries being run have to match.  In your case you are running an armhf binary but with an arm64 PRoot.  I am not 100% certain whether converting all of the system calls that exist in one arch but not in another would be enough.  The easiest solution would be to add an advanced option where you can force what architecture you are using.

**Comment by corbinlc** [comment]
Actually, the easiest solution in your case would be if you can find arm64 versions of the binaries you want to run.  But the easiest solution for us would be to have a way for you to force us to use armhf.

**Comment by tigran123** [comment]
The first solution is not viable, because there is no aarch64 binary of the application available (and there is no source code, so I can't recompile it myself). So, the only real solution is to be able to choose armhf architecture when creating a new session. Please consider implementing it as otherwise the tablets running Android 8 or 9 are excluded from running this wonderful piece of scientific software. I specifically bought Samsung Galaxy TAB S4 for the sake of the S-Pen and bigger screen (than my Nexus 10) and being able to store my library on a 400GB micro sd, but the lack of Wolfram Mathematica seriously deducts from all the positive features of this tablet...

**Comment by tigran123** [comment]
I noticed in the `Filesystems` tab the option to import your own filesystem. Can't someone build an armhf architecture filesystem (Debian) and make it available somewhere, so I can download it and import into the application? That would be very much appreciated, thank you.

**Comment by tigran123** [comment]
I just had an idea: can't we use proot under Termux (plus qemu presumably) to boot the entire iso image of Raspbian? Or, proot binary being of aarch64 architecture running inside Termux would not be able to do this? Eh, the best thing really is to make UserLAnd allow the selection of armhf architecture when building a rootfs.

**Comment by tigran123** [comment]
I am very impressed with the amount of good work that is going on in this project as I get updates as a beta-tester and so I'll keep looking for the magic number `#867` in the changelog, hoping that you will implement this feature at some point. Needless to say, all my attempts at workaround (including on Termux) failed, precisely for the reason you described, i.e. proot's architecture must much that of the binaries I am trying to run.

**Comment by tigran123** [comment]
Hello guys,

Is there any ETA on when/if this feature will be implemented? Samsung Galaxy Tab S4 (and presumably other Android 9 tablets, if there are any) is a very good device, but without this extremely important capability (of running Raspbian binaries) it is really not competitive even against the cheap Chinese tablets which cost four times less, because they run the good old Android 7 on which GNURoot Debian works perfectly.

So, I really hope that you will implement this feature and then I will have all three key computing components in one compact device (python with numpy, scipy, matplotlib, jupyter + XeLaTeX + Wolfram Mathematica).

**Comment by KarlHeinzMali** [comment]
That means that armhf multiarch is not working with PRoot / UserLAnd? I installed the armhf architecture under Ubuntu 18.04 with:
dpkg --add-architecture armhf
apt-get update
apt-get install libc6:armhf libstdc++6:armhf
After starten the 32 bit Java I get a segmentation fault.

**Comment by tigran123** [comment]
@KarlHeinzMali You are absolutely correct. The multiarch feature is not working with proot. So, the only solution to my problem (being able to run Wolfram Mathematica on a tablet running Android 9) is for UserLAnd to allow installing armhf rootfs image on aarch64 Android tablet. On all other versions of Android (5, 6 and 7) Wolfram Mathematica is running absolutely fine, including parallel computations. So, you can build a cluster of 1000-node old mobile phones and it scales quite nicely :)

**Comment by KarlHeinzMali** [comment]
**@tigran123** Thank you for your response. I think multiarch is a mandatory feature for legacy applications. Not every application is able to be ported quickly to 64 bit.
By the way how do you install an armhf rootfs image on aarch64 Android with UserLAnd?

**Comment by tigran123** [comment]
@KarlHeinzMali It is at present IMPOSSIBLE to install an armhf rootfs image on aarch64 Android with UserLAnd. This is the whole point of the present issue and the feature request.

**Comment by KarlHeinzMali** [comment]
Than UserLAnd is useless for me. Thank you for your support.

**Comment by tigran123** [comment]
Thank you, I am glad to hear that someone else also thinks that this is a very essential feature. I hope the developer will take this into consideration.

**Comment by stephenprater** [comment]
@tigran123 There's a couple of different ways we can approach this and we're evaluating which one we ought to do.  Since it's kind of an edge case feature it's not a super high priority for any of our devs right now.  I wouldn't expect it before Q42019 at the earliest.

**Comment by tigran123** [comment]
@stephenprater Thank you, I really appreciate it! I will patiently wait. If I can help in any way, please let me know. I am not an Android developer, but a Linux kernel developer with more than one decade of experience :)

**Comment by KarlHeinzMali** [comment]
**@stepenprater** Thank you for your announcement! I appreciate it!

**Comment by tigran123** [comment]
@stephenprater Btw, if while investigating this you also figure out why we can't start graphical frontend (mathematica) it would be absolutely FANTASTIC. If this problem is also solved, then it would be an event of planetary-wide significance in my opinion (because with a faster tablet like this Samsung Galaxy Tab S4 it would make laptop almost irrelevant). My preliminary investigation suggested that proot is spending enormous amount of time (i.e. slowed down by a factor of millions or, maybe even infinite) in ptrace(2) system call trying to trace the process in question (presumably that is how system calls are emulated by proot) and the "mathematica" process is always in "t" state, i.e. being traced. Normally the startup should happen in a couple of seconds (judging from the startup time of the console-based "math" kernel), but I left it running for five or six days and it still never completed. So, either it is slowed down by a huge factor or just loops there forever, being ptrace-d. Anyway, this is just an "extra bonus" --- if you do sort it out, then it would be absolutely great and worthy of every praise. But if not, even having a console-based version working (like on older Androids with GNURoot Debian it does brilliantly) is good enough for me. Thank you!

**Comment by tigran123** [comment]
Another option would be to try Limbo x86 emulator for Android, but I doubt that it will boot and run an Ubuntu 18.04 x86_64 distribution. But I am going to give it a try.

**Comment by tigran123** [comment]
Good news! I managed to boot x86_64 Ubuntu 18.04 distribution inside Termux using qemu-system-x86_64. However, this is a headless version (by Leonid Plyushch) and I still need to figure out how to access the system via ssh. But I am very close to the solution...

**Comment by ZZZXXX0110** [comment]
However running x86_64 version of the OS under QEMU should not be considered as a valid alternative, because the performance under such heavy emulation is abysmal compares to running PRoot natively with armhf support... 

A slightly better yet hypothetical alternative is to use QEMU user mode for per thread emulation to run a armhf or x86_64 binary, but as far as I am aware QEMU user mode is not supported on ARM64 processor, which brings us back to this issue to the beginning...

**Comment by tigran123** [comment]
Yes, you are absolutely right --- although the x86_64 image runs absolutely smoothly (no issues) under qemu-system-arm on Android, the performance is abysmal, just like you say. So, I am still hoping that the developers of UserLAnd will support this feature we are asking.

**Comment by tigran123** [comment]
Thank you very much --- the latest update fixes this problem! And my favourite app now works perfectly on Samsung Galaxy Tab S4, so this tablet is from now on the best Android device in the world (until something better comes out, which I doubt will happen for the next 10-15 years :)

Btw, I still get this error message when running any armhf binaries:

```
ERROR: ld.so: object '/support/libdisableselinux.so' from /etc/ld.so.preload cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

But this doesn't seem to affect the actual functionality, so I am very happy. Thank you again! :+1:

**Comment by corbinlc** [comment]
Great.  I didn't mention it yet because I was still testing.  @tigran123 can you provide steps to repeat what you did?

**Comment by tigran123** [comment]
Do you mean how reproduce the above error? Easy. Just copy any binary from Raspberry Pi, e.g. cp or ls command and run it. It will produce the above error message, but otherwise will work fine.

**Comment by corbinlc** [comment]
No sorry.  I have seen that error.  Interested in how you got Mathematica working.  I tried similar and noticed it complained after it called `uname` because they device info didn't match it's expectation.

**Comment by tigran123** [comment]
Ah ok, yes, that's easy --- just edit the `math` (or `wolfram`) script to add "aarch64|" to the left of the armv* architecture and it will not complaine. But you will also have to copy a couple of libraries from rpi to /opt/Wolfram/WolframEngine/11.2/SystemFiles/Libraries/Linux-ARM and make symlinks. Which libraries... Well, it was libgmp.so.10.3.2 and another one. I forgot its name, because I had to copy about 40 other libraries in the attempt to get the graphical frontend to work as well (the console-based kernel doesn't need them). However, the frontend would complain about failing to load the Qt platform plugin "xcb", but maybe I would succeed if I had first configured X11 stuff properly in UserLAnd side --- maybe I'll try that at some point (to have a graphical frontend working would be really nice!).

And finally, after the libraries and symlinks are in place you would have to satisfy the program's craving for the license number :)

**Comment by tigran123** [comment]
Also, use version 11.2 as the latest (12.0.1) is a bit more picky about making sure it really is rpi platform. But I think I know how to workaround it, I was just too lazy to verify this (we need udev rules or mknod some devices on each startup) as 11.2 was sufficient for my needs. But at some point I'll try 12.0.1 as well (maybe I'll try it now :)

**Comment by tigran123** [comment]
The version 12.0.1 fails with this error:

```
/home/tigran/Wolfram/WolframEngine/12.0/SystemFiles/Kernel/Binaries/Linux-ARM/WolframKernel: error while loading shared libraries: libopenblas.so.0: cannot enable executable stack as shared object requires: Permission denied
```

As I cannot disable selinux on this tablet, I am not sure how to overcome this.
