### ISSUE TITLE
Cannot start ssh.

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [CypherpunkArmory/UserLAnd#877]
I just downloaded Userland and chose Debian and when I installed Openssh and the whole default setup was completed I tried starting the service but it returns with 'sshd re-exec requires execution with an absolute path'.
Please Help!

**Comment by corbinlc** [comment]
This is normal.  You need to provide the full path when starting sshd.  This means you run it like this `/path/to/sshd` instead of just `sshd`.  You can use `which sshd` to file the full path.  Normally, this is `/usr/sbin/sshd`
