### ISSUE TITLE
Nodejs is outdated and npm is not found.

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [CypherpunkArmory/UserLAnd#879]
Recently I installed UserLand app on my android device to start learning NodeRed by installing it (I know that Termux is the easy way but have got some issues that are not yet resolved) but the Nodejs version is outdated (Nodejs version = 4.8.2) and I can't seem to find npm too.

I need some help solving this issue, I didn't know where to ask for help so I am posting it here.

**Comment by corbinlc** [comment]
We were already communicating with you via #878 about this.  We have not heard back, so we are closing this issue.
