### ISSUE TITLE
Bug report - [symbolic link got broken]

### ISSUE THREAD

**Issue by sarigama** [CypherpunkArmory/UserLAnd#881]
# Describe the bug
until the recent update(?)
i could access the files in /Download/sarigama as things in /root/sarigama
by doing
ln -s /sdcard/Download/sarigama sarigama
at /root
now it says there aint such dir

# Steps to reproduce the behavior:

simply
cd sarigama 
says no such dir :(
(used to work)

Device: [wiko g08(japanese name)].  
Android Version: [7.1.2].  
UserLAnd Version [2.5.13].  
Whether the device is rooted.  nope
Whether the device is running LineageOS nope

**Comment by corbinlc** [comment]
Duplicate
