### ISSUE TITLE
Bug report - [symbolic link got boken]

### ISSUE THREAD

**Issue by sarigama** [CypherpunkArmory/UserLAnd#883]
# Describe the bug
until the recent update(?)
i could access the files in /Download/sarigama as things in /root/sarigama
by doing
ln -s /sdcard/Download/sarigama sarigama
at /root
now it says there aint such dir

# Steps to reproduce the behavior
simply
cd sarigama
says no such dir :(
(used to work)

# Screenshots
not ready sorry

# Device Information
Device: [wiko g08(japanese name)].
Android Version: [7.1.2].
UserLAnd Version [2.5.13].
Whether the device is rooted. nope
Whether the device is running LineageOS nope

**Comment by corbinlc** [comment]
The bot complained because it wanted you to leave the `#` at the beginning of the lines.

**Comment by corbinlc** [comment]
You have provided enough info to start.  You are use the beta version right?  The beta release currently has a change we are testing related to changed coming in Android Q.  Here is some details on the change coming in Android Q ( https://developer.android.com/preview/privacy/scoped-storage ).  Let me summarize...  In Android Q and beyond, apps will no longer be able to read and write a public area at /sdcard.  Instead each app is given a private storage space.  Then to get files into and out you have to copy them into or out of an apps space.  This is definitely not ideal for our users, but this is what google is requiring for the future.  We will provide more information to make this transition more obvious to users.

**Comment by sarigama** [comment]
yes ive heard something like that via some android related podcast .. so its coming at last :O i think i will deal with it by using the storage of my www-site as my cloud and use ncftp to update things in userland .. es-file-man was a good one on the android.app side but now ppl say its a dagerous one:( got to find a nice one that does the ftp

thank you for teaching!

**Comment by MatthewTighe** [comment]
Because of the changes to Q, we have changed how you can access files on Android. Please see the [wiki](https://github.com/CypherpunkArmory/UserLAnd/wiki/Importing-and-exporting-files-in-UserLAnd) for more info.
