### ISSUE TITLE
Sudo  Permission denied

### ISSUE THREAD

**Issue by hocine-hj** [CypherpunkArmory/UserLAnd#888]
sudo -u user
/usr/local/bin/sudo: line 8: /dev/stderr: Permission denied

**Comment by corbinlc** [comment]
Interesting.  For now you should be able to do simply `su user` and then run whatever command you want. 
  That should be a fine workaround for right now.  For `sudo -u user`, I thought you had to do `sudo -u user command_to_run`.

**Comment by corbinlc** [comment]
Can you also update your issue to follow the template as the bot pointed out?

**Comment by MatthewTighe** [comment]
@corbinlc is correct, that is incorrect usage of `sudo`. See the [man page](https://linux.die.net/man/8/sudo) for more information.
