### ISSUE TITLE
Help - [How to get rid of the two extra lines above keyboard?]

### ISSUE THREAD

**Issue by tigran123** [CypherpunkArmory/UserLAnd#892]
# Describe the issue you are having
When running a UserLAnd session I get two huge lines above onscreen keyboard with keys like "ESC", "CTRL" etc. But this is totally unnecessary, because a proper keyboard (i.e. Hacker's Keyboard) includes all these keys in their proper places, so the space is wasted unnecessarily. In Termux one just presses Volume Key + K to get rid of the extra line, but I haven't figured out what is the UserLAnd's equivalent keyboard shortcut to do the same.

**Comment by MatthewTighe** [comment]
Volume key up + q should do it

**Comment by 0atman** [comment]
Any idea how to do it if your device doesn't have physical volume keys? Thanks!

**Comment by 0atman** [comment]
Opened a new issue in #1175
