### ISSUE TITLE
Bug report - Access Android filesystem from UserLAnd

### ISSUE THREAD

**Issue by LutzHas** [CypherpunkArmory/UserLAnd#903]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug

I can't access the Android filesystem anymore.
I had a working directory /sdcard/work but /sdcard is now empty.
I did read something about adding userland DocumentProvider but did not found help on this.
Without access to at least one directory on the internal storage of the phone userland is completely useless for me.

# Steps to reproduce the behavior:

# Screenshots

# Device Information

Device: Samsung Galaxy A6  
Android Version: 9  
UserLAnd Version: 2.5.13-beta-145693  
Whether the device is rooted: no
Whether the device is running LineageOS: no

**Comment by corbinlc** [comment]
Can you read through this and tell us if it helps explain the change and what to do about it?

https://github.com/CypherpunkArmory/UserLAnd/wiki/Importing-and-exporting-files-in-UserLAnd

We are building our beta branch out to be fully Android Q compliant currently and we would love feedback about the changes we are making.

**Comment by LutzHas** [comment]
That was exactly what i needed.

The methods described work very well.

Thank you very much.


corbinlc <notifications@github.com> schrieb am Di., 18. Juni 2019, 07:23:
