### ISSUE TITLE
Bug report - [Exporting Debian Filesystem Fails]

### ISSUE THREAD

**Issue by woodydeck** [CypherpunkArmory/UserLAnd#907]
# Describe the bug
Cannot export the filesystem. Fails on vague code 1 on export.

# Steps to reproduce the behavior:

1. Go to Filesystems
2. Long press to open menu
3. Select Export
4. Wait for it to dump almost all files into a tarball.
5. Smash your desk because it failed again

# Screenshot
[The error after it happens.](https://i.imgur.com/AcykJ1q.jpg)

# Device Information

Device: [Xiaomi A2].  
Android Version: [Pie 9.0].  
UserLAnd Version [Latest Play Store version.].  

# Notes
Filesystem was built before UserLand update that allowed exporting.

**Comment by MatthewTighe** [comment]
Which version exactly are you on? Need to know if you're on the beta channel or not

**Comment by woodydeck** [comment]
Where can I find this info? It doesn't seem to be in the program, nor can I find it on the play store.

**Comment by MatthewTighe** [comment]
It's also displayed on the play store page for the app, for future reference.

Could you try creating a new filesystem, creating some test file on it, and exporting that one?

**Comment by woodydeck** [comment]
It's the same error for Kali too, fresh install. :/ Could it be in the way I'm saving? I am saving to the default file manager. 

I have 22GB free, and I also updated Android today for first time since around the export release. I have a custom R installation, and I'm desperately trying to not redo it as reinstalling R will take at least a week to get running again there are so many nested dependencies.

**Comment by MatthewTighe** [comment]
No, that error is coming from PRoot. The flow for export is basically:

- Use PRoot to execute a script that tars up the filesystem.
- Use Android's Storage Access Framework to export the tarball to a URI chosen by the user.

The failure is happening in the first part. Script execution is failing, which just returns a `1` status code.

Another thing you can try is clearing support files. It's possible something is janked up with that script or with PRoot. v2.1.3 has an implementation error that will require you to completely kill and reopen the app to get support files back in their intended locations after clearing them.

**Comment by woodydeck** [comment]
I should probably clarify that Kali fails instantly, while the Debian one I have R on dumps I assume the whole thing before failing. It's like 15-20 minutes of files going before it fails.

Thanks for the explanation of the flow. I will try this now.

**Comment by woodydeck** [comment]
We have a winner. I'm still glad I didn't click the button without asking first. Thank you for the help!

**Comment by MatthewTighe** [comment]
Sure thing! Thanks for being helpful in resolving this.

**Comment by woodydeck** [comment]
I'd like to add that I could replicate the behavior again after this, it has failed twice since. I haven't booted into it again yet, so I will see if that makes a difference in the future. I did try clear before export each time. 

The output file was 1.87GB, so I don't see issues with the size in terms of Pie erroring with a large file.
