### ISSUE TITLE
Firefox Error

### ISSUE THREAD

**Issue by Martfig** [CypherpunkArmory/UserLAnd#917]
Ubuntu with LXDE normal installation
Have a bug on installation of LXDE in Ubuntu. Something tell about fetch error, but manually download and installing works fine

# Describe the issue you are having.
I'm trying run the Firefox but in every distro Ubuntu or Debian pop up the same window image below
![Screenshot from 2019-06-20 23-10-22](https://user-images.githubusercontent.com/46379980/59887037-164d7d80-9398-11e9-8d4a-6dc367110542.png)
And when I try run in terminal I receive this thing.
![Screenshot from 2019-06-20 23-11-44](https://user-images.githubusercontent.com/46379980/59887066-367d3c80-9398-11e9-9fce-769aabdb720f.png)

# Describe how your task behaves in a regular Linux environment

Normally the Firefox should work properly
Without crash windows

My specs:
Moto G5 (Cedric)
Android 8.1
Non rooted
Stock Room
UserLand version: 2.5.13-beta-145693

**Comment by Marcus0086** [comment]
@Martfig you can install chromium instead and open it through the command " chromium --no-sandbox" and if you want to use firefox instead you have to use old version like 47-48

**Comment by nalcwap** [comment]
@MatthewTighe MatthewTighe sorry oftopic, i used the firefox in userland bythe use the old version that have in the userland but when i try access some site example editor.construct.net     asks for webgl , i try change the option to active the webgl in firefox but not work, is this because the firefox is old or the userland not permit webgl?sorry im a newbie and sorry oftopic , please answer this, thanks, the device is tablet samsung galaxy tab A  2016   ,android 5.5.1    and userland downloads armhf files thats all i remember

**Comment by corbinlc** [comment]
Firefox-ESR is working in Debian and Ubuntu.  These instructions were just tested with new installs of Debian and Ubuntu:
https://github.com/CypherpunkArmory/UserLAnd/wiki/FAQ#2-how-do-i-get-firefox-working

**Comment by vaccarieli** [comment]
@corbinlc I get this error when running firefox-esr 

I know you said above u tested it already but I have a Samsung S10e Phone and followed the guide on the FAQ and did install all as it says, but it does not matter what i do i will allways get this error, i've uninstalled the app multiple times and reinstall from scratch trying multiple other options as well but i allways end up with the same issue again.

`user@localhost:~$ firefox-esr
[Parent 15305, Main Thread] WARNING: read-only dup failed (Permission denied); not using memfd: file /build/firefox-esr-a2DEDG/firefox-esr-102.1.0esr+build1/ipc/chromium/src/base/shared_memory_posix.cc:247
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: No GPUs detected via PCI (t=5.04312) [GFX1-]: No GPUs detected via PCI
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: No GPUs detected via PCI (t=5.04312) |[1][GFX1-]: glxtest: process failed (received signal 11) (t=5.04324) [GFX1-]: glxtest: process failed (received signal 11)
Missing chrome or resource URL: resource://gre/modules/UpdateListener.jsm
Missing chrome or resource URL: resource://gre/modules/UpdateListener.sys.mjs
`

**Comment by 4AloxeCorton** [comment]
I'm using a newer Galaxy S23 ultra and I've tried both the Ubuntu and Debian (pro) versions and I seem to be getting very similar error logs.
Are we the only ones or is this a Samsung specific issue?

![Screenshot_20230312_123636_UserLAnd](https://user-images.githubusercontent.com/74682668/224542072-01673e06-1f29-4659-a24b-529853317a77.jpg)

**Comment by Sharbell** [comment]
It's also happening to me, Kali with LXDE, I'm using a Xiaomi 10T Pro phone

It seems to me like Firefox is blocked by UserLand since it's a paid option now, even though I already paid for the LXDE installation

**Comment by 4AloxeCorton** [comment]
@corbinlc can you please confirm if Firefox has been purposely disabled in the latest UserLand OS install or if there is a fix and/or if this is a bug that I should register?  I also installed and paid for the stand alone firefox option (only a few $ and a good way to support the dev team) but what I'm really interested in is using Firefox within the Ubuntu / Debian full OS (which I also paid for).  I tried to install several several alternate browsers but the choice is limited on an arm64 platform and Firefox is the best option.  I would really like this key component to work...

Thanks

AC

**Comment by sbabcoc** [comment]
As a workaround, you can add this to your RC file:
`export MOZ_FAKE_NO_SANDBOX=1`
I still see the "read-only dup" message in the console output, but now it's a warning instead of an error.

**Comment by nitori848** [comment]
Sorry I new to this userland and this discussion 
 was closed but, I can fix that
Open Firefox in your terminal,and search about:config
Then type (sandbox.cubeband) and set it to false, and then type (security.sandbox.content.level) and type 0 (zero) then close the tab and open again to see it is work.
