### ISSUE TITLE
consultation-there is a question

### ISSUE THREAD

**Issue by fxzxmicah** [CypherpunkArmory/UserLAnd#920]
can you please tell me where is the storage directory for software downloads? thank you very much.

**Comment by MatthewTighe** [comment]
UserLAnd assets are downloaded to scoped storage. This is usually under `/storage/emulated/0/Android/data/tech.ula/files/downloads`, but this path can be device specific. 

If you are wondering where software downloaded during a UserLAnd session is downloaded to, that is determined by whatever application you are using to download it.
