### ISSUE TITLE
Bug report - [YOUR BUG TITLE]

### ISSUE THREAD

**Issue by niri81** [CypherpunkArmory/UserLAnd#921]
# Describe the bug

It fails to load the filesystem at any distribution.

# Steps to reproduce the behavior:

If you try to install any distribution

# Screenshots

I've got no screens

# Device Information

Device: [Huawei Mate 10 Lite].  
Android Version: [Oreo, 8.0].  
UserLAnd Version [2.5.13].  
No root
No LineageOS 

I also tried to uninstall and reinstall and to clear the support files.

**Comment by MatthewTighe** [comment]
There are some issues with Hauwei's version of Oreo that we are still working on. Are you able to upgrade to Android 9.0?

**Comment by Marcus0086** [comment]
@niri81 it looks like that userland also banned huawei 🤣🤣 lol. Just kidding.
