### ISSUE TITLE
[Feature Request] Android Q, SD Cards, and Scoped Storage: Make SD Cards Visible Under /storage

### ISSUE THREAD

**Issue by aplumafreak500** [CypherpunkArmory/UserLAnd#937]
# Describe the problem your feature request solves.
I'm aware of the changes Android Q will make regarding scoped storage, but I don't want to have to manually move my files from, say, my SD card to the scoped storage directory, as my phone's internal storage is full enough as it is.

Prior to the latest update, I had a symlink to the scoped storage directories (for me, `/host-rootfs/storage/emulated/0/Android/data/tech.ula` and `/host-rootfs/storage/XXXX-XXXX/Android/data/tech.ula`; XXXX-XXXX being the volume ID of my SD card's FAT32 partition) as /int and /ext respectively, as a way to get around Android's restrictions on writing to arbitrary locations on SD cards. The latest update broke those symlinks (again, I am aware of the changes regarding Android Q and the /storage directory), because /host-rootfs/storage also points to the scoped directory instead of just /storage and I'm unsure if that counts as a separate bug.

# Describe the solution you'd like 
Scoped storage does exist on inserted SD cards (and USB flash drives, I think), under the same path as on internal storage as noted above. I'd like all attached storage devices (SD cards, USB devices, etc.) be visible under /storage, and each directory listed would lead straight to that device's scoped storage for this app.

# Describe alternatives you've considered
n/a

(Note that I'm actually on non-root Android 7.1)

Thank you for your consideration!

**Comment by MatthewTighe** [comment]
Yeah, I really like this idea actually. Wish I'd thought of it in the first place. I'll throw a card into our backlog for it and try to get it done in the near future.

I'm a little confused still by what you meant here:
>  because /host-rootfs/storage also points to the scoped directory instead of just /storage and I'm unsure if that counts as a separate bug.

Are you saying that `/host-rootfs/storage` is pointing to the same directory as `/storage`? If so that is indeed a bug, though I'm not sure if it's on our end. I'm not able to reproduce using my Pixel 2 running the latest Q beta.

**Comment by MatthewTighe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Top level user scoped storage should have directories for each storage device's scoped storage](https://trello.com/c/gYAWoHeS/732-top-level-user-scoped-storage-should-have-directories-for-each-storage-devices-scoped-storage)

**Comment by aplumafreak500** [comment]
It turns out /storage was merely a symlink. However /host-rootfs/storage still points to scoped storage instead of the real /storage; /sdcard is still present and non-symlinked, but gives `Permission denied` when trying to access it.

**Comment by MatthewTighe** [comment]
Yeah, `/storage`, `/hoot-rootfs`, and `/sdcard` are all proot bindings to the actual directories they represent. `/sdcard` is no longer used, but the directory created for it must not have been automatically deleted. @corbinlc can speak in more depth on how those bindings actually work.

> However /host-rootfs/storage still points to scoped storage instead of the real /storage

If what you mean is it doesn't allow you to view the root of your SD card at that directory anymore, that is probably a direct consequence of the fact that we are compiling targeting Q now. Unfortunately there's just no getting around that in Q and future versions of Android. 

`/host-rootfs/storage/emulated/0/Android/data/tech.ula/files/storage` and `/storage` are the same directory.
