### ISSUE TITLE
Help - [how to invoke | and \ on German keyboard]

### ISSUE THREAD

**Issue by Dirk-LG** [CypherpunkArmory/UserLAnd#942]
Hi,

I connect a standard German USB keyboard of PC to my smartphone and everything works fine except the important | and \ which are usually invoked with "ALT GR" + button. How to do it in UserLAnd?

Thanks
Dirk

**Comment by Dirk-LG** [comment]
# Describe the issue you are having.
Cannot write \ nor | in xterm of XWindow.

# Describe how your task behaves in a regular Linux environment
I just press "ALT GR" and the corresponding buttons.

**Comment by corbinlc** [comment]
Issues with the vnc client, bVNC, need to be filed here: https://github.com/iiordanov/remote-desktop-clients/issues
That will allow the developer of that app to help out.  Sorry for not getting back sooner.

**Comment by laem** [comment]
@dirk-lg try Remotix as a VNC client, setting the option "remap system key" to "user right alt as win/cmd"
