### ISSUE TITLE
Help - [full 1920x1080 image on HDMI output]

### ISSUE THREAD

**Issue by Dirk-LG** [CypherpunkArmory/UserLAnd#943]
Hi,

to get a convenient setup I purchased a "3 in 1 Typ C USB 3.1 to USB-C HDMI USB 3.0-Adapter" (see https://www.ebay.de/itm/192857236720) but the output to HDMI is not as expected: The monitor always gets a 1920x1080 image but the provided contents are never enlarged to the full screen.
It tried successfully to change the X Window resolution from 2952x1440 to 1920x1080 and then to 1280x720 but nothing changes this behaviour.
--> How to get a full image? Perhaps there's another adapter available? I have a LG G7 ThinQ smartphone.

Thanks
Dirk

**Comment by Dirk-LG** [comment]
![IMG_4795](https://user-images.githubusercontent.com/52800761/61183114-2e35bb80-a63d-11e9-81d0-f4c0ec8284ea.JPG)
![IMG_4793](https://user-images.githubusercontent.com/52800761/61183115-2e35bb80-a63d-11e9-916d-2ad2f5b43152.JPG)

**Comment by Dirk-LG** [comment]
# Describe the issue you are having.
Image is not fit to screen, see pictures.

# Describe how your task behaves in a regular Linux environment
Screen is filled.

**Comment by MatthewTighe** [comment]
So you are connecting your phone directly to the TV? When you start the session on your phone, does it fill the entire screen?

**Comment by Dirk-LG** [comment]
Good morning Matthew,

I connect this unbranded hub to my phone and it has HDMI out.
While the screen of my phone is always filled entirely, the TV screen is never filled even for other Android apps.

Cheers
Dirk



Am 15. Juli 2019 18:54:30 MESZ, schrieb Matthew Tighe <notifications@github.com>:
>So you are connecting your phone directly to the TV? When you start the
>session on your phone, does it fill the entire screen?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/CypherpunkArmory/UserLAnd/issues/943#issuecomment-511482403

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MatthewTighe** [comment]
If the screen is never filled for other apps either, it's just some issue with the connection type or the TV itself. They sell HDMI to USB-C direct connectors, so maybe try one of them. Unfortunately that means I don't think there's anything we can do to improve your experience in this regard.

**Comment by Dirk-LG** [comment]
I have a solution now! :)
My smartphone was upgraded to Android 10 recently, and now there is a button on screen to allow the output ratio for the secondary screen (TV set). When I set 16:9 I get the full screen.
