### ISSUE TITLE
Feature Request - [Update Kernel on ArchLinux]

### ISSUE THREAD

**Issue by Jzarecta** [CypherpunkArmory/UserLAnd#951]
# Describe the issue you are having.
I have tried to update the kernel on my arch to 5.x, neofetch gave me I am still on a 3.x kernel and after trying to manually install the linux kernel I got my issue destroyed.

I am having multiple problems like activating samba, installing pacaur or launching Qt based applications. 

# Describe how your task behaves in a regular Linux environment
Usually my kernel gets updated. After doing: ```pacman -S linux-harden ```.

**Comment by jlainema** [comment]
UserLand uses your phone's kernel directly. You will need to either get a new phone, or update to a newer Android version if one is available for your model.

**Comment by corbinlc** [comment]
Modifying your kernel would at least require running as real root.  This is not supported in UserLAnd. 
 Please see #910.  Even if it was supported already, it would be very dangerous to modify the kernel on your phone in this manner.  Closing this, because #910 is already open.
