### ISSUE TITLE
Bug report - [Octave app will not install]

### ISSUE THREAD

**Issue by Frainj** [CypherpunkArmory/UserLAnd#953]
# Describe the bug
When userland is started the octave app is failing.
Trying to download and install octave gives an error message message

unable to locate package octave-odepkg

When Debian Linux is started, octave 4.4.1 can be installed from the Debian command prompt using the usual apt-get.  An earlier version of UserLand used octave 4.0.  Is the UserLAnd app trying to download a dependency for 4.4.1 that has changed since 4.0.

# Steps to reproduce the behavior:

1 Install Userland and open
2 Select the Debian app and close UserLAnd
3 Restart  UserLAnd and select the octave app
4. Error as reported above

# Device Information
Device. Honor Play
Android Version 9
UserLAnd Version 2.5.15-beta-457616
device not rooted
Not running LineageOS

**Comment by corbinlc** [comment]
I can confirm this one.  It will be fixed very soon.

**Comment by corbinlc** [comment]
Thanks for bringing this to our attention.  This is now fixed.
