### ISSUE TITLE
Bug report - [Error on install]

### ISSUE THREAD

**Issue by andresfdel17** [CypherpunkArmory/UserLAnd#956]
Samsung galaxy Tab A 6 
Error on install
![Screenshot_20190724-074824_UserLAnd](https://user-images.githubusercontent.com/53264064/61795116-46999900-ade8-11e9-9f22-9d655e500bd7.jpg)

**Comment by andresfdel17** [comment]
I told you all  i know

**Comment by corbinlc** [comment]
We fixed the octave install a little bit ago.  Sorry I didn't think to update this issue as well.  Please try again.
