### ISSUE TITLE
[Help] Remote Control

### ISSUE THREAD

**Issue by FranGamer1892** [CypherpunkArmory/UserLAnd#961]
I've tried both NoMachine (couldn't connect yet) which either uses NX or SSH, or TeamViewer (doesn't work at all). I really want to control my UserLand (Ubuntu with XFCE4) from my PC.

Any suggestions for connecting from my PC (Windows/Ubuntu) to UserLand, please feel free to leave them.

I'd rather not using root, but if I need to I will (maybe if I got to use SSH).

Another question, does no-root ssh support work on LAN, globally or just within the cellphone?

**Comment by FranGamer1892** [comment]
@enforce-issue-templates[bot] I don't know how to use headers. I'm on my phone!

**Comment by MatthewTighe** [comment]
@FranGamer1892 This should be possible using the following steps:

1. Start an SSH session in UserLAnd. This will start a dropbear server.
2. Determine your devices public IP address.
3. Connect to the server using your SSH client on your computer. You will need to use that public IP address, the user you have created for the filesystem, **and the port 2022**.

**Comment by FranGamer1892** [comment]
Is there a SSH client for Remote Control that I can use? The ones either don't support armhf architecture or don't work with UserLand.

**Comment by MatthewTighe** [comment]
Yes, any SSH client will work. For example, if you are running Ubuntu on your PC the command would be 

`ssh <the username you chose when creating a filesystem>@<your phone's public ip> -p 2022`

**Comment by FranGamer1892** [comment]
Great. I'm on it. By the way, Is there a way to stream my UserLand XFCE desktop via VNC so I connect either from a PC in my network or a foreign one.

**Comment by corbinlc** [comment]
This is covered here:  https://github.com/CypherpunkArmory/UserLAnd/wiki/FAQ

Hope that helps.
