### ISSUE TITLE
Help - Synaptic Not Working

### ISSUE THREAD

**Issue by qqqwwweee123-ping** [CypherpunkArmory/UserLAnd#974]
# Describe the issue you are having.
This should include things like:

I just installed debian and xfce4 environment and saw a synaptic
i have tried to open it but only i get is An occurred error window

# Describe how your task behaves in a regular Linux environment
Its bugged and is unable to give whats crash or submit it. idk if its problem of ff or userland.
![62000526-b91db800-b10b-11e9-99b5-2c79da26d04a](https://user-images.githubusercontent.com/53271744/62143519-b812a380-b322-11e9-97d4-65b6f5e28f23.png)

**Comment by MatthewTighe** [comment]
Duplicate of #916
