### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gutclone** [CypherpunkArmory/UserLAnd#979]
![Screenshot_٢٠١٩٠٨٠١-٢٣٥٣٢٤_UserLAnd](https://user-images.githubusercontent.com/47323188/62332470-b1696500-b4b7-11e9-9682-e1facc003df7.jpg)
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the issue you are having.

This should include things like:
- What you are trying to accomplish
- What you have tried so far

# Describe how your task behaves in a regular Linux environment

Describe how the task you are trying to accomplish behaves in a regular Linux environment.

**Comment by MatthewTighe** [comment]
Unfortunately, none of our development team can read, write, or comprehend Arabic. Additionally, we are unable to copy the text of the screenshot to paste it into a translation service. This means we cannot really help you resolve this issue, as we are unable to know what it is. If you are able to set your phone's language to English to recreate the issue, please post a new issue with a screenshot of the problem.
