### ISSUE TITLE
Arch Linux on android 9.0 -Operation not permitted

### ISSUE THREAD

**Issue by foodmaher** [CypherpunkArmory/UserLAnd#983]
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the issue you are having.

This should include things like:
- I have a problem installing the packages on Arch on the android 9.0 system where root file permissions error occurs.

     could not change the root directory (Operation not permitted)
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/5) Updating fontconfig cache...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
(2/5) Updating icon theme caches...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
(3/5) Arming ConditionNeedsUpdate...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
(4/5) Updating the desktop file MIME type cache...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
(5/5) Updating X fontdir indices...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly

- I tried to update the packages but without any utility.

# Describe how your task behaves in a regular Linux environment

Packages are installed normally.

**Comment by MatthewTighe** [comment]
What is the command you tried to run?

**Comment by foodmaher** [comment]
@MatthewTighe 
`pacman -S [package]`

**Comment by corbinlc** [comment]
Can you do `sudo pacman -S [package]` ?

**Comment by 12101111** [comment]
```shell
Welcome to Arch Linux in UserLAnd!
[han@localhost ~]$ pacman -S nano
error: you cannot perform this operation unless you are root.
[han@localhost ~]$ sudo pacman -S nano
resolving dependencies...
looking for conflicting packages...

Packages (1) nano-4.3-1

Total Download Size:   0.47 MiB
Total Installed Size:  2.50 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 nano-4.3-1-aarch64       480.2 KiB  56.3K/s 00:09 [########################] 100%
(1/1) checking keys in keyring                     [########################] 100%
(1/1) checking package integrity                   [########################] 100%
(1/1) loading package files                        [########################] 100%
(1/1) checking for file conflicts                  [########################] 100%
:: Processing package changes...
(1/1) installing nano                              [########################] 100%
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
could not change the root directory (Operation not permitted)
error: command failed to execute correctly
[han@localhost ~]$ chroot /usr
chroot: cannot change root directory to '/usr': Operation not permitted
[han@localhost ~]$ sudo chroot /usr
chroot: cannot change root directory to '/usr': Function not implemented
```
/var/log/pacman.log:
```log
[2019-08-12 06:03] [PACMAN] Running 'pacman -S nano'
[2019-08-12 06:04] [ALPM] transaction started
[2019-08-12 06:04] [ALPM] installed nano (4.3-1)
[2019-08-12 06:04] [ALPM-SCRIPTLET] could not change the root directory (Operation not permitted)
[2019-08-12 06:04] [ALPM] transaction completed
[2019-08-12 06:04] [ALPM] running 'systemd-update.hook'...
[2019-08-12 06:04] [ALPM-SCRIPTLET] could not change the root directory (Operation not permitted)           
```
Phone: ASUS ROG game phone II
Android version: Pie, security patch 2019/6/5
Kernel version: 4.14.83

**Comment by corbinlc** [comment]
@foodmaher, as @MatthewTighe said, you need to use `sudo` to install packages.  

@12101111 I believe your issue is what was just solved in #1014 .  Please try v2.6.3 when you see an option to update to it (might be a few hours).

**Comment by RAVIRAVEEN** [comment]
Getting same problem in userland on blackarch os..the problem is that
Could not change the root directory(operation not permitted)
Error:command failed to execute correctly..

Am using update version of userland..2.6.3
![Screenshot_20190917-110026_JuiceSSH](https://user-images.githubusercontent.com/52444257/65014001-d36d5880-d93a-11e9-974f-69e423ddc138.jpg)

**Comment by lennyerik** [comment]
I have the same problem (on a OnePlus 6) and version 2.6.3.

**Comment by b3nsh4** [comment]
Even after new update, I still have this issue in Arch.

**Comment by ntrp** [comment]
I can confirm the issue, cannot update or install packages even using su.

OnePlus 3T
Android 9 rooted
App 2.6.5
Arch

**Comment by Lite5h4dow** [comment]
Can Confirm, still an issue 

Samsung Galaxy Note 8
Android 9 (non root)
Arch

**Comment by Ranguna** [comment]
Can confirm too.
realme x2 pro (snapdragon 855+)
Android 10 no roor
Arch

**Comment by dogon11** [comment]
Can confirm, still an issue.
Arch

**Comment by dburnsii** [comment]
I have this issue as well. I assume pacman is running `chroot` at the end of installation and seems to be failing?

**Comment by erhan-** [comment]
Testing ArchLinux and did nothing but try to update the system with -Syu and surely with sudo or root. Same error. 

Was this image tested? And why is this closed?

**Comment by intralexus** [comment]
Same Problem on Android v9 Could Not Change to root directory Operation Not permited

**Comment by rollerozxa** [comment]
Same issue when trying to update or install packages, Android 10.

**Comment by TimYt44** [comment]
I have the same problem.
Ubuntu 22

**Comment by jokokoerna-hash** [comment]
Gimna cara melihat saldo card lewat nfc
