### ISSUE TITLE
Debian 10 Buster

### ISSUE THREAD

**Issue by qqqwwweee123-arch** [CypherpunkArmory/UserLAnd#984]
hi All,
Debian 10 Buster is out. deb.debian.org/debian/dists/buster/ shows that there is a arm64.
Will this be coming to UserLAnd soon? (hope-hope).

thanks,
GB

edit 181120: I got what I needed by a different route (sources.list).

**Comment by qqqwwweee123-arch** [comment]
update debian 10 buster?

**Comment by MatthewTighe** [comment]
Added to #581
