### ISSUE TITLE
Feature Request - Add support for Devuan

### ISSUE THREAD

**Issue by kbhasi** [CypherpunkArmory/UserLAnd#987]
# Describe the problem your feature request solves.

[Devuan GNU/Linux](http://devuan.org) is a fork of Debian GNU/Linux that aims to remove any dependencies on `systemd` from the latter, though it does end up lagging behind that when it comes to releases. However, not being dependent on this may translate to it being friendlier with `chroot` and `proot` environments.

# Describe the solution you'd like 

It may be possible to fork the Debian support repo and change a number of things to make it work with Devuan. However, I'm too busy with other things to be able to try this for myself.

# Describe alternatives you've considered

I have tried to just set up a Debian filesystem and switch the APT sources to Devuan sources, but an error comes up about missing public keys. At this point, I would need to get the Devuan archive keyring right from the repository itself as a package, and install that, but that wouldn't be easy for others, so I decided to just stop there.

Edit: I found [this guide](https://devuan.org/os/documentation/dev1fanboy/migrate-to-ascii) and will try to follow that to get the archive keyring installed. As this isn't a full install, I wouldn't have to follow most of it.

**Comment by MatthewTighe** [comment]
Added to #581
