### ISSUE TITLE
Apt-Get Install failing - Udisks2 Permission Denied error leads to lots of DPKG error

### ISSUE THREAD

**Issue by jgiddens** [CypherpunkArmory/UserLAnd#992]
Hi!
I have just setup UserLAnd and have run into an issue.  I installed the Kali distro and then was able to successfully SSH into it from my desktop machine.  Pretty slick.  However, the goal of my install was to run some wifi cracking tools from kali.  When i try to install some i get this issue:
`jasong@localhost:~$ sudo apt-get install wifite
Reading package lists... Done
Building dependency tree
Reading state information... Done
wifite is already the newest version (2.2.5-2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
6 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
E: Setting in Start via TCSAFLUSH for stdin failed! - tcsetattr (13: Permission denied)
Setting up udisks2 (2.8.4-1) ...
Failed to scan devices: Permission denied
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.38.1-5); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gnome-disk-utility:
 gnome-disk-utility depends on udisks2 (>= 2.7.6); however:
  Package udisks2 is not configured yet.

dpkg: error processing package gnome-disk-utility (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs:arm64:
 gvfs:arm64 depends on gvfs-daemons (<< 1.38.1-5.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:arm64 depends on gvfs-daemons (>= 1.38.1-5); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:arm64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-fuse:
 gvfs-fuse depends on gvfs (= 1.38.1-5); however:
  Package gvfs:arm64 is not configured yet.

dpkg: error processing package gvfs-fuse (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gnome-disk-utility
 gvfs:arm64
 gvfs-fuse
E: Sub-process /usr/bin/dpkg returned an error code (1)`

I have tried running apt-get fix missing, I have deleted the libcups2 dir as noted in another thread, still no love.  Any suggestions?

**Comment by Upanori7** [comment]
Dear jgiddens 
The first thing you have to do must update and upgrade your termux and then root your android. so then, install the wifite in your termux
in regard if its doesnt work you must configure to be auto-fixing ( follow this command : #dpkg --configure -a
if you need more assistan or help feel free to contact me as you like

**Comment by q-codes** [comment]
Upanori7, do I have to root, really?
I already did it without root 1.5 months ago, I ran parrot, kali. But now, udisks2 is really bugging the whole thing.

**Comment by Upanori7** [comment]
jgiddens .....as l know when you run another distro of linux except kali ,.l didnt know about that 
l use kali linux and its running normal

**Comment by corbinlc** [comment]
Started debugging this.  Please see #1072 .

**Comment by corbinlc** [comment]
Closing this one as #1072 will track my progress on this.

**Comment by MrXrX7** [comment]
how to solve "E: Sub-process / usr / bin / dpkg returned an error code (2)"?

**Comment by ghost** [comment]
@corbinlc 
hey damn,Fix this error ASAP. this hasn't been fixed more than 2 years since I found.

**Comment by ninjaghostdev1** [comment]
sudo apt install udisks2
sudo rm /var/lib/dpkg/info/udisks2.postinst
sudo dpkg --configure udisks2
sudo apt install xfce4

**Comment by stackfifo** [comment]
> sudo apt install udisks2 sudo rm /var/lib/dpkg/info/udisks2.postinst sudo dpkg --configure udisks2 sudo apt install xfce4

Thank you
