### ISSUE TITLE
Bug report - Function not implemented tar: can't change directory to '/': 

### ISSUE THREAD

**Issue by bitcoinmeetups** [CypherpunkArmory/UserLAnd#995]
# Describe the bug

[H[J/support/common/extractFilesystem.sh: line 8: ln: Function not implemented
tar: can't change directory to '/': Function not implemented

# Steps to reproduce the behavior:

Occurs every time I try to install Debian

# Device Information

Samsung J7, Android 8

Hi,

The last couple of months I have been unable to install Debian on Userland. I get the error message above. Clearing support files does not help. Any fix or advice?

**Comment by TechDossier** [comment]
Am used userland in my mobile. A d it was works fine a few days ago. Am already installed kali in my mobile..one day shows.. " update Please wait" 

After am reinstall not have to install any linux distro in my mobile
 

Am using Samsung j7 8.0v a android. 

Am also havinga same problem

**Comment by corbinlc** [comment]
We don't have a device that shows this error, but have made an attempt at fixing it from what we know.  Can you join the beta program and install the latest beta release and tell us if it helps?  To join the beta, you scroll down to the bottom of the app details from within Google Play (see first pic).  When you go to install, it should show `beta` in the version name (see second pic).
![Screenshot_20190817-200144_Google Play Store](https://user-images.githubusercontent.com/1421245/63220817-c9352000-c12a-11e9-86f3-f597b8beecc9.jpg)
![Screenshot_20190817-200248_Google Play Store](https://user-images.githubusercontent.com/1421245/63220819-ccc8a700-c12a-11e9-8886-4263fa6f60dc.jpg)

**Comment by TechDossier** [comment]
**After update #1012 userland also have same directory problem**
#1012 #58 #877

**Comment by TechDossier** [comment]
#userland 

2019 update... directory error not solved. Wasted my data tod....
WTF  ? 👿

I can't expected... Please remove this app in playstore. Fake app

**Comment by corbinlc** [comment]
Thanks for being so understanding and helpful!  Can you confirm what version you are running?  Can you also capture a Proot debug log (go to settings to enable, then repeat the error, then send us the file)?  That would actually help.

**Comment by corbinlc** [comment]
@TechDossier and @bitcoinmeetups this is now fixed.  Please see #1014 - you can see there how necessary the PRoot log were in solving this issue.  It is fixed in v2.6.3 which is rolling out now (may take a few hours before you see the option to update).
